# Molecular Generator Evaluation using TUPOR, SESY and ASER Metrics

🔹 **Objective**  
This notebook evaluates molecular generators by computing four key metrics:  
   - **TUPOR**: scaffold recall metrics  
   - **SESY**: scaffold hopping potencial  
   - **ASER**: chemical space exploration

🔹 **Workflow**  
1️⃣ **Compute Metrics**: The script calculates TUPOR, SESY and ASER for different molecular generators.  
2️⃣ **Merge Data**: Results from multiple generators are combined into a single Pandas DataFrame.  
3️⃣ **Normalize Values**: The computed metrics are normalized using Min-Max scaling for comparison.  
4️⃣ **Save Outputs**: Processed data is stored in CSV files for further analysis.  

🔹 **Data Structure**  
- The calculations are performed for different **scaffold types** (`csk`, `murcko`) and **cluster types** (`dis`, `sim`).  
- Results are computed for multiple **generators** (`Molpher`, `REINVENT`, `DrugEx`, `GB_GA`, `AddCarbon`).  
- The analysis is conducted for a specific **biological target receptor**, such as the **Glucocorticoid receptor**.

This notebook allows us to compare the performance of various molecular generators in terms of structural diversity, similarity to known bioactive compounds, and synthetic feasibility.

# Loading required libraries

In [83]:
from src import metrics_scaffold # Importing custom metric functions
import importlib as imp
imp.reload(metrics_scaffold)

# Function to calculate metrics

In [2]:
def calculate_metrics(type_cluster, type_scaffold,generator, receptor, data_folder='', ncpus = 1):
    """
    Function to calculate molecular generation metrics.
    
    Parameters:
    - scaffold_type: Type of scaffold (e.g., 'csk' or 'murcko')
    - type_cluster: Cluster type  (e.g., 'dis' or 'sim') dis = Dissimilarity split; sim = Similarity split
    - generator: Name of the molecular generator (e.g. 'Molpher', 'REINVENT', 'DrugEx_GT_epsilon_0.1', 'DrugEx_GT_epsilon_0.6'
        'DrugEx_RNN_epsilon_0.1', 'DrugEx_RNN_epsilon_0.6', 'GB_GA_mut_r_0.01', 'GB_GA_mut_r_0.5', 'GB_GA_log_p_mut_r_0.01','GB_GA_log_p_mut_r_0.5', 'addcarbon')
    - receptor: Target receptor for drug design (e.g. 'Glucocorticoid_receptor', 'Leukocyte_elastase')

    Returns:
    - Computed metrics
    """
    mt = metrics_scaffold.Metrics_scaffold(type_cluster, type_scaffold, generator, receptor, data_folder, ncpus)     
    result = mt.calculate()
    display(result)
    return result

# Define parameters for metric calculations

In [25]:
type_cluster = 'sim' #options: 'dis'|'sim' 
type_scaffold = 'csk' #options: 'csk'|'murcko'
generator = 'Molpher_10k' #options: 'Molpher'|'DrugEx_GT_epsilon_0.1'|'REINVENT'|'addcarbon' |'GB_GA_mut_r_0.5'|'GB_GA_log_p_mut_r_0.01'
receptor = 'Leukocyte_elastase' #options: 'Glucocorticoid_receptor'|'Leukocyte_elastase'
data_folder = '../'

calculate_metrics(type_cluster,type_scaffold,generator,receptor, data_folder, ncpus = 150)

============================================================
Starting calculation for Molpher_10k
Receptor: Leukocyte_elastase
Cluster type: sim
Scaffold type: csk
CPUs: 150
============================================================

--- Processing cluster 0 ---

Loading data from:
  Output: ..//data/output_sets/Leukocyte_elastase/Molpher_10k/cOS_Molpher_10k_sim_0_one_column.csv
  Recall: ..//data/input_recall_sets/Leukocyte_elastase/cRS_Leukocyte_elastase_sim_0.csv
Loaded 10,122 output compounds
Loaded 644 recall compounds

Calculating metrics...

Converting to csk scaffolds...
  Processing recall set...
    Recall scaffolds: 644
  Processing output set...
    Output scaffolds: 10,122
  Unique output scaffolds: 2,294
  Unique recall scaffolds: 46

Metrics calculated:
  RS: 0.4565 (21/46)
  SED:  0.2266
  ASER:  0.0492

Results saved to: ..//data/results/Leukocyte_elastase/csk_scaffolds/sim/Molpher_10k

--- Processing cluster 1 ---

Loading data from:
  Output: ..//data/output_sets/Leukocyte_elastase/Molpher_10k/cOS_Molpher_10k_sim_1_one_column.csv
  Recall: ..//data/input_recall_sets/Leukocyte_elastase/cRS_Leukocyte_elastase_sim_1.csv
Loaded 10,025 output compounds
Loaded 161 recall compounds

Calculating metrics...

Converting to csk scaffolds...
  Processing recall set...
    Recall scaffolds: 161
  Processing output set...

[10:58:27] Explicit valence for atom # 7 C, 5, is greater than permitted

    Output scaffolds: 10,024
  Unique output scaffolds: 2,541
  Unique recall scaffolds: 44

Metrics calculated:
  RS: 0.3182 (14/44)
  SED:  0.2535
  ASER:  0.0207

Results saved to: ..//data/results/Leukocyte_elastase/csk_scaffolds/sim/Molpher_10k

--- Processing cluster 2 ---

Loading data from:
  Output: ..//data/output_sets/Leukocyte_elastase/Molpher_10k/cOS_Molpher_10k_sim_2_one_column.csv
  Recall: ..//data/input_recall_sets/Leukocyte_elastase/cRS_Leukocyte_elastase_sim_2.csv
Loaded 10,065 output compounds
Loaded 124 recall compounds

Calculating metrics...

Converting to csk scaffolds...
  Processing recall set...
    Recall scaffolds: 124
  Processing output set...
    Output scaffolds: 10,065
  Unique output scaffolds: 2,224
  Unique recall scaffolds: 42

Metrics calculated:
  RS: 0.2143 (9/42)
  SED:  0.2210
  ASER:  0.0031

Results saved to: ..//data/results/Leukocyte_elastase/csk_scaffolds/sim/Molpher_10k

--- Processing cluster 3 ---

Loading data from:
  Output: ..//data/output_sets/Leukocyte_elastase/Molpher_10k/cOS_Molpher_10k_sim_3_one_column.csv
  Recall: ..//data/input_recall_sets/Leukocyte_elastase/cRS_Leukocyte_elastase_sim_3.csv
Loaded 10,150 output compounds
Loaded 77 recall compounds

Calculating metrics...

Converting to csk scaffolds...
  Processing recall set...
    Recall scaffolds: 77
  Processing output set...
    Output scaffolds: 10,150
  Unique output scaffolds: 2,157
  Unique recall scaffolds: 42

Metrics calculated:
  RS: 0.3333 (14/42)
  SED:  0.2125
  ASER:  0.0143

Results saved to: ..//data/results/Leukocyte_elastase/csk_scaffolds/sim/Molpher_10k

--- Processing cluster 4 ---

Loading data from:
  Output: ..//data/output_sets/Leukocyte_elastase/Molpher_10k/cOS_Molpher_10k_sim_4_one_column.csv
  Recall: ..//data/input_recall_sets/Leukocyte_elastase/cRS_Leukocyte_elastase_sim_4.csv
Loaded 10,151 output compounds
Loaded 54 recall compounds

Calculating metrics...

Converting to csk scaffolds...
  Processing recall set...
    Recall scaffolds: 54
  Processing output set...
    Output scaffolds: 10,151
  Unique output scaffolds: 2,121
  Unique recall scaffolds: 42

Metrics calculated:
  RS: 0.2143 (9/42)
  SED:  0.2089
  ASER:  0.0018

Results saved to: ..//data/results/Leukocyte_elastase/csk_scaffolds/sim/Molpher_10k

Averaging results across 5 clusters...
Average results saved to: ..//data/results/Leukocyte_elastase/csk_scaffolds/sim/Molpher_10k

============================================================
Calculation complete! Processed 5 clusters
============================================================

               name type_cluster scaffold        RS       SED      ASER
0     Molpher_10k_0          sim      csk  0.456522  0.226635  0.049200
1     Molpher_10k_1          sim      csk  0.318182  0.253492  0.020650
2     Molpher_10k_2          sim      csk  0.214286  0.220964  0.003080
3     Molpher_10k_3          sim      csk  0.333333  0.212512  0.014286
4     Molpher_10k_4          sim      csk  0.214286  0.208945  0.001773
5  Molpher_10k_mean          sim      csk  0.307322  0.224510  0.017798

               name type_cluster scaffold        RS       SED      ASER
0     Molpher_10k_0          sim      csk  0.456522  0.226635  0.049200
1     Molpher_10k_1          sim      csk  0.318182  0.253492  0.020650
2     Molpher_10k_2          sim      csk  0.214286  0.220964  0.003080
3     Molpher_10k_3          sim      csk  0.333333  0.212512  0.014286
4     Molpher_10k_4          sim      csk  0.214286  0.208945  0.001773
5  Molpher_10k_mean          sim      csk  0.307322  0.224510  0.017798

# Execute metric calculation function

In [ ]:
for receptor in ['Glucocorticoid_receptor']:
    for type_scaffold in ['csk']:
        for type_cluster in ['dis']:
            for subset in ['_500k', '_250k', '_125k', '_62.5k', '_10k']:
                ncpus = 100
                data_folder = '../'
                # Define generator names with different epsilon values
                generators_name_list = [
                    f"Molpher{subset}",
                    f"REINVENT{subset}",
                    f"DrugEx_GT_epsilon_0.1{subset}",
                    f"DrugEx_GT_epsilon_0.6{subset}",
                    f"DrugEx_RNN_epsilon_0.1{subset}",
                    f"DrugEx_RNN_epsilon_0.6{subset}",
                    f"GB_GA_mut_r_0.01{subset}",
                    f"GB_GA_mut_r_0.5{subset}",
                    f"GB_GA_log_p_mut_r_0.01{subset}",
                    f"GB_GA_log_p_mut_r_0.5{subset}",
                    f"addcarbon{subset}"
                ]
                for generator in generators_name_list:
                    print(generator)
                    calculate_metrics(type_cluster,type_scaffold,generator,receptor, data_folder = data_folder,ncpus = ncpus)

Molpher_500k

============================================================
Starting calculation for Molpher_500k
Receptor: Glucocorticoid_receptor
Cluster type: dis
Scaffold type: csk
CPUs: 100
============================================================

--- Processing cluster 0 ---

[12:21:25] Explicit valence for atom # 5 C, 5, is greater than permitted
[12:21:25] Explicit valence for atom # 5 C, 5, is greater than permitted
[12:21:25] Explicit valence for atom # 7 C, 5, is greater than permitted
[12:21:25] Explicit valence for atom # 22 C, 5, is greater than permitted
[12:21:25] Explicit valence for atom # 18 C, 5, is greater than permitted

--- Processing cluster 1 ---

--- Processing cluster 2 ---

[12:21:52] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:21:53] Explicit valence for atom # 9 C, 5, is greater than permitted
[12:21:53] Explicit valence for atom # 12 C, 5, is greater than permitted
[12:21:53] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:21:53] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:21:53] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:21:53] Explicit valence for atom # 4 C, 5, is greater than permitted

--- Processing cluster 3 ---

[12:22:23] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:22:23] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:22:23] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:22:23] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:22:23] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:22:23] Explicit valence for atom # 18 C, 5, is greater than permitted

--- Processing cluster 4 ---
Calculation complete! Processed 5 clusters

                name type_cluster scaffold        RS       SED      ASER
0     Molpher_500k_0          dis      csk  0.375000  0.126759  0.003653
1     Molpher_500k_1          dis      csk  0.608696  0.127501  0.001134
2     Molpher_500k_2          dis      csk  0.100000  0.130766  0.000104
3     Molpher_500k_3          dis      csk  0.513513  0.136785  0.005927
4     Molpher_500k_4          dis      csk  0.790698  0.154582  0.011775
5  Molpher_500k_mean          dis      csk  0.477581  0.135278  0.004519

REINVENT_500k

============================================================
Starting calculation for REINVENT_500k
Receptor: Glucocorticoid_receptor
Cluster type: dis
Scaffold type: csk
CPUs: 100
============================================================

--- Processing cluster 0 ---

[12:23:27] Can't kekulize mol.  Unkekulized atoms: 29 30 31 32 33 34 35 39 40
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 29 31 32 33 42 43 44
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 30 31 32 33 34 35 37 38 42 43 44
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 27 28 29 30 31 33 39 40 41
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 36 37 38 39 40
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 17 18 19 20 21 22 23 32 33
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 30 32 33 34 41 42 50 51 52
[12:23:27] SMILES Parse Error: unclosed ring for input: 'CC(NC(NCc1n2ccsc2nc1C)=O)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c2cccc(N2CCCC2)c1'
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 5 6 7 9 10 11 24
[12:23:27] SMILES Parse Error: unclosed ring for input: 'CC(NC(c1ccc2c(c1)CCCO2)=O)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1n(CCF)c2cccc(OC3CCC4)c3c2C1'
[12:23:27] SMILES Parse Error: extra close parentheses while parsing: CC(C)C(CC(O)(Cc1cc2nc(C)oc2cc1)C(F)(F)F)C(C)N)(F)F
[12:23:27] SMILES Parse Error: check for mistakes around position 46:
[12:23:27] c2cc1)C(F)(F)F)C(C)N)(F)F
[12:23:27] ~~~~~~~~~~~~~~~~~~~~^
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 24 25 26 27 28 31 33 34
[12:23:27] SMILES Parse Error: Failed parsing SMILES 'CC(C)C(CC(O)(Cc1cc2nc(C)oc2cc1)C(F)(F)F)C(C)N)(F)F' for input: 'CC(C)C(CC(O)(Cc1cc2nc(C)oc2cc1)C(F)(F)F)C(C)N)(F)F'
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 30 31 32 33 36 37 38 39 40
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 26 28 29 36 37 39
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 32 33 34 36 38 39 40 41 42
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 32 33 34 35 37 38 39 40 41
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 10 11 12 13 14 15 22 23 24
[12:23:27] SMILES Parse Error: extra close parentheses while parsing: CC(CC(C(F)(F)F)(O)CNc1c2cnn(-c3cccnc3)c2cc(F)c1)C(O)(C)c1ncco1)C
[12:23:27] SMILES Parse Error: check for mistakes around position 63:
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 35 36 37 38 39 41 43
[12:23:27] (F)c1)C(O)(C)c1ncco1)C
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 12 13 14 15 16 17 18 27 28
[12:23:27] ~~~~~~~~~~~~~~~~~~~~^
[12:23:27] SMILES Parse Error: Failed parsing SMILES 'CC(CC(C(F)(F)F)(O)CNc1c2cnn(-c3cccnc3)c2cc(F)c1)C(O)(C)c1ncco1)C' for input: 'CC(CC(C(F)(F)F)(O)CNc1c2cnn(-c3cccnc3)c2cc(F)c1)C(O)(C)c1ncco1)C'
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 27 30 31 32 37 38
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 34 35 36 37 42 43 44 45 46
[12:23:27] SMILES Parse Error: extra close parentheses while parsing: CC(NC(NCc1sc2c(n1)CCCC2)=O)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1ccc2c(c1)N(C)CCO2)C
[12:23:27] SMILES Parse Error: check for mistakes around position 78:
[12:23:27] )c1ccc2c(c1)N(C)CCO2)C
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 29 31 32 33 42 43 44
[12:23:27] ~~~~~~~~~~~~~~~~~~~~^
[12:23:27] SMILES Parse Error: Failed parsing SMILES 'CC(NC(NCc1sc2c(n1)CCCC2)=O)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1ccc2c(c1)N(C)CCO2)C' for input: 'CC(NC(NCc1sc2c(n1)CCCC2)=O)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1ccc2c(c1)N(C)CCO2)C'
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 33 34 48
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 33 35 36 37 46 47 49
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 4 6 7 8 10 12 13 14 16 24 25
[12:23:27] Explicit valence for atom # 6 O, 5, is greater than permitted
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 26 27 28 29 30 44 45 46 47
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 6 7 8 9 11 12 13 14 15
[12:23:27] SMILES Parse Error: unclosed ring for input: 'CC(NC(NCc1cccnc1OC)=O)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1n(-c2cccc3c2c(C)no4)ccc3'
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 15 16 17 18 19 20 21 29 30 31 32
[12:23:27] SMILES Parse Error: unclosed ring for input: 'CC(NC(=O)c1cnn(CC)c1Cl)C(Oc1ccc2c(cnn2-c2ccncc2)c1)c1cc2c(C)noc3c(Cl)cc2c1'
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 24 25 26 27 29 30 31 32 33
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 5 6 9
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 28 29 30 31 32 35 36 37 38
[12:23:27] SMILES Parse Error: unclosed ring for input: 'CC(NC(COc1cccc(F)c1)=O)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c2ccc2c(O)oc1'
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 26 27 29 30 31 32 33 34 36 37 38
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 28 29 34
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 31 32 33 35 36 37
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 29 30 31 32 33 36 37 38 40
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 29 31 32 33 35 36 39
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 29 31 32 34 35 41 43
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 31 32 33 35 36 37 38 47 48
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 14 15 16 17 18 30 34
[12:23:27] SMILES Parse Error: ring closure 1 duplicates bond between atom 42 and atom 43 for input: 'CC(NC(Nc1cccc2cnc(C)cc21)=O)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c2cc2c(F)cnc1C1CCC1'
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 31 32 47
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 28 29 30 31 32 33 40
[12:23:27] Explicit valence for atom # 36 S, 7, is greater than permitted
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6 7 8 29 30
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 6 7 8 9 10 11 12
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 25 26 27 28 29 32 33
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 31 32 42 43 44 45 46 47 48 49 50
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 28 31 32 33 34 41 42 45 46
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 29 30 31 32 33 34 36 37 45 46 47
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 30 31 32 33 34 35 36 42 43
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 28 29 30 31 32
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 47 48 49
[12:23:27] SMILES Parse Error: extra close parentheses while parsing: CC(NC(=O)c1ccnn1C)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1cc2c(c(C)cc(N(C)C)n2)cc1)(C)C
[12:23:27] SMILES Parse Error: check for mistakes around position 76:
[12:23:27] (c(C)cc(N(C)C)n2)cc1)(C)C
[12:23:27] ~~~~~~~~~~~~~~~~~~~~^
[12:23:27] SMILES Parse Error: Failed parsing SMILES 'CC(NC(=O)c1ccnn1C)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1cc2c(c(C)cc(N(C)C)n2)cc1)(C)C' for input: 'CC(NC(=O)c1ccnn1C)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1cc2c(c(C)cc(N(C)C)n2)cc1)(C)C'
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 30 31 32 33 34 35 36 37 40
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 15 16 17
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 36 37 38 41 42
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 1 2 10 12 13 14 19 20 21
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 30 31 32 34 36 37 40
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 29 30 31 32 37 38 40
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 5 7 8
[12:23:27] SMILES Parse Error: unclosed ring for input: 'CC(=O)NC(C)C(Oc2ccc3c(cnn3-c3cncnc3)c2CC1)C(c1ccccc1)Oc1ccc2c(cnn2-c2ccc(F)cc2)c1'
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 30 31 32 35 37 38 39
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 31 33 34 35 36 37
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 27 29 30 31 32 33 34 38 39
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 28 29 30 32 33 34 36
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 31 32 33 34 36 37 44
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 35 36 37 38 39 40 41 42 43
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 29 30 31 32 34 35 37 41 42
[12:23:27] SMILES Parse Error: unclosed ring for input: 'CC(NC(N1CCC(c2cc3c(ccc(F)c3)[nH]2)CC1)=O)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)cc3c1CCCNC1)Cn1cncc1'
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 6 7 8 9 10 12 13 14 15 16 17
[12:23:27] SMILES Parse Error: ring closure 1 duplicates bond between atom 13 and atom 14 for input: 'CC(NC(NCc1cnc2c(c1)CC1(C1)C(=O)N(C)C(=O)N(C)C2=O)=O)c1n(N2CCCCC2)c(=O)c2c(cc(F)cc2F)n1'
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 28 29 40 41 48
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 33 34 35 36 37 38 39 43 44
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 32 34 35 36 37 38
[12:23:27] SMILES Parse Error: unclosed ring for input: 'CCNC(=O)c1oc(OC)cc1C=C2C(=O)Nc2cc(F)c(F)c1'
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 36 37 38 39 42 43 44
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 2 3 5 6 8 9 10 11 12 13 14
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 28 29 30 32 33 34 37
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 30 31 45
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 4 5 6 7 8 9 10 11 12
[12:23:27] Can't kekulize mol.  Unkekulized atoms: 15 16 17 18 19 20 21 32 33
[12:23:28] Explicit valence for atom # 38 N, 4, is greater than permitted
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 30 31 32 33 34 35 38 39 40
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 27 30 31 32 33 34 42 43 44
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 27 29 30 37 38 40
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 4 5 6 7 8 9 10 13 14
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 34 35 36 38 40 41 51 52 53
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 2 3 5 6 7 34 35
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 28 29 30 31 32 33 39
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 33 34 35 39 40
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 2 3 5 6 7 9 11 24 25
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 4 6 7 8 9 11
[12:23:28] SMILES Parse Error: unclosed ring for input: 'CC(NC(=O)Cc1noc(-c2cccs2)c1)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1ccc2c(c1)OCC1CC2C1(C)CCCC1'
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 31 32 33 35 36 37 38 41 42
[12:23:28] SMILES Parse Error: unclosed ring for input: 'CC(NC(c1nccnc1)=O)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1csc2c1nnn(-c1ccc(F)c(Cl)c1)c1=N2'
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 24 26 27 28 36 37
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 14 15 16 17 18 19 20 22 23 24 25 26 28
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 33 35 36 37 38 39
[12:23:28] SMILES Parse Error: ring closure 1 duplicates bond between atom 1 and atom 2 for input: 'oc1-c1ccc2c(c(C(C)=O)cn2CC(C)C)c1C#N'
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 4 5 7 8 9 10 11 24 25
[12:23:28] Explicit valence for atom # 39 C greater than permitted
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 33 35 36 38 39 42
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 5 6 8 10 11 12 13
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 29 30 31 32 33 34 36
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 2 3 5 6 7 8 9 10 11 12 13 14 24 25 26 27 28 30 31 32
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 27 29 30 31 32 33
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 5 6 7 8 9
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 36 37 38 39 40 41 47 49 50
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 29 31 32 33 34 35 36 41
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 28 30 31 32 33 34
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 27 30 31 32 39 40 42
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 29 30 31 33 35
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 29 30 31 33 35 36 39
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 4 5 6 7 9 10 16 17 18
[12:23:28] Explicit valence for atom # 35 C greater than permitted
[12:23:28] SMILES Parse Error: unclosed ring for input: 'CC(NC(NC1CCCCC1)=O)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c2ccc2c(nn(C)c2)c1'
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 6 7 8 9 11 12 13 14 15
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 29 31 32 33 34 35 41 42 43
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 29 30 31 32 33 34 38 40 41
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 31 34 35 36 37 44
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 32 33 34 35 36 37 41 43 44
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 30 31 32 34 36 37 46 47 48
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 27 28 29 30 31 32 33 34 35 43 44
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 30 31 32 34 35 36 37 38 46
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 30 31 32 34 36 37 47 48 49
[12:23:28] SMILES Parse Error: unclosed ring for input: 'CC(NC(=O)c1cccnn1)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1cc(F)c2oc(C3OCCC3)nc3c2c1'
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 33 34 35 36 37 38 39 40 41
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 26 27 28 29 37 38 39 42
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 26 27 28 29 30 31 32 33 34 35 36
[12:23:28] Explicit valence for atom # 7 C, 5, is greater than permitted
[12:23:28] SMILES Parse Error: unclosed ring for input: 'CC(NC(=O)c1ncoc1C)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1cc2c(cc(C)nc2C)nc1N1CC2(OCC1)CC4OCC2'
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 4 5 6 7 8 9 10 12 17 18 19
[12:23:28] SMILES Parse Error: ring closure 1 duplicates bond between atom 30 and atom 31 for input: 'CC(NC(=O)c1cc(C)cnc1)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1c1cncn1'
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 6 8 9 10 11 18
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 30 31 32 33 34 35 43 44 45
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 3 4 5 7 8 9 10 11 21
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 5 6 7 8 9 10 11 12 13 15 16
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 34 35 36 38 39 40 43 45 48
[12:23:28] Explicit valence for atom # 5 C, 6, is greater than permitted
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 9 10 11 12 13 14 22 23 24 26 28
[12:23:28] SMILES Parse Error: extra open parentheses while parsing: CC(NC(=O)c1cc2c(c(F)c1)OCCN2
[12:23:28] SMILES Parse Error: check for mistakes around position 3:
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 19 20 21 22 23 24 25 32 33
[12:23:28] CC(NC(=O)c1cc2c(c(F)c1)OCCN2
[12:23:28] ~~^
[12:23:28] SMILES Parse Error: Failed parsing SMILES 'CC(NC(=O)c1cc2c(c(F)c1)OCCN2' for input: 'CC(NC(=O)c1cc2c(c(F)c1)OCCN2'
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 29 30 31 32 33 34 35 36 37
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 28 29 30 31 32 33 34 35 42
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 2 3 5 6 7 8 9 10 11 12 14 15 22 23 25 28 29
[12:23:28] SMILES Parse Error: unclosed ring for input: 'CC(NC(Cc1cscn1)=O)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1cc(OC)c1c(F)ccc1'
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 7 8 9 10 11 35 36
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 31 32 33 34 35 36 44
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 28 29 30 32 33 39 40 41 42
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 30 32 33 38 39 40
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 19 20 21 22 23
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 33 35 36 37 39 40 43
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 8 10 11 12
[12:23:28] SMILES Parse Error: unclosed ring for input: 'CC(NC(c1cncs1)=O)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c2cc(F)c2oc(-c2ccc(F)cc2)cc1=O'
[12:23:28] SMILES Parse Error: extra close parentheses while parsing: CC(NC(=O)C(C)(F)F)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1ccnc(-c2ccnn2C)c1)(C)C
[12:23:28] SMILES Parse Error: check for mistakes around position 69:
[12:23:28] )c1ccnc(-c2ccnn2C)c1)(C)C
[12:23:28] ~~~~~~~~~~~~~~~~~~~~^
[12:23:28] SMILES Parse Error: Failed parsing SMILES 'CC(NC(=O)C(C)(F)F)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1ccnc(-c2ccnn2C)c1)(C)C' for input: 'CC(NC(=O)C(C)(F)F)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1ccnc(-c2ccnn2C)c1)(C)C'
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 4 5 6 8 11 12 14
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 34 35 36 37 38 39 43 45 46
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 3 30 31
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 7 8 9 10 12 13 14
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 29 30 31 32 33 34 40 42 43
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 29 31 32 33 34 35 36 42
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 4 6 7 20
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 35 36 37 39 40 41 42 47 48
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 32 33 34 35 37 38 39 40 41
[12:23:28] SMILES Parse Error: ring closure 3 duplicates bond between atom 38 and atom 39 for input: 'CC(NC(=O)Cc1csc(C)n1)C(Oc1ccc2c(cnn2-c2ccc(F)cc2F)c1)c1ccc(N2CCC3(C3)CC2)nc1'
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 10 11 13 14 15 16 17
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 30 32 33 34 41 42 44
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 28 31 32 33 34 41
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 38 39 40
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 4 5 7 9 11 14
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 2 3 6 7 9 12 13 15 17 19 21
[12:23:28] SMILES Parse Error: unclosed ring for input: 'CC(=O)NC(C)C(Oc1ccc2c(cnn2-c2ccsc2)c1)c1ccc2c(c1)OCCO3'
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 26 28 29 30 43 44 46
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 30 32 33 34 35 36
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 5 6 7 8 9 10 11 13 16 20 21 22
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 29 30 31 32 33 34 35 36 42
[12:23:28] SMILES Parse Error: unclosed ring for input: 'CC(NC(=O)c1sc2c(Cl)cccc2c1)C(Oc2ccc2c(cnn2-c3ccc(F)cc3)c(=O)c-2c(C)c1)c1cc(F)c(F)c(F)c1'
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 32 33 34 36 42
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 5 6 7 8 9 10 12 13 14
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 0 1 13 14 21
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 5 7 8 10 11 12 13 14 17
[12:23:28] SMILES Parse Error: ring closure 1 duplicates bond between atom 37 and atom 41 for input: 'CC(NC(=O)c1cn(C)cn1)C(Oc1ccc2c(cnn2-c2ccsc2)c1)c1cc(F)c2c(c1)OCCC1(CCC2)C1'
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 28 29 30 31 33 35 37 38 39
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 28 30 31 33 34 36 38
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 28 30 31 35 36 37 38 39 40
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 0 1 29 30 31 32 33
[12:23:28] Explicit valence for atom # 17 Cl, 2, is greater than permitted
[12:23:28] Explicit valence for atom # 2 C greater than permitted
[12:23:28] SMILES Parse Error: extra close parentheses while parsing: CC(=O)NC(C)C(Cc1cc(C)c(C)cc1)(O)C(F)(F)F)c1cccc(F)c1
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 33 34 35 36 37 38 39 40 41
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 30 42
[12:23:28] SMILES Parse Error: check for mistakes around position 41:
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 0 1 29 30 31 32 33 34 36
[12:23:28] )c(C)cc1)(O)C(F)(F)F)c1cccc(F)c1
[12:23:28] SMILES Parse Error: unclosed ring for input: 'CC(NC(c1c(F)cccn1)=O)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1cc1c(-c2cc(C)cnc2F)ncn1'
[12:23:28] ~~~~~~~~~~~~~~~~~~~~^
[12:23:28] SMILES Parse Error: Failed parsing SMILES 'CC(=O)NC(C)C(Cc1cc(C)c(C)cc1)(O)C(F)(F)F)c1cccc(F)c1' for input: 'CC(=O)NC(C)C(Cc1cc(C)c(C)cc1)(O)C(F)(F)F)c1cccc(F)c1'
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 34 36 37 38 39 40
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 28 29 30 31 33 34 35 36 37
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 17 20 24
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 9 11
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 30 32 33 41 42 44
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 12 13 14 16 35
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 28 29 34
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 29 30 31 33 35 36 37 44 45
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 30 31 32 34 35 36 37 38 40
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 12 13 14 15 16 17 18 29 30
[12:23:28] SMILES Parse Error: unclosed ring for input: 'CC(NC(Nc1c2c(cncc3)ccc2)c(C)cc1)=O'
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 32 33 34 36 37 38 46 47 48
[12:23:28] Can't kekulize mol.  Unkekulized atoms: 5 6 7 8 9 10 11

--- Processing cluster 1 ---

[12:24:11] SMILES Parse Error: extra close parentheses while parsing: CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CC(CC1NC(=O)c3ccccc3N1C)C)C2
[12:24:11] SMILES Parse Error: check for mistakes around position 56:
[12:24:11] 1NC(=O)c3ccccc3N1C)C)C2
[12:24:11] ~~~~~~~~~~~~~~~~~~~~^
[12:24:11] SMILES Parse Error: Failed parsing SMILES 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CC(CC1NC(=O)c3ccccc3N1C)C)C2' for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CC(CC1NC(=O)c3ccccc3N1C)C)C2'
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 27 28 29 30 31
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 30 31 32
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 21 23 24 25 26 27
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 23 24 25 26 28 29 31 32 33
[12:24:11] SMILES Parse Error: unclosed ring for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCN(CC(=O)N(CCC)C1CCc3c1ccc(-n4cccn4)n1C3)C2'
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 25 26 28 29 30
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 25 26 27 35 36
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 20 21 22 31 32
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 2 4 5 6 7
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 25 26 27 32 33
[12:24:11] SMILES Parse Error: ring closure 4 duplicates bond between atom 26 and atom 30 for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CC(CC1CN(C(CC3C4(CCC3)C4)C)CCC1)C2'
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 26 27 28 29 30 31 32 33 34
[12:24:11] Explicit valence for atom # 26 C, 5, is greater than permitted
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 22 23 24 26 29
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 26 27 28 29 30
[12:24:11] SMILES Parse Error: unclosed ring for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2C1CN2CCc3c(c(-c3cccnc3)c(C)cn2)C1'
[12:24:11] SMILES Parse Error: ring closure 2 duplicates bond between atom 33 and atom 34 for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2CC(=O)C1CCCC1C(N)C(N1CC2C2CNC1)C'
[12:24:11] SMILES Parse Error: unclosed ring for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CC(CN1CCc3c(C)nn4c5c(n(C)c3C1)ccc(OC)c4c2)CC4C'
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 10 11 12 25 26 27 28 29 30
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 30 31 35
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 20 24 25 30 32
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 20 21 25
[12:24:11] Explicit valence for atom # 25 O, 3, is greater than permitted
[12:24:11] Explicit valence for atom # 26 C, 5, is greater than permitted
[12:24:11] SMILES Parse Error: duplicated ring closure 1 bonds atom 20 to itself for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CC(CC11CCN(C(=O)COc3ccc(OC)cc3)CC1)CC2'
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 20 21 22 23 26 27 34 35 36
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 24 25 26 35 36
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 29 30 34
[12:24:11] SMILES Parse Error: ring closure 1 duplicates bond between atom 22 and atom 26 for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2C(CC1(C2CC2)C1)NC(=O)C1C(C)(C)C1'
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 26 29 30
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 20 21 22 23 24 25 26
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 23 24 26
[12:24:11] SMILES Parse Error: unclosed ring for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2N1CC(C)N(Cc2cccc3c2nccc3-c2c(C)nnc3C)CC2CC1'
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 22 23 25 26 27 33 34 35 36
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 25
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 20 22 23 24 29 30
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 21 22 24 25 26 28 29
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 24 25 26 27 29 31 32 33 35
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 22 23 27 28 29 30 31 32 33
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 20 21 31
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 25 26 28 29 30 33 34
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 31 32 33
[12:24:11] SMILES Parse Error: unclosed ring for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2C1CN2CCc3c(ccc(-c3ccc(O)cc3)c2)C1c1ccsc1'
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 26 27 28 29 30 31 32 33 34
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 30 31 32 33 34 36 37 38 39
[12:24:11] SMILES Parse Error: ring closure 1 duplicates bond between atom 22 and atom 23 for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CC(N(C(=O)c1c1c(C)no1)CC1CCCCC1)CC2'
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 25 26 27 34 35
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 21 22 25 26 41 42 43
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 26 27 36 37 38
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 22 23 24 26 27 29
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 23 24 25 26 27 28 32
[12:24:11] Explicit valence for atom # 22 O, 4, is greater than permitted
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 25 26 27 35 36
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 23 24 25 26 29
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 28 29 30 32 33
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 20 21 22 23 24 25 26 32 33
[12:24:11] SMILES Parse Error: unclosed ring for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2C1CN2CCc3c(c(NC(=O)CC(O)(C(F)(F)F)CNc3cccc(C#N)c3)C)ccc2C1'
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 24 25 26 27 28
[12:24:11] Explicit valence for atom # 20 C, 5, is greater than permitted
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 23 24 25
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 26
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 20 22 23 24 25 26 27 28 30 32 33
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 26 30 31 32 33
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 21 22 23 25 26 29 30 31
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 33 34 36 37 38
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 23 24 25 26 27 28 29 30 31
[12:24:11] Explicit valence for atom # 19 C, 5, is greater than permitted
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 22 23 27 29 30 32 33
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 23 24 25 26 27 32 33 34 35
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 23 24 25 26 31 32 33
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 20 21 22
[12:24:11] SMILES Parse Error: unclosed ring for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CC(n1cnc(Cc3ccccc3)c1)C3C2'
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 25 26 27 35 36
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 21 24 25 26 27
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 20 22 23 28 29 30 40
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 28 29 30 31 32
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 25 26 27 33 34 36
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 23 24 25 26 29
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 25 26 27 28 29 31 33
[12:24:11] SMILES Parse Error: ring closure 1 duplicates bond between atom 20 and atom 21 for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CC(Cc1n1cc(Cl)cc2)(Cc1ccncc1)C'
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 3 4 5 14 19 20 21 22 23
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 22 23 24 26 27
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 29 30 31
[12:24:11] SMILES Parse Error: unclosed ring for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2C1CN2CCc3ccc(-c3c(F)nccc3)cc2C1C'
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 32 33 34 35 36
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 24 25 26 37 38
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 27 28 31
[12:24:11] SMILES Parse Error: unclosed ring for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2C1CN2CCN(c4ncccc4Cl)CC2CC1C3'
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 3 4 5 14 24 25 26 27 36 37 38
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 20 21 22 23 24
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 26 36 38 39 40 41 42 43
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 28 29 30
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 26 27 28 29 30 31 32
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 24 25 27 28 35
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 26 35 36 37 38
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 24 26 27 28 29 30 31
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 26 27 28 29 30
[12:24:11] Explicit valence for atom # 19 N, 4, is greater than permitted
[12:24:11] Explicit valence for atom # 19 C, 5, is greater than permitted
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 25 26 27 28 29
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 34 36 37
[12:24:11] SMILES Parse Error: unclosed ring for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2Cn1ncc2c1-c1c(cc(C)nc1C(F)(F)F)CC1C=C2'
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 22 24 25 36 37 38 39
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 25 26 29 30 31
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 25 26 27 28 35
[12:24:11] non-ring atom 25 marked aromatic
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 23 24 25 27 28
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 20 25 32
[12:24:11] SMILES Parse Error: unclosed ring for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2C1CN2CCC3C1(CNCc1ccc(Cl)cc1)C2'
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 20 22 23 24 26 27 28 30 31 34
[12:24:11] SMILES Parse Error: ring closure 1 duplicates bond between atom 23 and atom 24 for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2C(C)(N=c1c1c(C)ccn1-c1c(Cl)cc(F)cc1)C'
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 27 28 29 30 31
[12:24:11] SMILES Parse Error: unclosed ring for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2C1CN2CCc3c(c(N=CNC3CCCCC3)cc(OC)c2O)C1'
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 21 22 23 26 28 29
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 22 23 27 28 32 33 34
[12:24:11] Explicit valence for atom # 20 C, 5, is greater than permitted
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 21 22 23 26 27 28 29 30 31 33
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 23 24 25 38 39
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 23 24 25 26 28
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 23 24 25 26 27
[12:24:11] Explicit valence for atom # 30 N, 5, is greater than permitted
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 22 24 25 26 27 41
[12:24:11] Explicit valence for atom # 23 N, 4, is greater than permitted
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 30 32 33 34 35 36 37
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 25 26 32 33 34
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 21 22 24 25 26 31 32
[12:24:11] Explicit valence for atom # 20 N, 4, is greater than permitted
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 4 5 6 7 16 18 19 20 21
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 20 21 23 24 25 26 27
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 24 25 26
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 4 6 8 9 11 12 24
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 25 26 27 28 29 30 41 42 43
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 22 23 24 39
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 30 31 32
[12:24:11] SMILES Parse Error: ring closure 1 duplicates bond between atom 38 and atom 39 for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2C(CN(C(=O)C(C)(C)C)Cc1cc2c(cn1)CCn1c1ccc2)C'
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 24 25 26 27 29 31 32 33 34 35 36 37 38
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 23 24 25 26 27 30 32 33 34
[12:24:11] Explicit valence for atom # 22 N, 4, is greater than permitted
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 4 5 6 7 9 10 18 19 20 21 34 35 36
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 22 23 24 33 34
[12:24:11] SMILES Parse Error: unclosed ring for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2C1CN2CCN(c4nc(N5CCOCC5)ncc4)CC2CCC1C3'
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 25 26 28
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 3 4 5 14 24 25 26 33 35
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 27 28 29 30 31 32 34
[12:24:11] Explicit valence for atom # 23 C, 5, is greater than permitted
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 21 24 25 28 29 30 33 34 36 37
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 22 23 24 26 28 29 30 31 32
[12:24:11] SMILES Parse Error: ring closure 1 duplicates bond between atom 21 and atom 33 for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCCC2C1(Cc2cccc3n(C)ccc23)C1'
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5 7 8 9 11
[12:24:11] SMILES Parse Error: ring closure 2 duplicates bond between atom 31 and atom 32 for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CC(=Cc1cccs1)C2=NOCC1(C)C2C2c2c(cc(O)cc2)C1'
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 27 28 29 31 35 36 38 39 40
[12:24:11] Explicit valence for atom # 24 C, 5, is greater than permitted
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 22 23 25 26 27 28 29 30 31 32 33
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 28
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 36 37 38 40 41
[12:24:11] SMILES Parse Error: ring closure 2 duplicates bond between atom 37 and atom 38 for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2CC(C1C=C2C(C)C(=O)CC2C(C)(CO)C1)CC2C2C'
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 3 4 5 14 26
[12:24:11] SMILES Parse Error: unclosed ring for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2C1CN2CCc3c(cnn2)C1'
[12:24:11] SMILES Parse Error: unclosed ring for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2C1CC(CC(=O)N2CCN(CC(N3C4CCC3CC3)CCC4)CC2)CC1'
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 24 25 26 27 35
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 30 31 32 33 34 35 36 37 38
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6 7 14 15 16 17 18 19 22
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 25
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 26 27 33 34 35 36 37
[12:24:11] Explicit valence for atom # 32 O, 3, is greater than permitted
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 25
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 25 26 27 28 29 30 31
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 26 27 28 35 36
[12:24:11] SMILES Parse Error: unclosed ring for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2C(=O)c1cc(-n3cccn2)ccc3ccc1'
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 20 22 23 24
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 25 26 27 28 31
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 21 22 24 25 31 32 33
[12:24:11] SMILES Parse Error: unclosed ring for input: 'CC12Cc3cnn(-c5ccc(F)cc3)c1CCC2C1(O)CCC2C(CCc3c2ccc(C(N2CCCC2)=O)c3)C1'
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 21 22 24 25 26 28
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 26 27 28
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 21 22 24 25 26 27 28 29 30 31 32
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 27 28 30 31 32
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 27
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 34 35 36
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 26 28
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 23 24 26 27 28
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 30
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 26 29 30
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 26 27 28 30 32
[12:24:11] SMILES Parse Error: unclosed ring for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2C1CN2CCN(C(CN)=O)C(=O)C2CC1C3'
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 26 27 29 30 32 33 34
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 23 24 25 27 34 35 36 37
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 20 21 24 25 26 27 33
[12:24:11] Explicit valence for atom # 28 N, 4, is greater than permitted
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 26 28 35 36 37
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 25 26 27 28 29 30 31 32 33
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 3 4 5 14 22 23 24 32 35
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 23 25 38 39 40
[12:24:11] SMILES Parse Error: ring closure 4 duplicates bond between atom 24 and atom 33 for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CC(CC1CC3(C)C4(CCCC3=CC(=O)C1)C4)CC2'
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 24 25 26 27 28
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 26 27 30 31 32 33 34
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 21 22 32
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 23 24 28 29 31 32 33 34 35
[12:24:11] SMILES Parse Error: unclosed ring for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCN(Cc1cccc(Cl)c1)C24CCN(C)CC1CC1'
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 27 31 32 33 34
[12:24:11] SMILES Parse Error: unclosed ring for input: 'S(N)(=O)(c1ccc(-n2ncc3c2C=C2CCCC(C(c4c5c(ccc2)OCCO4)S(=O)(=O)C3)ccc4F)cc2c(C)cc(=O)[nH]c21)=O'
[12:24:11] SMILES Parse Error: unclosed ring for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2C(CSc1nc2n(C)ccc3cc2nn1)(O)C(C)(C)C'
[12:24:11] SMILES Parse Error: ring closure 2 duplicates bond between atom 26 and atom 35 for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2C(CN(C1CCC2(c3cnc(OC)nc3)C2C1)C)C'
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 3 4 5 14 20 21 22 23 25 31 32
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 22 24 25 26 27 28 29 31 32 33 34 35 36
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 20 21 22 28 29
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 24 37 38 39 40 42
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 22 23 24
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 3 4 5 6 7 8 9 10 11
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 23 24 25 27 37
[12:24:11] Explicit valence for atom # 19 C, 5, is greater than permitted
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 21 22 23 33 35
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 28 29 31 32 33 34 35
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 23 24 25 26 27 28 29 30 31
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 25 26 27 34 35
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 22 23 28 29 30
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 3 4 5 14 21 22 23 24 25 26 27 28 29
[12:24:11] Explicit valence for atom # 21 C, 6, is greater than permitted
[12:24:11] SMILES Parse Error: unclosed ring for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2C1CC2=C(C)CCC3C2(CC1)C#N'
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 27 28 29 30 31 32 33
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 23 24 25 26 27 29 31 32 33
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 28 29 30 31 32 33 34 35 36
[12:24:11] SMILES Parse Error: ring closure 2 duplicates bond between atom 28 and atom 31 for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2C1(c2ccccn2)CC2(CC)C2C=C1'
[12:24:11] Explicit valence for atom # 22 O, 3, is greater than permitted
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 20 21 22 28 29 30 32
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 25 26 37 38 39
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 20 21 22 23 24
[12:24:11] Explicit valence for atom # 26 C, 5, is greater than permitted
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 21 22 23
[12:24:11] Explicit valence for atom # 25 C, 5, is greater than permitted
[12:24:11] SMILES Parse Error: unclosed ring for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2C1CCc2cc(F)cc3c2C1C1CCCN1C'
[12:24:11] SMILES Parse Error: unclosed ring for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCCC2NCc1c(-n2cncn3)cccc2CC1'
[12:24:11] Can't kekulize mol.  Unkekulized atoms: 21 22 23 27 28 29 30

--- Processing cluster 2 ---

[12:24:44] SMILES Parse Error: ring closure 1 duplicates bond between atom 31 and atom 32 for input: 'CC(NC(=O)c1cnncc1)C(Oc1ccc2c(cnn2-c2ccc3c(c2)CCC3)c1)c1c1cncc1'
[12:24:44] Can't kekulize mol.  Unkekulized atoms: 36 37 38 39 40 42
[12:24:44] SMILES Parse Error: unclosed ring for input: 'ClC(C#Cc2cncnc2)nc1'
[12:24:44] SMILES Parse Error: unclosed ring for input: 'CC(NC(=O)c1cc[nH]n1)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1cn(C23CC4CC(C2)CC3)nc1'
[12:24:44] Can't kekulize mol.  Unkekulized atoms: 27 29 31 32 33 39
[12:24:44] Can't kekulize mol.  Unkekulized atoms: 31 32 33 34 36
[12:24:44] Can't kekulize mol.  Unkekulized atoms: 27 28 30 31 32 33 34 35 36 38 39
[12:24:44] Can't kekulize mol.  Unkekulized atoms: 31 32 34 35 36 37 38 40 41 42 43 44 45
[12:24:44] Can't kekulize mol.  Unkekulized atoms: 32 33 35 36 42 43 44
[12:24:44] Can't kekulize mol.  Unkekulized atoms: 29 30 31
[12:24:44] Can't kekulize mol.  Unkekulized atoms: 33 34 35 36 37 41 42 43 44 45 46
[12:24:44] Can't kekulize mol.  Unkekulized atoms: 29 31 33 35 36 37 38
[12:24:44] Can't kekulize mol.  Unkekulized atoms: 32 33 36 37 38 39 40 41 42
[12:24:44] Can't kekulize mol.  Unkekulized atoms: 25 26 27 28 29 30 31 32 33
[12:24:44] Can't kekulize mol.  Unkekulized atoms: 17 18 19 20 21 22 23 27 40
[12:24:44] Can't kekulize mol.  Unkekulized atoms: 19 20 21 26 27
[12:24:44] Can't kekulize mol.  Unkekulized atoms: 20 21 22 23 24 27 29
[12:24:44] Can't kekulize mol.  Unkekulized atoms: 27 28 29 30 31 32 33 34 35 36 37
[12:24:44] SMILES Parse Error: unclosed ring for input: 'CC(NC(=O)NCC1OCCC1)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1nnn(C2CCC3C(C)CCC4C3(OO3)CCC(C)C24)c1'
[12:24:44] Can't kekulize mol.  Unkekulized atoms: 40 42 43 44 45 46
[12:24:44] Can't kekulize mol.  Unkekulized atoms: 28 29 30 31 34 46
[12:24:44] Can't kekulize mol.  Unkekulized atoms: 33 34 35 36 37 38 41 43 44
[12:24:44] Can't kekulize mol.  Unkekulized atoms: 10 17 18
[12:24:44] Can't kekulize mol.  Unkekulized atoms: 9 13 14
[12:24:44] Can't kekulize mol.  Unkekulized atoms: 5 6 7 8 11 12 13 14 15
[12:24:44] Can't kekulize mol.  Unkekulized atoms: 6 7 9 10 11
[12:24:44] Can't kekulize mol.  Unkekulized atoms: 30 32 34 36 37 38
[12:24:44] Can't kekulize mol.  Unkekulized atoms: 29 30 31 32 37 38 39
[12:24:44] Can't kekulize mol.  Unkekulized atoms: 32 33 34 35 36 38 40 41 43
[12:24:44] Can't kekulize mol.  Unkekulized atoms: 5 8 9
[12:24:44] Can't kekulize mol.  Unkekulized atoms: 30 31 32 33 34 36 38 39 41 42 43
[12:24:44] SMILES Parse Error: unclosed ring for input: 'CC(NC(N2CCN(c2ccccn1)CC2)=O)C(Oc1ccc2c(cnn2-c2ccncc2)c1)c1cocc1'
[12:24:44] SMILES Parse Error: ring closure 2 duplicates bond between atom 34 and atom 35 for input: 'CC(NC(c1c(Cl)cc(Cl)cc1)=O)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1nnc2n2CCC1'
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 29 31 32 33 34
[12:24:44] Explicit valence for atom # 39 C greater than permitted
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 29 30 31 33 34 38 39 41 42
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 5 6 7 8 17 19 20 21 22
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 31 32 33 35 36 37 38 47 48
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 28 29 31 32 33
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 33 34 39 40 41
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 29 30 31 32 33 37 38 39 40
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 32 33 34 35 36 46 48 49 50
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 31 33 34 35 42 43 44 45 46
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 19 20 21 22 25 27 28
[12:24:45] SMILES Parse Error: extra open parentheses while parsing: CC(NC(c1[nH]c2ccc(Cl
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 5 16 17 18 19
[12:24:45] SMILES Parse Error: check for mistakes around position 3:
[12:24:45] CC(NC(c1[nH]c2ccc(Cl
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 29 31 33 35 36 41 42
[12:24:45] ~~^
[12:24:45] SMILES Parse Error: extra open parentheses while parsing: CC(NC(c1[nH]c2ccc(Cl
[12:24:45] SMILES Parse Error: check for mistakes around position 6:
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 27 28 29 31 32 33 35 36 37
[12:24:45] CC(NC(c1[nH]c2ccc(Cl
[12:24:45] ~~~~~^
[12:24:45] SMILES Parse Error: extra open parentheses while parsing: CC(NC(c1[nH]c2ccc(Cl
[12:24:45] SMILES Parse Error: check for mistakes around position 18:
[12:24:45] CC(NC(c1[nH]c2ccc(Cl
[12:24:45] ~~~~~~~~~~~~~~~~~^
[12:24:45] SMILES Parse Error: Failed parsing SMILES 'CC(NC(c1[nH]c2ccc(Cl' for input: 'CC(NC(c1[nH]c2ccc(Cl'
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 32 33 35 36 37 38 56
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 38 39 40 41 42 43 48 49 50
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 32 33 34 36 37 38 39
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 29 30 31 32 33 43 44 45 46
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 6 7 8 9 16 17 18 19 20
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 28 29 30 40 41 42 45
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 29 30 33 34 37 41 42
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 32 33 34 36 37
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 30 31 32 34 35
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 29 30 31 32 33 45 46 47 48
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 2 3 4 6 7 8 9 12 13
[12:24:45] SMILES Parse Error: extra close parentheses while parsing: CC(NC(=O)c1ccncc1)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1ccn2c(c1)c(C)cn2)(CC)CC
[12:24:45] SMILES Parse Error: check for mistakes around position 68:
[12:24:45] 1)c1ccn2c(c1)c(C)cn2)(CC)CC
[12:24:45] ~~~~~~~~~~~~~~~~~~~~^
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 6 7 8 9 10 12 13 14 15 16 17
[12:24:45] SMILES Parse Error: Failed parsing SMILES 'CC(NC(=O)c1ccncc1)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1ccn2c(c1)c(C)cn2)(CC)CC' for input: 'CC(NC(=O)c1ccncc1)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1ccn2c(c1)c(C)cn2)(CC)CC'
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 8 9 10 11 12 13 14 16 17 20 21 22 23 24 25
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 5 6 8 10 11 12 14
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 5 6 7 8 9 10 14
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6 9 10 11 12 14 15 16 17 18 23 24 25
[12:24:45] SMILES Parse Error: unclosed ring for input: 'c1c(-n2ncc3cc(-c4ncnc5c4cc(F)cn4)cccc2c3)cnc(OC(C)C)c1'
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 32 33 34 35 36 38 40 41 43 44 45
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 28 29 30 31 32 33 36 38 39
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 30 31 32 33 34 35 36 37 38 39 40
[12:24:45] SMILES Parse Error: unclosed ring for input: 'CC(NC(c1cnccn1)=O)C(Oc2cccc2cccn1)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1cc(F)cnc1'
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 31 33 34 35 36 37
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 31 32 33 34 35 37 39 40 41
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 36 37 38 39 40 42 43 50 51
[12:24:45] SMILES Parse Error: unclosed ring for input: 'CC(NC(=O)c1cccc2c1CCCC2)C(Oc1ccc2c(cnn2-c2cccnc2)c1)c1nn1ccc1C(F)(F)F'
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 7 8 9 10 11 18 19
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 26 27 28 29 31 32 33 34 36
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 25 26 27 28 29 30 43 44 45
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 6 7 8
[12:24:45] SMILES Parse Error: unclosed ring for input: 'CC(NC(=O)N1CCC(OC)C1)C(Oc1ccc2c(cnn2-c3ccc(F)cc2)cc3c(-c2ccncc2)n1)c1ccc(C)cc1'
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 5 6 7 8 9 15 16 17 18
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 7 8 9 10 33 34 35
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 11 12 13 14 15 19 20
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 22 23 24 29 30
[12:24:45] Explicit valence for atom # 37 N, 6, is greater than permitted
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 27 28 30 31 33 34 36 37 38
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 20 21 22 23 24 25 26 27 28
[12:24:45] SMILES Parse Error: unclosed ring for input: 'c1c(-n2ncc3cc(OC(c4ccccn4)C(C)NC(=O)c4n(C)ccc4)ccc23)cc2c(c1)c2c(C)nn(C)c1=O'
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 7 8 9 10 11 12 13 29 30
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 27 28 29 30 32 33 35 36 37
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 23 24 25 26 27 28 29 30 31
[12:24:45] SMILES Parse Error: extra close parentheses while parsing: CC(NC(=O)c1c(SC)cccc1)C(Oc1ccc2c(cnn2-c2cccnc2)c1)c1cnn(C(C)(C(F)(F)F)F)c1)C
[12:24:45] SMILES Parse Error: check for mistakes around position 75:
[12:24:45] n(C(C)(C(F)(F)F)F)c1)C
[12:24:45] ~~~~~~~~~~~~~~~~~~~~^
[12:24:45] SMILES Parse Error: Failed parsing SMILES 'CC(NC(=O)c1c(SC)cccc1)C(Oc1ccc2c(cnn2-c2cccnc2)c1)c1cnn(C(C)(C(F)(F)F)F)c1)C' for input: 'CC(NC(=O)c1c(SC)cccc1)C(Oc1ccc2c(cnn2-c2cccnc2)c1)c1cnn(C(C)(C(F)(F)F)F)c1)C'
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 34 36 40 41 42
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 14 15 16 25 26 27 28 29 30
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 4 5 8 9 10 11 20 21 22
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 32 33 35 36 37 38 39 40 41 42 43
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 9 10 11 25 26
[12:24:45] SMILES Parse Error: ring closure 2 duplicates bond between atom 37 and atom 38 for input: 'CC(NC(=O)NCc1ccc(S(=O)(C)=O)cc1)C(Oc1ccc2c(cnn2-c2cccnc2)c1)c1ccc2n2CCCC1'
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 4 5 6 8 9
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 29 30 33 34 35 36 37 38 39
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 33 34 35 36 42
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 28 29 31 32 39
[12:24:45] SMILES Parse Error: extra close parentheses while parsing: CC(NC(=O)C(C)(C)C)C(Oc1ccc2c(cnn2-c2cc(C#N)ccc2)c1)c1c[nH]n2c1nc(C)cc2=N)C
[12:24:45] SMILES Parse Error: check for mistakes around position 73:
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 36 38 39 41 42 43
[12:24:45] 1c[nH]n2c1nc(C)cc2=N)C
[12:24:45] ~~~~~~~~~~~~~~~~~~~~^
[12:24:45] SMILES Parse Error: Failed parsing SMILES 'CC(NC(=O)C(C)(C)C)C(Oc1ccc2c(cnn2-c2cc(C#N)ccc2)c1)c1c[nH]n2c1nc(C)cc2=N)C' for input: 'CC(NC(=O)C(C)(C)C)C(Oc1ccc2c(cnn2-c2cc(C#N)ccc2)c1)c1c[nH]n2c1nc(C)cc2=N)C'
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 31 33 34 35 36 38 47
[12:24:45] SMILES Parse Error: ring closure 1 duplicates bond between atom 40 and atom 41 for input: 'CC(NC(=O)C1CCCC1)C(Oc1ccc2c(cnn2-c2cc3c(cco3)cc2)c1)c1ccc2c(c1)CCN2C(c1c1ccccc1)=O'
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 41 43 44
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 30 32 33 34 35 36 38
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 30 31 33 34 36 37 40
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 29 30 31 32 33 34 35 37 38 39 40
[12:24:45] SMILES Parse Error: extra close parentheses while parsing: CC(NC(=O)C(F)(F)F)C(Oc1ccc2c(cnn2-c2cccnc2)c1)c1ccc2c(c1O)nc(OCC)[nH]2)(C)C
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 32 33 35 36 44 45 46
[12:24:45] SMILES Parse Error: check for mistakes around position 71:
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 29 30 32 33 34
[12:24:45] c2c(c1O)nc(OCC)[nH]2)(C)C
[12:24:45] ~~~~~~~~~~~~~~~~~~~~^
[12:24:45] SMILES Parse Error: Failed parsing SMILES 'CC(NC(=O)C(F)(F)F)C(Oc1ccc2c(cnn2-c2cccnc2)c1)c1ccc2c(c1O)nc(OCC)[nH]2)(C)C' for input: 'CC(NC(=O)C(F)(F)F)C(Oc1ccc2c(cnn2-c2cccnc2)c1)c1ccc2c(c1O)nc(OCC)[nH]2)(C)C'
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 33 34 35 36 37 38 47 48 49 50 52 53 54
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 34 35 36 38 39 42 43 44 45
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 29 30 31 33 34
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 5 6 7 8 9 10 14 15 16
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 27 28 29 31 32 33 34
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 38 39 40 41 42
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 29 30 31 32 34 35 36 38 39
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 32 33 35 36 37 39 40 41 42 43 44
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 28 29 30 31 32 34 36 37 38
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 19 20 21 26 27
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 27 28 29 30 31 32 47
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 29 30 31 32 33 36 37 38 39 40 41
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 29 32 33
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 12 13 14 15 16 17 18 27 28 29 30 31 32
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 36 37 38 39 40 42 44 45 46
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 31 32 35 36 37 38 39 40 41
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 27 28 29 30 31 32 44
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 35 36 37 38 39 42 43
[12:24:45] Explicit valence for atom # 38 N, 5, is greater than permitted
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 5 6 7 8 9 11 12 13 14 15 16
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 26 27 28 29 31
[12:24:45] SMILES Parse Error: unclosed ring for input: 'CC(NC(=O)C1CC1)C(Oc1ccc2c(cnn2-c2cccnc2)c1)c1ccc2n(C)c(C(Oc3ccc4c(cnn4-c4ccc(F)cc4)c3)C4CC3)nc2c1'
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 27 31
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 30 31 32 34 35 46 47
[12:24:45] SMILES Parse Error: unclosed ring for input: 'CC(NC(=O)NCc1ccsc1)C(Occc2ccc3c(cnn3-c3ccc(F)cc3)c2CC1)C(F)(F)F'
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 27 28 29 30 31
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 31 32 33 34 36
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 29 30 31 33 34 37 38 39
[12:24:45] SMILES Parse Error: unclosed ring for input: 'CC(NC(=O)c1nocc1)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1cn(C23CC4CC(CC(C2)C3)C2CC2)nc1'
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 2 3 4 38 39
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 8 10 11 17 18 19 20
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 5 6 7 8 9 11 12 31 32
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 26 27 28 29 32 44
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 4 5 6 14 15 16 17
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 43 44 45
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 8 9 15 20 24
[12:24:45] SMILES Parse Error: unclosed ring for input: 'CC(NC(N1CCN(CC2CCCCC2)CC1)=O)C(Oc1ccc2c(cnn2-c2cccc(F)c2)c1)c2cnn(C)c1'
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 36 37 38 46 47 48 49
[12:24:45] Can't kekulize mol.  Unkekulized atoms: 17 19 20 21 22 29
[12:24:46] Can't kekulize mol.  Unkekulized atoms: 32 33 38 40 50
[12:24:46] Can't kekulize mol.  Unkekulized atoms: 27 28 29 30 31
[12:24:46] Can't kekulize mol.  Unkekulized atoms: 34 35 36 39 47 48 49
[12:24:46] SMILES Parse Error: extra close parentheses while parsing: CC(NC(c1ncn(C)c1)=O)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1cc2c(cn1)cnn2C1CCC1)CC
[12:24:46] Can't kekulize mol.  Unkekulized atoms: 33 34 36 37 39 41
[12:24:46] SMILES Parse Error: check for mistakes around position 73:
[12:24:46] 1cc2c(cn1)cnn2C1CCC1)CC
[12:24:46] ~~~~~~~~~~~~~~~~~~~~^
[12:24:46] SMILES Parse Error: Failed parsing SMILES 'CC(NC(c1ncn(C)c1)=O)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1cc2c(cn1)cnn2C1CCC1)CC' for input: 'CC(NC(c1ncn(C)c1)=O)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1cc2c(cn1)cnn2C1CCC1)CC'
[12:24:46] Can't kekulize mol.  Unkekulized atoms: 5 6 7 8 9 10 21
[12:24:46] Can't kekulize mol.  Unkekulized atoms: 28 29 30 32 33 34 35 41 42
[12:24:46] Can't kekulize mol.  Unkekulized atoms: 28 29 30 32 33 34 38 39 40
[12:24:46] Can't kekulize mol.  Unkekulized atoms: 18 19 21 22 23
[12:24:46] SMILES Parse Error: unclosed ring for input: 'c1coc2cc(-n3ncc4cc(OC(c5ccc6c(c5)CCCC4)C(C)NC(=O)C4CC4)c3)ccc12'
[12:24:46] Can't kekulize mol.  Unkekulized atoms: 5 6 7 8 9 10 11 12 13
[12:24:46] Explicit valence for atom # 37 F, 2, is greater than permitted
[12:24:46] Can't kekulize mol.  Unkekulized atoms: 5 7 8 9 16 17 18 19 20
[12:24:46] Can't kekulize mol.  Unkekulized atoms: 30 31 32 33 34 36 38 39 41
[12:24:46] SMILES Parse Error: ring closure 1 duplicates bond between atom 38 and atom 42 for input: 'CC(NC(=O)NCc1ccnnc1)C(Oc1ccc2c(cnn2-c2cncnc2)c1)c1ccc2c(c1)OCC1(CCC2)C1'
[12:24:46] SMILES Parse Error: unclosed ring for input: 'CC(NC(=O)c1cc2c(cccc2)s1)C(Oc1ccc2c(cnn2-c2ccc3c(c2)CCO2)cc3cc1)c1ccc(F)c(F)c1'
[12:24:46] Can't kekulize mol.  Unkekulized atoms: 32 33 36 37 38 39 40 41 42
[12:24:46] Can't kekulize mol.  Unkekulized atoms: 34 35 36 37 39
[12:24:46] Can't kekulize mol.  Unkekulized atoms: 0 2 3 4 5 6 16 17 18 19 25
[12:24:46] Can't kekulize mol.  Unkekulized atoms: 7 8 9 11 29
[12:24:46] SMILES Parse Error: extra open parentheses while parsing: CC(NC(c1c(F)cccc1Cl)=O)C(Oc1ccc2c(cnn2-c2ccncc2
[12:24:46] SMILES Parse Error: check for mistakes around position 25:
[12:24:46] C(c1c(F)cccc1Cl)=O)C(Oc1ccc2c(cnn2-c2ccnc
[12:24:46] Can't kekulize mol.  Unkekulized atoms: 20 21 22 27 28
[12:24:46] ~~~~~~~~~~~~~~~~~~~~^
[12:24:46] SMILES Parse Error: extra open parentheses while parsing: CC(NC(c1c(F)cccc1Cl)=O)C(Oc1ccc2c(cnn2-c2ccncc2
[12:24:46] SMILES Parse Error: check for mistakes around position 34:
[12:24:46] ccc1Cl)=O)C(Oc1ccc2c(cnn2-c2ccncc2
[12:24:46] ~~~~~~~~~~~~~~~~~~~~^
[12:24:46] SMILES Parse Error: unclosed ring for input: 'CC(NC(c1sccc1)=O)C(Oc1ccc2c(cnn2-c2ccc3onc(-c4c(F)cccc6)c4c3c2)c1)c1ccccc1'
[12:24:46] SMILES Parse Error: Failed parsing SMILES 'CC(NC(c1c(F)cccc1Cl)=O)C(Oc1ccc2c(cnn2-c2ccncc2' for input: 'CC(NC(c1c(F)cccc1Cl)=O)C(Oc1ccc2c(cnn2-c2ccncc2'
[12:24:46] Can't kekulize mol.  Unkekulized atoms: 30 31 32
[12:24:46] Can't kekulize mol.  Unkekulized atoms: 29 31 34 35 54
[12:24:46] Can't kekulize mol.  Unkekulized atoms: 34 35 36 37 38 39 41 44 46
[12:24:46] Can't kekulize mol.  Unkekulized atoms: 35 36 37 39 40 41 51 52 53
[12:24:46] Can't kekulize mol.  Unkekulized atoms: 29 30 31 32 34
[12:24:46] SMILES Parse Error: ring closure 2 duplicates bond between atom 7 and atom 8 for input: 'CC(Oc1ccc(-n2c2ccc(S(=O)(NC3CCCC3)=O)cc2)cc1)C(Nc1ccc2c(c1)CCC2)=O'
[12:24:46] Can't kekulize mol.  Unkekulized atoms: 5 6 7 9 10
[12:24:46] SMILES Parse Error: unclosed ring for input: 'CC(NC(=O)NCC1OCCC1)C(Oc1ccc2c(cnn2-c2ccccc2)c1)c1cn(C23CC4CC(CC(C2)C3)C2CC2)nn1'
[12:24:46] SMILES Parse Error: unclosed ring for input: 'CC(NC(c1c(F)cccc2)c1)=O'
[12:24:46] SMILES Parse Error: unclosed ring for input: 'CC(NC(N1CCN(CC(C)(C)C)CC1)=O)C(Oc1ccc2c(cnn2-c2cccnc2)c1)c1cn(C23CC4CC(C2)CC3)nc1'
[12:24:46] Can't kekulize mol.  Unkekulized atoms: 32 33 34 36 37 40 41
[12:24:46] Can't kekulize mol.  Unkekulized atoms: 4 5 16 17 18 22 29 30 31
[12:24:46] Can't kekulize mol.  Unkekulized atoms: 31 32 33 34 35 36 41 43
[12:24:46] Can't kekulize mol.  Unkekulized atoms: 32 33 35 36 37 38 41
[12:24:46] SMILES Parse Error: unclosed ring for input: 'CC(NC(=O)NCc1cocc1)C(Oc1ccc2c(cnn2-c2ccc3c(c2)OCCO2)cc3cc1)c1ccccc1'
[12:24:46] Can't kekulize mol.  Unkekulized atoms: 7 8 9 10 11 12 13 22 23
[12:24:46] Can't kekulize mol.  Unkekulized atoms: 19 20 21 23 25 27
[12:24:46] Can't kekulize mol.  Unkekulized atoms: 12 13 14 15 16 18 19 29 30
[12:24:46] Can't kekulize mol.  Unkekulized atoms: 7 9 10 11 13 14
[12:24:46] Can't kekulize mol.  Unkekulized atoms: 23 24 25 26 29 30 31 33 34
[12:24:46] Can't kekulize mol.  Unkekulized atoms: 26 27 28 30 31 33 34
[12:24:46] Can't kekulize mol.  Unkekulized atoms: 30 31 32 34 35 36 37 38 39
[12:24:46] Can't kekulize mol.  Unkekulized atoms: 29 30 31 39 40 41 42
[12:24:46] Can't kekulize mol.  Unkekulized atoms: 28 29 30 31 32 33 35 36 37 38 39
[12:24:46] Can't kekulize mol.  Unkekulized atoms: 29 32 33 35 36 37 38
[12:24:46] Can't kekulize mol.  Unkekulized atoms: 19 20 21 22 23 24 25 26 27
[12:24:46] Can't kekulize mol.  Unkekulized atoms: 29 30 35 36 37 38 39 40 41
[12:24:46] Can't kekulize mol.  Unkekulized atoms: 5 7 8 13 14 21
[12:24:46] SMILES Parse Error: unclosed ring for input: 'CC(NC(c1cc2oc(C)nc2cc1)=O)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1cn(C2CC2)cn3'

--- Processing cluster 3 ---

[12:25:28] Can't kekulize mol.  Unkekulized atoms: 6 7 8 9 27 28 30
[12:25:28] Explicit valence for atom # 10 C, 5, is greater than permitted
[12:25:28] Can't kekulize mol.  Unkekulized atoms: 5 6 7 25 26
[12:25:28] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6 9 10 25 26
[12:25:28] Explicit valence for atom # 5 C, 5, is greater than permitted
[12:25:28] Explicit valence for atom # 19 C, 5, is greater than permitted
[12:25:28] Explicit valence for atom # 4 C, 5, is greater than permitted
[12:25:28] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 2 3 10 11 12 33 34 35
[12:25:29] Explicit valence for atom # 12 C, 5, is greater than permitted
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 1 2 30 31 33 34 35 36
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 7 8 11 12 13
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 18 22 23 24 26 27
[12:25:29] Explicit valence for atom # 15 O, 3, is greater than permitted
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 16 18 19 20 21 22 23
[12:25:29] SMILES Parse Error: extra open parentheses while parsing: FC(C(CNC(c1c(Sc2cc3n[nH]c(C=Cc4ncccc4)c3cc2)cccc1)=O)(CC1CC1)OC(=O)CC(C)(C)C
[12:25:29] SMILES Parse Error: check for mistakes around position 3:
[12:25:29] Explicit valence for atom # 28 C, 5, is greater than permitted
[12:25:29] FC(C(CNC(c1c(Sc2cc3n[nH]c(C=Cc4ncccc4)c3c
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6 7 8 9 10
[12:25:29] Explicit valence for atom # 0 N, 4, is greater than permitted
[12:25:29] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:25:29] ~~^
[12:25:29] SMILES Parse Error: Failed parsing SMILES 'FC(C(CNC(c1c(Sc2cc3n[nH]c(C=Cc4ncccc4)c3cc2)cccc1)=O)(CC1CC1)OC(=O)CC(C)(C)C' for input: 'FC(C(CNC(c1c(Sc2cc3n[nH]c(C=Cc4ncccc4)c3cc2)cccc1)=O)(CC1CC1)OC(=O)CC(C)(C)C'
[12:25:29] Explicit valence for atom # 0 C, 5, is greater than permitted
[12:25:29] Explicit valence for atom # 14 C, 7, is greater than permitted
[12:25:29] Explicit valence for atom # 11 C, 5, is greater than permitted
[12:25:29] SMILES Parse Error: unclosed ring for input: 'c1ccc2c(c1)C(NC(C(CC(O)C(CC1CCCCC1)NC(=O)c1cc(-c1ccccc1S(C)(=O)=O)=O)Cc1ccccc1)O)C(O)C2'
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 16 17 20 22 23 24 25 26 27 28 29
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 10 11 12 24 27
[12:25:29] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 2 3 5 6 7 12 13 14 15 16 17
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 10 11 12 14 23 24 25 28 34
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 10 11 13 14 16 17 19
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 10 13 23
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 6 7 28
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 6 8 9 12 13 14 15 16 17
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 2 13 14 15 16 17 18
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 11 12 13 14 15 17 19
[12:25:29] SMILES Parse Error: unclosed ring for input: 'c1c(C=C2C3CCC4(C)C5(CC(c6ccccc6)OC6C5)C5C(CC4C2C3)C2(C)C(=CC(=O)CC2)CO5)ccc(C)c1'
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 7 8 9 10 11 17 26 27 28 29 30 31 32
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 11 12 13
[12:25:29] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:25:29] SMILES Parse Error: unclosed ring for input: 'CC1(C)C(O)CCC2(C)C1CCC1(C)C3(C)CCC45CC3(CCC4C(C)(C)C(O)C5)CCC5C12O'
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 9 10 11 12 13 14 15 17 18 19 20 24 25 27 28
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 7 8 19 20 21 22 23
[12:25:29] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:25:29] SMILES Parse Error: ring closure 4 duplicates bond between atom 16 and atom 30 for input: 'Fc1cccc(C2C3(Cc4ccccc4)CC4(C(CN(Cc5ccccc5)C#N)N2)(C4)C(=O)OC3)c1F'
[12:25:29] Explicit valence for atom # 9 C, 5, is greater than permitted
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 4 5 6 7 8 9 10 12 13 14 16 17 18
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 15 16 17 18 19 20 21 22 23
[12:25:29] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:25:29] Explicit valence for atom # 31 C, 5, is greater than permitted
[12:25:29] Explicit valence for atom # 24 C, 5, is greater than permitted
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 4 5 7 8 11 12 31 32 33 34 35
[12:25:29] Explicit valence for atom # 10 C, 5, is greater than permitted
[12:25:29] SMILES Parse Error: unclosed ring for input: 'C12(C)C3CC(O)C4=CC5C6C(C)(O5)CCC4(CCC(O)=O)C3CCC1(C)C(O)(C#Cc1cccc(CN3CC(O)CCC3)c1)CC2'
[12:25:29] SMILES Parse Error: ring closure 3 duplicates bond between atom 0 and atom 10 for input: 'C123C4C(=O)CCC1(CCCC23O)C(O)C4C(C)(C)c1nc2ccccc2cc1'
[12:25:29] SMILES Parse Error: unclosed ring for input: 'C1(C2(O)CCC3(C4CC5CC(CC5C5)C4)(OCC)C4(CC=C(C)C)C(=O)C(=CC(CO)C(O)C42O)C3)CCCCC1'
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 6 7 10 11 12 13 14 19
[12:25:29] Explicit valence for atom # 39 F, 2, is greater than permitted
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 6 25 26 27 28 30 31
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 8 9 10 11 12 13 23 24 25 26 27 28 29 30 31
[12:25:29] Explicit valence for atom # 16 C, 5, is greater than permitted
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 1 2 7 8 9 22
[12:25:29] SMILES Parse Error: unclosed ring for input: 'C1C(O)(C2(O)CCC3C4CCC5=Cc6c(cnn5-c6ccc(F)cc6)CC5(C)C4C(O)CC32C)C=CC(=O)C1'
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 7 20 21
[12:25:29] Explicit valence for atom # 13 S, 8, is greater than permitted
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 6 7 8 9 10 11 12
[12:25:29] SMILES Parse Error: unclosed ring for input: 'C1C(c2ccc(OC)c(OC)c2)n2c3c(c(Cl)ccc3C(C)N12)c(C)nc2C#N'
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 1 3 4 5 6 7 8 9 10 11 15 16 17 18 19 21 22
[12:25:29] SMILES Parse Error: unclosed ring for input: 'C1(=C)C=CC2(C)C(=C1)C(C)CC1C2C(O)CC2(C)C(O)(C(=O)CSc3c4oc5c(c4nc33)cccc5)C(C)CC21'
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 1 5 13 15 16 17 18 23
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 2 4 5 6 11 12
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 14 15 17 18 19 21 22 23 24 27 28 29
[12:25:29] Explicit valence for atom # 28 C, 5, is greater than permitted
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 1 5 6 10 11 12 13 15 16 17 18 19 20 21 24 25 26 27 28 29
[12:25:29] Explicit valence for atom # 14 C, 5, is greater than permitted
[12:25:29] SMILES Parse Error: unclosed ring for input: 'C1C(=O)C=C2C(C)(C3C(C4C(C)(C(OC(=O)NCC)(C(OC)=O)CC4)CC3O)CC2CC(C)C(=O)O2)C1'
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 7 18 30
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 7 9 10 11 12 14 15 16 19 20 21
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 16 17 18 19 20
[12:25:29] Explicit valence for atom # 16 C, 5, is greater than permitted
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 2 3 4 5 6 7 17 18 21 22 23 24 25 26
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 1 2 4 5 6 15
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 1 3 4 5 6 7 8 9 11 12 13 14 17 18 19 24
[12:25:29] Explicit valence for atom # 9 N, 4, is greater than permitted
[12:25:29] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:25:29] Explicit valence for atom # 9 N, 4, is greater than permitted
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 19 20 21 22 23 24 25 26 27
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 34 35 37 39 40
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 28 29 32 34 36
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 18 19 20 21 22 23 24 25 26
[12:25:29] Explicit valence for atom # 9 N, 4, is greater than permitted
[12:25:29] Explicit valence for atom # 17 C, 6, is greater than permitted
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 1 7 19 20 21 22 23 24 25 26
[12:25:29] Explicit valence for atom # 1 N, 4, is greater than permitted
[12:25:29] Explicit valence for atom # 21 C, 5, is greater than permitted
[12:25:29] Explicit valence for atom # 14 C, 6, is greater than permitted
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 17 18
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 39
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 28 29 30
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 14 15 16 17 22 24 25
[12:25:29] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 4 5 6 7 8 9 10 12 13 15 16 20 29 30 31 32 33
[12:25:29] SMILES Parse Error: unclosed ring for input: 'c1ccc2c3c(nc4c(cccc4)c3=NCCCCCCCN)c3cccc4c5c(ccc6c(=O)n(CCNCCNCCNCCCCNCCCN)c(=O)c(cc5)c(c(c(O)c7))c6cccc1)c2c43'
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 1 3 4 6 7 8 21 23
[12:25:29] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 16 17 18 19 20 21 22 23 24
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 1 3 4 5 6 7 8 9 13 14 15 16 17 18
[12:25:29] Explicit valence for atom # 4 C, 5, is greater than permitted
[12:25:29] SMILES Parse Error: unclosed ring for input: 'C1=CCC23c4c(cc(N5CCCC5)cc4)CCC2O1'
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 2 3 4 25 26 27 28 29 30 31
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 15 16 17 18 19 20 21
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 6 7 20 21 22 24 25 26 27 28 38
[12:25:29] SMILES Parse Error: unclosed ring for input: 'CC1CC2(O)C(C=C(C)C3C(C(=C)CC3)C2)C2OC(O3)C2(O)C1'
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 18 19 20
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 2 3 4 15
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 1 2 7 8 32
[12:25:29] SMILES Parse Error: unclosed ring for input: 'C12(C(CCC)=CC)C(O3)C3C(C(=O)CC(C)(C)O3)C=CC1(CC)CC(CCc1ccccc1)O2'
[12:25:29] SMILES Parse Error: unclosed ring for input: 'c12c(C)ccc(Oc3c(C)c(N4C5CC6(C)C(C5)C4)c(C(N)=O)cn3)c1ccnc2'
[12:25:29] SMILES Parse Error: unclosed ring for input: 'c12ccoc1cc1c(c3c(o1)C=C1C(CCCN11)C3)c2'
[12:25:29] SMILES Parse Error: unclosed ring for input: 'c1cc(NC(=O)NC(CC)CC)cc(C(=NO)c3ccccc2)cc1'
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 34
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 1 2 4 5 6 21 22 23 24
[12:25:29] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 2 3 6 7 8 28 29
[12:25:29] Explicit valence for atom # 14 N, 4, is greater than permitted
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 10 28 29 30 31 32 33 34
[12:25:29] SMILES Parse Error: unclosed ring for input: 'C1(C)(C)C(OC(NC(C)C)=O)C(=C)C2C3C4C5(C)C(CC3)(C2)C1CO5'
[12:25:29] Explicit valence for atom # 11 C, 5, is greater than permitted
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 6 7 8 9 10 11 14 15 16 18 19 20 21 22 23
[12:25:29] SMILES Parse Error: ring closure 5 duplicates bond between atom 9 and atom 10 for input: 'C12(O)C3(O)CCC(C)(C4C5(O5)C(C)CC(=O)C4=C)C(c4ccoc4)CC3CC1C2'
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 9 11 12 13 14 15 16
[12:25:29] Explicit valence for atom # 2 N, 6, is greater than permitted
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6 7 8 9 10 13 15
[12:25:29] Explicit valence for atom # 3 F, 2, is greater than permitted
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 8 9 18 19 60 61 62 69 70
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 13 14 15 16 24
[12:25:29] Explicit valence for atom # 17 C, 5, is greater than permitted
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 1 10 11 12 13 21 22 23 29 30
[12:25:29] Explicit valence for atom # 8 N, 4, is greater than permitted
[12:25:29] SMILES Parse Error: unclosed ring for input: 'C1=C2CC(N3CCCC3)C3Oc4c5c(ccc4)CC4N(CC6CC6)CCC56C3(CC4)O2(OC)CC1'
[12:25:29] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:25:29] SMILES Parse Error: unclosed ring for input: 'O=C1OC(c2cocc2)C2(C)CC(=O)C3C4(C)C(CC(OC(=O)C)C33C12C(C)(Oc1c2c(ccc3O)CC3CC2CCC(C)(C)C35C)cccc14)OC(C)(C)OO3'
[12:25:29] Explicit valence for atom # 16 C, 5, is greater than permitted
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 11 12 13 14 15
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 2 4 10 11 14 16
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 6 8 35
[12:25:29] Explicit valence for atom # 19 C, 5, is greater than permitted
[12:25:29] Explicit valence for atom # 11 O, 3, is greater than permitted
[12:25:29] Explicit valence for atom # 12 C, 5, is greater than permitted
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 8 9 10 11 12 13 42
[12:25:29] SMILES Parse Error: unclosed ring for input: 'C1CC2C(C)(C3C(O)CC4(C)C(C(=O)CSc5n(C)c5c(cccc6)n5)(O)CCC4C13)CCC(=O)C2'
[12:25:29] SMILES Parse Error: unclosed ring for input: 'O1CCC(Oc2c(N=c3nc4c(c[nH]5)-c5c(cnc(C)n5)N(CC(F)(F)F)CN4C(=O)N3)ccc2)C(=O)C1'
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 2 3 4 44
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 2 5 6 7 8 9 10 11 12
[12:25:29] Explicit valence for atom # 31 N, 4, is greater than permitted
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 1 2 4 5 6 29
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 5 11 12 13 14 15 18
[12:25:29] SMILES Parse Error: unclosed ring for input: 'C123C4C(O)CC5=CC(=O)C=CC5(C)C4(O)CCC1(C)C(C(=O)C)C(C)C2'
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 1 3 4 5 6 7 43 44
[12:25:29] Explicit valence for atom # 4 N, 6, is greater than permitted
[12:25:29] Explicit valence for atom # 0 C, 5, is greater than permitted
[12:25:29] SMILES Parse Error: unclosed ring for input: 'C1CN2CC(=Cc3cc(F)ccc3F)C3C4Cc5ccc(O)c1c5C35CCN2CCC41CCCC(C)C1OCC'
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5 6 7 9 10 13 14 15 17 18 19
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 4 5 6 7 8 23 24 25
[12:25:29] SMILES Parse Error: ring closure 4 duplicates bond between atom 8 and atom 31 for input: 'C1CC2C(C)(CC(O)C34C2CCC(C)(NC(=O)C=Cc2cc(OC)c(OC)cc2C)CC43)C1C(C)=O'
[12:25:29] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:25:29] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 9 10 11 12 13 14 15 16 17
[12:25:29] SMILES Parse Error: unclosed ring for input: 'C1C(F)CC2=C3C(OC(=O)c4ccccc4)C(C(=O)C)(O)C2(C)C1OC(C)=O'
[12:25:29] Explicit valence for atom # 5 C, 5, is greater than permitted
[12:25:29] Explicit valence for atom # 8 C, 5, is greater than permitted
[12:25:29] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:25:29] Explicit valence for atom # 7 C, 5, is greater than permitted
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 2 3 4 27 29 31 32
[12:25:29] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 3 4 5 8 12 14 15
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 1 3 4 7 32 36 37 38
[12:25:29] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:25:29] Explicit valence for atom # 20 C, 5, is greater than permitted
[12:25:29] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:25:29] Explicit valence for atom # 13 C, 5, is greater than permitted
[12:25:29] SMILES Parse Error: unclosed ring for input: 'CC(Cc1ccc(Cl)cc1)C(CC(C(O)(C1CCC1)c1ccccc1)(O)C(F)(F)F)NC(OC2COCC1)C2'
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 16 17 18 19 20 21 30 31 33
[12:25:29] Explicit valence for atom # 3 N, 4, is greater than permitted
[12:25:29] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:25:29] Explicit valence for atom # 6 C, 6, is greater than permitted
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 10 11 12 13 14 15 16 23 24 25 26
[12:25:29] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:25:29] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6 7 10 11 12 13 14 15 16 17 18
[12:25:29] Explicit valence for atom # 5 C, 5, is greater than permitted
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 6 7 12 13 14 24 25 29 30 31 32
[12:25:29] SMILES Parse Error: ring closure 2 duplicates bond between atom 14 and atom 17 for input: 'o1cccc1C(O)(C(C)C)C(C)C1CC2(CC)C2OC(C)(C)O1'
[12:25:29] Explicit valence for atom # 13 C, 5, is greater than permitted
[12:25:29] Explicit valence for atom # 16 C, 5, is greater than permitted
[12:25:29] Explicit valence for atom # 0 C, 5, is greater than permitted
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 2 3 6 7 8 9 10 11 12 13 16 19 20 21 22 23 24
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 6 7 8
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 3 4 5 6 7 8 9 10 11 12 13 14 17 18 19
[12:25:29] SMILES Parse Error: ring closure 3 duplicates bond between atom 0 and atom 34 for input: 'C123C(C)(CC(O)C1)CC(O)C(C)(COc1ccc(C4Oc5c(c(O)cc(O)c5C)C(O)C4)cc1)C23'
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 7 8 9 10 11 13 33
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 1 3 9
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 1 2 4 7 22 24 27 28
[12:25:29] SMILES Parse Error: unclosed ring for input: 'C1(O)CC(O)C=CC12CCC1C(=C2)C#CC(C)(C)C'
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 11 12 18 19 20 22 23 24 25 26 27
[12:25:29] SMILES Parse Error: unclosed ring for input: 'C1=C2CCC3C4C(C)(CCC3C2(C)CCC1=NOC1CC2CCC1(C)C4(C)CC2)CC(Cl)C2(F)F'
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 8 9 10 14 15 16 17 18 19 20 21 22 23
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 12 13 14 23 24 25 26
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 7 10 11
[12:25:29] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:25:29] SMILES Parse Error: extra close parentheses while parsing: O=C(c1nc2n(c1)CCOc1c-2cc(C#CC(C)(C)O)cc1)NC1C(O)CCS2(=O)=O)cnn2c1
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 5 6 7 15 16 17 18 19
[12:25:29] Explicit valence for atom # 5 C, 5, is greater than permitted
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 3 4 13
[12:25:29] SMILES Parse Error: check for mistakes around position 59:
[12:25:29] c1)NC1C(O)CCS2(=O)=O)cnn2c1
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 6 7 8 21 41
[12:25:29] Explicit valence for atom # 6 C, 6, is greater than permitted
[12:25:29] SMILES Parse Error: ring closure 2 duplicates bond between atom 28 and atom 29 for input: 'c1ccccc1-c1c(C#CC2(O)CCC3C2(C)CC(c2ccc(N(C)C)cc2)C2=C2CCC(=O)C3)ccc(F)c1'
[12:25:29] ~~~~~~~~~~~~~~~~~~~~^
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 8 9 19 20 27 28 29 30 31
[12:25:29] SMILES Parse Error: unclosed ring for input: 'C12=CC(=O)CCC1(C)C1C(CC2)C2CCC(OC3CCC4(C)C(CC5C4C5CC4)C3)CC2O1'
[12:25:29] SMILES Parse Error: Failed parsing SMILES 'O=C(c1nc2n(c1)CCOc1c-2cc(C#CC(C)(C)O)cc1)NC1C(O)CCS2(=O)=O)cnn2c1' for input: 'O=C(c1nc2n(c1)CCOc1c-2cc(C#CC(C)(C)O)cc1)NC1C(O)CCS2(=O)=O)cnn2c1'
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 0 2 3 4 5 8 9 10 11 12 13 14 16 17 19
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 2 36 37 38 39 40 41 44
[12:25:29] SMILES Parse Error: ring closure 4 duplicates bond between atom 12 and atom 30 for input: 'CC1(O)C(C)CC2C(C)(CC(O)C34C5CCC(O)(C(C)C)C5(C)C(OC(C)=O)C(O)C324)C1=O'
[12:25:29] Explicit valence for atom # 5 N, 4, is greater than permitted
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 12 13 14 15 18 19 20 21 22
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 4 5 6 7 8 13 14 15 16 21 22 23 24 26 29 30 31 32 33 34 35
[12:25:29] Can't kekulize mol.  Unkekulized atoms: 1 2 3 27 32

--- Processing cluster 4 ---

[12:25:59] Can't kekulize mol.  Unkekulized atoms: 23 24 25 26 27 28 29 30 31 32 33 35 36
[12:25:59] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 34 35 36
[12:25:59] Explicit valence for atom # 25 C, 6, is greater than permitted
[12:25:59] SMILES Parse Error: extra close parentheses while parsing: C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(C)C(N(C(=O)C1CCCO1)Cc1cc(C)c(O)c(C)c1)CCC2)(F
[12:25:59] Explicit valence for atom # 19 N, 4, is greater than permitted
[12:25:59] SMILES Parse Error: check for mistakes around position 73:
[12:25:59] cc(C)c(O)c(C)c1)CCC2)(F
[12:25:59] ~~~~~~~~~~~~~~~~~~~~^
[12:25:59] SMILES Parse Error: Failed parsing SMILES 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(C)C(N(C(=O)C1CCCO1)Cc1cc(C)c(O)c(C)c1)CCC2)(F' for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(C)C(N(C(=O)C1CCCO1)Cc1cc(C)c(O)c(C)c1)CCC2)(F'
[12:25:59] SMILES Parse Error: unclosed ring for input: 'CC(NC(=O)C(F)(F)F)C(Oc1ccc2c(cnn2C)c1)c1ccc2c(c1)OCC3N2CC=C'
[12:25:59] Explicit valence for atom # 22 C, 5, is greater than permitted
[12:25:59] Can't kekulize mol.  Unkekulized atoms: 6 7 8 9 10 11 12 13 14 15 16 31 32 34 35 37 38
[12:25:59] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 27 28 29 30 31
[12:25:59] Explicit valence for atom # 21 O, 3, is greater than permitted
[12:25:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 17 18 19 20 24 26 27
[12:25:59] SMILES Parse Error: unclosed ring for input: 'C12=Cc3c(cnn3-c3ccc(F)cc4)cc3CC1(COCC1COCC1)CCCC2Cc1cncn1C'
[12:25:59] SMILES Parse Error: unclosed ring for input: 'O=C1C=CC2(C)C(=C1)CCC1C3CCC(O)(C(=O)CSc4nc5c(n4CC)ccc(Cl)c3)CC21C'
[12:25:59] Can't kekulize mol.  Unkekulized atoms: 25 26 27 29 30
[12:25:59] Can't kekulize mol.  Unkekulized atoms: 9 10 11 12 13 14 16 17 20 21 22
[12:25:59] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 30
[12:25:59] Can't kekulize mol.  Unkekulized atoms: 23 24 25 26 27 28 36
[12:25:59] Can't kekulize mol.  Unkekulized atoms: 22 23 24 26 37 38 39
[12:25:59] Can't kekulize mol.  Unkekulized atoms: 26 27 28 29 40
[12:25:59] Explicit valence for atom # 22 C, 5, is greater than permitted
[12:25:59] Can't kekulize mol.  Unkekulized atoms: 9 10 11 12 13 20 21 22 25 26 27 30 31
[12:25:59] SMILES Parse Error: unclosed ring for input: 'c1(Cl)nc2c(SC)ncc(-c3cc(F)c(C2(C)C(=O)N(C)CCC3)c2)cc1'
[12:25:59] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:25:59] Can't kekulize mol.  Unkekulized atoms: 22 23 29
[12:25:59] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 30
[12:26:00] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 33 34 36
[12:26:00] Explicit valence for atom # 18 N, 4, is greater than permitted
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 19 20 21 22 23
[12:26:00] Explicit valence for atom # 18 N, 4, is greater than permitted
[12:26:00] SMILES Parse Error: ring closure 1 duplicates bond between atom 22 and atom 26 for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(C)C(O)C(C)(C)C1(CCC2)C1'
[12:26:00] Explicit valence for atom # 18 N, 4, is greater than permitted
[12:26:00] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:26:00] Explicit valence for atom # 35 N, 6, is greater than permitted
[12:26:00] SMILES Parse Error: ring closure 1 duplicates bond between atom 21 and atom 28 for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(C)C(O)CC(C1(CCCCCC)C1)C2'
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 21 22 39
[12:26:00] SMILES Parse Error: unclosed ring for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(CCN(S(=O)(=O)c1cc3c(cc1)CC(C)(C)CN1)CC3)CCC2'
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 0 1 33 44 45
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 3 4 5 6 19 22
[12:26:00] Explicit valence for atom # 2 C greater than permitted
[12:26:00] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 26 27 29
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 23 24 25 26 27
[12:26:00] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:26:00] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:26:00] SMILES Parse Error: unclosed ring for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(CCN(S(=O)(CCC1C(O)CCC5CC1)=O)CCC2)CCCCCC1CC1'
[12:26:00] Explicit valence for atom # 22 C, 5, is greater than permitted
[12:26:00] SMILES Parse Error: unclosed ring for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(C)C(C(c1cnn1ccc1)C)(N1CCCC1)CCC2'
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 28
[12:26:00] SMILES Parse Error: ring closure 1 duplicates bond between atom 18 and atom 19 for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(CCN1C1(C(F)(F)F)c1ccccn1)CCC2'
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 31 32 33
[12:26:00] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 18 19 33
[12:26:00] Explicit valence for atom # 22 S, 6, is greater than permitted
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 21 22 23 30 31
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 19 20 21 22 23 24 25 27 28
[12:26:00] Explicit valence for atom # 18 N, 4, is greater than permitted
[12:26:00] SMILES Parse Error: unclosed ring for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(C)C(NC(C1C3(C)CCC4C(CCC(C)5)C4(C)C(C3)CC1)=C)CC2'
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 29 30 32 33 35 37 39
[12:26:00] SMILES Parse Error: ring closure 3 duplicates bond between atom 22 and atom 25 for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(C)C(C(N1CCC3(CC1)C3(C1CC1)C)O)CCC2'
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 32 33 34
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 34
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 24 25 26
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 22 23 26
[12:26:00] SMILES Parse Error: unclosed ring for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(C)C(C(N1CCC(Oc3cnc(Cl)c(Cl)c4)CC3C1)=O)CC2'
[12:26:00] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:26:00] Explicit valence for atom # 18 N, 4, is greater than permitted
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 0 31 41 42 43 45 48 49
[12:26:00] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:26:00] SMILES Parse Error: unclosed ring for input: 'C12(C)C3(F)C(O)CC4(C)C(C(CSc5ccc6c(nc(-c5cc(C)ccc8C)cc6)n5)=O)CCC4C3CC(F)C1=CC(=O)C=C2'
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 19 20 21 23 34
[12:26:00] SMILES Parse Error: unclosed ring for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(COCCN(CCCc1cc(F)cc3F)c3ccc(F)cc31)CCC2'
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 19 20 21
[12:26:00] Explicit valence for atom # 26 S, 6, is greater than permitted
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 17 18 19 24 25 27 28
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 45
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 2 3 5 6 7 8 9 10 11 13 14 15 17 19 20
[12:26:00] SMILES Parse Error: ring closure 2 duplicates bond between atom 39 and atom 40 for input: 'c1(-n2ncc3cc(OC(c4ccc(F)cc4)C(C)NC(=O)C4CCCO4)ccc32)ncc(-c2cc3c(cn2)CC2(C2)C(=O)Nc2ccccc23)cc1'
[12:26:00] Explicit valence for atom # 24 C, 5, is greater than permitted
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 5 6 7 8 17
[12:26:00] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:26:00] SMILES Parse Error: unclosed ring for input: 'c1(-n2ncc3cc(OC(c4ccc(OC)cc4)C(C)NC(=O)C(F)(F)F)ccc23)cc(-c1nc(C2CC2)ncc1)CO'
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 21 32
[12:26:00] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:26:00] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 15 16 17 18 19 20 27 28 29
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 19 20 21 22 23 24 25 26 27
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 22 23 24 25 27 28 29 31 32
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 22 23 25 26 27
[12:26:00] Explicit valence for atom # 18 C, 6, is greater than permitted
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 19 20 21 22 24
[12:26:00] Explicit valence for atom # 19 S, 7, is greater than permitted
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 2 3 20
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 19 20 21 22 25 26 27
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 19 20 21 22 24 26 27 28 29
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 17 18 24 25 26
[12:26:00] Explicit valence for atom # 34 C, 5, is greater than permitted
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 23 24 25 26 27 28 29
[12:26:00] SMILES Parse Error: unclosed ring for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(C)C(C(=O)N1CC3C(C1)CCC6C3)CC2'
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 33 36 37 38 39
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 21 22 24 27
[12:26:00] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 0 1 33 53 54
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 31 32 42
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 10 13
[12:26:00] Explicit valence for atom # 19 N, 4, is greater than permitted
[12:26:00] Explicit valence for atom # 18 N, 4, is greater than permitted
[12:26:00] Explicit valence for atom # 18 N, 4, is greater than permitted
[12:26:00] Explicit valence for atom # 18 N, 4, is greater than permitted
[12:26:00] SMILES Parse Error: unclosed ring for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(CC1(CCNCc1c(F)c(Cl)sc1)C)CCCC2'
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 24 25 36
[12:26:00] Explicit valence for atom # 22 C, 6, is greater than permitted
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 22 23 24 26 27
[12:26:00] Explicit valence for atom # 18 N, 4, is greater than permitted
[12:26:00] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:26:00] Explicit valence for atom # 37 F, 2, is greater than permitted
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 19 20 22 23 24 25 32
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 16 18 19
[12:26:00] SMILES Parse Error: unclosed ring for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(C)C(N1CCC(C3(C)CC3c4c(cc(Cl)c(F)c4)NC3=O)CC1)CC2'
[12:26:00] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 22 23 36
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 26 27 29
[12:26:00] Explicit valence for atom # 18 N, 4, is greater than permitted
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 0 2 3 4 5 6 11 12 13 14 15 18 21
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 17 18 19 20 34 35 36
[12:26:00] Explicit valence for atom # 19 N, 4, is greater than permitted
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 19 20 21 23 24 31
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 19 23 30 31 32
[12:26:00] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:26:00] SMILES Parse Error: unclosed ring for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(C)C(C(C1=CCCCC13C)CCC2)O'
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 22 24 25
[12:26:00] Explicit valence for atom # 18 N, 4, is greater than permitted
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 23 24 25 27 28 30 32
[12:26:00] Explicit valence for atom # 18 C, 6, is greater than permitted
[12:26:00] SMILES Parse Error: unclosed ring for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(C)C(C(C1CCCCN1)1)(C)CC2(C)c1ccc(Cl)s1'
[12:26:00] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 33 34 35
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 3
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6 7 8 9 10 11 12 14 15 18 19 20 21 22 24
[12:26:00] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:26:00] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:26:00] SMILES Parse Error: unclosed ring for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(C)C(C(N1CC3C(C4(C)C(=Cc5c(O)n(C)c(O)c55)CCC4C3C)CC1)=O)CC2'
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 25 26 27 28 29
[12:26:00] non-ring atom 10 marked aromatic
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 4 5 6 12 13 19 20
[12:26:00] SMILES Parse Error: unclosed ring for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(C)C(N(C(=O)c1ncc(Oc3cccc4ccccc33)cc4C1)C)CC2'
[12:26:00] SMILES Parse Error: unclosed ring for input: 'c1cc(-n2ncc3cc(OC(c4ccc(OC)cc4)C(NC(=O)C(F)(C)C)C)ccc23)ncc1-c2ccc(O)cc1'
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 24 25 27 28 29
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 19 20 21 24 25
[12:26:00] Explicit valence for atom # 18 N, 4, is greater than permitted
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 23 24 25 27 29
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 20 21 22 23 27
[12:26:00] SMILES Parse Error: unclosed ring for input: 'CC12C(C3C(C4(C)CCC(O)CC4CC3OC3=CC4=CCC5C(CCC6=Cc7c(cnn6)CC5)C4CC3)CC1)CCC2(C(=O)C)O'
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 21 22 23 35 36
[12:26:00] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:26:00] Explicit valence for atom # 17 N, 4, is greater than permitted
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 18 19 20 21 22 25 26
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 25 26 31
[12:26:00] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:26:00] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 12 13 14 15 16 20 21 22 23 24 25
[12:26:00] Explicit valence for atom # 18 N, 4, is greater than permitted
[12:26:00] SMILES Parse Error: ring closure 1 duplicates bond between atom 18 and atom 19 for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(C)C(C1(C1)CCCC2)CC1CCCC1'
[12:26:00] Explicit valence for atom # 30 C, 5, is greater than permitted
[12:26:00] Explicit valence for atom # 22 N, 4, is greater than permitted
[12:26:00] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 25 26 27
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 0 1 29 39 40
[12:26:00] SMILES Parse Error: unclosed ring for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(C)C(N(C(=O)c1cnc3c(c1)CN(CC)CC4)CCCC3)CC2'
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 5 6 7 8 17
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 26 27 30
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 19 20 21 22 25
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 17 18 19 21 23
[12:26:00] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:26:00] Explicit valence for atom # 18 N, 4, is greater than permitted
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 36 37 38
[12:26:00] Explicit valence for atom # 0 C, 5, is greater than permitted
[12:26:00] SMILES Parse Error: unclosed ring for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(C)C(C(Nc1c(Cl)cc([N+]3(C)C(=O)CC3CC1)cc1)(C)CCC2)=O'
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 23 36 37
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 4 6 21
[12:26:00] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 25 26 27 29 30
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 20 21 22 24 26 27
[12:26:00] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 22 23 24 35 36
[12:26:00] Explicit valence for atom # 18 N, 4, is greater than permitted
[12:26:00] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 23 24 26 27 28 29 30 38 39
[12:26:00] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:26:00] SMILES Parse Error: unclosed ring for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(C)C(N(C(=O)C1CCC(O)CC13)CC1CCC1)CCC2'
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 23 24 25 26 27
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 27
[12:26:00] Explicit valence for atom # 18 N, 4, is greater than permitted
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 27 28 29 30 31 32 33 34 35 38 39
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 23 24 25 26 31
[12:26:00] SMILES Parse Error: extra close parentheses while parsing: CC(NC(C(C)(C)C)C(NC)=O)C(Oc1ccc2c(cnn2C)c1)c1ccc2c(c1)OCC1OC(CC)COC1C2)C
[12:26:00] SMILES Parse Error: check for mistakes around position 71:
[12:26:00] (c1)OCC1OC(CC)COC1C2)C
[12:26:00] ~~~~~~~~~~~~~~~~~~~~^
[12:26:00] SMILES Parse Error: Failed parsing SMILES 'CC(NC(C(C)(C)C)C(NC)=O)C(Oc1ccc2c(cnn2C)c1)c1ccc2c(c1)OCC1OC(CC)COC1C2)C' for input: 'CC(NC(C(C)(C)C)C(NC)=O)C(Oc1ccc2c(cnn2C)c1)c1ccc2c(c1)OCC1OC(CC)COC1C2)C'
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 17 18 20 21 31
[12:26:00] SMILES Parse Error: unclosed ring for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(C)C(C(c1ncnc(-n3nnc4c3ccc(Cl)c1)[nH]n1)CC2)c1C#N'
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 0 29 39 40 41 44 45 46 47
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 19 21 22 23 27 28 29
[12:26:00] Explicit valence for atom # 18 N, 4, is greater than permitted
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 26 27 28 29 34 35 36
[12:26:00] Explicit valence for atom # 20 N, 4, is greater than permitted
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 26 27 28 29 30 31 32 33 35
[12:26:00] SMILES Parse Error: ring closure 3 duplicates bond between atom 24 and atom 33 for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(CN(C(=O)CO1CCC3(CC1c1ccccn1)C3)C)CCC2'
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 27
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 26 27 29
[12:26:00] SMILES Parse Error: unclosed ring for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(CCN(C(=O)N(C1CCC3)CC1)C1(O)CCCC1)CC2'
[12:26:00] Explicit valence for atom # 26 C, 5, is greater than permitted
[12:26:00] Explicit valence for atom # 21 N, 4, is greater than permitted
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 0 34 35 42 47
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 22 24 29
[12:26:00] Explicit valence for atom # 22 C, 5, is greater than permitted
[12:26:00] Explicit valence for atom # 22 C, 5, is greater than permitted
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 1 2 3 33 34 35 36 37 38 39 48 49 50
[12:26:00] Explicit valence for atom # 25 C, 5, is greater than permitted
[12:26:00] Explicit valence for atom # 21 F, 2, is greater than permitted
[12:26:00] SMILES Parse Error: ring closure 1 duplicates bond between atom 21 and atom 22 for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(CCN(C(=O)C1C1C)CCC1(C3(C)NCc4c(F)ccc(F)c43)CCC1)CCC2'
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 25 26 27 28 29 30 31 32 33
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 25 26 29
[12:26:00] SMILES Parse Error: ring closure 1 duplicates bond between atom 18 and atom 19 for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(C)C(C1C1(C)CCC1C2CCC2=Cc3c(cnn3-c3ccc(F)cc3)C2)C1'
[12:26:00] Explicit valence for atom # 26 C greater than permitted
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 26 27 28 29 31 32 33 34 35
[12:26:00] SMILES Parse Error: ring closure 1 duplicates bond between atom 17 and atom 28 for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(CC1(CNC(c3nn(C)cc3)=O)C1(C)C)CCC2'
[12:26:00] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 21 22 23 30 31
[12:26:00] Explicit valence for atom # 18 N, 4, is greater than permitted
[12:26:00] Explicit valence for atom # 9 C, 6, is greater than permitted
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 26 27 28
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 19 20 21 23 24 32 33
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 17 18 19 20 21 33
[12:26:00] Explicit valence for atom # 18 N, 4, is greater than permitted
[12:26:00] Can't kekulize mol.  Unkekulized atoms: 22 23 24 27 28

Calculation complete! Processed 5 clusters

                 name type_cluster scaffold        RS       SED      ASER
0     REINVENT_500k_0          dis      csk  0.250000  0.084945  0.000801
1     REINVENT_500k_1          dis      csk  0.478261  0.146371  0.000217
2     REINVENT_500k_2          dis      csk  0.075000  0.095977  0.000014
3     REINVENT_500k_3          dis      csk  0.729730  0.199195  0.013645
4     REINVENT_500k_4          dis      csk  0.488372  0.158643  0.007265
5  REINVENT_500k_mean          dis      csk  0.404272  0.137026  0.004388

DrugEx_GT_epsilon_0.1_500k

============================================================
Starting calculation for DrugEx_GT_epsilon_0.1_500k
Receptor: Glucocorticoid_receptor
Cluster type: dis
Scaffold type: csk
CPUs: 100
============================================================

--- Processing cluster 0 ---

[12:26:44] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:26:45] Explicit valence for atom # 7 C, 5, is greater than permitted
[12:26:50] Explicit valence for atom # 14 C, 5, is greater than permitted

--- Processing cluster 1 ---

[12:27:13] Explicit valence for atom # 20 C, 5, is greater than permitted
[12:27:17] Explicit valence for atom # 9 C, 5, is greater than permitted
[12:27:17] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:27:18] Explicit valence for atom # 19 C, 5, is greater than permitted
[12:27:18] Explicit valence for atom # 37 C, 5, is greater than permitted
[12:27:19] Explicit valence for atom # 10 C, 5, is greater than permitted
[12:27:19] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:27:20] Explicit valence for atom # 17 C, 5, is greater than permitted
[12:27:22] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[12:27:22] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[12:27:22] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[12:27:22] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[12:27:22] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:27:22] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:27:23] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:27:23] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:27:26] Explicit valence for atom # 4 C, 5, is greater than permitted
[12:27:30] Explicit valence for atom # 6 C, 5, is greater than permitted

--- Processing cluster 2 ---

[12:27:50] Explicit valence for atom # 9 C, 5, is greater than permitted
[12:27:54] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[12:27:54] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[12:27:54] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[12:27:54] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[12:27:54] Explicit valence for atom # 25 C, 5, is greater than permitted
[12:27:54] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:27:56] Explicit valence for atom # 8 C, 6, is greater than permitted
[12:27:56] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:27:58] Explicit valence for atom # 11 C, 5, is greater than permitted
[12:27:58] Explicit valence for atom # 23 C, 5, is greater than permitted
[12:27:58] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:27:59] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:28:00] Explicit valence for atom # 30 C, 5, is greater than permitted
[12:28:01] Explicit valence for atom # 11 C, 5, is greater than permitted
[12:28:01] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:28:02] Explicit valence for atom # 9 C, 5, is greater than permitted
[12:28:02] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:28:04] Explicit valence for atom # 1 C, 5, is greater than permitted

--- Processing cluster 3 ---

[12:28:28] Explicit valence for atom # 16 C, 5, is greater than permitted
[12:28:28] Explicit valence for atom # 26 C, 5, is greater than permitted
[12:28:30] Explicit valence for atom # 5 C, 5, is greater than permitted
[12:28:32] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:28:32] Explicit valence for atom # 21 C, 5, is greater than permitted
[12:28:32] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:28:33] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:28:33] Explicit valence for atom # 35 C, 5, is greater than permitted
[12:28:33] Explicit valence for atom # 13 C, 5, is greater than permitted
[12:28:34] Explicit valence for atom # 14 C, 5, is greater than permitted
[12:28:34] Explicit valence for atom # 16 C, 5, is greater than permitted
[12:28:35] Explicit valence for atom # 12 C, 5, is greater than permitted
[12:28:36] Explicit valence for atom # 29 C, 5, is greater than permitted
[12:28:36] Explicit valence for atom # 13 C, 5, is greater than permitted
[12:28:36] Explicit valence for atom # 4 C, 5, is greater than permitted
[12:28:37] Explicit valence for atom # 20 C, 5, is greater than permitted
[12:28:37] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:28:38] Explicit valence for atom # 26 C, 5, is greater than permitted
[12:28:39] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:28:39] Explicit valence for atom # 33 C, 5, is greater than permitted
[12:28:40] Explicit valence for atom # 33 C, 5, is greater than permitted
[12:28:44] Explicit valence for atom # 24 C, 5, is greater than permitted
[12:28:45] Explicit valence for atom # 17 C, 5, is greater than permitted

--- Processing cluster 4 ---

[12:29:06] Explicit valence for atom # 17 C, 5, is greater than permitted
[12:29:06] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:29:07] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:29:07] Explicit valence for atom # 11 C, 5, is greater than permitted
[12:29:07] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:29:07] Explicit valence for atom # 5 C, 5, is greater than permitted
[12:29:08] Explicit valence for atom # 33 C, 5, is greater than permitted
[12:29:08] Explicit valence for atom # 24 C, 5, is greater than permitted
[12:29:09] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:29:10] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:29:11] Explicit valence for atom # 37 C, 5, is greater than permitted
[12:29:11] Explicit valence for atom # 29 C, 5, is greater than permitted
[12:29:11] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:29:11] Explicit valence for atom # 10 C, 5, is greater than permitted
[12:29:11] Explicit valence for atom # 4 C, 5, is greater than permitted
[12:29:11] Explicit valence for atom # 36 C, 5, is greater than permitted
[12:29:11] Explicit valence for atom # 12 C, 5, is greater than permitted
[12:29:12] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:29:12] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:29:12] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:29:12] Explicit valence for atom # 33 C, 5, is greater than permitted
[12:29:12] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:29:12] Explicit valence for atom # 38 C, 5, is greater than permitted
[12:29:13] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:29:13] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:29:13] Explicit valence for atom # 17 C, 5, is greater than permitted
[12:29:13] Explicit valence for atom # 20 C, 5, is greater than permitted
[12:29:14] Explicit valence for atom # 24 C, 5, is greater than permitted
[12:29:14] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:29:15] Explicit valence for atom # 37 C, 5, is greater than permitted
[12:29:15] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:29:20] Explicit valence for atom # 15 C, 5, is greater than permitted
[12:29:22] Explicit valence for atom # 21 C, 5, is greater than permitted

Calculation complete! Processed 5 clusters

,name,type_cluster,scaffold,RS,SED,ASER
0,DrugEx_GT_epsilon_0.1_500k_0,dis,csk,0.500000,0.206793,0.006812
1,DrugEx_GT_epsilon_0.1_500k_1,dis,csk,0.652174,0.162834,0.000611
2,DrugEx_GT_epsilon_0.1_500k_2,dis,csk,0.225000,0.189610,0.000180
3,DrugEx_GT_epsilon_0.1_500k_3,dis,csk,0.405405,0.174670,0.005638
4,DrugEx_GT_epsilon_0.1_500k_4,dis,csk,0.790698,0.236786,0.011383
5,DrugEx_GT_epsilon_0.1_500k_mean,dis,csk,0.514655,0.194139,0.004925

DrugEx_GT_epsilon_0.6_500k

============================================================
Starting calculation for DrugEx_GT_epsilon_0.6_500k
Receptor: Glucocorticoid_receptor
Cluster type: dis
Scaffold type: csk
CPUs: 100
============================================================

--- Processing cluster 0 ---

[12:29:39] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:29:40] Explicit valence for atom # 23 C, 5, is greater than permitted
[12:29:40] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:29:40] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:29:40] Explicit valence for atom # 35 C, 5, is greater than permitted
[12:29:41] Explicit valence for atom # 23 C, 5, is greater than permitted
[12:29:41] Explicit valence for atom # 10 C, 5, is greater than permitted
[12:29:41] Explicit valence for atom # 44 C, 5, is greater than permitted
[12:29:41] Explicit valence for atom # 22 C, 5, is greater than permitted
[12:29:41] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:29:41] Explicit valence for atom # 4 C, 5, is greater than permitted
[12:29:42] Explicit valence for atom # 21 C, 5, is greater than permitted
[12:29:42] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[12:29:42] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[12:29:42] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[12:29:42] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[12:29:42] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:29:42] Explicit valence for atom # 11 C, 5, is greater than permitted
[12:29:42] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:29:42] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:29:42] Explicit valence for atom # 13 C, 5, is greater than permitted
[12:29:42] Explicit valence for atom # 12 C, 5, is greater than permitted
[12:29:43] Explicit valence for atom # 16 C, 5, is greater than permitted
[12:29:43] Explicit valence for atom # 31 C, 5, is greater than permitted
[12:29:43] Explicit valence for atom # 12 C, 5, is greater than permitted
[12:29:43] Explicit valence for atom # 4 C, 5, is greater than permitted
[12:29:43] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:29:43] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:29:43] Explicit valence for atom # 10 C, 5, is greater than permitted
[12:29:43] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:29:43] Explicit valence for atom # 8 C, 5, is greater than permitted
[12:29:44] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:29:44] Explicit valence for atom # 8 C, 5, is greater than permitted
[12:29:44] Explicit valence for atom # 39 C, 5, is greater than permitted
[12:29:44] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:29:44] Explicit valence for atom # 12 C, 5, is greater than permitted
[12:29:44] Explicit valence for atom # 37 C, 5, is greater than permitted
[12:29:45] Explicit valence for atom # 38 C, 5, is greater than permitted
[12:29:45] Explicit valence for atom # 12 C, 5, is greater than permitted
[12:29:45] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:29:45] Explicit valence for atom # 26 C, 5, is greater than permitted
[12:29:45] Explicit valence for atom # 15 C, 5, is greater than permitted
[12:29:45] Explicit valence for atom # 7 C, 5, is greater than permitted
[12:29:45] Explicit valence for atom # 12 C, 5, is greater than permitted
[12:29:45] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:29:46] Explicit valence for atom # 33 C, 5, is greater than permitted
[12:29:46] Explicit valence for atom # 11 C, 5, is greater than permitted
[12:29:46] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:29:46] Explicit valence for atom # 9 C, 5, is greater than permitted
[12:29:46] Explicit valence for atom # 26 C, 5, is greater than permitted
[12:29:46] Explicit valence for atom # 23 C, 5, is greater than permitted
[12:29:46] Explicit valence for atom # 36 C, 5, is greater than permitted
[12:29:46] Explicit valence for atom # 38 C, 5, is greater than permitted
[12:29:47] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:29:47] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:29:47] Explicit valence for atom # 17 C, 5, is greater than permitted
[12:29:47] Explicit valence for atom # 12 C, 5, is greater than permitted
[12:29:47] Explicit valence for atom # 49 C, 5, is greater than permitted
[12:29:47] Explicit valence for atom # 33 C, 5, is greater than permitted
[12:29:47] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:29:47] Explicit valence for atom # 16 C, 5, is greater than permitted
[12:29:47] Explicit valence for atom # 12 C, 5, is greater than permitted
[12:29:48] Explicit valence for atom # 28 C, 5, is greater than permitted
[12:29:48] Explicit valence for atom # 21 C, 5, is greater than permitted
[12:29:48] Explicit valence for atom # 12 C, 5, is greater than permitted
[12:29:48] Explicit valence for atom # 33 C, 5, is greater than permitted
[12:29:48] Explicit valence for atom # 37 C, 5, is greater than permitted
[12:29:48] Explicit valence for atom # 20 C, 5, is greater than permitted
[12:29:49] Explicit valence for atom # 31 C, 5, is greater than permitted
[12:29:49] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:29:49] Explicit valence for atom # 4 C, 5, is greater than permitted
[12:29:49] Explicit valence for atom # 23 C, 5, is greater than permitted
[12:29:49] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:29:49] Explicit valence for atom # 33 C, 5, is greater than permitted
[12:29:49] Explicit valence for atom # 22 C, 5, is greater than permitted
[12:29:49] Explicit valence for atom # 31 C, 5, is greater than permitted
[12:29:49] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:29:51] Explicit valence for atom # 10 C, 5, is greater than permitted

--- Processing cluster 1 ---

[12:30:10] Explicit valence for atom # 15 C, 5, is greater than permitted
[12:30:11] Explicit valence for atom # 8 C, 5, is greater than permitted
[12:30:11] Explicit valence for atom # 8 C, 5, is greater than permitted
[12:30:11] Explicit valence for atom # 24 C, 5, is greater than permitted
[12:30:12] Explicit valence for atom # 12 C, 5, is greater than permitted
[12:30:12] Explicit valence for atom # 37 C, 5, is greater than permitted
[12:30:13] Explicit valence for atom # 4 C, 5, is greater than permitted
[12:30:13] Explicit valence for atom # 14 C, 5, is greater than permitted
[12:30:14] Explicit valence for atom # 32 C, 5, is greater than permitted
[12:30:14] Explicit valence for atom # 32 C, 5, is greater than permitted
[12:30:14] Explicit valence for atom # 14 C, 5, is greater than permitted
[12:30:15] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:30:15] Explicit valence for atom # 4 C, 5, is greater than permitted
[12:30:16] Explicit valence for atom # 33 C, 5, is greater than permitted
[12:30:16] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:30:16] Explicit valence for atom # 5 C, 5, is greater than permitted
[12:30:16] Explicit valence for atom # 12 C, 5, is greater than permitted
[12:30:16] Explicit valence for atom # 55 C, 5, is greater than permitted
[12:30:17] Explicit valence for atom # 20 C, 5, is greater than permitted
[12:30:17] Explicit valence for atom # 14 C, 5, is greater than permitted
[12:30:17] Explicit valence for atom # 35 C, 5, is greater than permitted
[12:30:18] Explicit valence for atom # 21 C, 5, is greater than permitted
[12:30:18] Explicit valence for atom # 13 C, 5, is greater than permitted
[12:30:18] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:30:19] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:30:20] Explicit valence for atom # 17 C, 5, is greater than permitted
[12:30:20] Explicit valence for atom # 31 C, 5, is greater than permitted
[12:30:21] Explicit valence for atom # 24 C, 5, is greater than permitted
[12:30:22] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:30:23] Explicit valence for atom # 11 C, 5, is greater than permitted
[12:30:28] Explicit valence for atom # 1 C, 5, is greater than permitted

--- Processing cluster 2 ---

[12:30:46] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:30:47] Explicit valence for atom # 33 C, 5, is greater than permitted
[12:30:48] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:30:48] Explicit valence for atom # 11 C, 5, is greater than permitted
[12:30:48] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:30:48] Explicit valence for atom # 35 C, 5, is greater than permitted
[12:30:48] Explicit valence for atom # 17 C, 5, is greater than permitted
[12:30:48] Explicit valence for atom # 21 C, 5, is greater than permitted
[12:30:48] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:30:48] Explicit valence for atom # 19 C, 5, is greater than permitted
[12:30:48] Explicit valence for atom # 33 C, 5, is greater than permitted
[12:30:49] Explicit valence for atom # 34 C, 5, is greater than permitted
[12:30:49] Explicit valence for atom # 17 C, 5, is greater than permitted
[12:30:49] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:30:49] Explicit valence for atom # 33 C, 5, is greater than permitted
[12:30:49] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:30:49] Explicit valence for atom # 22 C, 5, is greater than permitted
[12:30:50] Explicit valence for atom # 4 C, 5, is greater than permitted
[12:30:50] Explicit valence for atom # 20 C, 5, is greater than permitted
[12:30:50] Explicit valence for atom # 43 C, 5, is greater than permitted
[12:30:50] Explicit valence for atom # 16 C, 5, is greater than permitted
[12:30:50] Explicit valence for atom # 11 C, 5, is greater than permitted
[12:30:50] Explicit valence for atom # 17 C, 5, is greater than permitted
[12:30:51] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:30:51] Explicit valence for atom # 20 C, 5, is greater than permitted
[12:30:51] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:30:51] Explicit valence for atom # 7 C, 5, is greater than permitted
[12:30:51] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:30:51] Explicit valence for atom # 4 C, 5, is greater than permitted
[12:30:51] Explicit valence for atom # 49 C, 5, is greater than permitted
[12:30:51] Explicit valence for atom # 13 C, 5, is greater than permitted
[12:30:52] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:30:52] Explicit valence for atom # 9 C, 5, is greater than permitted
[12:30:52] Explicit valence for atom # 7 C, 5, is greater than permitted
[12:30:52] Explicit valence for atom # 5 C, 5, is greater than permitted
[12:30:52] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:30:52] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:30:52] Explicit valence for atom # 10 C, 5, is greater than permitted
[12:30:52] Explicit valence for atom # 48 C, 5, is greater than permitted
[12:30:52] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:30:53] Explicit valence for atom # 7 C, 5, is greater than permitted
[12:30:53] Explicit valence for atom # 5 C, 5, is greater than permitted
[12:30:53] Explicit valence for atom # 17 C, 5, is greater than permitted
[12:30:53] Explicit valence for atom # 30 C, 5, is greater than permitted
[12:30:54] Explicit valence for atom # 7 C, 5, is greater than permitted
[12:30:54] Explicit valence for atom # 21 C, 5, is greater than permitted
[12:30:54] Explicit valence for atom # 62 C, 5, is greater than permitted
[12:30:54] Explicit valence for atom # 4 C, 5, is greater than permitted
[12:30:55] Explicit valence for atom # 8 C, 5, is greater than permitted
[12:30:55] Explicit valence for atom # 10 C, 5, is greater than permitted
[12:30:55] Explicit valence for atom # 15 C, 5, is greater than permitted
[12:30:55] Explicit valence for atom # 4 C, 5, is greater than permitted
[12:30:55] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:30:55] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:30:55] Explicit valence for atom # 41 C, 5, is greater than permitted
[12:30:55] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:30:56] Explicit valence for atom # 4 C, 5, is greater than permitted
[12:30:58] Explicit valence for atom # 36 C, 5, is greater than permitted
[12:30:59] Explicit valence for atom # 13 C, 5, is greater than permitted
[12:31:00] Explicit valence for atom # 28 C, 5, is greater than permitted
[12:31:00] Explicit valence for atom # 22 C, 5, is greater than permitted
[12:31:00] Explicit valence for atom # 14 C, 5, is greater than permitted

--- Processing cluster 3 ---

[12:31:22] Explicit valence for atom # 30 C, 5, is greater than permitted
[12:31:23] Explicit valence for atom # 29 C, 5, is greater than permitted
[12:31:24] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:31:24] Explicit valence for atom # 8 C, 5, is greater than permitted
[12:31:25] Explicit valence for atom # 39 C, 5, is greater than permitted
[12:31:25] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[12:31:25] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[12:31:25] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[12:31:25] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[12:31:26] Explicit valence for atom # 4 C, 5, is greater than permitted
[12:31:26] Explicit valence for atom # 19 C, 5, is greater than permitted
[12:31:26] Explicit valence for atom # 34 C, 5, is greater than permitted
[12:31:26] Explicit valence for atom # 16 C, 5, is greater than permitted
[12:31:26] Explicit valence for atom # 13 C, 5, is greater than permitted
[12:31:26] Explicit valence for atom # 8 C, 5, is greater than permitted
[12:31:28] Explicit valence for atom # 29 C, 5, is greater than permitted
[12:31:28] Explicit valence for atom # 5 C, 5, is greater than permitted
[12:31:28] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:31:28] Explicit valence for atom # 19 C, 5, is greater than permitted
[12:31:29] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:31:29] Explicit valence for atom # 7 C, 5, is greater than permitted
[12:31:29] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:31:30] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:31:31] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:31:32] Explicit valence for atom # 14 C, 5, is greater than permitted
[12:31:33] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:31:33] Explicit valence for atom # 11 C, 5, is greater than permitted
[12:31:34] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:31:34] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:31:34] Explicit valence for atom # 40 C, 5, is greater than permitted
[12:31:38] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:31:38] Explicit valence for atom # 10 C, 5, is greater than permitted
[12:31:38] Explicit valence for atom # 19 C, 5, is greater than permitted
[12:31:39] Explicit valence for atom # 10 C, 5, is greater than permitted
[12:31:41] Explicit valence for atom # 9 C, 5, is greater than permitted

--- Processing cluster 4 ---

[12:32:03] Explicit valence for atom # 12 C, 5, is greater than permitted
[12:32:04] Explicit valence for atom # 10 C, 5, is greater than permitted
[12:32:04] Explicit valence for atom # 30 C, 5, is greater than permitted
[12:32:05] Explicit valence for atom # 38 C, 5, is greater than permitted
[12:32:06] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:32:08] Explicit valence for atom # 8 C, 5, is greater than permitted
[12:32:09] Explicit valence for atom # 11 C, 5, is greater than permitted
[12:32:10] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:32:11] Explicit valence for atom # 17 C, 5, is greater than permitted
[12:32:11] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[12:32:11] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[12:32:11] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[12:32:11] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[12:32:11] Explicit valence for atom # 7 C, 5, is greater than permitted
[12:32:11] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:32:11] Explicit valence for atom # 7 C, 5, is greater than permitted

Calculation complete! Processed 5 clusters

,name,type_cluster,scaffold,RS,SED,ASER
0,DrugEx_GT_epsilon_0.6_500k_0,dis,csk,0.700000,0.307877,0.007580
1,DrugEx_GT_epsilon_0.6_500k_1,dis,csk,0.739130,0.305997,0.004327
2,DrugEx_GT_epsilon_0.6_500k_2,dis,csk,0.375000,0.304899,0.000873
3,DrugEx_GT_epsilon_0.6_500k_3,dis,csk,0.648649,0.351036,0.007942
4,DrugEx_GT_epsilon_0.6_500k_4,dis,csk,0.837209,0.359942,0.018724
5,DrugEx_GT_epsilon_0.6_500k_mean,dis,csk,0.659998,0.325950,0.007889

DrugEx_RNN_epsilon_0.1_500k

============================================================
Starting calculation for DrugEx_RNN_epsilon_0.1_500k
Receptor: Glucocorticoid_receptor
Cluster type: dis
Scaffold type: csk
CPUs: 100
============================================================

--- Processing cluster 0 ---

[12:32:38] Explicit valence for atom # 31 C greater than permitted
[12:32:38] Explicit valence for atom # 31 C greater than permitted
[12:32:38] Explicit valence for atom # 24 P, 7, is greater than permitted
[12:32:38] Explicit valence for atom # 13 C greater than permitted
[12:32:38] Explicit valence for atom # 20 C greater than permitted
[12:32:38] Explicit valence for atom # 28 C greater than permitted
[12:32:38] Explicit valence for atom # 28 C, 5, is greater than permitted
[12:32:38] Explicit valence for atom # 25 C greater than permitted
[12:32:38] Explicit valence for atom # 13 C greater than permitted
[12:32:38] Explicit valence for atom # 6 C greater than permitted
[12:32:38] Explicit valence for atom # 40 C greater than permitted
[12:32:39] Explicit valence for atom # 29 C greater than permitted
[12:32:39] Explicit valence for atom # 6 C greater than permitted
[12:32:39] Explicit valence for atom # 33 Si, 5, is greater than permitted
[12:32:39] Explicit valence for atom # 35 C greater than permitted
[12:32:39] Explicit valence for atom # 40 C greater than permitted
[12:32:39] Explicit valence for atom # 30 Si, 5, is greater than permitted
[12:32:39] Explicit valence for atom # 18 C greater than permitted
[12:32:39] Explicit valence for atom # 34 C greater than permitted
[12:32:39] Explicit valence for atom # 15 C greater than permitted
[12:32:39] Explicit valence for atom # 31 C greater than permitted
[12:32:39] Explicit valence for atom # 19 C greater than permitted
[12:32:39] Explicit valence for atom # 27 C greater than permitted
[12:32:39] Explicit valence for atom # 43 C greater than permitted
[12:32:40] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:32:40] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:32:40] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:32:40] Explicit valence for atom # 28 C greater than permitted
[12:32:40] Explicit valence for atom # 30 C greater than permitted
[12:32:40] Explicit valence for atom # 29 C, 5, is greater than permitted
[12:32:40] Explicit valence for atom # 28 C greater than permitted
[12:32:40] Explicit valence for atom # 31 C greater than permitted
[12:32:40] Explicit valence for atom # 27 C greater than permitted
[12:32:40] Explicit valence for atom # 16 C greater than permitted
[12:32:40] Explicit valence for atom # 31 C, 5, is greater than permitted
[12:32:40] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:32:40] Explicit valence for atom # 29 C greater than permitted
[12:32:40] Explicit valence for atom # 17 C greater than permitted
[12:32:40] Explicit valence for atom # 11 C greater than permitted
[12:32:41] Explicit valence for atom # 24 C greater than permitted
[12:32:41] Explicit valence for atom # 28 C greater than permitted
[12:32:41] Explicit valence for atom # 26 C greater than permitted
[12:32:41] Explicit valence for atom # 23 C greater than permitted
[12:32:41] Explicit valence for atom # 19 C greater than permitted
[12:32:41] Explicit valence for atom # 26 Si, 5, is greater than permitted
[12:32:41] Explicit valence for atom # 32 C, 6, is greater than permitted
[12:32:41] Explicit valence for atom # 29 C greater than permitted
[12:32:41] Explicit valence for atom # 19 C, 5, is greater than permitted
[12:32:41] Explicit valence for atom # 29 C greater than permitted
[12:32:41] Explicit valence for atom # 29 C greater than permitted
[12:32:41] Explicit valence for atom # 31 C greater than permitted
[12:32:41] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:32:42] Explicit valence for atom # 28 C, 5, is greater than permitted
[12:32:42] Explicit valence for atom # 33 C greater than permitted
[12:32:42] Explicit valence for atom # 31 C greater than permitted
[12:32:42] Explicit valence for atom # 19 Si, 5, is greater than permitted
[12:32:42] Explicit valence for atom # 14 C, 5, is greater than permitted
[12:32:42] Explicit valence for atom # 31 C, 5, is greater than permitted
[12:32:42] Explicit valence for atom # 33 C greater than permitted
[12:32:42] Explicit valence for atom # 31 C greater than permitted
[12:32:42] Explicit valence for atom # 35 C greater than permitted
[12:32:42] Explicit valence for atom # 22 C, 5, is greater than permitted
[12:32:42] Explicit valence for atom # 32 C, 5, is greater than permitted
[12:32:42] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:32:42] Explicit valence for atom # 35 C greater than permitted
[12:32:42] Explicit valence for atom # 13 C greater than permitted
[12:32:42] Explicit valence for atom # 32 C, 5, is greater than permitted
[12:32:42] Explicit valence for atom # 28 C greater than permitted
[12:32:42] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:32:42] Explicit valence for atom # 13 C greater than permitted
[12:32:42] Explicit valence for atom # 24 C greater than permitted
[12:32:42] Explicit valence for atom # 11 C greater than permitted
[12:32:43] Explicit valence for atom # 30 C greater than permitted
[12:32:43] Explicit valence for atom # 30 C greater than permitted
[12:32:43] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:32:43] Explicit valence for atom # 13 C greater than permitted
[12:32:43] Explicit valence for atom # 31 C, 5, is greater than permitted
[12:32:43] Explicit valence for atom # 18 C greater than permitted
[12:32:43] Explicit valence for atom # 10 C greater than permitted
[12:32:43] Explicit valence for atom # 24 C greater than permitted
[12:32:43] Explicit valence for atom # 28 C greater than permitted
[12:32:43] Explicit valence for atom # 37 C greater than permitted
[12:32:43] Explicit valence for atom # 2 P, 7, is greater than permitted
[12:32:43] Explicit valence for atom # 17 C greater than permitted
[12:32:43] Explicit valence for atom # 26 Si, 5, is greater than permitted
[12:32:43] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:32:43] Explicit valence for atom # 26 C, 5, is greater than permitted
[12:32:43] Explicit valence for atom # 13 C greater than permitted
[12:32:43] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:32:43] Explicit valence for atom # 10 C, 5, is greater than permitted
[12:32:43] Explicit valence for atom # 40 C, 5, is greater than permitted
[12:32:43] Explicit valence for atom # 39 C greater than permitted
[12:32:44] Explicit valence for atom # 31 C greater than permitted
[12:32:44] Explicit valence for atom # 34 C, 5, is greater than permitted
[12:32:44] Explicit valence for atom # 29 C greater than permitted
[12:32:44] Explicit valence for atom # 13 C greater than permitted
[12:32:44] Explicit valence for atom # 13 C greater than permitted
[12:32:44] Explicit valence for atom # 47 C greater than permitted
[12:32:44] Explicit valence for atom # 32 C greater than permitted
[12:32:44] Explicit valence for atom # 29 C, 6, is greater than permitted
[12:32:44] Explicit valence for atom # 31 C, 5, is greater than permitted
[12:32:44] Explicit valence for atom # 31 C greater than permitted
[12:32:44] Explicit valence for atom # 29 C greater than permitted
[12:32:44] Explicit valence for atom # 40 C greater than permitted
[12:32:44] Explicit valence for atom # 35 C, 5, is greater than permitted
[12:32:44] Explicit valence for atom # 23 C, 5, is greater than permitted
[12:32:44] Explicit valence for atom # 32 C greater than permitted
[12:32:44] Explicit valence for atom # 24 P, 7, is greater than permitted
[12:32:44] Explicit valence for atom # 17 Si, 5, is greater than permitted
[12:32:44] Explicit valence for atom # 29 C, 6, is greater than permitted
[12:32:44] Explicit valence for atom # 26 C, 5, is greater than permitted
[12:32:45] Explicit valence for atom # 28 C greater than permitted
[12:32:45] Explicit valence for atom # 32 C, 5, is greater than permitted
[12:32:45] Explicit valence for atom # 37 C greater than permitted
[12:32:45] Explicit valence for atom # 6 C greater than permitted
[12:32:45] Explicit valence for atom # 12 C greater than permitted
[12:32:45] Explicit valence for atom # 13 C greater than permitted
[12:32:45] Explicit valence for atom # 17 C greater than permitted
[12:32:45] Explicit valence for atom # 32 C greater than permitted
[12:32:45] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:32:45] Explicit valence for atom # 21 C greater than permitted
[12:32:45] Explicit valence for atom # 27 C, 6, is greater than permitted
[12:32:45] Explicit valence for atom # 29 C greater than permitted
[12:32:45] Explicit valence for atom # 21 C greater than permitted
[12:32:45] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:32:45] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:32:45] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:32:45] Explicit valence for atom # 33 C greater than permitted
[12:32:46] Explicit valence for atom # 30 C, 5, is greater than permitted
[12:32:46] Explicit valence for atom # 30 C greater than permitted
[12:32:46] Explicit valence for atom # 12 C greater than permitted
[12:32:46] Explicit valence for atom # 28 C greater than permitted
[12:32:46] Explicit valence for atom # 28 C, 5, is greater than permitted
[12:32:46] Explicit valence for atom # 28 C greater than permitted
[12:32:46] Explicit valence for atom # 29 C greater than permitted
[12:32:46] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:32:46] Explicit valence for atom # 17 C greater than permitted
[12:32:46] Explicit valence for atom # 20 Si, 5, is greater than permitted
[12:32:46] Explicit valence for atom # 13 C greater than permitted
[12:32:47] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:32:47] Explicit valence for atom # 28 C greater than permitted
[12:32:47] Explicit valence for atom # 31 C, 5, is greater than permitted
[12:32:47] Explicit valence for atom # 28 C, 5, is greater than permitted
[12:32:47] Explicit valence for atom # 28 C greater than permitted
[12:32:47] Explicit valence for atom # 5 C greater than permitted
[12:32:47] Explicit valence for atom # 35 C greater than permitted
[12:32:47] Explicit valence for atom # 25 C greater than permitted
[12:32:47] Explicit valence for atom # 24 C, 5, is greater than permitted
[12:32:47] Explicit valence for atom # 14 C, 5, is greater than permitted
[12:32:47] Explicit valence for atom # 28 C greater than permitted
[12:32:48] Explicit valence for atom # 18 C greater than permitted
[12:32:48] Explicit valence for atom # 31 C, 5, is greater than permitted
[12:32:48] Explicit valence for atom # 29 C greater than permitted
[12:32:48] Explicit valence for atom # 13 C greater than permitted
[12:32:48] Explicit valence for atom # 25 C greater than permitted
[12:32:48] Explicit valence for atom # 29 C greater than permitted
[12:32:48] Explicit valence for atom # 31 C greater than permitted
[12:32:48] Explicit valence for atom # 36 C, 5, is greater than permitted
[12:32:48] Explicit valence for atom # 24 C greater than permitted
[12:32:48] Explicit valence for atom # 37 C greater than permitted
[12:32:48] Explicit valence for atom # 28 C, 5, is greater than permitted
[12:32:48] Explicit valence for atom # 14 C greater than permitted
[12:32:48] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:32:48] Explicit valence for atom # 28 C greater than permitted
[12:32:48] Explicit valence for atom # 20 Si, 5, is greater than permitted
[12:32:48] Explicit valence for atom # 19 C greater than permitted
[12:32:48] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:32:48] Explicit valence for atom # 19 C, 5, is greater than permitted
[12:32:48] Explicit valence for atom # 31 C greater than permitted
[12:32:48] Explicit valence for atom # 13 C greater than permitted
[12:32:48] Explicit valence for atom # 28 C greater than permitted
[12:32:48] Explicit valence for atom # 34 C, 5, is greater than permitted
[12:32:49] Explicit valence for atom # 11 C greater than permitted
[12:32:49] Explicit valence for atom # 29 C, 5, is greater than permitted
[12:32:49] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:32:49] Explicit valence for atom # 22 C greater than permitted
[12:32:49] Explicit valence for atom # 28 C greater than permitted
[12:32:49] Explicit valence for atom # 18 C greater than permitted
[12:32:49] Explicit valence for atom # 23 C, 5, is greater than permitted
[12:32:49] Explicit valence for atom # 16 C greater than permitted
[12:32:49] Explicit valence for atom # 20 C greater than permitted
[12:32:49] Explicit valence for atom # 23 C, 5, is greater than permitted
[12:32:49] Explicit valence for atom # 21 C greater than permitted
[12:32:49] Explicit valence for atom # 13 C greater than permitted
[12:32:49] Explicit valence for atom # 28 C greater than permitted
[12:32:49] Explicit valence for atom # 30 C greater than permitted
[12:32:49] Explicit valence for atom # 41 C greater than permitted
[12:32:49] Explicit valence for atom # 15 C, 5, is greater than permitted
[12:32:49] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:32:49] Explicit valence for atom # 3 P, 7, is greater than permitted
[12:32:49] Explicit valence for atom # 28 C greater than permitted
[12:32:49] Explicit valence for atom # 27 C greater than permitted
[12:32:49] Explicit valence for atom # 31 C greater than permitted
[12:32:49] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:32:50] Explicit valence for atom # 5 C greater than permitted
[12:32:50] Explicit valence for atom # 7 C greater than permitted
[12:32:50] Explicit valence for atom # 24 C greater than permitted
[12:32:50] Explicit valence for atom # 36 C greater than permitted
[12:32:50] Explicit valence for atom # 30 C, 5, is greater than permitted
[12:32:50] Explicit valence for atom # 31 C greater than permitted
[12:32:50] Explicit valence for atom # 28 C greater than permitted
[12:32:50] Explicit valence for atom # 28 C greater than permitted
[12:32:50] Explicit valence for atom # 28 C, 5, is greater than permitted
[12:32:50] Explicit valence for atom # 22 C, 5, is greater than permitted
[12:32:50] Explicit valence for atom # 29 C greater than permitted
[12:32:50] Explicit valence for atom # 25 C greater than permitted
[12:32:50] Explicit valence for atom # 25 C greater than permitted
[12:32:50] Explicit valence for atom # 31 C, 5, is greater than permitted
[12:32:50] Explicit valence for atom # 29 C greater than permitted
[12:32:50] Explicit valence for atom # 28 C greater than permitted
[12:32:50] Explicit valence for atom # 6 C greater than permitted
[12:32:51] Explicit valence for atom # 22 C greater than permitted
[12:32:51] Explicit valence for atom # 21 C greater than permitted
[12:32:51] Explicit valence for atom # 33 C greater than permitted
[12:32:51] Explicit valence for atom # 31 C greater than permitted
[12:32:51] Explicit valence for atom # 28 C greater than permitted
[12:32:51] Explicit valence for atom # 31 C, 5, is greater than permitted
[12:32:51] Explicit valence for atom # 29 C greater than permitted
[12:32:52] Explicit valence for atom # 17 C greater than permitted
[12:32:52] Explicit valence for atom # 34 C greater than permitted
[12:32:53] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:32:54] Explicit valence for atom # 26 Si, 5, is greater than permitted
[12:32:54] Explicit valence for atom # 29 C greater than permitted
[12:32:54] Explicit valence for atom # 4 C greater than permitted

--- Processing cluster 1 ---

[12:33:14] Explicit valence for atom # 26 C greater than permitted
[12:33:14] Explicit valence for atom # 22 C greater than permitted
[12:33:14] Explicit valence for atom # 10 C greater than permitted
[12:33:15] Explicit valence for atom # 32 C greater than permitted
[12:33:15] Explicit valence for atom # 31 Si, 5, is greater than permitted
[12:33:15] Explicit valence for atom # 31 C greater than permitted
[12:33:15] Explicit valence for atom # 27 C greater than permitted
[12:33:15] Explicit valence for atom # 28 P, 7, is greater than permitted
[12:33:15] Explicit valence for atom # 27 C greater than permitted
[12:33:15] Explicit valence for atom # 27 P, 7, is greater than permitted
[12:33:15] Explicit valence for atom # 21 C greater than permitted
[12:33:15] Explicit valence for atom # 28 C greater than permitted
[12:33:15] Explicit valence for atom # 41 C greater than permitted
[12:33:15] Explicit valence for atom # 33 C greater than permitted
[12:33:15] Explicit valence for atom # 15 C greater than permitted
[12:33:15] Explicit valence for atom # 25 C greater than permitted
[12:33:15] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:33:16] Explicit valence for atom # 31 C greater than permitted
[12:33:16] Explicit valence for atom # 28 C greater than permitted
[12:33:16] Explicit valence for atom # 29 C greater than permitted
[12:33:16] Explicit valence for atom # 15 C greater than permitted
[12:33:16] Explicit valence for atom # 33 C greater than permitted
[12:33:16] Explicit valence for atom # 40 C greater than permitted
[12:33:16] Explicit valence for atom # 37 C greater than permitted
[12:33:16] Explicit valence for atom # 33 C greater than permitted
[12:33:16] Explicit valence for atom # 33 C greater than permitted
[12:33:16] Explicit valence for atom # 30 P, 7, is greater than permitted
[12:33:16] Explicit valence for atom # 29 P, 7, is greater than permitted
[12:33:16] Explicit valence for atom # 31 C greater than permitted
[12:33:16] Explicit valence for atom # 33 C greater than permitted
[12:33:17] Explicit valence for atom # 26 Si, 5, is greater than permitted
[12:33:17] Explicit valence for atom # 25 C, 5, is greater than permitted
[12:33:17] Explicit valence for atom # 42 C greater than permitted
[12:33:17] Explicit valence for atom # 32 C greater than permitted
[12:33:17] Explicit valence for atom # 29 C, 5, is greater than permitted
[12:33:17] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:33:17] Explicit valence for atom # 34 C greater than permitted
[12:33:17] Explicit valence for atom # 24 C greater than permitted
[12:33:17] Explicit valence for atom # 27 P, 7, is greater than permitted
[12:33:17] Explicit valence for atom # 38 C greater than permitted
[12:33:17] Explicit valence for atom # 26 Si, 5, is greater than permitted
[12:33:17] Explicit valence for atom # 30 C greater than permitted
[12:33:17] Explicit valence for atom # 27 Si, 5, is greater than permitted
[12:33:17] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:33:17] Explicit valence for atom # 28 C greater than permitted
[12:33:17] Explicit valence for atom # 29 C greater than permitted
[12:33:17] Explicit valence for atom # 34 C greater than permitted
[12:33:17] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:33:17] Explicit valence for atom # 26 C greater than permitted
[12:33:18] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:33:18] Explicit valence for atom # 13 C greater than permitted
[12:33:18] Explicit valence for atom # 32 C greater than permitted
[12:33:18] Explicit valence for atom # 15 C greater than permitted
[12:33:18] Explicit valence for atom # 24 C greater than permitted
[12:33:18] Explicit valence for atom # 29 C greater than permitted
[12:33:18] Explicit valence for atom # 24 C, 5, is greater than permitted
[12:33:18] Explicit valence for atom # 27 C greater than permitted
[12:33:18] Explicit valence for atom # 31 C greater than permitted
[12:33:18] Explicit valence for atom # 32 C, 5, is greater than permitted
[12:33:18] Explicit valence for atom # 29 Si, 5, is greater than permitted
[12:33:19] Explicit valence for atom # 26 C greater than permitted
[12:33:19] Explicit valence for atom # 36 C greater than permitted
[12:33:19] Explicit valence for atom # 34 C, 5, is greater than permitted
[12:33:19] Explicit valence for atom # 37 C greater than permitted
[12:33:19] Explicit valence for atom # 22 C greater than permitted
[12:33:19] Explicit valence for atom # 37 C greater than permitted
[12:33:19] Explicit valence for atom # 27 C greater than permitted
[12:33:19] Explicit valence for atom # 42 C greater than permitted
[12:33:19] Explicit valence for atom # 28 C, 5, is greater than permitted
[12:33:19] Explicit valence for atom # 35 C greater than permitted
[12:33:19] Explicit valence for atom # 30 C greater than permitted
[12:33:19] Explicit valence for atom # 32 C greater than permitted
[12:33:19] Explicit valence for atom # 32 C greater than permitted
[12:33:19] Explicit valence for atom # 38 C greater than permitted
[12:33:19] Explicit valence for atom # 25 C greater than permitted
[12:33:19] Explicit valence for atom # 26 C greater than permitted
[12:33:19] Explicit valence for atom # 33 C greater than permitted
[12:33:19] Explicit valence for atom # 30 C greater than permitted
[12:33:19] Explicit valence for atom # 31 Si, 5, is greater than permitted
[12:33:19] Explicit valence for atom # 32 C greater than permitted
[12:33:20] Explicit valence for atom # 31 C greater than permitted
[12:33:20] Explicit valence for atom # 30 C greater than permitted
[12:33:20] Explicit valence for atom # 35 C greater than permitted
[12:33:20] Explicit valence for atom # 33 Si, 5, is greater than permitted
[12:33:20] Explicit valence for atom # 31 C greater than permitted
[12:33:20] Explicit valence for atom # 34 C greater than permitted
[12:33:20] Explicit valence for atom # 29 C greater than permitted
[12:33:20] Explicit valence for atom # 33 C greater than permitted
[12:33:20] Explicit valence for atom # 36 C greater than permitted
[12:33:20] Explicit valence for atom # 33 Si, 5, is greater than permitted
[12:33:20] Explicit valence for atom # 39 Si, 5, is greater than permitted
[12:33:20] Explicit valence for atom # 27 C, 4, is greater than permitted
[12:33:20] Explicit valence for atom # 32 C greater than permitted
[12:33:20] Explicit valence for atom # 25 Si, 5, is greater than permitted
[12:33:20] Explicit valence for atom # 40 C greater than permitted
[12:33:20] Explicit valence for atom # 44 C greater than permitted
[12:33:20] Explicit valence for atom # 26 C greater than permitted
[12:33:20] Explicit valence for atom # 33 C greater than permitted
[12:33:20] Explicit valence for atom # 27 C, 6, is greater than permitted
[12:33:20] Explicit valence for atom # 0 C greater than permitted
[12:33:20] Explicit valence for atom # 32 C greater than permitted
[12:33:20] Explicit valence for atom # 0 C greater than permitted
[12:33:20] Explicit valence for atom # 36 C greater than permitted
[12:33:20] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:33:20] Explicit valence for atom # 11 C greater than permitted
[12:33:21] Explicit valence for atom # 29 C greater than permitted
[12:33:21] Explicit valence for atom # 23 C greater than permitted
[12:33:21] Explicit valence for atom # 30 C greater than permitted
[12:33:21] Explicit valence for atom # 13 C greater than permitted
[12:33:21] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:33:21] Explicit valence for atom # 40 C greater than permitted
[12:33:21] Explicit valence for atom # 39 C greater than permitted
[12:33:21] Explicit valence for atom # 25 C, 4, is greater than permitted
[12:33:21] Explicit valence for atom # 24 C, 5, is greater than permitted
[12:33:21] Explicit valence for atom # 29 C greater than permitted
[12:33:21] Explicit valence for atom # 29 C greater than permitted
[12:33:21] Explicit valence for atom # 33 C greater than permitted
[12:33:21] Explicit valence for atom # 33 C greater than permitted
[12:33:21] Explicit valence for atom # 28 C greater than permitted
[12:33:21] Explicit valence for atom # 15 C greater than permitted
[12:33:21] Explicit valence for atom # 29 C greater than permitted
[12:33:21] Explicit valence for atom # 16 C greater than permitted
[12:33:21] Explicit valence for atom # 28 P, 7, is greater than permitted
[12:33:21] Explicit valence for atom # 35 C greater than permitted
[12:33:21] Explicit valence for atom # 39 Si, 5, is greater than permitted
[12:33:21] Explicit valence for atom # 30 C greater than permitted
[12:33:21] Explicit valence for atom # 26 C greater than permitted
[12:33:21] Explicit valence for atom # 1 C greater than permitted
[12:33:21] Explicit valence for atom # 32 C greater than permitted
[12:33:21] Explicit valence for atom # 30 Si, 6, is greater than permitted
[12:33:21] Explicit valence for atom # 26 C greater than permitted
[12:33:22] Explicit valence for atom # 33 Si, 5, is greater than permitted
[12:33:22] Explicit valence for atom # 33 Si, 5, is greater than permitted
[12:33:22] Explicit valence for atom # 21 C greater than permitted
[12:33:22] Explicit valence for atom # 11 C greater than permitted
[12:33:22] Explicit valence for atom # 25 C greater than permitted
[12:33:22] Explicit valence for atom # 33 C greater than permitted
[12:33:22] Explicit valence for atom # 37 C, 5, is greater than permitted
[12:33:22] Explicit valence for atom # 24 C greater than permitted
[12:33:22] Explicit valence for atom # 13 Si, 5, is greater than permitted
[12:33:22] Explicit valence for atom # 24 C greater than permitted
[12:33:22] Explicit valence for atom # 19 C greater than permitted
[12:33:22] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:33:22] Explicit valence for atom # 31 C greater than permitted
[12:33:22] Explicit valence for atom # 38 C greater than permitted
[12:33:22] Explicit valence for atom # 32 C greater than permitted
[12:33:22] Explicit valence for atom # 26 C greater than permitted
[12:33:22] Explicit valence for atom # 29 C greater than permitted
[12:33:22] Explicit valence for atom # 24 C greater than permitted
[12:33:22] Explicit valence for atom # 32 C greater than permitted
[12:33:22] Explicit valence for atom # 21 C greater than permitted
[12:33:22] Explicit valence for atom # 4 P, 6, is greater than permitted
[12:33:22] Explicit valence for atom # 30 C, 5, is greater than permitted
[12:33:22] Explicit valence for atom # 29 P, 7, is greater than permitted
[12:33:22] Explicit valence for atom # 30 C greater than permitted
[12:33:22] Explicit valence for atom # 29 C greater than permitted
[12:33:23] Explicit valence for atom # 34 C greater than permitted
[12:33:23] Explicit valence for atom # 10 C greater than permitted
[12:33:23] Explicit valence for atom # 32 C greater than permitted
[12:33:23] Explicit valence for atom # 10 C, 6, is greater than permitted
[12:33:23] Explicit valence for atom # 24 Si, 5, is greater than permitted
[12:33:23] Explicit valence for atom # 24 C greater than permitted
[12:33:23] Explicit valence for atom # 33 C, 5, is greater than permitted
[12:33:23] Explicit valence for atom # 32 C greater than permitted
[12:33:23] Explicit valence for atom # 31 Si, 5, is greater than permitted
[12:33:23] Explicit valence for atom # 32 C greater than permitted
[12:33:23] Explicit valence for atom # 37 C greater than permitted
[12:33:23] Explicit valence for atom # 31 P, 7, is greater than permitted
[12:33:23] Explicit valence for atom # 31 C greater than permitted
[12:33:23] Explicit valence for atom # 27 C greater than permitted
[12:33:23] Explicit valence for atom # 28 C greater than permitted
[12:33:23] Explicit valence for atom # 29 C greater than permitted
[12:33:23] Explicit valence for atom # 24 Si, 5, is greater than permitted
[12:33:23] Explicit valence for atom # 27 C greater than permitted
[12:33:23] Explicit valence for atom # 27 C greater than permitted
[12:33:23] Explicit valence for atom # 33 C greater than permitted
[12:33:23] Explicit valence for atom # 10 C greater than permitted
[12:33:23] Explicit valence for atom # 17 C greater than permitted
[12:33:23] Explicit valence for atom # 26 C greater than permitted
[12:33:23] Explicit valence for atom # 29 C greater than permitted
[12:33:23] Explicit valence for atom # 10 C greater than permitted
[12:33:23] Explicit valence for atom # 34 Si, 5, is greater than permitted
[12:33:24] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:33:24] Explicit valence for atom # 27 C greater than permitted
[12:33:24] Explicit valence for atom # 28 C greater than permitted
[12:33:24] Explicit valence for atom # 23 C greater than permitted
[12:33:24] Explicit valence for atom # 32 C greater than permitted
[12:33:24] Explicit valence for atom # 13 C greater than permitted
[12:33:24] Explicit valence for atom # 29 C greater than permitted
[12:33:24] Explicit valence for atom # 30 C greater than permitted
[12:33:24] Explicit valence for atom # 29 C greater than permitted
[12:33:24] Explicit valence for atom # 30 C greater than permitted
[12:33:24] Explicit valence for atom # 32 C greater than permitted
[12:33:24] Explicit valence for atom # 26 C greater than permitted
[12:33:24] Explicit valence for atom # 28 C, 5, is greater than permitted
[12:33:24] Explicit valence for atom # 32 C greater than permitted
[12:33:24] Explicit valence for atom # 32 C greater than permitted
[12:33:24] Explicit valence for atom # 10 C, 6, is greater than permitted
[12:33:24] Explicit valence for atom # 26 C greater than permitted
[12:33:24] Explicit valence for atom # 27 C greater than permitted
[12:33:24] Explicit valence for atom # 26 C greater than permitted
[12:33:24] Explicit valence for atom # 12 C greater than permitted
[12:33:24] Explicit valence for atom # 26 C greater than permitted
[12:33:24] Explicit valence for atom # 28 C greater than permitted
[12:33:24] Explicit valence for atom # 28 C, 5, is greater than permitted
[12:33:24] Explicit valence for atom # 38 C greater than permitted
[12:33:25] Explicit valence for atom # 33 C greater than permitted
[12:33:25] Explicit valence for atom # 23 C greater than permitted
[12:33:25] Explicit valence for atom # 11 P, 5, is greater than permitted
[12:33:25] Explicit valence for atom # 31 C greater than permitted
[12:33:25] Explicit valence for atom # 33 P, 7, is greater than permitted
[12:33:25] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:33:25] Explicit valence for atom # 29 C greater than permitted
[12:33:25] Explicit valence for atom # 27 C greater than permitted
[12:33:25] Explicit valence for atom # 25 C greater than permitted
[12:33:25] Explicit valence for atom # 32 C greater than permitted
[12:33:25] Explicit valence for atom # 36 C greater than permitted
[12:33:25] Explicit valence for atom # 24 C, 6, is greater than permitted
[12:33:25] Explicit valence for atom # 28 C greater than permitted
[12:33:25] Explicit valence for atom # 14 C, 5, is greater than permitted
[12:33:25] Explicit valence for atom # 36 C greater than permitted
[12:33:25] Explicit valence for atom # 27 P, 7, is greater than permitted
[12:33:25] Explicit valence for atom # 21 C greater than permitted
[12:33:25] Explicit valence for atom # 27 C greater than permitted
[12:33:25] Explicit valence for atom # 34 C greater than permitted
[12:33:25] Explicit valence for atom # 28 C, 5, is greater than permitted
[12:33:25] Explicit valence for atom # 19 C greater than permitted
[12:33:25] Explicit valence for atom # 26 C greater than permitted
[12:33:25] Explicit valence for atom # 41 C greater than permitted
[12:33:25] Explicit valence for atom # 21 C greater than permitted
[12:33:26] Explicit valence for atom # 37 C greater than permitted
[12:33:27] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:33:27] Explicit valence for atom # 31 C greater than permitted
[12:33:27] Explicit valence for atom # 31 P, 7, is greater than permitted
[12:33:28] Explicit valence for atom # 23 C greater than permitted
[12:33:28] Explicit valence for atom # 24 C greater than permitted
[12:33:29] Explicit valence for atom # 26 C greater than permitted
[12:33:29] Explicit valence for atom # 31 C greater than permitted
[12:33:30] Explicit valence for atom # 22 C greater than permitted
[12:33:31] Explicit valence for atom # 27 C greater than permitted
[12:33:31] Explicit valence for atom # 29 P, 7, is greater than permitted

--- Processing cluster 2 ---

[12:33:50] Explicit valence for atom # 8 C, 5, is greater than permitted
[12:33:50] Explicit valence for atom # 4 C, 5, is greater than permitted
[12:33:50] Explicit valence for atom # 23 C greater than permitted
[12:33:50] Explicit valence for atom # 23 C greater than permitted
[12:33:50] Explicit valence for atom # 23 C, 5, is greater than permitted
[12:33:51] Explicit valence for atom # 37 C greater than permitted
[12:33:51] Explicit valence for atom # 11 C greater than permitted
[12:33:51] Explicit valence for atom # 31 C greater than permitted
[12:33:51] Explicit valence for atom # 29 C greater than permitted
[12:33:51] Explicit valence for atom # 23 C greater than permitted
[12:33:51] Explicit valence for atom # 34 C greater than permitted
[12:33:51] Explicit valence for atom # 7 C greater than permitted
[12:33:52] Explicit valence for atom # 25 C greater than permitted
[12:33:52] Explicit valence for atom # 18 C greater than permitted
[12:33:52] Explicit valence for atom # 22 Si, 6, is greater than permitted
[12:33:52] Explicit valence for atom # 25 C greater than permitted
[12:33:52] Explicit valence for atom # 33 C greater than permitted
[12:33:52] Explicit valence for atom # 26 C greater than permitted
[12:33:53] Explicit valence for atom # 19 C greater than permitted
[12:33:53] Explicit valence for atom # 30 C greater than permitted
[12:33:53] Explicit valence for atom # 35 C greater than permitted
[12:33:53] Explicit valence for atom # 32 C greater than permitted
[12:33:53] Explicit valence for atom # 33 C greater than permitted
[12:33:53] Explicit valence for atom # 28 C, 5, is greater than permitted
[12:33:53] Explicit valence for atom # 25 C greater than permitted
[12:33:53] Explicit valence for atom # 28 C greater than permitted
[12:33:53] Explicit valence for atom # 35 C greater than permitted
[12:33:53] Explicit valence for atom # 15 C, 5, is greater than permitted
[12:33:53] Explicit valence for atom # 34 C greater than permitted
[12:33:54] Explicit valence for atom # 28 C, 5, is greater than permitted
[12:33:54] Explicit valence for atom # 30 C greater than permitted
[12:33:54] Explicit valence for atom # 26 C greater than permitted
[12:33:54] Explicit valence for atom # 22 C greater than permitted
[12:33:54] Explicit valence for atom # 33 C greater than permitted
[12:33:54] Explicit valence for atom # 37 C greater than permitted
[12:33:54] Explicit valence for atom # 11 C greater than permitted
[12:33:54] Explicit valence for atom # 28 C, 5, is greater than permitted
[12:33:54] Explicit valence for atom # 32 C greater than permitted
[12:33:54] Explicit valence for atom # 34 C greater than permitted
[12:33:54] Explicit valence for atom # 24 C greater than permitted
[12:33:55] Explicit valence for atom # 29 C greater than permitted
[12:33:55] Explicit valence for atom # 28 C greater than permitted
[12:33:55] Explicit valence for atom # 36 C greater than permitted
[12:33:55] Explicit valence for atom # 26 C, 5, is greater than permitted
[12:33:55] Explicit valence for atom # 29 C greater than permitted
[12:33:55] Explicit valence for atom # 31 C greater than permitted
[12:33:55] Explicit valence for atom # 31 C greater than permitted
[12:33:55] Explicit valence for atom # 18 C greater than permitted
[12:33:55] Explicit valence for atom # 16 C greater than permitted
[12:33:55] Explicit valence for atom # 30 C greater than permitted
[12:33:55] Explicit valence for atom # 32 C greater than permitted
[12:33:55] Explicit valence for atom # 28 C greater than permitted
[12:33:56] Explicit valence for atom # 36 C greater than permitted
[12:33:56] Explicit valence for atom # 30 C, 5, is greater than permitted
[12:33:56] Explicit valence for atom # 29 C greater than permitted
[12:33:56] Explicit valence for atom # 8 C greater than permitted
[12:33:56] Explicit valence for atom # 26 C greater than permitted
[12:33:56] Explicit valence for atom # 39 C greater than permitted
[12:33:56] Explicit valence for atom # 30 C greater than permitted
[12:33:56] Explicit valence for atom # 28 C greater than permitted
[12:33:56] Explicit valence for atom # 37 C greater than permitted
[12:33:56] Explicit valence for atom # 23 C greater than permitted
[12:33:56] Explicit valence for atom # 33 C greater than permitted
[12:33:56] Explicit valence for atom # 8 C greater than permitted
[12:33:56] Explicit valence for atom # 33 C greater than permitted
[12:33:56] Explicit valence for atom # 27 C greater than permitted
[12:33:56] Explicit valence for atom # 22 C, 6, is greater than permitted
[12:33:56] Explicit valence for atom # 28 C greater than permitted
[12:33:56] Explicit valence for atom # 35 C greater than permitted
[12:33:57] Explicit valence for atom # 29 C greater than permitted
[12:33:57] Explicit valence for atom # 31 C greater than permitted
[12:33:57] Explicit valence for atom # 27 C greater than permitted
[12:33:57] Explicit valence for atom # 32 C, 5, is greater than permitted
[12:33:57] Explicit valence for atom # 20 C, 6, is greater than permitted
[12:33:57] Explicit valence for atom # 29 Si, 5, is greater than permitted
[12:33:57] Explicit valence for atom # 9 Si, 5, is greater than permitted
[12:33:57] Explicit valence for atom # 27 C greater than permitted
[12:33:57] Explicit valence for atom # 33 C greater than permitted
[12:33:57] Explicit valence for atom # 8 C, 5, is greater than permitted
[12:33:57] Explicit valence for atom # 31 C, 5, is greater than permitted
[12:33:57] Explicit valence for atom # 20 C greater than permitted
[12:33:57] Explicit valence for atom # 33 C greater than permitted
[12:33:57] Explicit valence for atom # 8 C greater than permitted
[12:33:57] Explicit valence for atom # 28 C, 5, is greater than permitted
[12:33:58] Explicit valence for atom # 20 C, 5, is greater than permitted
[12:33:58] Explicit valence for atom # 30 C greater than permitted
[12:33:58] Explicit valence for atom # 17 C greater than permitted
[12:33:58] Explicit valence for atom # 10 C greater than permitted
[12:33:58] Explicit valence for atom # 31 C greater than permitted
[12:33:58] Explicit valence for atom # 38 C greater than permitted
[12:33:58] Explicit valence for atom # 29 C greater than permitted
[12:33:58] Explicit valence for atom # 27 C greater than permitted
[12:33:58] Explicit valence for atom # 16 C greater than permitted
[12:33:58] Explicit valence for atom # 27 C greater than permitted
[12:33:58] Explicit valence for atom # 24 C greater than permitted
[12:33:58] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:33:59] Explicit valence for atom # 29 C greater than permitted
[12:33:59] Explicit valence for atom # 35 C greater than permitted
[12:33:59] Explicit valence for atom # 24 C greater than permitted
[12:33:59] Explicit valence for atom # 21 C greater than permitted
[12:33:59] Explicit valence for atom # 12 C greater than permitted
[12:33:59] Explicit valence for atom # 35 C, 6, is greater than permitted
[12:33:59] Explicit valence for atom # 6 C greater than permitted
[12:33:59] Explicit valence for atom # 24 C greater than permitted
[12:33:59] Explicit valence for atom # 7 C greater than permitted
[12:33:59] Explicit valence for atom # 28 C greater than permitted
[12:33:59] Explicit valence for atom # 27 C greater than permitted
[12:33:59] Explicit valence for atom # 25 C greater than permitted
[12:33:59] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:33:59] Explicit valence for atom # 27 C greater than permitted
[12:34:00] Explicit valence for atom # 24 C greater than permitted
[12:34:00] Explicit valence for atom # 27 C greater than permitted
[12:34:00] Explicit valence for atom # 27 C greater than permitted
[12:34:00] Explicit valence for atom # 29 C greater than permitted
[12:34:00] Explicit valence for atom # 28 C greater than permitted
[12:34:00] Explicit valence for atom # 27 C greater than permitted
[12:34:00] Explicit valence for atom # 18 Si, 5, is greater than permitted
[12:34:00] Explicit valence for atom # 15 C, 5, is greater than permitted
[12:34:00] Explicit valence for atom # 21 C greater than permitted
[12:34:00] Explicit valence for atom # 27 C greater than permitted
[12:34:00] Explicit valence for atom # 21 C greater than permitted
[12:34:00] Explicit valence for atom # 15 C, 5, is greater than permitted
[12:34:00] Explicit valence for atom # 31 C greater than permitted
[12:34:00] Explicit valence for atom # 28 C, 5, is greater than permitted
[12:34:00] Explicit valence for atom # 32 C greater than permitted
[12:34:00] Explicit valence for atom # 32 C greater than permitted
[12:34:00] Explicit valence for atom # 29 C, 5, is greater than permitted
[12:34:00] Explicit valence for atom # 24 C greater than permitted
[12:34:00] Explicit valence for atom # 31 C greater than permitted
[12:34:01] Explicit valence for atom # 31 C greater than permitted
[12:34:01] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:34:01] Explicit valence for atom # 24 C greater than permitted
[12:34:01] Explicit valence for atom # 38 C greater than permitted
[12:34:01] Explicit valence for atom # 28 C greater than permitted
[12:34:01] Explicit valence for atom # 30 C, 5, is greater than permitted
[12:34:01] Explicit valence for atom # 6 C greater than permitted
[12:34:01] Explicit valence for atom # 26 C greater than permitted
[12:34:01] Explicit valence for atom # 36 C greater than permitted
[12:34:01] Explicit valence for atom # 24 C greater than permitted
[12:34:01] Explicit valence for atom # 6 C greater than permitted
[12:34:01] Explicit valence for atom # 21 C greater than permitted
[12:34:01] Explicit valence for atom # 24 C greater than permitted
[12:34:01] Explicit valence for atom # 11 C greater than permitted
[12:34:01] Explicit valence for atom # 24 C greater than permitted
[12:34:02] Explicit valence for atom # 34 C greater than permitted
[12:34:02] Explicit valence for atom # 28 C greater than permitted
[12:34:02] Explicit valence for atom # 30 C greater than permitted
[12:34:02] Explicit valence for atom # 24 C greater than permitted
[12:34:02] Explicit valence for atom # 7 C greater than permitted
[12:34:02] Explicit valence for atom # 45 C greater than permitted
[12:34:02] Explicit valence for atom # 33 C greater than permitted
[12:34:02] Explicit valence for atom # 34 C greater than permitted
[12:34:02] Explicit valence for atom # 31 C greater than permitted
[12:34:02] Explicit valence for atom # 37 C greater than permitted
[12:34:02] Explicit valence for atom # 32 C greater than permitted
[12:34:03] Explicit valence for atom # 28 C greater than permitted
[12:34:03] Explicit valence for atom # 9 C, 5, is greater than permitted
[12:34:03] Explicit valence for atom # 33 C greater than permitted
[12:34:04] Explicit valence for atom # 29 C greater than permitted
[12:34:05] Explicit valence for atom # 28 C greater than permitted
[12:34:05] Explicit valence for atom # 29 C greater than permitted
[12:34:05] Explicit valence for atom # 23 C greater than permitted
[12:34:06] Explicit valence for atom # 32 C greater than permitted
[12:34:07] Explicit valence for atom # 29 C greater than permitted
[12:34:07] Explicit valence for atom # 27 C greater than permitted

--- Processing cluster 3 ---

[12:34:25] Explicit valence for atom # 25 C, 5, is greater than permitted
[12:34:25] Explicit valence for atom # 32 C greater than permitted
[12:34:25] Explicit valence for atom # 36 P, 7, is greater than permitted
[12:34:25] Explicit valence for atom # 32 C, 5, is greater than permitted
[12:34:25] Explicit valence for atom # 31 Si, 5, is greater than permitted
[12:34:25] Explicit valence for atom # 32 Si, 6, is greater than permitted
[12:34:25] Explicit valence for atom # 20 C greater than permitted
[12:34:25] Explicit valence for atom # 3 C greater than permitted
[12:34:25] Explicit valence for atom # 32 Si, 5, is greater than permitted
[12:34:25] Explicit valence for atom # 32 C, 5, is greater than permitted
[12:34:25] Explicit valence for atom # 33 C greater than permitted
[12:34:25] Explicit valence for atom # 31 Si, 5, is greater than permitted
[12:34:25] Explicit valence for atom # 32 Si, 5, is greater than permitted
[12:34:26] Explicit valence for atom # 33 C, 5, is greater than permitted
[12:34:26] Explicit valence for atom # 31 Si, 5, is greater than permitted
[12:34:26] Explicit valence for atom # 30 P, 7, is greater than permitted
[12:34:26] Explicit valence for atom # 25 C greater than permitted
[12:34:26] Explicit valence for atom # 28 C greater than permitted
[12:34:26] Explicit valence for atom # 33 C greater than permitted
[12:34:26] Explicit valence for atom # 29 C greater than permitted
[12:34:26] Explicit valence for atom # 2 P, 7, is greater than permitted
[12:34:26] Explicit valence for atom # 30 C, 5, is greater than permitted
[12:34:26] Explicit valence for atom # 16 C greater than permitted
[12:34:26] Explicit valence for atom # 29 C greater than permitted
[12:34:26] Explicit valence for atom # 36 P, 7, is greater than permitted
[12:34:26] Explicit valence for atom # 25 C greater than permitted
[12:34:26] Explicit valence for atom # 3 C greater than permitted
[12:34:26] Explicit valence for atom # 24 P, 7, is greater than permitted
[12:34:26] Explicit valence for atom # 32 P, 7, is greater than permitted
[12:34:26] Explicit valence for atom # 30 C greater than permitted
[12:34:26] Explicit valence for atom # 35 P, 7, is greater than permitted
[12:34:26] Explicit valence for atom # 36 C greater than permitted
[12:34:27] Explicit valence for atom # 34 C greater than permitted
[12:34:27] Explicit valence for atom # 34 Si, 5, is greater than permitted
[12:34:27] Explicit valence for atom # 18 C greater than permitted
[12:34:27] Explicit valence for atom # 40 C greater than permitted
[12:34:27] Explicit valence for atom # 41 C greater than permitted
[12:34:27] Explicit valence for atom # 27 Si, 5, is greater than permitted
[12:34:27] Explicit valence for atom # 36 Si, 5, is greater than permitted
[12:34:27] Explicit valence for atom # 31 Si, 5, is greater than permitted
[12:34:27] Explicit valence for atom # 33 C greater than permitted
[12:34:27] Explicit valence for atom # 38 C greater than permitted
[12:34:27] Explicit valence for atom # 33 C greater than permitted
[12:34:27] Explicit valence for atom # 34 P, 7, is greater than permitted
[12:34:27] Explicit valence for atom # 36 C greater than permitted
[12:34:27] Explicit valence for atom # 36 P, 7, is greater than permitted
[12:34:27] Explicit valence for atom # 32 Si, 5, is greater than permitted
[12:34:27] Explicit valence for atom # 14 C greater than permitted
[12:34:27] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:34:27] Explicit valence for atom # 27 C greater than permitted
[12:34:27] Explicit valence for atom # 30 Si, 5, is greater than permitted
[12:34:27] Explicit valence for atom # 19 Si, 5, is greater than permitted
[12:34:27] Explicit valence for atom # 24 C greater than permitted
[12:34:28] Explicit valence for atom # 37 C greater than permitted
[12:34:28] Explicit valence for atom # 27 P, 7, is greater than permitted
[12:34:28] Explicit valence for atom # 33 C greater than permitted
[12:34:28] Explicit valence for atom # 30 Si, 5, is greater than permitted
[12:34:28] Explicit valence for atom # 30 Si, 5, is greater than permitted
[12:34:28] Explicit valence for atom # 30 Si, 5, is greater than permitted
[12:34:28] Explicit valence for atom # 36 P, 7, is greater than permitted
[12:34:28] Explicit valence for atom # 5 C greater than permitted
[12:34:28] Explicit valence for atom # 33 Si, 5, is greater than permitted
[12:34:28] Explicit valence for atom # 32 C greater than permitted
[12:34:28] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:34:28] Explicit valence for atom # 28 P, 7, is greater than permitted
[12:34:28] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:34:28] Explicit valence for atom # 33 C greater than permitted
[12:34:28] Explicit valence for atom # 24 C, 5, is greater than permitted
[12:34:28] Explicit valence for atom # 26 C greater than permitted
[12:34:28] Explicit valence for atom # 27 C greater than permitted
[12:34:28] Explicit valence for atom # 37 Si, 5, is greater than permitted
[12:34:28] Explicit valence for atom # 3 C greater than permitted
[12:34:28] Explicit valence for atom # 4 C, 5, is greater than permitted
[12:34:28] Explicit valence for atom # 33 C greater than permitted
[12:34:28] Explicit valence for atom # 33 C greater than permitted
[12:34:28] Explicit valence for atom # 32 Si, 5, is greater than permitted
[12:34:28] Explicit valence for atom # 27 P, 7, is greater than permitted
[12:34:29] Explicit valence for atom # 32 C greater than permitted
[12:34:29] Explicit valence for atom # 28 P, 7, is greater than permitted
[12:34:29] Explicit valence for atom # 28 Si, 5, is greater than permitted
[12:34:29] Explicit valence for atom # 32 Si, 5, is greater than permitted
[12:34:29] Explicit valence for atom # 37 Si, 5, is greater than permitted
[12:34:29] Explicit valence for atom # 3 C greater than permitted
[12:34:29] Explicit valence for atom # 6 C greater than permitted
[12:34:29] Explicit valence for atom # 26 C greater than permitted
[12:34:29] Explicit valence for atom # 2 C greater than permitted
[12:34:29] Explicit valence for atom # 36 Si, 5, is greater than permitted
[12:34:29] Explicit valence for atom # 32 C greater than permitted
[12:34:29] Explicit valence for atom # 33 Si, 5, is greater than permitted
[12:34:29] Explicit valence for atom # 14 Si, 5, is greater than permitted
[12:34:29] Explicit valence for atom # 31 C greater than permitted
[12:34:29] Explicit valence for atom # 36 C greater than permitted
[12:34:29] Explicit valence for atom # 33 P, 7, is greater than permitted
[12:34:29] Explicit valence for atom # 24 C greater than permitted
[12:34:29] Explicit valence for atom # 26 P, 7, is greater than permitted
[12:34:29] Explicit valence for atom # 33 C greater than permitted
[12:34:29] Explicit valence for atom # 30 P, 7, is greater than permitted
[12:34:29] Explicit valence for atom # 6 C greater than permitted
[12:34:29] Explicit valence for atom # 30 Si, 5, is greater than permitted
[12:34:29] Explicit valence for atom # 31 C greater than permitted
[12:34:29] Explicit valence for atom # 30 C, 6, is greater than permitted
[12:34:29] Explicit valence for atom # 27 P, 7, is greater than permitted
[12:34:29] Explicit valence for atom # 18 C greater than permitted
[12:34:29] Explicit valence for atom # 35 P, 7, is greater than permitted
[12:34:29] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:34:29] Explicit valence for atom # 31 Si, 5, is greater than permitted
[12:34:29] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:34:29] Explicit valence for atom # 32 C greater than permitted
[12:34:30] Explicit valence for atom # 42 C greater than permitted
[12:34:30] Explicit valence for atom # 38 C greater than permitted
[12:34:30] Explicit valence for atom # 18 C greater than permitted
[12:34:30] Explicit valence for atom # 33 Si, 5, is greater than permitted
[12:34:30] Explicit valence for atom # 26 C, 5, is greater than permitted
[12:34:30] Explicit valence for atom # 25 C greater than permitted
[12:34:30] Explicit valence for atom # 30 Si, 5, is greater than permitted
[12:34:30] Explicit valence for atom # 26 C, 5, is greater than permitted
[12:34:30] Explicit valence for atom # 29 C, 5, is greater than permitted
[12:34:30] Explicit valence for atom # 35 Si, 5, is greater than permitted
[12:34:30] Explicit valence for atom # 30 Si, 5, is greater than permitted
[12:34:30] Explicit valence for atom # 35 Si, 5, is greater than permitted
[12:34:30] Explicit valence for atom # 14 C greater than permitted
[12:34:30] Explicit valence for atom # 37 P, 7, is greater than permitted
[12:34:30] Explicit valence for atom # 33 C greater than permitted
[12:34:30] Explicit valence for atom # 32 C greater than permitted
[12:34:30] Explicit valence for atom # 37 Si, 5, is greater than permitted
[12:34:30] Explicit valence for atom # 3 C greater than permitted
[12:34:30] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:34:30] Explicit valence for atom # 27 C greater than permitted
[12:34:30] Explicit valence for atom # 27 C greater than permitted
[12:34:30] Explicit valence for atom # 28 C greater than permitted
[12:34:30] Explicit valence for atom # 31 C greater than permitted
[12:34:30] Explicit valence for atom # 33 C greater than permitted
[12:34:30] Explicit valence for atom # 28 C greater than permitted
[12:34:30] Explicit valence for atom # 33 C greater than permitted
[12:34:30] Explicit valence for atom # 31 C, 5, is greater than permitted
[12:34:30] Explicit valence for atom # 30 C greater than permitted
[12:34:30] Explicit valence for atom # 27 P, 7, is greater than permitted
[12:34:30] Explicit valence for atom # 32 Si, 5, is greater than permitted
[12:34:30] Explicit valence for atom # 20 C, 5, is greater than permitted
[12:34:30] Explicit valence for atom # 35 C greater than permitted
[12:34:30] Explicit valence for atom # 36 C greater than permitted
[12:34:30] Explicit valence for atom # 24 C greater than permitted
[12:34:30] Explicit valence for atom # 32 P, 7, is greater than permitted
[12:34:30] Explicit valence for atom # 32 C greater than permitted
[12:34:31] Explicit valence for atom # 35 P, 7, is greater than permitted
[12:34:31] Explicit valence for atom # 24 P, 7, is greater than permitted
[12:34:31] Explicit valence for atom # 29 C greater than permitted
[12:34:31] Explicit valence for atom # 33 Si, 5, is greater than permitted
[12:34:31] Explicit valence for atom # 26 C, 5, is greater than permitted
[12:34:31] Explicit valence for atom # 30 C greater than permitted
[12:34:31] Explicit valence for atom # 31 C greater than permitted
[12:34:31] Explicit valence for atom # 27 P, 7, is greater than permitted
[12:34:31] Explicit valence for atom # 30 Si, 5, is greater than permitted
[12:34:31] Explicit valence for atom # 30 Si, 5, is greater than permitted
[12:34:31] Explicit valence for atom # 29 C greater than permitted
[12:34:31] Explicit valence for atom # 25 C greater than permitted
[12:34:31] Explicit valence for atom # 31 Si, 5, is greater than permitted
[12:34:31] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:34:31] Explicit valence for atom # 39 P, 7, is greater than permitted
[12:34:31] Explicit valence for atom # 32 Si, 5, is greater than permitted
[12:34:31] Explicit valence for atom # 33 C greater than permitted
[12:34:31] Explicit valence for atom # 30 C, 5, is greater than permitted
[12:34:31] Explicit valence for atom # 20 C greater than permitted
[12:34:31] Explicit valence for atom # 31 Si, 5, is greater than permitted
[12:34:31] Explicit valence for atom # 30 C greater than permitted
[12:34:31] Explicit valence for atom # 33 Si, 5, is greater than permitted
[12:34:31] Explicit valence for atom # 32 C, 5, is greater than permitted
[12:34:31] Explicit valence for atom # 33 C greater than permitted
[12:34:31] Explicit valence for atom # 32 Si, 5, is greater than permitted
[12:34:31] Explicit valence for atom # 32 C greater than permitted
[12:34:32] Explicit valence for atom # 41 C greater than permitted
[12:34:32] Explicit valence for atom # 24 C greater than permitted
[12:34:32] Explicit valence for atom # 34 P, 7, is greater than permitted
[12:34:32] Explicit valence for atom # 29 C, 5, is greater than permitted
[12:34:32] Explicit valence for atom # 24 C greater than permitted
[12:34:32] Explicit valence for atom # 23 C greater than permitted
[12:34:32] Explicit valence for atom # 25 C greater than permitted
[12:34:32] Explicit valence for atom # 28 C greater than permitted
[12:34:32] Explicit valence for atom # 34 P, 7, is greater than permitted
[12:34:32] Explicit valence for atom # 34 Si, 5, is greater than permitted
[12:34:32] Explicit valence for atom # 40 Si, 5, is greater than permitted
[12:34:32] Explicit valence for atom # 5 Si, 5, is greater than permitted
[12:34:32] Explicit valence for atom # 29 C greater than permitted
[12:34:32] Explicit valence for atom # 15 C greater than permitted
[12:34:32] Explicit valence for atom # 35 Si, 5, is greater than permitted
[12:34:32] Explicit valence for atom # 24 P, 7, is greater than permitted
[12:34:32] Explicit valence for atom # 30 Si, 5, is greater than permitted
[12:34:32] Explicit valence for atom # 36 Si, 5, is greater than permitted
[12:34:32] Explicit valence for atom # 28 P, 7, is greater than permitted
[12:34:32] Explicit valence for atom # 27 P, 7, is greater than permitted
[12:34:32] Explicit valence for atom # 31 Si, 5, is greater than permitted
[12:34:32] Explicit valence for atom # 28 C greater than permitted
[12:34:32] Explicit valence for atom # 30 C greater than permitted
[12:34:32] Explicit valence for atom # 33 C greater than permitted
[12:34:32] Explicit valence for atom # 35 C greater than permitted
[12:34:32] Explicit valence for atom # 6 C greater than permitted
[12:34:32] Explicit valence for atom # 33 Si, 5, is greater than permitted
[12:34:32] Explicit valence for atom # 18 P, 7, is greater than permitted
[12:34:32] Explicit valence for atom # 38 C greater than permitted
[12:34:32] Explicit valence for atom # 27 C greater than permitted
[12:34:32] Explicit valence for atom # 21 C, 5, is greater than permitted
[12:34:32] Explicit valence for atom # 33 C greater than permitted
[12:34:32] Explicit valence for atom # 41 C greater than permitted
[12:34:32] Explicit valence for atom # 28 C greater than permitted
[12:34:32] Explicit valence for atom # 24 P, 7, is greater than permitted
[12:34:32] Explicit valence for atom # 6 C greater than permitted
[12:34:32] Explicit valence for atom # 33 Si, 5, is greater than permitted
[12:34:32] Explicit valence for atom # 24 C greater than permitted
[12:34:32] Explicit valence for atom # 33 C greater than permitted
[12:34:32] Explicit valence for atom # 3 C greater than permitted
[12:34:32] Explicit valence for atom # 29 C greater than permitted
[12:34:32] Explicit valence for atom # 34 Si, 5, is greater than permitted
[12:34:32] Explicit valence for atom # 21 P, 7, is greater than permitted
[12:34:32] Explicit valence for atom # 4 C greater than permitted
[12:34:32] Explicit valence for atom # 29 C greater than permitted
[12:34:32] Explicit valence for atom # 25 C, 5, is greater than permitted
[12:34:33] Explicit valence for atom # 29 C, 5, is greater than permitted
[12:34:33] Explicit valence for atom # 24 C greater than permitted
[12:34:33] Explicit valence for atom # 33 C greater than permitted
[12:34:33] Explicit valence for atom # 29 C greater than permitted
[12:34:33] Explicit valence for atom # 32 Si, 5, is greater than permitted
[12:34:33] Explicit valence for atom # 29 Si, 6, is greater than permitted
[12:34:33] Explicit valence for atom # 29 C greater than permitted
[12:34:33] Explicit valence for atom # 19 C greater than permitted
[12:34:33] Explicit valence for atom # 31 Si, 5, is greater than permitted
[12:34:33] Explicit valence for atom # 37 C greater than permitted
[12:34:33] Explicit valence for atom # 29 P, 7, is greater than permitted
[12:34:33] Explicit valence for atom # 29 P, 7, is greater than permitted
[12:34:33] Explicit valence for atom # 33 Si, 5, is greater than permitted
[12:34:33] Explicit valence for atom # 32 C greater than permitted
[12:34:33] Explicit valence for atom # 32 Si, 5, is greater than permitted
[12:34:33] Explicit valence for atom # 29 C greater than permitted
[12:34:33] Explicit valence for atom # 39 P, 7, is greater than permitted
[12:34:33] Explicit valence for atom # 26 P, 7, is greater than permitted
[12:34:33] Explicit valence for atom # 27 C greater than permitted
[12:34:33] Explicit valence for atom # 22 C greater than permitted
[12:34:33] Explicit valence for atom # 29 Si, 5, is greater than permitted
[12:34:33] Explicit valence for atom # 25 C greater than permitted
[12:34:33] Explicit valence for atom # 30 P, 7, is greater than permitted
[12:34:33] Explicit valence for atom # 26 C greater than permitted
[12:34:33] Explicit valence for atom # 33 C greater than permitted
[12:34:33] Explicit valence for atom # 29 C greater than permitted
[12:34:33] Explicit valence for atom # 3 C greater than permitted
[12:34:33] Explicit valence for atom # 11 C greater than permitted
[12:34:33] Explicit valence for atom # 28 P, 7, is greater than permitted
[12:34:33] Explicit valence for atom # 32 C greater than permitted
[12:34:33] Explicit valence for atom # 30 C greater than permitted
[12:34:33] Explicit valence for atom # 31 Si, 5, is greater than permitted
[12:34:33] Explicit valence for atom # 26 C, 5, is greater than permitted
[12:34:33] Explicit valence for atom # 33 C, 5, is greater than permitted
[12:34:33] Explicit valence for atom # 28 C greater than permitted
[12:34:33] Explicit valence for atom # 33 Si, 6, is greater than permitted
[12:34:34] Explicit valence for atom # 26 C, 5, is greater than permitted
[12:34:34] Explicit valence for atom # 32 Si, 5, is greater than permitted
[12:34:34] Explicit valence for atom # 29 P, 7, is greater than permitted
[12:34:34] Explicit valence for atom # 29 C, 6, is greater than permitted
[12:34:34] Explicit valence for atom # 33 Si, 5, is greater than permitted
[12:34:34] Explicit valence for atom # 27 P, 7, is greater than permitted
[12:34:34] Explicit valence for atom # 34 C greater than permitted
[12:34:34] Explicit valence for atom # 30 C greater than permitted
[12:34:34] Explicit valence for atom # 7 Si, 5, is greater than permitted
[12:34:34] Explicit valence for atom # 30 C greater than permitted
[12:34:34] Explicit valence for atom # 29 C greater than permitted
[12:34:34] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:34:34] Explicit valence for atom # 35 Si, 5, is greater than permitted
[12:34:34] Explicit valence for atom # 31 P, 7, is greater than permitted
[12:34:35] Explicit valence for atom # 40 C greater than permitted
[12:34:35] Explicit valence for atom # 34 C greater than permitted
[12:34:35] Explicit valence for atom # 29 C greater than permitted
[12:34:35] Explicit valence for atom # 32 P, 7, is greater than permitted
[12:34:35] Explicit valence for atom # 32 C greater than permitted
[12:34:35] Explicit valence for atom # 27 P, 7, is greater than permitted
[12:34:35] Explicit valence for atom # 29 C greater than permitted
[12:34:36] Explicit valence for atom # 27 P, 7, is greater than permitted
[12:34:36] Explicit valence for atom # 40 C greater than permitted
[12:34:37] Explicit valence for atom # 34 Si, 5, is greater than permitted
[12:34:37] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:34:37] Explicit valence for atom # 33 Si, 5, is greater than permitted
[12:34:37] Explicit valence for atom # 28 P, 7, is greater than permitted
[12:34:37] Explicit valence for atom # 30 Si, 6, is greater than permitted
[12:34:38] Explicit valence for atom # 30 Si, 5, is greater than permitted
[12:34:38] Explicit valence for atom # 17 C greater than permitted

--- Processing cluster 4 ---

[12:34:58] Explicit valence for atom # 17 C greater than permitted
[12:34:59] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:34:59] Explicit valence for atom # 26 C, 6, is greater than permitted
[12:34:59] Explicit valence for atom # 17 C greater than permitted
[12:34:59] Explicit valence for atom # 28 C greater than permitted
[12:34:59] Explicit valence for atom # 2 C greater than permitted
[12:34:59] Explicit valence for atom # 35 Si, 5, is greater than permitted
[12:34:59] Explicit valence for atom # 29 C greater than permitted
[12:34:59] Explicit valence for atom # 28 C greater than permitted
[12:34:59] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:34:59] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:34:59] Explicit valence for atom # 23 Si, 5, is greater than permitted
[12:34:59] Explicit valence for atom # 26 C greater than permitted
[12:34:59] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:34:59] Explicit valence for atom # 31 C greater than permitted
[12:34:59] Explicit valence for atom # 27 C greater than permitted
[12:34:59] Explicit valence for atom # 26 P, 6, is greater than permitted
[12:34:59] Explicit valence for atom # 28 C greater than permitted
[12:34:59] Explicit valence for atom # 25 C greater than permitted
[12:34:59] Explicit valence for atom # 9 C greater than permitted
[12:35:00] Explicit valence for atom # 28 C greater than permitted
[12:35:00] Explicit valence for atom # 30 C greater than permitted
[12:35:00] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:00] Explicit valence for atom # 31 Si, 5, is greater than permitted
[12:35:00] Explicit valence for atom # 25 C greater than permitted
[12:35:00] Explicit valence for atom # 26 Si, 5, is greater than permitted
[12:35:00] Explicit valence for atom # 24 C greater than permitted
[12:35:00] Explicit valence for atom # 30 Si, 5, is greater than permitted
[12:35:00] Explicit valence for atom # 27 C greater than permitted
[12:35:00] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:00] Explicit valence for atom # 25 C greater than permitted
[12:35:00] Explicit valence for atom # 28 P, 5, is greater than permitted
[12:35:00] Explicit valence for atom # 31 C greater than permitted
[12:35:00] Explicit valence for atom # 43 C greater than permitted
[12:35:00] Explicit valence for atom # 3 C greater than permitted
[12:35:00] Explicit valence for atom # 23 C greater than permitted
[12:35:00] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:00] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:00] Explicit valence for atom # 28 C greater than permitted
[12:35:00] Explicit valence for atom # 26 Si, 6, is greater than permitted
[12:35:00] Explicit valence for atom # 42 C greater than permitted
[12:35:00] Explicit valence for atom # 31 Si, 5, is greater than permitted
[12:35:00] Explicit valence for atom # 38 C greater than permitted
[12:35:00] Explicit valence for atom # 23 C greater than permitted
[12:35:00] Explicit valence for atom # 29 C greater than permitted
[12:35:00] Explicit valence for atom # 28 C greater than permitted
[12:35:00] Explicit valence for atom # 42 C greater than permitted
[12:35:00] Explicit valence for atom # 27 C greater than permitted
[12:35:00] Explicit valence for atom # 40 C greater than permitted
[12:35:00] Explicit valence for atom # 35 C, 5, is greater than permitted
[12:35:00] Explicit valence for atom # 32 C greater than permitted
[12:35:00] Explicit valence for atom # 27 C greater than permitted
[12:35:00] Explicit valence for atom # 27 C greater than permitted
[12:35:00] Explicit valence for atom # 11 C greater than permitted
[12:35:00] Explicit valence for atom # 29 C greater than permitted
[12:35:00] Explicit valence for atom # 43 C greater than permitted
[12:35:00] Explicit valence for atom # 6 C greater than permitted
[12:35:00] Explicit valence for atom # 33 C greater than permitted
[12:35:00] Explicit valence for atom # 38 C, 5, is greater than permitted
[12:35:00] Explicit valence for atom # 1 C greater than permitted
[12:35:00] Explicit valence for atom # 41 C greater than permitted
[12:35:00] Explicit valence for atom # 35 C greater than permitted
[12:35:00] Explicit valence for atom # 30 C greater than permitted
[12:35:00] Explicit valence for atom # 27 Si, 5, is greater than permitted
[12:35:00] Explicit valence for atom # 22 C greater than permitted
[12:35:00] Explicit valence for atom # 39 C greater than permitted
[12:35:00] Explicit valence for atom # 36 C greater than permitted
[12:35:00] Explicit valence for atom # 2 C greater than permitted
[12:35:00] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:00] Explicit valence for atom # 35 C, 5, is greater than permitted
[12:35:00] Explicit valence for atom # 27 C greater than permitted
[12:35:00] Explicit valence for atom # 27 C greater than permitted
[12:35:00] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:00] Explicit valence for atom # 29 C greater than permitted
[12:35:00] Explicit valence for atom # 35 C greater than permitted
[12:35:01] Explicit valence for atom # 38 P, 7, is greater than permitted
[12:35:01] Explicit valence for atom # 29 C greater than permitted
[12:35:01] Explicit valence for atom # 33 P, 7, is greater than permitted
[12:35:01] Explicit valence for atom # 24 C greater than permitted
[12:35:01] Explicit valence for atom # 36 C greater than permitted
[12:35:01] Explicit valence for atom # 25 C greater than permitted
[12:35:01] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:01] Explicit valence for atom # 28 C greater than permitted
[12:35:01] Explicit valence for atom # 12 C, 5, is greater than permitted
[12:35:01] Explicit valence for atom # 27 C greater than permitted
[12:35:01] Explicit valence for atom # 28 C greater than permitted
[12:35:01] Explicit valence for atom # 30 C, 5, is greater than permitted
[12:35:01] Explicit valence for atom # 38 C greater than permitted
[12:35:01] Explicit valence for atom # 42 C greater than permitted
[12:35:01] Explicit valence for atom # 14 Si, 6, is greater than permitted
[12:35:01] Explicit valence for atom # 26 C greater than permitted
[12:35:01] Explicit valence for atom # 27 C greater than permitted
[12:35:01] Explicit valence for atom # 8 C greater than permitted
[12:35:01] Explicit valence for atom # 28 C greater than permitted
[12:35:01] Explicit valence for atom # 34 C greater than permitted
[12:35:01] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:01] Explicit valence for atom # 36 C greater than permitted
[12:35:01] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:01] Explicit valence for atom # 34 C greater than permitted
[12:35:01] Explicit valence for atom # 38 C greater than permitted
[12:35:01] Explicit valence for atom # 24 C greater than permitted
[12:35:01] Explicit valence for atom # 28 C greater than permitted
[12:35:01] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:01] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:01] Explicit valence for atom # 30 C greater than permitted
[12:35:01] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:01] Explicit valence for atom # 32 C greater than permitted
[12:35:01] Explicit valence for atom # 22 C greater than permitted
[12:35:01] Explicit valence for atom # 8 C greater than permitted
[12:35:01] Explicit valence for atom # 29 C greater than permitted
[12:35:01] Explicit valence for atom # 4 C, 5, is greater than permitted
[12:35:01] Explicit valence for atom # 27 C greater than permitted
[12:35:01] Explicit valence for atom # 36 C greater than permitted
[12:35:01] Explicit valence for atom # 29 C greater than permitted
[12:35:01] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:02] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:02] Explicit valence for atom # 27 C, 6, is greater than permitted
[12:35:02] Explicit valence for atom # 33 C greater than permitted
[12:35:02] Explicit valence for atom # 31 C greater than permitted
[12:35:02] Explicit valence for atom # 35 C greater than permitted
[12:35:02] Explicit valence for atom # 36 C greater than permitted
[12:35:02] Explicit valence for atom # 39 C greater than permitted
[12:35:02] Explicit valence for atom # 27 C greater than permitted
[12:35:02] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:02] Explicit valence for atom # 25 C greater than permitted
[12:35:02] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:02] Explicit valence for atom # 28 C, 5, is greater than permitted
[12:35:02] Explicit valence for atom # 21 C greater than permitted
[12:35:02] Explicit valence for atom # 33 C greater than permitted
[12:35:02] Explicit valence for atom # 15 C greater than permitted
[12:35:02] Explicit valence for atom # 26 C greater than permitted
[12:35:02] Explicit valence for atom # 12 C, 5, is greater than permitted
[12:35:02] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:02] Explicit valence for atom # 35 C greater than permitted
[12:35:02] Explicit valence for atom # 1 C greater than permitted
[12:35:02] Explicit valence for atom # 27 Si, 6, is greater than permitted
[12:35:02] Explicit valence for atom # 15 P, 7, is greater than permitted
[12:35:02] Explicit valence for atom # 28 C greater than permitted
[12:35:02] Explicit valence for atom # 35 C greater than permitted
[12:35:02] Explicit valence for atom # 1 C greater than permitted
[12:35:02] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:02] Explicit valence for atom # 40 C greater than permitted
[12:35:02] Explicit valence for atom # 26 C greater than permitted
[12:35:02] Explicit valence for atom # 29 C, 5, is greater than permitted
[12:35:02] Explicit valence for atom # 30 C greater than permitted
[12:35:02] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:02] Explicit valence for atom # 29 Si, 5, is greater than permitted
[12:35:02] Explicit valence for atom # 23 C greater than permitted
[12:35:02] Explicit valence for atom # 24 Si, 5, is greater than permitted
[12:35:02] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:02] Explicit valence for atom # 26 C greater than permitted
[12:35:02] Explicit valence for atom # 25 Si, 5, is greater than permitted
[12:35:02] Explicit valence for atom # 32 P, 7, is greater than permitted
[12:35:02] Explicit valence for atom # 32 C, 5, is greater than permitted
[12:35:02] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:02] Explicit valence for atom # 28 C greater than permitted
[12:35:02] Explicit valence for atom # 34 C greater than permitted
[12:35:02] Explicit valence for atom # 28 C greater than permitted
[12:35:02] Explicit valence for atom # 17 C greater than permitted
[12:35:02] Explicit valence for atom # 25 P, 7, is greater than permitted
[12:35:02] Explicit valence for atom # 22 C greater than permitted
[12:35:02] Explicit valence for atom # 37 Si, 5, is greater than permitted
[12:35:02] Explicit valence for atom # 16 Si, 5, is greater than permitted
[12:35:02] Explicit valence for atom # 30 C greater than permitted
[12:35:02] Explicit valence for atom # 23 C greater than permitted
[12:35:02] Explicit valence for atom # 32 C, 6, is greater than permitted
[12:35:02] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:02] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:02] Explicit valence for atom # 41 Si, 5, is greater than permitted
[12:35:03] Explicit valence for atom # 38 C greater than permitted
[12:35:02] Explicit valence for atom # 23 Si, 5, is greater than permitted
[12:35:03] Explicit valence for atom # 20 C greater than permitted
[12:35:03] Explicit valence for atom # 3 C greater than permitted
[12:35:03] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:03] Explicit valence for atom # 30 C greater than permitted
[12:35:03] Explicit valence for atom # 28 Si, 5, is greater than permitted
[12:35:03] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:03] Explicit valence for atom # 28 C greater than permitted
[12:35:03] Explicit valence for atom # 34 P, 7, is greater than permitted
[12:35:03] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:03] Explicit valence for atom # 24 C greater than permitted
[12:35:03] Explicit valence for atom # 32 C, 6, is greater than permitted
[12:35:03] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:03] Explicit valence for atom # 24 C greater than permitted
[12:35:03] Explicit valence for atom # 29 C greater than permitted
[12:35:03] Explicit valence for atom # 41 C greater than permitted
[12:35:03] Explicit valence for atom # 30 C greater than permitted
[12:35:03] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:03] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:03] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:03] Explicit valence for atom # 30 C greater than permitted
[12:35:03] Explicit valence for atom # 36 C greater than permitted
[12:35:03] Explicit valence for atom # 10 C greater than permitted
[12:35:03] Explicit valence for atom # 29 C greater than permitted
[12:35:03] Explicit valence for atom # 28 C, 5, is greater than permitted
[12:35:03] Explicit valence for atom # 34 C greater than permitted
[12:35:03] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:03] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:03] Explicit valence for atom # 25 P, 7, is greater than permitted
[12:35:03] Explicit valence for atom # 14 C greater than permitted
[12:35:03] Explicit valence for atom # 9 C greater than permitted
[12:35:03] Explicit valence for atom # 28 C greater than permitted
[12:35:03] Explicit valence for atom # 21 C greater than permitted
[12:35:03] Explicit valence for atom # 35 C greater than permitted
[12:35:03] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:03] Explicit valence for atom # 4 C greater than permitted
[12:35:03] Explicit valence for atom # 37 C greater than permitted
[12:35:03] Explicit valence for atom # 34 C greater than permitted
[12:35:03] Explicit valence for atom # 26 C, 5, is greater than permitted
[12:35:03] Explicit valence for atom # 33 C greater than permitted
[12:35:03] Explicit valence for atom # 33 C greater than permitted
[12:35:03] Explicit valence for atom # 28 C greater than permitted
[12:35:03] Explicit valence for atom # 29 C greater than permitted
[12:35:03] Explicit valence for atom # 8 C, 5, is greater than permitted
[12:35:03] Explicit valence for atom # 20 C greater than permitted
[12:35:03] Explicit valence for atom # 27 C greater than permitted
[12:35:03] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:35:04] Explicit valence for atom # 23 Si, 5, is greater than permitted
[12:35:04] Explicit valence for atom # 35 Si, 5, is greater than permitted
[12:35:04] Explicit valence for atom # 31 C greater than permitted
[12:35:04] Explicit valence for atom # 32 P, 7, is greater than permitted
[12:35:04] Explicit valence for atom # 6 C greater than permitted
[12:35:04] Explicit valence for atom # 26 C greater than permitted
[12:35:04] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:04] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:04] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:04] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:04] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:04] Explicit valence for atom # 23 Si, 5, is greater than permitted
[12:35:04] Explicit valence for atom # 27 C greater than permitted
[12:35:04] Explicit valence for atom # 34 C greater than permitted
[12:35:04] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:04] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:04] Explicit valence for atom # 32 C greater than permitted
[12:35:04] Explicit valence for atom # 40 C greater than permitted
[12:35:04] Explicit valence for atom # 37 C greater than permitted
[12:35:04] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:04] Explicit valence for atom # 41 C greater than permitted
[12:35:04] Explicit valence for atom # 34 C greater than permitted
[12:35:04] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:04] Explicit valence for atom # 27 C greater than permitted
[12:35:04] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:04] Explicit valence for atom # 35 C greater than permitted
[12:35:04] Explicit valence for atom # 34 C greater than permitted
[12:35:04] Explicit valence for atom # 27 C greater than permitted
[12:35:04] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:04] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:04] Explicit valence for atom # 35 C greater than permitted
[12:35:04] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:04] Explicit valence for atom # 30 C greater than permitted
[12:35:04] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:04] Explicit valence for atom # 25 C greater than permitted
[12:35:04] Explicit valence for atom # 31 C greater than permitted
[12:35:04] Explicit valence for atom # 37 C greater than permitted
[12:35:04] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:04] Explicit valence for atom # 9 C greater than permitted
[12:35:04] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:04] Explicit valence for atom # 33 C greater than permitted
[12:35:04] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:04] Explicit valence for atom # 1 C greater than permitted
[12:35:04] Explicit valence for atom # 29 C greater than permitted
[12:35:04] Explicit valence for atom # 28 C greater than permitted
[12:35:04] Explicit valence for atom # 28 C greater than permitted
[12:35:04] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:04] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:04] Explicit valence for atom # 41 C greater than permitted
[12:35:04] Explicit valence for atom # 25 C greater than permitted
[12:35:05] Explicit valence for atom # 27 C greater than permitted
[12:35:05] Explicit valence for atom # 41 C greater than permitted
[12:35:05] Explicit valence for atom # 28 C greater than permitted
[12:35:05] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:05] Explicit valence for atom # 32 C greater than permitted
[12:35:05] Explicit valence for atom # 15 C, 5, is greater than permitted
[12:35:05] Explicit valence for atom # 44 C greater than permitted
[12:35:05] Explicit valence for atom # 35 C, 5, is greater than permitted
[12:35:05] Explicit valence for atom # 31 C greater than permitted
[12:35:05] Explicit valence for atom # 18 C greater than permitted
[12:35:05] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:05] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:05] Explicit valence for atom # 30 C, 5, is greater than permitted
[12:35:05] Explicit valence for atom # 26 C, 5, is greater than permitted
[12:35:05] Explicit valence for atom # 28 C greater than permitted
[12:35:05] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:05] Explicit valence for atom # 5 C greater than permitted
[12:35:05] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:05] Explicit valence for atom # 34 C greater than permitted

Calculation complete! Processed 5 clusters

,name,type_cluster,scaffold,RS,SED,ASER
0,DrugEx_RNN_epsilon_0.1_500k_0,dis,csk,0.275000,0.086368,0.001879
1,DrugEx_RNN_epsilon_0.1_500k_1,dis,csk,0.347826,0.101221,0.002882
2,DrugEx_RNN_epsilon_0.1_500k_2,dis,csk,0.125000,0.105781,0.000024
3,DrugEx_RNN_epsilon_0.1_500k_3,dis,csk,0.324324,0.084538,0.001445
4,DrugEx_RNN_epsilon_0.1_500k_4,dis,csk,0.674419,0.150172,0.018957
5,DrugEx_RNN_epsilon_0.1_500k_mean,dis,csk,0.349314,0.105616,0.005037

DrugEx_RNN_epsilon_0.6_500k

============================================================
Starting calculation for DrugEx_RNN_epsilon_0.6_500k
Receptor: Glucocorticoid_receptor
Cluster type: dis
Scaffold type: csk
CPUs: 100
============================================================

--- Processing cluster 0 ---

[12:35:28] Explicit valence for atom # 12 C greater than permitted
[12:35:28] Explicit valence for atom # 13 C greater than permitted
[12:35:28] Explicit valence for atom # 31 C greater than permitted
[12:35:28] Explicit valence for atom # 23 C greater than permitted
[12:35:28] Explicit valence for atom # 27 C greater than permitted
[12:35:28] Explicit valence for atom # 21 C greater than permitted
[12:35:28] Explicit valence for atom # 28 C greater than permitted
[12:35:28] Explicit valence for atom # 19 C greater than permitted
[12:35:28] Explicit valence for atom # 30 C greater than permitted
[12:35:28] Explicit valence for atom # 23 C, 5, is greater than permitted
[12:35:28] Explicit valence for atom # 25 C greater than permitted
[12:35:28] Explicit valence for atom # 28 C greater than permitted
[12:35:28] Explicit valence for atom # 25 C greater than permitted
[12:35:29] Explicit valence for atom # 28 C, 6, is greater than permitted
[12:35:29] Explicit valence for atom # 19 C greater than permitted
[12:35:29] Explicit valence for atom # 35 C, 5, is greater than permitted
[12:35:29] Explicit valence for atom # 28 C, 5, is greater than permitted
[12:35:29] Explicit valence for atom # 31 C greater than permitted
[12:35:29] Explicit valence for atom # 22 C greater than permitted
[12:35:29] Explicit valence for atom # 33 C greater than permitted
[12:35:29] Explicit valence for atom # 4 C, 5, is greater than permitted
[12:35:29] Explicit valence for atom # 19 C greater than permitted
[12:35:29] Explicit valence for atom # 28 C, 6, is greater than permitted
[12:35:29] Explicit valence for atom # 21 C, 5, is greater than permitted
[12:35:29] Explicit valence for atom # 25 C greater than permitted
[12:35:29] Explicit valence for atom # 22 C greater than permitted
[12:35:29] Explicit valence for atom # 24 P, 6, is greater than permitted
[12:35:29] Explicit valence for atom # 26 C greater than permitted
[12:35:29] Explicit valence for atom # 31 C greater than permitted
[12:35:29] Explicit valence for atom # 30 C greater than permitted
[12:35:29] Explicit valence for atom # 36 C greater than permitted
[12:35:29] Explicit valence for atom # 19 C greater than permitted
[12:35:29] Explicit valence for atom # 28 C, 6, is greater than permitted
[12:35:29] Explicit valence for atom # 4 C greater than permitted
[12:35:30] Explicit valence for atom # 4 C greater than permitted
[12:35:30] Explicit valence for atom # 31 C greater than permitted
[12:35:30] Explicit valence for atom # 26 C greater than permitted
[12:35:30] Explicit valence for atom # 28 C greater than permitted
[12:35:30] Explicit valence for atom # 22 C greater than permitted
[12:35:30] Explicit valence for atom # 12 C greater than permitted
[12:35:30] Explicit valence for atom # 10 C, 6, is greater than permitted
[12:35:30] Explicit valence for atom # 22 C greater than permitted
[12:35:30] Explicit valence for atom # 18 C greater than permitted
[12:35:30] Explicit valence for atom # 37 C, 5, is greater than permitted
[12:35:30] Explicit valence for atom # 22 C greater than permitted
[12:35:30] Explicit valence for atom # 30 C greater than permitted
[12:35:30] Explicit valence for atom # 23 C, 5, is greater than permitted
[12:35:30] Explicit valence for atom # 34 Si, 5, is greater than permitted
[12:35:30] Explicit valence for atom # 24 P, 6, is greater than permitted
[12:35:30] Explicit valence for atom # 22 C greater than permitted
[12:35:30] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:35:30] Explicit valence for atom # 28 C, 6, is greater than permitted
[12:35:30] Explicit valence for atom # 28 C greater than permitted
[12:35:30] Explicit valence for atom # 23 C, 5, is greater than permitted
[12:35:30] Explicit valence for atom # 29 C greater than permitted
[12:35:30] Explicit valence for atom # 18 P, 7, is greater than permitted
[12:35:30] Explicit valence for atom # 22 C greater than permitted
[12:35:30] Explicit valence for atom # 24 P, 7, is greater than permitted
[12:35:30] Explicit valence for atom # 28 C greater than permitted
[12:35:30] Explicit valence for atom # 42 C greater than permitted
[12:35:30] Explicit valence for atom # 24 C greater than permitted
[12:35:30] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:30] Explicit valence for atom # 15 C greater than permitted
[12:35:30] Explicit valence for atom # 16 C greater than permitted
[12:35:31] Explicit valence for atom # 20 C greater than permitted
[12:35:31] Explicit valence for atom # 22 C greater than permitted
[12:35:31] Explicit valence for atom # 26 P, 7, is greater than permitted
[12:35:31] Explicit valence for atom # 18 C greater than permitted
[12:35:31] Explicit valence for atom # 35 C, 5, is greater than permitted
[12:35:31] Explicit valence for atom # 34 C greater than permitted
[12:35:31] Explicit valence for atom # 7 C greater than permitted
[12:35:31] Explicit valence for atom # 21 C greater than permitted
[12:35:31] Explicit valence for atom # 22 C, 6, is greater than permitted
[12:35:31] Explicit valence for atom # 16 C greater than permitted
[12:35:31] Explicit valence for atom # 20 C greater than permitted
[12:35:31] Explicit valence for atom # 23 C greater than permitted
[12:35:31] Explicit valence for atom # 19 Si, 5, is greater than permitted
[12:35:31] Explicit valence for atom # 23 Si, 5, is greater than permitted
[12:35:31] Explicit valence for atom # 13 C greater than permitted
[12:35:31] Explicit valence for atom # 23 C greater than permitted
[12:35:31] Explicit valence for atom # 20 C greater than permitted
[12:35:31] Explicit valence for atom # 28 C, 5, is greater than permitted
[12:35:31] Explicit valence for atom # 9 C, 5, is greater than permitted
[12:35:32] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:32] Explicit valence for atom # 30 C, 5, is greater than permitted
[12:35:32] Explicit valence for atom # 13 C greater than permitted
[12:35:32] Explicit valence for atom # 13 C greater than permitted
[12:35:32] Explicit valence for atom # 29 C greater than permitted
[12:35:32] Explicit valence for atom # 26 C, 5, is greater than permitted
[12:35:32] Explicit valence for atom # 31 C greater than permitted
[12:35:32] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:32] Explicit valence for atom # 10 C greater than permitted
[12:35:32] Explicit valence for atom # 33 C greater than permitted
[12:35:32] Explicit valence for atom # 23 C greater than permitted
[12:35:32] Explicit valence for atom # 11 C, 5, is greater than permitted
[12:35:32] Explicit valence for atom # 34 C greater than permitted
[12:35:32] Explicit valence for atom # 22 C greater than permitted
[12:35:32] Explicit valence for atom # 24 C greater than permitted
[12:35:32] Explicit valence for atom # 10 C greater than permitted
[12:35:32] Explicit valence for atom # 4 C, 5, is greater than permitted
[12:35:32] Explicit valence for atom # 20 C greater than permitted
[12:35:32] Explicit valence for atom # 21 C greater than permitted
[12:35:32] Explicit valence for atom # 18 C greater than permitted
[12:35:32] Explicit valence for atom # 11 C greater than permitted
[12:35:32] Explicit valence for atom # 33 C greater than permitted
[12:35:32] Explicit valence for atom # 16 C greater than permitted
[12:35:32] Explicit valence for atom # 30 C greater than permitted
[12:35:32] Explicit valence for atom # 6 C greater than permitted
[12:35:32] Explicit valence for atom # 16 P, 7, is greater than permitted
[12:35:32] Explicit valence for atom # 31 C, 5, is greater than permitted
[12:35:33] Explicit valence for atom # 29 C greater than permitted
[12:35:33] Explicit valence for atom # 29 C greater than permitted
[12:35:33] Explicit valence for atom # 31 C greater than permitted
[12:35:33] Explicit valence for atom # 26 Si, 5, is greater than permitted
[12:35:33] Explicit valence for atom # 26 C greater than permitted
[12:35:33] Explicit valence for atom # 7 C greater than permitted
[12:35:33] Explicit valence for atom # 19 C greater than permitted
[12:35:33] Explicit valence for atom # 17 C greater than permitted
[12:35:33] Explicit valence for atom # 21 C greater than permitted
[12:35:33] Explicit valence for atom # 29 Si, 5, is greater than permitted
[12:35:33] Explicit valence for atom # 27 Si, 5, is greater than permitted
[12:35:33] Explicit valence for atom # 19 C greater than permitted
[12:35:33] Explicit valence for atom # 21 C greater than permitted
[12:35:33] Explicit valence for atom # 38 C greater than permitted
[12:35:33] Explicit valence for atom # 15 C greater than permitted
[12:35:33] Explicit valence for atom # 40 C greater than permitted
[12:35:33] Explicit valence for atom # 34 C greater than permitted
[12:35:33] Explicit valence for atom # 6 C greater than permitted
[12:35:34] Explicit valence for atom # 28 C greater than permitted
[12:35:33] Explicit valence for atom # 13 P, 7, is greater than permitted
[12:35:34] Explicit valence for atom # 19 C, 5, is greater than permitted
[12:35:34] Explicit valence for atom # 23 C, 5, is greater than permitted
[12:35:34] Explicit valence for atom # 14 C greater than permitted
[12:35:34] Explicit valence for atom # 27 C greater than permitted
[12:35:34] Explicit valence for atom # 20 C greater than permitted
[12:35:34] Explicit valence for atom # 31 C, 5, is greater than permitted
[12:35:34] Explicit valence for atom # 12 P, 7, is greater than permitted
[12:35:34] Explicit valence for atom # 8 C greater than permitted
[12:35:34] Explicit valence for atom # 8 C, 5, is greater than permitted
[12:35:34] Explicit valence for atom # 24 C greater than permitted
[12:35:34] Explicit valence for atom # 1 C greater than permitted
[12:35:34] Explicit valence for atom # 25 C greater than permitted
[12:35:34] Explicit valence for atom # 19 C greater than permitted
[12:35:34] Explicit valence for atom # 0 C greater than permitted
[12:35:34] Explicit valence for atom # 32 C greater than permitted
[12:35:34] Explicit valence for atom # 11 C greater than permitted
[12:35:34] Explicit valence for atom # 41 C, 5, is greater than permitted
[12:35:34] Explicit valence for atom # 14 C greater than permitted
[12:35:34] Explicit valence for atom # 11 C, 5, is greater than permitted
[12:35:34] Explicit valence for atom # 25 C greater than permitted
[12:35:34] Explicit valence for atom # 24 C greater than permitted
[12:35:34] Explicit valence for atom # 11 C greater than permitted
[12:35:35] Explicit valence for atom # 12 C, 5, is greater than permitted
[12:35:35] Explicit valence for atom # 30 C greater than permitted
[12:35:35] Explicit valence for atom # 28 C greater than permitted
[12:35:35] Explicit valence for atom # 18 Si, 5, is greater than permitted
[12:35:35] Explicit valence for atom # 18 C greater than permitted
[12:35:35] Explicit valence for atom # 29 C greater than permitted
[12:35:35] Explicit valence for atom # 24 C greater than permitted
[12:35:35] Explicit valence for atom # 23 C greater than permitted
[12:35:35] Explicit valence for atom # 24 C, 5, is greater than permitted
[12:35:35] Explicit valence for atom # 24 C greater than permitted
[12:35:35] Explicit valence for atom # 13 C greater than permitted
[12:35:35] Explicit valence for atom # 11 C greater than permitted
[12:35:35] Explicit valence for atom # 11 C greater than permitted
[12:35:35] Explicit valence for atom # 17 C greater than permitted
[12:35:35] Explicit valence for atom # 17 C, 5, is greater than permitted
[12:35:35] Explicit valence for atom # 20 C greater than permitted
[12:35:35] Explicit valence for atom # 17 C, 5, is greater than permitted
[12:35:35] Explicit valence for atom # 18 P, 7, is greater than permitted
[12:35:35] Explicit valence for atom # 33 P, 7, is greater than permitted
[12:35:35] Explicit valence for atom # 30 C greater than permitted
[12:35:35] Explicit valence for atom # 32 C, 5, is greater than permitted
[12:35:35] Explicit valence for atom # 19 C greater than permitted
[12:35:35] Explicit valence for atom # 12 C greater than permitted
[12:35:35] Explicit valence for atom # 26 C greater than permitted
[12:35:35] Explicit valence for atom # 25 Si, 5, is greater than permitted
[12:35:35] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:35:35] Explicit valence for atom # 23 C greater than permitted
[12:35:35] Explicit valence for atom # 43 C greater than permitted
[12:35:35] Explicit valence for atom # 18 C, 6, is greater than permitted
[12:35:35] Explicit valence for atom # 25 C greater than permitted
[12:35:36] Explicit valence for atom # 20 C greater than permitted
[12:35:36] Explicit valence for atom # 32 C, 5, is greater than permitted
[12:35:36] Explicit valence for atom # 31 C greater than permitted
[12:35:36] Explicit valence for atom # 25 C, 5, is greater than permitted
[12:35:36] Explicit valence for atom # 25 C, 5, is greater than permitted
[12:35:36] Explicit valence for atom # 6 C greater than permitted
[12:35:36] Explicit valence for atom # 32 C, 6, is greater than permitted
[12:35:36] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:35:36] Explicit valence for atom # 36 C greater than permitted
[12:35:36] Explicit valence for atom # 22 C, 5, is greater than permitted
[12:35:36] Explicit valence for atom # 20 C, 6, is greater than permitted
[12:35:36] Explicit valence for atom # 16 C, 6, is greater than permitted
[12:35:36] Explicit valence for atom # 7 C greater than permitted
[12:35:36] Explicit valence for atom # 13 C greater than permitted
[12:35:36] Explicit valence for atom # 26 C, 5, is greater than permitted
[12:35:36] Explicit valence for atom # 20 C greater than permitted
[12:35:36] Explicit valence for atom # 23 C greater than permitted
[12:35:36] Explicit valence for atom # 1 C greater than permitted
[12:35:36] Explicit valence for atom # 14 C, 5, is greater than permitted
[12:35:36] Explicit valence for atom # 17 C greater than permitted
[12:35:36] Explicit valence for atom # 22 Si, 5, is greater than permitted
[12:35:36] Explicit valence for atom # 18 C greater than permitted
[12:35:36] Explicit valence for atom # 15 C greater than permitted
[12:35:36] Explicit valence for atom # 14 C, 5, is greater than permitted
[12:35:36] Explicit valence for atom # 36 C greater than permitted
[12:35:36] Explicit valence for atom # 4 C greater than permitted
[12:35:36] Explicit valence for atom # 29 Si, 5, is greater than permitted
[12:35:36] Explicit valence for atom # 13 C greater than permitted
[12:35:36] Explicit valence for atom # 24 C greater than permitted
[12:35:36] Explicit valence for atom # 24 Si, 5, is greater than permitted
[12:35:36] Explicit valence for atom # 5 C greater than permitted
[12:35:36] Explicit valence for atom # 10 C greater than permitted
[12:35:36] Explicit valence for atom # 35 C greater than permitted
[12:35:36] Explicit valence for atom # 6 C greater than permitted
[12:35:37] Explicit valence for atom # 24 C greater than permitted
[12:35:37] Explicit valence for atom # 26 C, 6, is greater than permitted
[12:35:37] Explicit valence for atom # 29 C, 6, is greater than permitted
[12:35:37] Explicit valence for atom # 18 C greater than permitted
[12:35:37] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:35:37] Explicit valence for atom # 34 C greater than permitted
[12:35:37] Explicit valence for atom # 19 C greater than permitted
[12:35:37] Explicit valence for atom # 35 C, 6, is greater than permitted
[12:35:37] Explicit valence for atom # 28 C greater than permitted
[12:35:37] Explicit valence for atom # 8 C, 5, is greater than permitted
[12:35:37] Explicit valence for atom # 33 C, 5, is greater than permitted
[12:35:37] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:35:37] Explicit valence for atom # 26 C greater than permitted
[12:35:37] Explicit valence for atom # 24 C, 5, is greater than permitted
[12:35:37] Explicit valence for atom # 13 Si, 5, is greater than permitted
[12:35:37] Explicit valence for atom # 35 C greater than permitted
[12:35:37] Explicit valence for atom # 26 C greater than permitted
[12:35:37] Explicit valence for atom # 4 C greater than permitted
[12:35:37] Explicit valence for atom # 25 C greater than permitted
[12:35:37] Explicit valence for atom # 15 C, 5, is greater than permitted
[12:35:37] Explicit valence for atom # 16 C, 5, is greater than permitted
[12:35:37] Explicit valence for atom # 27 C greater than permitted
[12:35:37] Explicit valence for atom # 26 C, 5, is greater than permitted
[12:35:37] Explicit valence for atom # 22 C greater than permitted
[12:35:37] Explicit valence for atom # 24 C, 5, is greater than permitted
[12:35:37] Explicit valence for atom # 15 C, 5, is greater than permitted
[12:35:37] Explicit valence for atom # 30 C greater than permitted
[12:35:37] Explicit valence for atom # 37 C, 5, is greater than permitted
[12:35:37] Explicit valence for atom # 36 C, 5, is greater than permitted
[12:35:37] Explicit valence for atom # 12 C greater than permitted
[12:35:37] Explicit valence for atom # 28 C greater than permitted
[12:35:37] Explicit valence for atom # 22 C greater than permitted
[12:35:37] Explicit valence for atom # 16 C greater than permitted
[12:35:37] Explicit valence for atom # 15 C greater than permitted
[12:35:37] Explicit valence for atom # 25 C greater than permitted
[12:35:37] Explicit valence for atom # 20 C greater than permitted
[12:35:37] Explicit valence for atom # 17 C, 6, is greater than permitted
[12:35:38] Explicit valence for atom # 13 C greater than permitted
[12:35:38] Explicit valence for atom # 13 C greater than permitted
[12:35:38] Explicit valence for atom # 15 P, 7, is greater than permitted
[12:35:38] Explicit valence for atom # 22 C greater than permitted
[12:35:38] Explicit valence for atom # 22 C greater than permitted
[12:35:38] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:35:38] Explicit valence for atom # 22 C greater than permitted
[12:35:38] Explicit valence for atom # 38 C greater than permitted
[12:35:38] Explicit valence for atom # 34 C greater than permitted
[12:35:38] Explicit valence for atom # 24 C greater than permitted
[12:35:38] Explicit valence for atom # 28 C, 5, is greater than permitted
[12:35:38] Explicit valence for atom # 36 C, 5, is greater than permitted
[12:35:38] Explicit valence for atom # 6 C greater than permitted
[12:35:38] Explicit valence for atom # 8 P, 7, is greater than permitted
[12:35:38] Explicit valence for atom # 18 C greater than permitted
[12:35:38] Explicit valence for atom # 31 C, 6, is greater than permitted
[12:35:38] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:38] Explicit valence for atom # 33 C greater than permitted
[12:35:38] Explicit valence for atom # 36 C, 5, is greater than permitted
[12:35:38] Explicit valence for atom # 16 C greater than permitted
[12:35:38] Explicit valence for atom # 32 C greater than permitted
[12:35:38] Explicit valence for atom # 4 C greater than permitted
[12:35:38] Explicit valence for atom # 25 C, 5, is greater than permitted
[12:35:38] Explicit valence for atom # 15 C greater than permitted
[12:35:39] Explicit valence for atom # 21 C, 5, is greater than permitted
[12:35:39] Explicit valence for atom # 37 P, 7, is greater than permitted
[12:35:39] Explicit valence for atom # 17 C greater than permitted
[12:35:39] Explicit valence for atom # 24 C greater than permitted
[12:35:39] Explicit valence for atom # 24 C greater than permitted
[12:35:39] Explicit valence for atom # 23 C greater than permitted
[12:35:39] Explicit valence for atom # 18 C greater than permitted
[12:35:39] Explicit valence for atom # 4 C, 5, is greater than permitted
[12:35:39] Explicit valence for atom # 31 C greater than permitted
[12:35:40] Explicit valence for atom # 7 C greater than permitted
[12:35:40] Explicit valence for atom # 9 C greater than permitted

--- Processing cluster 1 ---

[12:35:57] Explicit valence for atom # 22 C greater than permitted
[12:35:57] Explicit valence for atom # 13 C greater than permitted
[12:35:57] Explicit valence for atom # 9 P, 7, is greater than permitted
[12:35:57] Explicit valence for atom # 17 C greater than permitted
[12:35:57] Explicit valence for atom # 13 C greater than permitted
[12:35:57] Explicit valence for atom # 11 C, 6, is greater than permitted
[12:35:57] Explicit valence for atom # 31 C greater than permitted
[12:35:57] Explicit valence for atom # 21 C, 5, is greater than permitted
[12:35:57] Explicit valence for atom # 12 C greater than permitted
[12:35:57] Explicit valence for atom # 30 C greater than permitted
[12:35:57] Explicit valence for atom # 19 C greater than permitted
[12:35:57] Explicit valence for atom # 15 C greater than permitted
[12:35:57] Explicit valence for atom # 12 C greater than permitted
[12:35:57] Explicit valence for atom # 12 C greater than permitted
[12:35:57] Explicit valence for atom # 30 C greater than permitted
[12:35:57] Explicit valence for atom # 21 C, 5, is greater than permitted
[12:35:57] Explicit valence for atom # 22 P, 7, is greater than permitted
[12:35:57] Explicit valence for atom # 32 C greater than permitted
[12:35:57] Explicit valence for atom # 19 C greater than permitted
[12:35:57] Explicit valence for atom # 27 P, 7, is greater than permitted
[12:35:57] Explicit valence for atom # 23 C greater than permitted
[12:35:57] Explicit valence for atom # 27 P, 7, is greater than permitted
[12:35:57] Explicit valence for atom # 7 C greater than permitted
[12:35:57] Explicit valence for atom # 28 C greater than permitted
[12:35:57] Explicit valence for atom # 13 P, 7, is greater than permitted
[12:35:57] Explicit valence for atom # 36 C, 5, is greater than permitted
[12:35:57] Explicit valence for atom # 17 C greater than permitted
[12:35:57] Explicit valence for atom # 31 C greater than permitted
[12:35:57] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:35:57] Explicit valence for atom # 25 C greater than permitted
[12:35:57] Explicit valence for atom # 24 C, 5, is greater than permitted
[12:35:57] Explicit valence for atom # 18 C, 6, is greater than permitted
[12:35:57] Explicit valence for atom # 29 C greater than permitted
[12:35:57] Explicit valence for atom # 33 C greater than permitted
[12:35:57] Explicit valence for atom # 20 C greater than permitted
[12:35:57] Explicit valence for atom # 36 C greater than permitted
[12:35:57] Explicit valence for atom # 21 C greater than permitted
[12:35:57] Explicit valence for atom # 6 C greater than permitted
[12:35:57] Explicit valence for atom # 27 C, 6, is greater than permitted
[12:35:57] Explicit valence for atom # 20 C, 6, is greater than permitted
[12:35:57] Explicit valence for atom # 23 C, 5, is greater than permitted
[12:35:57] Explicit valence for atom # 23 C, 5, is greater than permitted
[12:35:58] Explicit valence for atom # 9 P, 6, is greater than permitted
[12:35:58] Explicit valence for atom # 24 Si, 5, is greater than permitted
[12:35:58] Explicit valence for atom # 37 C greater than permitted
[12:35:58] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:35:58] Explicit valence for atom # 25 P, 7, is greater than permitted
[12:35:58] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:35:58] Explicit valence for atom # 22 C, 5, is greater than permitted
[12:35:58] Explicit valence for atom # 25 C, 5, is greater than permitted
[12:35:58] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:35:58] Explicit valence for atom # 37 C greater than permitted
[12:35:58] Explicit valence for atom # 23 C, 5, is greater than permitted
[12:35:58] Explicit valence for atom # 20 C, 5, is greater than permitted
[12:35:58] Explicit valence for atom # 27 Si, 5, is greater than permitted
[12:35:58] Explicit valence for atom # 24 C greater than permitted
[12:35:58] Explicit valence for atom # 17 C greater than permitted
[12:35:58] Explicit valence for atom # 28 C greater than permitted
[12:35:58] Explicit valence for atom # 24 P, 7, is greater than permitted
[12:35:58] Explicit valence for atom # 6 C greater than permitted
[12:35:58] Explicit valence for atom # 31 C greater than permitted
[12:35:58] Explicit valence for atom # 13 C greater than permitted
[12:35:58] Explicit valence for atom # 5 C greater than permitted
[12:35:58] Explicit valence for atom # 39 C greater than permitted
[12:35:58] Explicit valence for atom # 31 C, 5, is greater than permitted
[12:35:58] Explicit valence for atom # 23 C, 6, is greater than permitted
[12:35:58] Explicit valence for atom # 21 C greater than permitted
[12:35:58] Explicit valence for atom # 21 C greater than permitted
[12:35:58] Explicit valence for atom # 37 C greater than permitted
[12:35:58] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:35:58] Explicit valence for atom # 22 C greater than permitted
[12:35:58] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:35:58] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:35:58] Explicit valence for atom # 15 C, 6, is greater than permitted
[12:35:58] Explicit valence for atom # 22 P, 7, is greater than permitted
[12:35:58] Explicit valence for atom # 18 C greater than permitted
[12:35:58] Explicit valence for atom # 13 C greater than permitted
[12:35:58] Explicit valence for atom # 20 C, 6, is greater than permitted
[12:35:58] Explicit valence for atom # 27 P, 7, is greater than permitted
[12:35:58] Explicit valence for atom # 3 C greater than permitted
[12:35:58] Explicit valence for atom # 26 C greater than permitted
[12:35:58] Explicit valence for atom # 37 C greater than permitted
[12:35:58] Explicit valence for atom # 19 C, 5, is greater than permitted
[12:35:58] Explicit valence for atom # 9 C, 5, is greater than permitted
[12:35:58] Explicit valence for atom # 26 C, 6, is greater than permitted
[12:35:58] Explicit valence for atom # 14 C greater than permitted
[12:35:58] Explicit valence for atom # 14 C greater than permitted
[12:35:58] Explicit valence for atom # 21 C greater than permitted
[12:35:58] Explicit valence for atom # 12 C greater than permitted
[12:35:58] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:35:58] Explicit valence for atom # 23 C, 6, is greater than permitted
[12:35:58] Explicit valence for atom # 11 C greater than permitted
[12:35:58] Explicit valence for atom # 28 C, 5, is greater than permitted
[12:35:58] Explicit valence for atom # 21 C greater than permitted
[12:35:58] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:35:58] Explicit valence for atom # 35 C greater than permitted
[12:35:58] Explicit valence for atom # 26 C, 6, is greater than permitted
[12:35:58] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:35:58] Explicit valence for atom # 19 Si, 5, is greater than permitted
[12:35:58] Explicit valence for atom # 23 C greater than permitted
[12:35:58] Explicit valence for atom # 22 C greater than permitted
[12:35:58] Explicit valence for atom # 13 C greater than permitted
[12:35:58] Explicit valence for atom # 24 C greater than permitted
[12:35:58] Explicit valence for atom # 21 P, 7, is greater than permitted
[12:35:58] Explicit valence for atom # 23 C greater than permitted
[12:35:59] Explicit valence for atom # 25 C greater than permitted
[12:35:59] Explicit valence for atom # 22 C greater than permitted
[12:35:59] Explicit valence for atom # 6 C greater than permitted
[12:35:59] Explicit valence for atom # 21 C greater than permitted
[12:35:59] Explicit valence for atom # 12 C greater than permitted
[12:35:59] Explicit valence for atom # 18 C greater than permitted
[12:35:59] Explicit valence for atom # 18 C greater than permitted
[12:35:59] Explicit valence for atom # 23 C greater than permitted
[12:35:59] Explicit valence for atom # 20 C greater than permitted
[12:35:59] Explicit valence for atom # 12 C greater than permitted
[12:35:59] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:35:59] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:35:59] Explicit valence for atom # 32 C greater than permitted
[12:35:59] Explicit valence for atom # 32 Si, 5, is greater than permitted
[12:35:59] Explicit valence for atom # 29 P, 7, is greater than permitted
[12:35:59] Explicit valence for atom # 20 C, 5, is greater than permitted
[12:35:59] Explicit valence for atom # 33 P, 7, is greater than permitted
[12:35:59] Explicit valence for atom # 15 C greater than permitted
[12:35:59] Explicit valence for atom # 17 C greater than permitted
[12:35:59] Explicit valence for atom # 22 C greater than permitted
[12:35:59] Explicit valence for atom # 25 C, 5, is greater than permitted
[12:35:59] Explicit valence for atom # 19 C, 6, is greater than permitted
[12:35:59] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:35:59] Explicit valence for atom # 14 C, 5, is greater than permitted
[12:35:59] Explicit valence for atom # 18 C greater than permitted
[12:35:59] Explicit valence for atom # 22 C greater than permitted
[12:35:59] Explicit valence for atom # 14 C, 5, is greater than permitted
[12:35:59] Explicit valence for atom # 30 C greater than permitted
[12:35:59] Explicit valence for atom # 12 P, 6, is greater than permitted
[12:35:59] Explicit valence for atom # 23 C greater than permitted
[12:35:59] Explicit valence for atom # 3 Si, 5, is greater than permitted
[12:35:59] Explicit valence for atom # 14 C, 5, is greater than permitted
[12:35:59] Explicit valence for atom # 17 C greater than permitted
[12:35:59] Explicit valence for atom # 35 C greater than permitted
[12:35:59] Explicit valence for atom # 13 P, 5, is greater than permitted
[12:35:59] Explicit valence for atom # 35 C greater than permitted
[12:35:59] Explicit valence for atom # 13 C greater than permitted
[12:35:59] Explicit valence for atom # 5 C, 5, is greater than permitted
[12:35:59] Explicit valence for atom # 20 C greater than permitted
[12:35:59] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:35:59] Explicit valence for atom # 7 C greater than permitted
[12:35:59] Explicit valence for atom # 22 C, 6, is greater than permitted
[12:35:59] Explicit valence for atom # 26 C greater than permitted
[12:35:59] Explicit valence for atom # 27 C, 6, is greater than permitted
[12:35:59] Explicit valence for atom # 22 C, 6, is greater than permitted
[12:35:59] Explicit valence for atom # 23 C, 6, is greater than permitted
[12:35:59] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:35:59] Explicit valence for atom # 7 C, 5, is greater than permitted
[12:35:59] Explicit valence for atom # 26 C greater than permitted
[12:35:59] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:35:59] Explicit valence for atom # 20 C greater than permitted
[12:35:59] Explicit valence for atom # 21 C greater than permitted
[12:35:59] Explicit valence for atom # 20 Si, 5, is greater than permitted
[12:35:59] Explicit valence for atom # 12 P, 5, is greater than permitted
[12:35:59] Explicit valence for atom # 22 C greater than permitted
[12:35:59] Explicit valence for atom # 16 C, 6, is greater than permitted
[12:35:59] Explicit valence for atom # 26 C greater than permitted
[12:35:59] Explicit valence for atom # 27 C greater than permitted
[12:35:59] Explicit valence for atom # 22 C, 5, is greater than permitted
[12:35:59] Explicit valence for atom # 34 C, 6, is greater than permitted
[12:35:59] Explicit valence for atom # 11 C, 5, is greater than permitted
[12:35:59] Explicit valence for atom # 22 C, 5, is greater than permitted
[12:35:59] Explicit valence for atom # 31 C, 6, is greater than permitted
[12:35:59] Explicit valence for atom # 26 C greater than permitted
[12:35:59] Explicit valence for atom # 34 C, 5, is greater than permitted
[12:35:59] Explicit valence for atom # 5 C, 5, is greater than permitted
[12:35:59] Explicit valence for atom # 22 C greater than permitted
[12:35:59] Explicit valence for atom # 23 C greater than permitted
[12:35:59] Explicit valence for atom # 26 C greater than permitted
[12:35:59] Explicit valence for atom # 21 Si, 5, is greater than permitted
[12:35:59] Explicit valence for atom # 7 C greater than permitted
[12:35:59] Explicit valence for atom # 31 Si, 5, is greater than permitted
[12:35:59] Explicit valence for atom # 10 C greater than permitted
[12:35:59] Explicit valence for atom # 34 C, 5, is greater than permitted
[12:35:59] Explicit valence for atom # 17 P, 7, is greater than permitted
[12:35:59] Explicit valence for atom # 22 C, 5, is greater than permitted
[12:35:59] Explicit valence for atom # 22 C greater than permitted
[12:35:59] Explicit valence for atom # 16 C, 5, is greater than permitted
[12:35:59] Explicit valence for atom # 12 P, 6, is greater than permitted
[12:35:59] Explicit valence for atom # 8 C, 5, is greater than permitted
[12:35:59] Explicit valence for atom # 25 C greater than permitted
[12:35:59] Explicit valence for atom # 23 C, 6, is greater than permitted
[12:36:00] Explicit valence for atom # 14 C greater than permitted
[12:36:00] Explicit valence for atom # 0 C greater than permitted
[12:36:00] Explicit valence for atom # 32 C, 5, is greater than permitted
[12:36:00] Explicit valence for atom # 11 C, 6, is greater than permitted
[12:36:00] Explicit valence for atom # 22 C greater than permitted
[12:36:00] Explicit valence for atom # 12 C, 5, is greater than permitted
[12:36:00] Explicit valence for atom # 2 Si, 5, is greater than permitted
[12:36:00] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:36:00] Explicit valence for atom # 17 C greater than permitted
[12:36:00] Explicit valence for atom # 6 C greater than permitted
[12:36:00] Explicit valence for atom # 18 C greater than permitted
[12:36:00] Explicit valence for atom # 7 C greater than permitted
[12:36:00] Explicit valence for atom # 29 C greater than permitted
[12:36:00] Explicit valence for atom # 30 C, 5, is greater than permitted
[12:36:00] Explicit valence for atom # 22 C greater than permitted
[12:36:00] Explicit valence for atom # 28 C, 5, is greater than permitted
[12:36:00] Explicit valence for atom # 22 Si, 5, is greater than permitted
[12:36:00] Explicit valence for atom # 30 C greater than permitted
[12:36:00] Explicit valence for atom # 25 C, 5, is greater than permitted
[12:36:00] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:36:00] Explicit valence for atom # 39 C greater than permitted
[12:36:00] Explicit valence for atom # 29 C greater than permitted
[12:36:00] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:36:00] Explicit valence for atom # 22 C greater than permitted
[12:36:00] Explicit valence for atom # 33 C greater than permitted
[12:36:00] Explicit valence for atom # 18 C greater than permitted
[12:36:00] Explicit valence for atom # 23 C, 6, is greater than permitted
[12:36:00] Explicit valence for atom # 30 C, 5, is greater than permitted
[12:36:00] Explicit valence for atom # 26 C greater than permitted
[12:36:00] Explicit valence for atom # 2 C greater than permitted
[12:36:00] Explicit valence for atom # 30 C greater than permitted
[12:36:00] Explicit valence for atom # 27 P, 7, is greater than permitted
[12:36:00] Explicit valence for atom # 25 C, 5, is greater than permitted
[12:36:00] Explicit valence for atom # 17 C, 6, is greater than permitted
[12:36:00] Explicit valence for atom # 36 Si, 5, is greater than permitted
[12:36:00] Explicit valence for atom # 19 C, 6, is greater than permitted
[12:36:00] Explicit valence for atom # 25 C greater than permitted
[12:36:00] Explicit valence for atom # 25 C, 5, is greater than permitted
[12:36:00] Explicit valence for atom # 21 P, 7, is greater than permitted
[12:36:00] Explicit valence for atom # 5 C, 5, is greater than permitted
[12:36:00] Explicit valence for atom # 4 P, 6, is greater than permitted
[12:36:00] Explicit valence for atom # 30 C greater than permitted
[12:36:00] Explicit valence for atom # 17 C greater than permitted
[12:36:00] Explicit valence for atom # 14 C, 5, is greater than permitted
[12:36:00] Explicit valence for atom # 8 Si, 5, is greater than permitted
[12:36:00] Explicit valence for atom # 18 C greater than permitted
[12:36:00] Explicit valence for atom # 22 C, 5, is greater than permitted
[12:36:00] Explicit valence for atom # 16 C greater than permitted
[12:36:00] Explicit valence for atom # 20 Si, 5, is greater than permitted
[12:36:00] Explicit valence for atom # 21 Si, 5, is greater than permitted
[12:36:00] Explicit valence for atom # 4 C, 6, is greater than permitted
[12:36:00] Explicit valence for atom # 16 C, 5, is greater than permitted
[12:36:00] Explicit valence for atom # 20 C, 5, is greater than permitted
[12:36:00] Explicit valence for atom # 18 C greater than permitted
[12:36:00] Explicit valence for atom # 9 C greater than permitted
[12:36:00] Explicit valence for atom # 19 C greater than permitted
[12:36:00] Explicit valence for atom # 18 C greater than permitted
[12:36:00] Explicit valence for atom # 45 C greater than permitted
[12:36:00] Explicit valence for atom # 33 C, 5, is greater than permitted
[12:36:00] Explicit valence for atom # 36 C greater than permitted
[12:36:00] Explicit valence for atom # 25 C greater than permitted
[12:36:00] Explicit valence for atom # 22 C greater than permitted
[12:36:00] Explicit valence for atom # 21 P, 7, is greater than permitted
[12:36:00] Explicit valence for atom # 26 C greater than permitted
[12:36:00] Explicit valence for atom # 21 C greater than permitted
[12:36:00] Explicit valence for atom # 38 C greater than permitted
[12:36:00] Explicit valence for atom # 22 C, 5, is greater than permitted
[12:36:00] Explicit valence for atom # 23 C, 5, is greater than permitted
[12:36:00] Explicit valence for atom # 28 C, 5, is greater than permitted
[12:36:00] Explicit valence for atom # 24 C greater than permitted
[12:36:00] Explicit valence for atom # 23 C, 5, is greater than permitted
[12:36:01] Explicit valence for atom # 12 P, 7, is greater than permitted
[12:36:01] Explicit valence for atom # 13 C greater than permitted
[12:36:01] Explicit valence for atom # 34 C greater than permitted
[12:36:00] Explicit valence for atom # 24 C greater than permitted
[12:36:01] Explicit valence for atom # 11 C, 5, is greater than permitted
[12:36:01] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:36:01] Explicit valence for atom # 28 C greater than permitted
[12:36:01] Explicit valence for atom # 17 C, 5, is greater than permitted
[12:36:01] Explicit valence for atom # 1 C greater than permitted
[12:36:01] Explicit valence for atom # 7 C, 6, is greater than permitted
[12:36:01] Explicit valence for atom # 24 C greater than permitted
[12:36:01] Explicit valence for atom # 27 C, 6, is greater than permitted
[12:36:01] Explicit valence for atom # 19 C greater than permitted
[12:36:01] Explicit valence for atom # 6 C greater than permitted
[12:36:01] Explicit valence for atom # 24 C greater than permitted
[12:36:01] Explicit valence for atom # 13 C, 5, is greater than permitted
[12:36:01] Explicit valence for atom # 17 C, 6, is greater than permitted
[12:36:01] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:36:01] Explicit valence for atom # 10 C greater than permitted
[12:36:01] Explicit valence for atom # 21 C, 5, is greater than permitted
[12:36:01] Explicit valence for atom # 23 C greater than permitted
[12:36:01] Explicit valence for atom # 23 C greater than permitted
[12:36:01] Explicit valence for atom # 19 C greater than permitted
[12:36:01] Explicit valence for atom # 22 P, 7, is greater than permitted
[12:36:01] Explicit valence for atom # 27 C, 6, is greater than permitted
[12:36:01] Explicit valence for atom # 26 C, 5, is greater than permitted

--- Processing cluster 2 ---

[12:36:22] Explicit valence for atom # 7 C greater than permitted
[12:36:22] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:36:22] Explicit valence for atom # 26 Si, 5, is greater than permitted
[12:36:22] Explicit valence for atom # 16 C greater than permitted
[12:36:22] Explicit valence for atom # 28 C, 5, is greater than permitted
[12:36:22] Explicit valence for atom # 23 Si, 5, is greater than permitted
[12:36:22] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:36:22] Explicit valence for atom # 30 C greater than permitted
[12:36:23] Explicit valence for atom # 28 P, 7, is greater than permitted
[12:36:23] Explicit valence for atom # 18 C greater than permitted
[12:36:23] Explicit valence for atom # 19 C greater than permitted
[12:36:23] Explicit valence for atom # 20 C, 5, is greater than permitted
[12:36:23] Explicit valence for atom # 30 C greater than permitted
[12:36:23] Explicit valence for atom # 21 C greater than permitted
[12:36:23] Explicit valence for atom # 4 C, 5, is greater than permitted
[12:36:23] Explicit valence for atom # 14 C greater than permitted
[12:36:23] Explicit valence for atom # 39 C greater than permitted
[12:36:23] Explicit valence for atom # 14 C greater than permitted
[12:36:23] Explicit valence for atom # 32 C greater than permitted
[12:36:23] Explicit valence for atom # 1 Si, 5, is greater than permitted
[12:36:23] Explicit valence for atom # 25 C, 5, is greater than permitted
[12:36:23] Explicit valence for atom # 29 C, 5, is greater than permitted
[12:36:23] Explicit valence for atom # 30 C greater than permitted
[12:36:23] Explicit valence for atom # 20 C, 5, is greater than permitted
[12:36:23] Explicit valence for atom # 20 P, 7, is greater than permitted
[12:36:23] Explicit valence for atom # 22 C greater than permitted
[12:36:23] Explicit valence for atom # 2 C greater than permitted
[12:36:23] Explicit valence for atom # 5 C, 5, is greater than permitted
[12:36:23] Explicit valence for atom # 29 C greater than permitted
[12:36:23] Explicit valence for atom # 28 C greater than permitted
[12:36:23] Explicit valence for atom # 38 C greater than permitted
[12:36:23] Explicit valence for atom # 30 C greater than permitted
[12:36:23] Explicit valence for atom # 16 C greater than permitted
[12:36:23] Explicit valence for atom # 12 C greater than permitted
[12:36:23] Explicit valence for atom # 32 P, 7, is greater than permitted
[12:36:23] Explicit valence for atom # 7 C, 5, is greater than permitted
[12:36:23] Explicit valence for atom # 28 C greater than permitted
[12:36:23] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:36:23] Explicit valence for atom # 16 C, 5, is greater than permitted
[12:36:23] Explicit valence for atom # 19 C, 6, is greater than permitted
[12:36:23] Explicit valence for atom # 44 C greater than permitted
[12:36:23] Explicit valence for atom # 12 C greater than permitted
[12:36:23] Explicit valence for atom # 24 C, 5, is greater than permitted
[12:36:23] Explicit valence for atom # 27 C greater than permitted
[12:36:23] Explicit valence for atom # 13 C, 5, is greater than permitted
[12:36:23] Explicit valence for atom # 29 C greater than permitted
[12:36:23] Explicit valence for atom # 20 C greater than permitted
[12:36:23] Explicit valence for atom # 22 C greater than permitted
[12:36:23] Explicit valence for atom # 26 C greater than permitted
[12:36:24] Explicit valence for atom # 29 C, 5, is greater than permitted
[12:36:24] Explicit valence for atom # 37 C greater than permitted
[12:36:24] Explicit valence for atom # 36 C, 5, is greater than permitted
[12:36:24] Explicit valence for atom # 29 C greater than permitted
[12:36:24] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:36:24] Explicit valence for atom # 8 C greater than permitted
[12:36:24] Explicit valence for atom # 5 C, 6, is greater than permitted
[12:36:24] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:36:24] Explicit valence for atom # 13 C greater than permitted
[12:36:24] Explicit valence for atom # 23 C greater than permitted
[12:36:24] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:36:24] Explicit valence for atom # 9 C, 5, is greater than permitted
[12:36:24] Explicit valence for atom # 28 C, 5, is greater than permitted
[12:36:24] Explicit valence for atom # 12 C greater than permitted
[12:36:24] Explicit valence for atom # 14 C greater than permitted
[12:36:24] Explicit valence for atom # 26 C greater than permitted
[12:36:24] Explicit valence for atom # 26 C, 5, is greater than permitted
[12:36:24] Explicit valence for atom # 33 C greater than permitted
[12:36:24] Explicit valence for atom # 12 C, 6, is greater than permitted
[12:36:24] Explicit valence for atom # 28 Si, 5, is greater than permitted
[12:36:24] Explicit valence for atom # 21 C greater than permitted
[12:36:24] Explicit valence for atom # 10 C greater than permitted
[12:36:24] Explicit valence for atom # 25 C greater than permitted
[12:36:24] Explicit valence for atom # 24 C greater than permitted
[12:36:24] Explicit valence for atom # 32 C greater than permitted
[12:36:24] Explicit valence for atom # 7 C, 5, is greater than permitted
[12:36:24] Explicit valence for atom # 6 C, 6, is greater than permitted
[12:36:24] Explicit valence for atom # 20 C greater than permitted
[12:36:24] Explicit valence for atom # 26 C, 5, is greater than permitted
[12:36:24] Explicit valence for atom # 6 Si, 5, is greater than permitted
[12:36:24] Explicit valence for atom # 20 C greater than permitted
[12:36:24] Explicit valence for atom # 12 C, 5, is greater than permitted
[12:36:24] Explicit valence for atom # 28 C, 5, is greater than permitted
[12:36:24] Explicit valence for atom # 28 C greater than permitted
[12:36:24] Explicit valence for atom # 14 C greater than permitted
[12:36:24] Explicit valence for atom # 26 C greater than permitted
[12:36:24] Explicit valence for atom # 7 C, 5, is greater than permitted
[12:36:24] Explicit valence for atom # 30 C, 5, is greater than permitted
[12:36:24] Explicit valence for atom # 26 C, 5, is greater than permitted
[12:36:24] Explicit valence for atom # 18 C, 6, is greater than permitted
[12:36:24] Explicit valence for atom # 28 C, 5, is greater than permitted
[12:36:24] Explicit valence for atom # 22 C greater than permitted
[12:36:24] Explicit valence for atom # 12 C, 5, is greater than permitted
[12:36:25] Explicit valence for atom # 22 C greater than permitted
[12:36:25] Explicit valence for atom # 29 C greater than permitted
[12:36:25] Explicit valence for atom # 20 C greater than permitted
[12:36:25] Explicit valence for atom # 28 P, 7, is greater than permitted
[12:36:25] Explicit valence for atom # 36 C greater than permitted
[12:36:25] Explicit valence for atom # 6 C greater than permitted
[12:36:25] Explicit valence for atom # 26 C greater than permitted
[12:36:25] Explicit valence for atom # 26 C greater than permitted
[12:36:25] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:36:25] Explicit valence for atom # 20 C, 5, is greater than permitted
[12:36:25] Explicit valence for atom # 15 C greater than permitted
[12:36:25] Explicit valence for atom # 28 C, 5, is greater than permitted
[12:36:25] Explicit valence for atom # 23 C greater than permitted
[12:36:25] Explicit valence for atom # 28 Si, 5, is greater than permitted
[12:36:25] Explicit valence for atom # 25 C greater than permitted
[12:36:25] Explicit valence for atom # 23 C greater than permitted
[12:36:25] Explicit valence for atom # 20 C greater than permitted
[12:36:25] Explicit valence for atom # 29 C greater than permitted
[12:36:25] Explicit valence for atom # 27 C greater than permitted
[12:36:25] Explicit valence for atom # 25 C greater than permitted
[12:36:25] Explicit valence for atom # 26 C greater than permitted
[12:36:25] Explicit valence for atom # 15 C, 6, is greater than permitted
[12:36:25] Explicit valence for atom # 16 C, 5, is greater than permitted
[12:36:25] Explicit valence for atom # 17 Si, 5, is greater than permitted
[12:36:25] Explicit valence for atom # 30 C, 5, is greater than permitted
[12:36:25] Explicit valence for atom # 28 C greater than permitted
[12:36:25] Explicit valence for atom # 18 C greater than permitted
[12:36:25] Explicit valence for atom # 13 Si, 5, is greater than permitted
[12:36:25] Explicit valence for atom # 26 C greater than permitted
[12:36:25] Explicit valence for atom # 12 C greater than permitted
[12:36:25] Explicit valence for atom # 28 C greater than permitted
[12:36:25] Explicit valence for atom # 18 C greater than permitted
[12:36:25] Explicit valence for atom # 11 P, 7, is greater than permitted
[12:36:25] Explicit valence for atom # 15 C greater than permitted
[12:36:25] Explicit valence for atom # 16 C greater than permitted
[12:36:25] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:36:25] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:36:25] Explicit valence for atom # 23 C, 5, is greater than permitted
[12:36:25] Explicit valence for atom # 33 C greater than permitted
[12:36:25] Explicit valence for atom # 12 C, 5, is greater than permitted
[12:36:25] Explicit valence for atom # 23 C greater than permitted
[12:36:25] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:36:25] Explicit valence for atom # 31 C, 5, is greater than permitted
[12:36:25] Explicit valence for atom # 29 C greater than permitted
[12:36:25] Explicit valence for atom # 34 C greater than permitted
[12:36:25] Explicit valence for atom # 23 C greater than permitted
[12:36:25] Explicit valence for atom # 32 C greater than permitted
[12:36:25] Explicit valence for atom # 11 C, 5, is greater than permitted
[12:36:25] Explicit valence for atom # 45 C greater than permitted
[12:36:25] Explicit valence for atom # 13 C greater than permitted
[12:36:25] Explicit valence for atom # 33 C greater than permitted
[12:36:26] Explicit valence for atom # 31 C, 5, is greater than permitted
[12:36:26] Explicit valence for atom # 26 C greater than permitted
[12:36:26] Explicit valence for atom # 14 C, 5, is greater than permitted
[12:36:26] Explicit valence for atom # 17 C, 5, is greater than permitted
[12:36:26] Explicit valence for atom # 28 C greater than permitted
[12:36:26] Explicit valence for atom # 23 C greater than permitted
[12:36:26] Explicit valence for atom # 24 C greater than permitted
[12:36:26] Explicit valence for atom # 20 C, 5, is greater than permitted
[12:36:26] Explicit valence for atom # 16 C greater than permitted
[12:36:26] Explicit valence for atom # 23 C, 5, is greater than permitted
[12:36:26] Explicit valence for atom # 18 Si, 5, is greater than permitted
[12:36:26] Explicit valence for atom # 21 C greater than permitted
[12:36:26] Explicit valence for atom # 13 C greater than permitted
[12:36:26] Explicit valence for atom # 25 C greater than permitted
[12:36:26] Explicit valence for atom # 22 C, 5, is greater than permitted
[12:36:26] Explicit valence for atom # 14 P, 7, is greater than permitted
[12:36:26] Explicit valence for atom # 8 C greater than permitted
[12:36:26] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:36:26] Explicit valence for atom # 26 C greater than permitted
[12:36:26] Explicit valence for atom # 28 P, 7, is greater than permitted
[12:36:26] Explicit valence for atom # 22 C greater than permitted
[12:36:26] Explicit valence for atom # 21 C greater than permitted
[12:36:26] Explicit valence for atom # 21 C, 6, is greater than permitted
[12:36:26] Explicit valence for atom # 16 C greater than permitted
[12:36:26] Explicit valence for atom # 25 C greater than permitted
[12:36:26] Explicit valence for atom # 25 C greater than permitted
[12:36:26] Explicit valence for atom # 25 C, 5, is greater than permitted
[12:36:26] Explicit valence for atom # 10 C greater than permitted
[12:36:26] Explicit valence for atom # 24 C greater than permitted
[12:36:26] Explicit valence for atom # 32 C, 5, is greater than permitted
[12:36:26] Explicit valence for atom # 26 Si, 5, is greater than permitted
[12:36:26] Explicit valence for atom # 24 C, 5, is greater than permitted
[12:36:26] Explicit valence for atom # 15 C, 5, is greater than permitted
[12:36:26] Explicit valence for atom # 13 C greater than permitted
[12:36:26] Explicit valence for atom # 22 C greater than permitted
[12:36:26] Explicit valence for atom # 18 C greater than permitted
[12:36:26] Explicit valence for atom # 27 C greater than permitted
[12:36:26] Explicit valence for atom # 18 P, 6, is greater than permitted
[12:36:26] Explicit valence for atom # 15 Si, 5, is greater than permitted
[12:36:26] Explicit valence for atom # 11 C greater than permitted
[12:36:26] Explicit valence for atom # 13 P, 7, is greater than permitted
[12:36:26] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:36:26] Explicit valence for atom # 20 Si, 5, is greater than permitted
[12:36:26] Explicit valence for atom # 21 C greater than permitted
[12:36:26] Explicit valence for atom # 28 C greater than permitted
[12:36:26] Explicit valence for atom # 15 C, 5, is greater than permitted
[12:36:26] Explicit valence for atom # 25 C greater than permitted
[12:36:26] Explicit valence for atom # 17 C, 6, is greater than permitted
[12:36:26] Explicit valence for atom # 29 C greater than permitted
[12:36:26] Explicit valence for atom # 29 Si, 5, is greater than permitted
[12:36:26] Explicit valence for atom # 20 C greater than permitted
[12:36:26] Explicit valence for atom # 30 C greater than permitted
[12:36:26] Explicit valence for atom # 33 C greater than permitted
[12:36:26] Explicit valence for atom # 28 C greater than permitted
[12:36:26] Explicit valence for atom # 3 C greater than permitted
[12:36:26] Explicit valence for atom # 30 C greater than permitted
[12:36:26] Explicit valence for atom # 29 P, 5, is greater than permitted
[12:36:26] Explicit valence for atom # 32 C greater than permitted
[12:36:26] Explicit valence for atom # 18 C greater than permitted
[12:36:26] Explicit valence for atom # 28 C greater than permitted
[12:36:26] Explicit valence for atom # 31 Si, 5, is greater than permitted
[12:36:26] Explicit valence for atom # 28 C greater than permitted
[12:36:26] Explicit valence for atom # 33 C greater than permitted
[12:36:26] Explicit valence for atom # 25 C greater than permitted
[12:36:26] Explicit valence for atom # 11 C, 5, is greater than permitted
[12:36:26] Explicit valence for atom # 15 C, 5, is greater than permitted
[12:36:26] Explicit valence for atom # 20 C, 5, is greater than permitted
[12:36:26] Explicit valence for atom # 20 C greater than permitted
[12:36:26] Explicit valence for atom # 30 C greater than permitted
[12:36:27] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:36:27] Explicit valence for atom # 22 C greater than permitted
[12:36:27] Explicit valence for atom # 12 C, 5, is greater than permitted
[12:36:27] Explicit valence for atom # 21 C, 5, is greater than permitted
[12:36:27] Explicit valence for atom # 30 C greater than permitted
[12:36:27] Explicit valence for atom # 11 C, 5, is greater than permitted
[12:36:27] Explicit valence for atom # 38 C greater than permitted
[12:36:27] Explicit valence for atom # 29 C greater than permitted
[12:36:27] Can't kekulize mol.  Unkekulized atoms: 2 15 16
[12:36:27] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:36:27] Explicit valence for atom # 15 Si, 5, is greater than permitted
[12:36:27] Explicit valence for atom # 24 C, 5, is greater than permitted
[12:36:27] Explicit valence for atom # 33 C, 5, is greater than permitted
[12:36:27] Explicit valence for atom # 12 P, 7, is greater than permitted
[12:36:27] Explicit valence for atom # 23 C, 5, is greater than permitted
[12:36:27] Explicit valence for atom # 23 C, 5, is greater than permitted
[12:36:27] Explicit valence for atom # 35 C greater than permitted
[12:36:27] Explicit valence for atom # 18 Si, 6, is greater than permitted
[12:36:27] Explicit valence for atom # 14 C greater than permitted
[12:36:27] Explicit valence for atom # 14 C greater than permitted
[12:36:27] Explicit valence for atom # 25 C greater than permitted
[12:36:27] Explicit valence for atom # 21 C, 5, is greater than permitted
[12:36:27] Explicit valence for atom # 24 C greater than permitted
[12:36:27] Explicit valence for atom # 15 C greater than permitted
[12:36:27] Explicit valence for atom # 17 C greater than permitted
[12:36:27] Explicit valence for atom # 13 Si, 5, is greater than permitted
[12:36:27] Explicit valence for atom # 11 C, 5, is greater than permitted
[12:36:27] Explicit valence for atom # 10 C, 5, is greater than permitted
[12:36:27] Explicit valence for atom # 18 C greater than permitted
[12:36:27] Explicit valence for atom # 22 C, 5, is greater than permitted
[12:36:27] Explicit valence for atom # 25 Si, 5, is greater than permitted
[12:36:27] Explicit valence for atom # 8 C greater than permitted
[12:36:27] Explicit valence for atom # 30 C, 5, is greater than permitted
[12:36:27] Explicit valence for atom # 25 C greater than permitted
[12:36:27] Explicit valence for atom # 23 C greater than permitted
[12:36:27] Explicit valence for atom # 21 C greater than permitted
[12:36:27] Explicit valence for atom # 21 C, 5, is greater than permitted
[12:36:27] Explicit valence for atom # 35 C greater than permitted
[12:36:27] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:36:27] Explicit valence for atom # 12 Si, 5, is greater than permitted
[12:36:27] Explicit valence for atom # 31 C greater than permitted
[12:36:27] Explicit valence for atom # 22 C, 6, is greater than permitted
[12:36:27] Explicit valence for atom # 28 C greater than permitted
[12:36:27] Explicit valence for atom # 28 C, 5, is greater than permitted
[12:36:27] Explicit valence for atom # 15 C greater than permitted
[12:36:27] Explicit valence for atom # 20 C greater than permitted
[12:36:27] Explicit valence for atom # 20 C, 6, is greater than permitted
[12:36:27] Explicit valence for atom # 15 C, 5, is greater than permitted
[12:36:27] Explicit valence for atom # 20 P, 6, is greater than permitted
[12:36:27] Explicit valence for atom # 25 C greater than permitted
[12:36:27] Explicit valence for atom # 21 C greater than permitted
[12:36:27] Explicit valence for atom # 10 C, 5, is greater than permitted
[12:36:27] Explicit valence for atom # 11 C greater than permitted
[12:36:27] Explicit valence for atom # 23 Si, 5, is greater than permitted
[12:36:27] Explicit valence for atom # 25 C greater than permitted
[12:36:27] Explicit valence for atom # 13 P, 7, is greater than permitted
[12:36:27] Explicit valence for atom # 29 C, 5, is greater than permitted
[12:36:27] Explicit valence for atom # 29 C greater than permitted
[12:36:27] Explicit valence for atom # 22 C, 6, is greater than permitted
[12:36:27] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:36:27] Explicit valence for atom # 35 C, 5, is greater than permitted
[12:36:27] Explicit valence for atom # 8 C, 6, is greater than permitted
[12:36:27] Explicit valence for atom # 23 C, 5, is greater than permitted
[12:36:27] Explicit valence for atom # 39 Si, 5, is greater than permitted
[12:36:28] Explicit valence for atom # 28 C, 6, is greater than permitted
[12:36:28] Explicit valence for atom # 28 C, 5, is greater than permitted
[12:36:28] Explicit valence for atom # 21 C greater than permitted
[12:36:28] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:36:28] Explicit valence for atom # 22 C, 5, is greater than permitted
[12:36:28] Explicit valence for atom # 24 C greater than permitted
[12:36:28] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:36:28] Explicit valence for atom # 22 C, 5, is greater than permitted

--- Processing cluster 3 ---

[12:36:52] Explicit valence for atom # 22 C, 5, is greater than permitted
[12:36:52] Explicit valence for atom # 17 C greater than permitted
[12:36:52] Explicit valence for atom # 31 C greater than permitted
[12:36:52] Explicit valence for atom # 23 C greater than permitted
[12:36:52] Explicit valence for atom # 27 C greater than permitted
[12:36:52] Explicit valence for atom # 19 C greater than permitted
[12:36:52] Explicit valence for atom # 42 C greater than permitted
[12:36:53] Explicit valence for atom # 33 Si, 5, is greater than permitted
[12:36:53] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:36:53] Explicit valence for atom # 36 C, 5, is greater than permitted
[12:36:53] Explicit valence for atom # 15 C, 5, is greater than permitted
[12:36:53] Explicit valence for atom # 26 C greater than permitted
[12:36:53] Explicit valence for atom # 22 C greater than permitted
[12:36:53] Explicit valence for atom # 31 C, 4, is greater than permitted
[12:36:53] Explicit valence for atom # 29 C greater than permitted
[12:36:53] Explicit valence for atom # 26 C greater than permitted
[12:36:53] Explicit valence for atom # 37 C greater than permitted
[12:36:53] Explicit valence for atom # 13 C greater than permitted
[12:36:53] Explicit valence for atom # 18 C greater than permitted
[12:36:53] Explicit valence for atom # 19 C, 5, is greater than permitted
[12:36:53] Explicit valence for atom # 33 C greater than permitted
[12:36:53] Explicit valence for atom # 32 C greater than permitted
[12:36:53] Explicit valence for atom # 10 C, 5, is greater than permitted
[12:36:53] Explicit valence for atom # 1 C greater than permitted
[12:36:53] Explicit valence for atom # 25 C, 5, is greater than permitted
[12:36:53] Explicit valence for atom # 37 C greater than permitted
[12:36:53] Explicit valence for atom # 36 C greater than permitted
[12:36:53] Explicit valence for atom # 33 C greater than permitted
[12:36:53] Explicit valence for atom # 25 C greater than permitted
[12:36:53] Explicit valence for atom # 28 C greater than permitted
[12:36:53] Explicit valence for atom # 23 C greater than permitted
[12:36:53] Explicit valence for atom # 31 C greater than permitted
[12:36:53] Explicit valence for atom # 29 C greater than permitted
[12:36:53] Explicit valence for atom # 28 C greater than permitted
[12:36:53] Explicit valence for atom # 17 C greater than permitted
[12:36:53] Explicit valence for atom # 37 C greater than permitted
[12:36:53] Explicit valence for atom # 23 C greater than permitted
[12:36:53] Explicit valence for atom # 20 C greater than permitted
[12:36:53] Explicit valence for atom # 41 C greater than permitted
[12:36:53] Explicit valence for atom # 30 C greater than permitted
[12:36:53] Explicit valence for atom # 34 C greater than permitted
[12:36:53] Explicit valence for atom # 35 Si, 6, is greater than permitted
[12:36:53] Explicit valence for atom # 33 Si, 5, is greater than permitted
[12:36:53] Explicit valence for atom # 16 C greater than permitted
[12:36:53] Explicit valence for atom # 16 C, 5, is greater than permitted
[12:36:53] Explicit valence for atom # 28 C greater than permitted
[12:36:53] Explicit valence for atom # 23 Si, 5, is greater than permitted
[12:36:53] Explicit valence for atom # 21 C, 5, is greater than permitted
[12:36:53] Explicit valence for atom # 22 C, 5, is greater than permitted
[12:36:53] Explicit valence for atom # 37 C greater than permitted
[12:36:53] Explicit valence for atom # 13 C greater than permitted
[12:36:53] Explicit valence for atom # 37 C greater than permitted
[12:36:53] Explicit valence for atom # 28 C greater than permitted
[12:36:53] Explicit valence for atom # 12 C, 5, is greater than permitted
[12:36:53] Explicit valence for atom # 34 C greater than permitted
[12:36:53] Explicit valence for atom # 27 C greater than permitted
[12:36:53] Explicit valence for atom # 0 C greater than permitted
[12:36:53] Explicit valence for atom # 24 C, 6, is greater than permitted
[12:36:53] Explicit valence for atom # 5 C greater than permitted
[12:36:53] Explicit valence for atom # 31 C greater than permitted
[12:36:53] Explicit valence for atom # 4 P, 6, is greater than permitted
[12:36:53] Explicit valence for atom # 17 C greater than permitted
[12:36:53] Explicit valence for atom # 3 P, 7, is greater than permitted
[12:36:53] Explicit valence for atom # 23 Si, 5, is greater than permitted
[12:36:53] Explicit valence for atom # 18 C, 6, is greater than permitted
[12:36:53] Explicit valence for atom # 24 C greater than permitted
[12:36:53] Explicit valence for atom # 26 Si, 5, is greater than permitted
[12:36:53] Explicit valence for atom # 17 C greater than permitted
[12:36:53] Explicit valence for atom # 12 P, 7, is greater than permitted
[12:36:54] Explicit valence for atom # 15 Si, 5, is greater than permitted
[12:36:54] Explicit valence for atom # 23 C greater than permitted
[12:36:54] Explicit valence for atom # 35 C greater than permitted
[12:36:54] Explicit valence for atom # 30 C greater than permitted
[12:36:54] Explicit valence for atom # 26 C greater than permitted
[12:36:54] Explicit valence for atom # 9 C greater than permitted
[12:36:54] Explicit valence for atom # 24 C greater than permitted
[12:36:54] Explicit valence for atom # 18 P, 7, is greater than permitted
[12:36:54] Explicit valence for atom # 15 C greater than permitted
[12:36:54] Explicit valence for atom # 25 C, 5, is greater than permitted
[12:36:54] Explicit valence for atom # 9 C greater than permitted
[12:36:54] Explicit valence for atom # 39 C greater than permitted
[12:36:54] Explicit valence for atom # 26 C greater than permitted
[12:36:54] Explicit valence for atom # 25 C greater than permitted
[12:36:54] Explicit valence for atom # 24 C, 5, is greater than permitted
[12:36:54] Explicit valence for atom # 29 C greater than permitted
[12:36:54] Explicit valence for atom # 21 C greater than permitted
[12:36:54] Explicit valence for atom # 17 Si, 5, is greater than permitted
[12:36:54] Explicit valence for atom # 23 C greater than permitted
[12:36:54] Explicit valence for atom # 32 C greater than permitted
[12:36:54] Explicit valence for atom # 23 C, 5, is greater than permitted
[12:36:54] Explicit valence for atom # 24 C greater than permitted
[12:36:54] Explicit valence for atom # 21 C greater than permitted
[12:36:54] Explicit valence for atom # 25 C greater than permitted
[12:36:54] Explicit valence for atom # 12 P, 7, is greater than permitted
[12:36:54] Explicit valence for atom # 27 C greater than permitted
[12:36:54] Explicit valence for atom # 36 C greater than permitted
[12:36:54] Explicit valence for atom # 17 C greater than permitted
[12:36:54] Explicit valence for atom # 16 Si, 6, is greater than permitted
[12:36:54] Explicit valence for atom # 3 C greater than permitted
[12:36:54] Explicit valence for atom # 47 C greater than permitted
[12:36:54] Explicit valence for atom # 14 C greater than permitted
[12:36:54] Explicit valence for atom # 31 C, 5, is greater than permitted
[12:36:54] Explicit valence for atom # 32 C greater than permitted
[12:36:54] Explicit valence for atom # 4 C greater than permitted
[12:36:54] Explicit valence for atom # 3 C greater than permitted
[12:36:54] Explicit valence for atom # 17 C greater than permitted
[12:36:54] Explicit valence for atom # 30 C greater than permitted
[12:36:54] Explicit valence for atom # 19 As, 6, is greater than permitted
[12:36:54] Explicit valence for atom # 23 C greater than permitted
[12:36:54] Explicit valence for atom # 26 C, 5, is greater than permitted
[12:36:54] Explicit valence for atom # 4 C greater than permitted
[12:36:54] Explicit valence for atom # 26 C greater than permitted
[12:36:54] Explicit valence for atom # 28 C, 5, is greater than permitted
[12:36:54] Explicit valence for atom # 22 C greater than permitted
[12:36:54] Explicit valence for atom # 10 P, 7, is greater than permitted
[12:36:54] Explicit valence for atom # 10 C, 5, is greater than permitted
[12:36:54] Explicit valence for atom # 19 C greater than permitted
[12:36:54] Explicit valence for atom # 17 C greater than permitted
[12:36:54] Explicit valence for atom # 25 C greater than permitted
[12:36:54] Explicit valence for atom # 22 P, 7, is greater than permitted
[12:36:54] Explicit valence for atom # 7 P, 7, is greater than permitted
[12:36:54] Explicit valence for atom # 22 C greater than permitted
[12:36:54] Explicit valence for atom # 17 Si, 5, is greater than permitted
[12:36:54] Explicit valence for atom # 40 C greater than permitted
[12:36:54] Explicit valence for atom # 4 P, 7, is greater than permitted
[12:36:54] Explicit valence for atom # 3 C greater than permitted
[12:36:54] Explicit valence for atom # 28 Si, 5, is greater than permitted
[12:36:54] Explicit valence for atom # 26 P, 7, is greater than permitted
[12:36:54] Explicit valence for atom # 24 C greater than permitted
[12:36:54] Explicit valence for atom # 23 C greater than permitted
[12:36:54] Explicit valence for atom # 33 P, 7, is greater than permitted
[12:36:54] Explicit valence for atom # 31 C greater than permitted
[12:36:54] Explicit valence for atom # 15 C greater than permitted
[12:36:54] Explicit valence for atom # 10 C, 5, is greater than permitted
[12:36:54] Explicit valence for atom # 28 C greater than permitted
[12:36:54] Explicit valence for atom # 23 C greater than permitted
[12:36:54] Explicit valence for atom # 24 C greater than permitted
[12:36:54] Explicit valence for atom # 6 C greater than permitted
[12:36:54] Explicit valence for atom # 7 C greater than permitted
[12:36:54] Explicit valence for atom # 24 C greater than permitted
[12:36:54] Explicit valence for atom # 31 C greater than permitted
[12:36:54] Explicit valence for atom # 5 C greater than permitted
[12:36:54] Explicit valence for atom # 23 C greater than permitted
[12:36:54] Explicit valence for atom # 28 C greater than permitted
[12:36:54] Explicit valence for atom # 26 Si, 5, is greater than permitted
[12:36:54] Explicit valence for atom # 25 C greater than permitted
[12:36:55] Explicit valence for atom # 10 C, 5, is greater than permitted
[12:36:55] Explicit valence for atom # 23 C greater than permitted
[12:36:55] Explicit valence for atom # 19 C greater than permitted
[12:36:55] Explicit valence for atom # 31 C greater than permitted
[12:36:55] Explicit valence for atom # 26 P, 7, is greater than permitted
[12:36:55] Explicit valence for atom # 28 C, 5, is greater than permitted
[12:36:55] Explicit valence for atom # 38 C greater than permitted
[12:36:55] Explicit valence for atom # 26 C greater than permitted
[12:36:55] Explicit valence for atom # 21 C, 5, is greater than permitted
[12:36:55] Explicit valence for atom # 24 P, 7, is greater than permitted
[12:36:55] Explicit valence for atom # 27 C greater than permitted
[12:36:55] Explicit valence for atom # 25 C, 5, is greater than permitted
[12:36:55] Explicit valence for atom # 28 C greater than permitted
[12:36:55] Explicit valence for atom # 20 Si, 5, is greater than permitted
[12:36:55] Explicit valence for atom # 32 C greater than permitted
[12:36:55] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:36:55] Explicit valence for atom # 13 C greater than permitted
[12:36:55] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:36:55] Explicit valence for atom # 24 C greater than permitted
[12:36:55] Explicit valence for atom # 16 C greater than permitted
[12:36:55] Explicit valence for atom # 8 C greater than permitted
[12:36:55] Explicit valence for atom # 3 C greater than permitted
[12:36:55] Explicit valence for atom # 17 C greater than permitted
[12:36:55] Explicit valence for atom # 26 C greater than permitted
[12:36:55] Explicit valence for atom # 18 C greater than permitted
[12:36:55] Explicit valence for atom # 33 C greater than permitted
[12:36:55] Explicit valence for atom # 5 Si, 5, is greater than permitted
[12:36:55] Explicit valence for atom # 22 Si, 5, is greater than permitted
[12:36:55] Explicit valence for atom # 42 Si, 5, is greater than permitted
[12:36:55] Explicit valence for atom # 20 C greater than permitted
[12:36:55] Explicit valence for atom # 23 P, 7, is greater than permitted
[12:36:55] Explicit valence for atom # 23 C greater than permitted
[12:36:55] Explicit valence for atom # 23 C greater than permitted
[12:36:55] Explicit valence for atom # 2 C greater than permitted
[12:36:55] Explicit valence for atom # 1 C greater than permitted
[12:36:55] Explicit valence for atom # 23 C greater than permitted
[12:36:55] Explicit valence for atom # 10 C, 5, is greater than permitted
[12:36:55] Explicit valence for atom # 22 Si, 5, is greater than permitted
[12:36:55] Explicit valence for atom # 19 C, 5, is greater than permitted
[12:36:55] Explicit valence for atom # 15 C greater than permitted
[12:36:55] Explicit valence for atom # 30 C greater than permitted
[12:36:55] Explicit valence for atom # 26 C greater than permitted
[12:36:55] Explicit valence for atom # 24 C greater than permitted
[12:36:55] Explicit valence for atom # 27 C greater than permitted
[12:36:55] Explicit valence for atom # 23 Si, 5, is greater than permitted
[12:36:55] Explicit valence for atom # 35 C greater than permitted
[12:36:55] Explicit valence for atom # 25 Si, 5, is greater than permitted
[12:36:55] Explicit valence for atom # 17 C greater than permitted
[12:36:55] Explicit valence for atom # 33 C greater than permitted
[12:36:55] Explicit valence for atom # 5 C greater than permitted
[12:36:55] Explicit valence for atom # 25 C, 5, is greater than permitted
[12:36:55] Explicit valence for atom # 13 C greater than permitted
[12:36:55] Explicit valence for atom # 24 C greater than permitted
[12:36:55] Explicit valence for atom # 30 C greater than permitted
[12:36:55] Explicit valence for atom # 22 Si, 5, is greater than permitted
[12:36:55] Explicit valence for atom # 31 C, 6, is greater than permitted
[12:36:55] Explicit valence for atom # 29 C greater than permitted
[12:36:55] Explicit valence for atom # 30 C, 5, is greater than permitted
[12:36:56] Explicit valence for atom # 20 C greater than permitted
[12:36:56] Explicit valence for atom # 5 P, 7, is greater than permitted
[12:36:56] Explicit valence for atom # 9 C greater than permitted
[12:36:56] Explicit valence for atom # 29 C greater than permitted
[12:36:56] Explicit valence for atom # 21 C greater than permitted
[12:36:56] Explicit valence for atom # 25 Si, 5, is greater than permitted
[12:36:56] Explicit valence for atom # 40 C greater than permitted
[12:36:56] Explicit valence for atom # 25 C greater than permitted
[12:36:56] Explicit valence for atom # 24 C, 5, is greater than permitted
[12:36:56] Explicit valence for atom # 29 C greater than permitted
[12:36:56] Explicit valence for atom # 28 C greater than permitted
[12:36:56] Explicit valence for atom # 8 C greater than permitted
[12:36:56] Explicit valence for atom # 17 C greater than permitted
[12:36:56] Explicit valence for atom # 29 C, 5, is greater than permitted
[12:36:56] Explicit valence for atom # 13 C greater than permitted
[12:36:56] Explicit valence for atom # 23 Si, 5, is greater than permitted
[12:36:56] Explicit valence for atom # 29 C greater than permitted
[12:36:56] Explicit valence for atom # 14 C greater than permitted
[12:36:56] Explicit valence for atom # 26 C greater than permitted
[12:36:56] Explicit valence for atom # 34 C greater than permitted
[12:36:56] Explicit valence for atom # 28 C greater than permitted
[12:36:56] Explicit valence for atom # 26 C greater than permitted
[12:36:56] Explicit valence for atom # 28 C greater than permitted
[12:36:56] Explicit valence for atom # 37 C greater than permitted
[12:36:56] Explicit valence for atom # 23 C greater than permitted
[12:36:56] Explicit valence for atom # 25 C, 5, is greater than permitted
[12:36:56] Explicit valence for atom # 38 C greater than permitted
[12:36:56] Explicit valence for atom # 25 C greater than permitted
[12:36:56] Explicit valence for atom # 4 C, 6, is greater than permitted
[12:36:56] Explicit valence for atom # 24 C greater than permitted
[12:36:56] Explicit valence for atom # 29 C greater than permitted
[12:36:56] Explicit valence for atom # 36 C greater than permitted
[12:36:56] Explicit valence for atom # 26 C greater than permitted
[12:36:56] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:36:56] Explicit valence for atom # 27 C greater than permitted
[12:36:56] Explicit valence for atom # 16 C greater than permitted
[12:36:56] Explicit valence for atom # 17 P, 7, is greater than permitted
[12:36:56] Explicit valence for atom # 43 C greater than permitted
[12:36:56] Explicit valence for atom # 39 C greater than permitted
[12:36:56] Explicit valence for atom # 15 C greater than permitted
[12:36:56] Explicit valence for atom # 17 C greater than permitted
[12:36:56] Explicit valence for atom # 26 C greater than permitted
[12:36:56] Explicit valence for atom # 30 P, 7, is greater than permitted
[12:36:56] Explicit valence for atom # 23 C greater than permitted
[12:36:56] Explicit valence for atom # 1 Si, 5, is greater than permitted
[12:36:56] Explicit valence for atom # 34 C greater than permitted
[12:36:56] Explicit valence for atom # 19 C greater than permitted
[12:36:56] Explicit valence for atom # 49 C greater than permitted
[12:36:56] Explicit valence for atom # 5 P, 7, is greater than permitted
[12:36:56] Explicit valence for atom # 37 C greater than permitted
[12:36:56] Explicit valence for atom # 21 C greater than permitted
[12:36:56] Explicit valence for atom # 25 C greater than permitted
[12:36:56] Explicit valence for atom # 14 As, 6, is greater than permitted
[12:36:56] Explicit valence for atom # 19 C greater than permitted
[12:36:56] Explicit valence for atom # 21 C greater than permitted
[12:36:56] Explicit valence for atom # 34 C greater than permitted
[12:36:56] Explicit valence for atom # 23 Si, 5, is greater than permitted
[12:36:56] Explicit valence for atom # 20 P, 7, is greater than permitted
[12:36:56] Explicit valence for atom # 24 P, 7, is greater than permitted
[12:36:56] Explicit valence for atom # 30 C greater than permitted
[12:36:56] Explicit valence for atom # 14 C greater than permitted
[12:36:56] Explicit valence for atom # 20 P, 7, is greater than permitted
[12:36:56] Explicit valence for atom # 35 C greater than permitted
[12:36:56] Explicit valence for atom # 22 C greater than permitted
[12:36:56] Explicit valence for atom # 41 C greater than permitted
[12:36:56] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:36:56] Explicit valence for atom # 13 C greater than permitted
[12:36:56] Explicit valence for atom # 31 C greater than permitted
[12:36:56] Explicit valence for atom # 16 C greater than permitted
[12:36:57] Explicit valence for atom # 21 Si, 5, is greater than permitted
[12:36:57] Explicit valence for atom # 29 C greater than permitted
[12:36:57] Explicit valence for atom # 36 C greater than permitted
[12:36:57] Explicit valence for atom # 18 C greater than permitted
[12:36:57] Explicit valence for atom # 6 Si, 5, is greater than permitted
[12:36:57] Explicit valence for atom # 26 C greater than permitted
[12:36:57] Explicit valence for atom # 33 C greater than permitted
[12:36:57] Explicit valence for atom # 21 C greater than permitted
[12:36:57] Explicit valence for atom # 16 C greater than permitted
[12:36:57] Explicit valence for atom # 30 C greater than permitted
[12:36:57] Explicit valence for atom # 30 C greater than permitted
[12:36:57] Explicit valence for atom # 17 C greater than permitted
[12:36:57] Explicit valence for atom # 49 C greater than permitted
[12:36:57] Explicit valence for atom # 28 C greater than permitted
[12:36:57] Explicit valence for atom # 26 C greater than permitted
[12:36:57] Explicit valence for atom # 25 C greater than permitted

--- Processing cluster 4 ---

[12:37:22] Explicit valence for atom # 14 C, 5, is greater than permitted
[12:37:23] Explicit valence for atom # 21 C greater than permitted
[12:37:23] Explicit valence for atom # 29 C greater than permitted
[12:37:23] Explicit valence for atom # 17 P, 7, is greater than permitted
[12:37:23] Explicit valence for atom # 31 C greater than permitted
[12:37:23] Explicit valence for atom # 24 C greater than permitted
[12:37:23] Explicit valence for atom # 40 C greater than permitted
[12:37:23] Explicit valence for atom # 34 C greater than permitted
[12:37:23] Explicit valence for atom # 20 C greater than permitted
[12:37:23] Explicit valence for atom # 20 C greater than permitted
[12:37:23] Explicit valence for atom # 1 C greater than permitted
[12:37:23] Explicit valence for atom # 21 C greater than permitted
[12:37:23] Explicit valence for atom # 14 C greater than permitted
[12:37:23] Explicit valence for atom # 20 C greater than permitted
[12:37:23] Explicit valence for atom # 22 C greater than permitted
[12:37:23] Explicit valence for atom # 41 C greater than permitted
[12:37:23] Explicit valence for atom # 20 C greater than permitted
[12:37:23] Explicit valence for atom # 26 C greater than permitted
[12:37:23] Explicit valence for atom # 8 C greater than permitted
[12:37:23] Explicit valence for atom # 6 C greater than permitted
[12:37:23] Explicit valence for atom # 19 Si, 5, is greater than permitted
[12:37:23] Explicit valence for atom # 20 C greater than permitted
[12:37:23] Explicit valence for atom # 1 C greater than permitted
[12:37:23] Explicit valence for atom # 23 C greater than permitted
[12:37:23] Explicit valence for atom # 18 C greater than permitted
[12:37:23] Explicit valence for atom # 43 C greater than permitted
[12:37:23] Explicit valence for atom # 28 C greater than permitted
[12:37:23] Explicit valence for atom # 22 Si, 5, is greater than permitted
[12:37:23] Explicit valence for atom # 25 C greater than permitted
[12:37:23] Explicit valence for atom # 19 C greater than permitted
[12:37:23] Explicit valence for atom # 34 C greater than permitted
[12:37:23] Explicit valence for atom # 20 C greater than permitted
[12:37:24] Explicit valence for atom # 31 C greater than permitted
[12:37:24] Explicit valence for atom # 41 Si, 5, is greater than permitted
[12:37:24] Explicit valence for atom # 32 C greater than permitted
[12:37:24] Explicit valence for atom # 47 C greater than permitted
[12:37:24] Explicit valence for atom # 6 C greater than permitted
[12:37:24] Explicit valence for atom # 25 C greater than permitted
[12:37:24] Explicit valence for atom # 30 C greater than permitted
[12:37:24] Explicit valence for atom # 26 P, 7, is greater than permitted
[12:37:24] Explicit valence for atom # 18 P, 7, is greater than permitted
[12:37:24] Explicit valence for atom # 31 C greater than permitted
[12:37:24] Explicit valence for atom # 35 C greater than permitted
[12:37:24] Explicit valence for atom # 18 C greater than permitted
[12:37:24] Explicit valence for atom # 33 C greater than permitted
[12:37:24] Explicit valence for atom # 17 C greater than permitted
[12:37:24] Explicit valence for atom # 8 C, 6, is greater than permitted
[12:37:24] Explicit valence for atom # 26 Si, 5, is greater than permitted
[12:37:24] Explicit valence for atom # 29 C greater than permitted
[12:37:24] Explicit valence for atom # 28 P, 7, is greater than permitted
[12:37:24] Explicit valence for atom # 36 C greater than permitted
[12:37:24] Explicit valence for atom # 19 P, 7, is greater than permitted
[12:37:24] Explicit valence for atom # 39 C greater than permitted
[12:37:24] Explicit valence for atom # 29 C greater than permitted
[12:37:24] Explicit valence for atom # 27 C greater than permitted
[12:37:24] Explicit valence for atom # 30 Si, 5, is greater than permitted
[12:37:24] Explicit valence for atom # 30 C greater than permitted
[12:37:24] Explicit valence for atom # 23 C, 4, is greater than permitted
[12:37:24] Explicit valence for atom # 2 Si, 5, is greater than permitted
[12:37:24] Explicit valence for atom # 23 C greater than permitted
[12:37:24] Explicit valence for atom # 28 C greater than permitted
[12:37:24] Explicit valence for atom # 12 C greater than permitted
[12:37:24] Explicit valence for atom # 40 C greater than permitted
[12:37:24] Explicit valence for atom # 16 C greater than permitted
[12:37:24] Explicit valence for atom # 31 C, 5, is greater than permitted
[12:37:24] Explicit valence for atom # 23 C greater than permitted
[12:37:24] Explicit valence for atom # 19 P, 6, is greater than permitted
[12:37:24] Explicit valence for atom # 24 C, 5, is greater than permitted
[12:37:24] Explicit valence for atom # 8 Si, 5, is greater than permitted
[12:37:24] Explicit valence for atom # 35 C greater than permitted
[12:37:24] Explicit valence for atom # 5 Si, 5, is greater than permitted
[12:37:24] Explicit valence for atom # 40 Si, 5, is greater than permitted
[12:37:24] Explicit valence for atom # 13 Si, 5, is greater than permitted
[12:37:24] Explicit valence for atom # 40 C greater than permitted
[12:37:24] Explicit valence for atom # 5 C greater than permitted
[12:37:24] Explicit valence for atom # 32 C greater than permitted
[12:37:24] Explicit valence for atom # 31 C greater than permitted
[12:37:24] Explicit valence for atom # 24 C greater than permitted
[12:37:24] Explicit valence for atom # 15 C, 5, is greater than permitted
[12:37:24] Explicit valence for atom # 21 C greater than permitted
[12:37:24] Explicit valence for atom # 21 C greater than permitted
[12:37:24] Explicit valence for atom # 23 C greater than permitted
[12:37:25] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:37:25] Explicit valence for atom # 39 C greater than permitted
[12:37:25] Explicit valence for atom # 17 C greater than permitted
[12:37:25] Explicit valence for atom # 25 C greater than permitted
[12:37:25] Explicit valence for atom # 25 C greater than permitted
[12:37:25] Explicit valence for atom # 39 C greater than permitted
[12:37:25] Explicit valence for atom # 3 C greater than permitted
[12:37:25] Explicit valence for atom # 19 C greater than permitted
[12:37:25] Explicit valence for atom # 16 C greater than permitted
[12:37:25] Explicit valence for atom # 20 C greater than permitted
[12:37:25] Explicit valence for atom # 12 C greater than permitted
[12:37:25] Explicit valence for atom # 19 C greater than permitted
[12:37:25] Explicit valence for atom # 23 C greater than permitted
[12:37:25] Explicit valence for atom # 35 C greater than permitted
[12:37:25] Explicit valence for atom # 13 C greater than permitted
[12:37:25] Explicit valence for atom # 25 C greater than permitted
[12:37:25] Explicit valence for atom # 28 C greater than permitted
[12:37:25] Explicit valence for atom # 15 C greater than permitted
[12:37:25] Explicit valence for atom # 25 C greater than permitted
[12:37:25] Explicit valence for atom # 26 C greater than permitted
[12:37:25] Explicit valence for atom # 30 C greater than permitted
[12:37:25] Explicit valence for atom # 21 C greater than permitted
[12:37:25] Explicit valence for atom # 22 Si, 5, is greater than permitted
[12:37:25] Explicit valence for atom # 30 C greater than permitted
[12:37:25] Explicit valence for atom # 35 C greater than permitted
[12:37:25] Explicit valence for atom # 10 C greater than permitted
[12:37:25] Explicit valence for atom # 37 C greater than permitted
[12:37:25] Explicit valence for atom # 24 C greater than permitted
[12:37:25] Explicit valence for atom # 31 C greater than permitted
[12:37:25] Explicit valence for atom # 21 C greater than permitted
[12:37:25] Explicit valence for atom # 30 C greater than permitted
[12:37:25] Explicit valence for atom # 29 C greater than permitted
[12:37:25] Explicit valence for atom # 12 Si, 5, is greater than permitted
[12:37:25] Explicit valence for atom # 3 Si, 5, is greater than permitted
[12:37:25] Explicit valence for atom # 34 C greater than permitted
[12:37:25] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:37:25] Explicit valence for atom # 31 C greater than permitted
[12:37:25] Explicit valence for atom # 7 C greater than permitted
[12:37:25] Explicit valence for atom # 17 C greater than permitted
[12:37:25] Explicit valence for atom # 22 C greater than permitted
[12:37:25] Explicit valence for atom # 24 C greater than permitted
[12:37:25] Explicit valence for atom # 10 C greater than permitted
[12:37:25] Explicit valence for atom # 27 P, 7, is greater than permitted
[12:37:25] Explicit valence for atom # 28 C greater than permitted
[12:37:25] Explicit valence for atom # 30 C, 5, is greater than permitted
[12:37:25] Explicit valence for atom # 20 C greater than permitted
[12:37:25] Explicit valence for atom # 14 C greater than permitted
[12:37:25] Explicit valence for atom # 45 C greater than permitted
[12:37:25] Explicit valence for atom # 27 C greater than permitted
[12:37:25] Explicit valence for atom # 31 Si, 5, is greater than permitted
[12:37:25] Explicit valence for atom # 34 C greater than permitted
[12:37:25] Explicit valence for atom # 19 C greater than permitted
[12:37:25] Explicit valence for atom # 26 P, 7, is greater than permitted
[12:37:25] Explicit valence for atom # 26 C greater than permitted
[12:37:25] Explicit valence for atom # 27 C greater than permitted
[12:37:25] Explicit valence for atom # 28 C greater than permitted
[12:37:26] Explicit valence for atom # 29 C greater than permitted
[12:37:26] Explicit valence for atom # 15 C, 5, is greater than permitted
[12:37:26] Explicit valence for atom # 21 C greater than permitted
[12:37:26] Explicit valence for atom # 19 P, 7, is greater than permitted
[12:37:26] Explicit valence for atom # 28 C greater than permitted
[12:37:26] Explicit valence for atom # 12 C, 6, is greater than permitted
[12:37:26] Explicit valence for atom # 31 C greater than permitted
[12:37:26] Explicit valence for atom # 26 C greater than permitted
[12:37:26] Explicit valence for atom # 38 C greater than permitted
[12:37:26] Explicit valence for atom # 22 C greater than permitted
[12:37:26] Explicit valence for atom # 31 C greater than permitted
[12:37:26] Explicit valence for atom # 21 C greater than permitted
[12:37:26] Explicit valence for atom # 31 C greater than permitted
[12:37:26] Explicit valence for atom # 18 C greater than permitted
[12:37:26] Explicit valence for atom # 13 C greater than permitted
[12:37:26] Explicit valence for atom # 32 C greater than permitted
[12:37:26] Explicit valence for atom # 31 C greater than permitted
[12:37:26] Explicit valence for atom # 26 C greater than permitted
[12:37:26] Explicit valence for atom # 20 Si, 5, is greater than permitted
[12:37:26] Explicit valence for atom # 20 C greater than permitted
[12:37:26] Explicit valence for atom # 27 C greater than permitted
[12:37:26] Explicit valence for atom # 30 C greater than permitted
[12:37:26] Explicit valence for atom # 29 C greater than permitted
[12:37:26] Explicit valence for atom # 13 C greater than permitted
[12:37:26] Explicit valence for atom # 30 C greater than permitted
[12:37:26] Explicit valence for atom # 18 C greater than permitted
[12:37:26] Explicit valence for atom # 26 C greater than permitted
[12:37:26] Explicit valence for atom # 45 C greater than permitted
[12:37:26] Explicit valence for atom # 24 C greater than permitted
[12:37:26] Explicit valence for atom # 18 C greater than permitted
[12:37:26] Explicit valence for atom # 26 C greater than permitted
[12:37:26] Explicit valence for atom # 36 C greater than permitted
[12:37:26] Explicit valence for atom # 34 C greater than permitted
[12:37:26] Explicit valence for atom # 30 C greater than permitted
[12:37:26] Explicit valence for atom # 12 C, 6, is greater than permitted
[12:37:26] Explicit valence for atom # 37 C, 5, is greater than permitted
[12:37:26] Explicit valence for atom # 21 C greater than permitted
[12:37:26] Explicit valence for atom # 30 C greater than permitted
[12:37:26] Explicit valence for atom # 25 C greater than permitted
[12:37:26] Explicit valence for atom # 22 C greater than permitted
[12:37:26] Explicit valence for atom # 18 C greater than permitted
[12:37:26] Explicit valence for atom # 1 C greater than permitted
[12:37:26] Explicit valence for atom # 31 P, 7, is greater than permitted
[12:37:26] Explicit valence for atom # 31 C, 5, is greater than permitted
[12:37:26] Explicit valence for atom # 13 C greater than permitted
[12:37:26] Explicit valence for atom # 18 Si, 5, is greater than permitted
[12:37:26] Explicit valence for atom # 20 Si, 5, is greater than permitted
[12:37:26] Explicit valence for atom # 36 C greater than permitted
[12:37:26] Explicit valence for atom # 44 Si, 5, is greater than permitted
[12:37:26] Explicit valence for atom # 22 C, 5, is greater than permitted
[12:37:26] Explicit valence for atom # 18 C greater than permitted
[12:37:26] Explicit valence for atom # 16 C, 5, is greater than permitted
[12:37:26] Explicit valence for atom # 23 Si, 5, is greater than permitted
[12:37:26] Explicit valence for atom # 18 C greater than permitted
[12:37:26] Explicit valence for atom # 17 C greater than permitted
[12:37:26] Explicit valence for atom # 33 C greater than permitted
[12:37:26] Explicit valence for atom # 32 Si, 5, is greater than permitted
[12:37:26] Explicit valence for atom # 17 P, 7, is greater than permitted
[12:37:26] Explicit valence for atom # 25 C greater than permitted
[12:37:26] Explicit valence for atom # 4 C greater than permitted
[12:37:26] Explicit valence for atom # 42 C greater than permitted
[12:37:26] Explicit valence for atom # 42 C greater than permitted
[12:37:26] Explicit valence for atom # 30 C greater than permitted
[12:37:27] Explicit valence for atom # 26 C greater than permitted
[12:37:27] Explicit valence for atom # 32 C greater than permitted
[12:37:27] Explicit valence for atom # 7 C greater than permitted
[12:37:27] Explicit valence for atom # 34 C greater than permitted
[12:37:27] Explicit valence for atom # 29 P, 7, is greater than permitted
[12:37:27] Explicit valence for atom # 22 C greater than permitted
[12:37:27] Explicit valence for atom # 35 C greater than permitted
[12:37:27] Explicit valence for atom # 31 C greater than permitted
[12:37:27] Explicit valence for atom # 15 C greater than permitted
[12:37:27] Explicit valence for atom # 30 C greater than permitted
[12:37:27] Explicit valence for atom # 35 C greater than permitted
[12:37:27] Explicit valence for atom # 19 C greater than permitted
[12:37:27] Explicit valence for atom # 44 C greater than permitted
[12:37:27] Explicit valence for atom # 6 P, 6, is greater than permitted
[12:37:27] Explicit valence for atom # 30 Si, 6, is greater than permitted
[12:37:27] Explicit valence for atom # 20 C greater than permitted
[12:37:27] Explicit valence for atom # 6 C greater than permitted
[12:37:27] Explicit valence for atom # 24 C greater than permitted
[12:37:27] Explicit valence for atom # 26 C greater than permitted
[12:37:27] Explicit valence for atom # 21 C greater than permitted
[12:37:27] Explicit valence for atom # 26 C greater than permitted
[12:37:27] Explicit valence for atom # 6 C greater than permitted
[12:37:27] Explicit valence for atom # 24 C greater than permitted
[12:37:27] Explicit valence for atom # 15 Si, 6, is greater than permitted
[12:37:27] Explicit valence for atom # 22 C, 6, is greater than permitted
[12:37:27] Explicit valence for atom # 15 C greater than permitted
[12:37:27] Explicit valence for atom # 25 C greater than permitted
[12:37:27] Explicit valence for atom # 13 C greater than permitted
[12:37:27] Explicit valence for atom # 25 C greater than permitted
[12:37:27] Explicit valence for atom # 23 C greater than permitted
[12:37:27] Explicit valence for atom # 39 C greater than permitted
[12:37:27] Explicit valence for atom # 27 C greater than permitted
[12:37:27] Explicit valence for atom # 29 C greater than permitted
[12:37:27] Explicit valence for atom # 15 C greater than permitted
[12:37:27] Explicit valence for atom # 31 C greater than permitted
[12:37:27] Explicit valence for atom # 2 P, 7, is greater than permitted
[12:37:27] Explicit valence for atom # 20 C greater than permitted
[12:37:27] Explicit valence for atom # 31 C greater than permitted
[12:37:27] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:37:27] Explicit valence for atom # 22 Si, 5, is greater than permitted
[12:37:27] Explicit valence for atom # 27 C greater than permitted
[12:37:27] Explicit valence for atom # 23 C greater than permitted
[12:37:27] Explicit valence for atom # 9 C, 5, is greater than permitted
[12:37:27] Explicit valence for atom # 22 C greater than permitted
[12:37:27] Explicit valence for atom # 26 C greater than permitted
[12:37:27] Explicit valence for atom # 29 C greater than permitted
[12:37:27] Explicit valence for atom # 22 C greater than permitted
[12:37:27] Explicit valence for atom # 34 C greater than permitted
[12:37:27] Explicit valence for atom # 30 C greater than permitted
[12:37:27] Explicit valence for atom # 26 C greater than permitted
[12:37:27] Explicit valence for atom # 19 C greater than permitted
[12:37:27] Explicit valence for atom # 35 C greater than permitted
[12:37:27] Explicit valence for atom # 21 C greater than permitted
[12:37:27] Explicit valence for atom # 19 C greater than permitted
[12:37:27] Explicit valence for atom # 28 C greater than permitted
[12:37:28] Explicit valence for atom # 28 C greater than permitted
[12:37:28] Explicit valence for atom # 4 C, 5, is greater than permitted
[12:37:28] Explicit valence for atom # 35 C greater than permitted
[12:37:28] Explicit valence for atom # 19 C greater than permitted
[12:37:28] Explicit valence for atom # 28 C greater than permitted
[12:37:28] Explicit valence for atom # 23 C greater than permitted
[12:37:28] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:37:28] Explicit valence for atom # 30 C greater than permitted
[12:37:28] Explicit valence for atom # 28 C greater than permitted
[12:37:28] Explicit valence for atom # 18 C greater than permitted
[12:37:28] Explicit valence for atom # 24 C greater than permitted
[12:37:28] Explicit valence for atom # 39 C greater than permitted
[12:37:28] Explicit valence for atom # 20 C greater than permitted
[12:37:28] Explicit valence for atom # 9 C greater than permitted
[12:37:28] Explicit valence for atom # 14 C, 5, is greater than permitted
[12:37:28] Explicit valence for atom # 35 C greater than permitted
[12:37:28] Explicit valence for atom # 31 C greater than permitted
[12:37:28] Explicit valence for atom # 17 C greater than permitted
[12:37:28] Explicit valence for atom # 20 C greater than permitted
[12:37:28] Explicit valence for atom # 24 C, 5, is greater than permitted
[12:37:28] Explicit valence for atom # 29 C greater than permitted
[12:37:28] Explicit valence for atom # 25 Si, 5, is greater than permitted
[12:37:28] Explicit valence for atom # 41 C greater than permitted
[12:37:28] Explicit valence for atom # 26 C greater than permitted
[12:37:28] Explicit valence for atom # 17 C greater than permitted
[12:37:28] Explicit valence for atom # 27 C greater than permitted
[12:37:28] Explicit valence for atom # 31 C greater than permitted
[12:37:28] Explicit valence for atom # 8 C greater than permitted
[12:37:28] Explicit valence for atom # 21 C greater than permitted
[12:37:28] Explicit valence for atom # 39 C greater than permitted
[12:37:28] Explicit valence for atom # 17 C greater than permitted
[12:37:28] Explicit valence for atom # 21 C greater than permitted
[12:37:28] Explicit valence for atom # 19 C greater than permitted
[12:37:28] Explicit valence for atom # 35 C greater than permitted
[12:37:28] Explicit valence for atom # 36 C greater than permitted
[12:37:28] Explicit valence for atom # 30 C greater than permitted

Calculation complete! Processed 5 clusters

,name,type_cluster,scaffold,RS,SED,ASER
0,DrugEx_RNN_epsilon_0.6_500k_0,dis,csk,0.425000,0.101512,0.007305
1,DrugEx_RNN_epsilon_0.6_500k_1,dis,csk,0.695652,0.091967,0.002425
2,DrugEx_RNN_epsilon_0.6_500k_2,dis,csk,0.225000,0.106427,0.000452
3,DrugEx_RNN_epsilon_0.6_500k_3,dis,csk,0.675676,0.120726,0.016558
4,DrugEx_RNN_epsilon_0.6_500k_4,dis,csk,0.883721,0.153829,0.061030
5,DrugEx_RNN_epsilon_0.6_500k_mean,dis,csk,0.581010,0.114892,0.017554

GB_GA_mut_r_0.01_500k

============================================================
Starting calculation for GB_GA_mut_r_0.01_500k
Receptor: Glucocorticoid_receptor
Cluster type: dis
Scaffold type: csk
CPUs: 100
============================================================

--- Processing cluster 0 ---

--- Processing cluster 1 ---

--- Processing cluster 2 ---

--- Processing cluster 3 ---

--- Processing cluster 4 ---

[12:40:14] Explicit valence for atom # 1 P, 7, is greater than permitted

Calculation complete! Processed 5 clusters

,name,type_cluster,scaffold,RS,SED,ASER
0,GB_GA_mut_r_0.01_500k_0,dis,csk,0.675000,0.073186,0.011313
1,GB_GA_mut_r_0.01_500k_1,dis,csk,0.695652,0.068559,0.002060
2,GB_GA_mut_r_0.01_500k_2,dis,csk,0.575000,0.077147,0.002164
3,GB_GA_mut_r_0.01_500k_3,dis,csk,0.621622,0.067663,0.028089
4,GB_GA_mut_r_0.01_500k_4,dis,csk,0.790698,0.070058,0.034716
5,GB_GA_mut_r_0.01_500k_mean,dis,csk,0.671594,0.071323,0.015668

GB_GA_mut_r_0.5_500k

============================================================
Starting calculation for GB_GA_mut_r_0.5_500k
Receptor: Glucocorticoid_receptor
Cluster type: dis
Scaffold type: csk
CPUs: 100
============================================================

--- Processing cluster 0 ---

[12:40:41] Explicit valence for atom # 5 C, 5, is greater than permitted
[12:40:42] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:43] Explicit valence for atom # 15 C, 5, is greater than permitted
[12:40:43] Explicit valence for atom # 8 C, 5, is greater than permitted
[12:40:43] Explicit valence for atom # 13 C, 5, is greater than permitted
[12:40:44] Explicit valence for atom # 26 C, 5, is greater than permitted
[12:40:44] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:40:44] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:40:45] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:40:45] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:40:46] Explicit valence for atom # 20 C, 5, is greater than permitted
[12:40:46] Explicit valence for atom # 5 C, 5, is greater than permitted
[12:40:46] Explicit valence for atom # 9 C, 5, is greater than permitted
[12:40:47] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:40:47] Explicit valence for atom # 12 C, 5, is greater than permitted
[12:40:48] Explicit valence for atom # 4 C, 5, is greater than permitted
[12:40:48] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:40:48] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:40:48] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:40:48] Explicit valence for atom # 4 C, 5, is greater than permitted
[12:40:48] Explicit valence for atom # 5 C, 5, is greater than permitted
[12:40:48] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:40:49] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:40:49] Explicit valence for atom # 4 C, 5, is greater than permitted
[12:40:49] Explicit valence for atom # 16 C, 5, is greater than permitted
[12:40:50] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:40:50] Explicit valence for atom # 7 C, 5, is greater than permitted
[12:40:50] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:40:51] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:40:51] Explicit valence for atom # 8 C, 5, is greater than permitted
[12:40:52] Explicit valence for atom # 1 C, 5, is greater than permitted

--- Processing cluster 1 ---

[12:41:14] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:14] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:41:17] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:17] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:41:18] Explicit valence for atom # 29 C, 5, is greater than permitted
[12:41:20] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:41:20] Explicit valence for atom # 25 C, 5, is greater than permitted
[12:41:21] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:21] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:41:22] Explicit valence for atom # 11 C, 5, is greater than permitted
[12:41:22] Explicit valence for atom # 19 C, 5, is greater than permitted
[12:41:23] Explicit valence for atom # 3 C, 5, is greater than permitted

--- Processing cluster 2 ---

[12:41:45] Explicit valence for atom # 15 C, 5, is greater than permitted
[12:41:47] Explicit valence for atom # 16 C, 5, is greater than permitted
[12:41:48] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:41:48] Explicit valence for atom # 5 C, 5, is greater than permitted
[12:41:50] Explicit valence for atom # 12 C, 5, is greater than permitted
[12:41:50] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:41:50] Explicit valence for atom # 22 C, 5, is greater than permitted
[12:41:51] Explicit valence for atom # 12 C, 5, is greater than permitted
[12:41:51] Explicit valence for atom # 8 C, 5, is greater than permitted
[12:41:52] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:41:53] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:41:53] Explicit valence for atom # 10 C, 5, is greater than permitted
[12:41:54] Explicit valence for atom # 15 C, 5, is greater than permitted
[12:41:55] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:41:57] Explicit valence for atom # 12 C, 5, is greater than permitted

--- Processing cluster 3 ---

[12:42:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:42:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:42:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:42:18] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:42:19] Explicit valence for atom # 10 C, 5, is greater than permitted
[12:42:19] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:42:22] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:42:22] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:42:24] Explicit valence for atom # 12 C, 5, is greater than permitted
[12:42:24] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:42:25] Explicit valence for atom # 5 C, 5, is greater than permitted
[12:42:26] Explicit valence for atom # 12 C, 5, is greater than permitted
[12:42:26] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:42:27] Explicit valence for atom # 30 C, 5, is greater than permitted
[12:42:29] Explicit valence for atom # 1 P, 7, is greater than permitted

--- Processing cluster 4 ---

[12:42:48] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:42:49] Explicit valence for atom # 4 C, 5, is greater than permitted
[12:42:49] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:42:50] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:42:50] Explicit valence for atom # 10 C, 5, is greater than permitted
[12:42:50] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:42:50] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:42:51] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:42:52] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:42:52] Explicit valence for atom # 4 C, 5, is greater than permitted
[12:42:53] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:42:55] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:42:56] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:42:56] Explicit valence for atom # 11 C, 5, is greater than permitted
[12:42:57] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:42:57] Explicit valence for atom # 1 P, 7, is greater than permitted
[12:42:58] Explicit valence for atom # 4 C, 5, is greater than permitted
[12:42:59] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:43:00] Explicit valence for atom # 1 P, 7, is greater than permitted

Calculation complete! Processed 5 clusters

,name,type_cluster,scaffold,RS,SED,ASER
0,GB_GA_mut_r_0.5_500k_0,dis,csk,0.800000,0.058827,0.018454
1,GB_GA_mut_r_0.5_500k_1,dis,csk,0.782609,0.057930,0.001565
2,GB_GA_mut_r_0.5_500k_2,dis,csk,0.600000,0.062197,0.002337
3,GB_GA_mut_r_0.5_500k_3,dis,csk,0.675676,0.055172,0.032322
4,GB_GA_mut_r_0.5_500k_4,dis,csk,0.837209,0.059513,0.023228
5,GB_GA_mut_r_0.5_500k_mean,dis,csk,0.739099,0.058728,0.015581

GB_GA_log_p_mut_r_0.01_500k

============================================================
Starting calculation for GB_GA_log_p_mut_r_0.01_500k
Receptor: Glucocorticoid_receptor
Cluster type: dis
Scaffold type: csk
CPUs: 100
============================================================

--- Processing cluster 0 ---

--- Processing cluster 1 ---

--- Processing cluster 2 ---

--- Processing cluster 3 ---

--- Processing cluster 4 ---
Calculation complete! Processed 5 clusters

,name,type_cluster,scaffold,RS,SED,ASER
0,GB_GA_log_p_mut_r_0.01_500k_0,dis,csk,0.300000,0.191441,0.001584
1,GB_GA_log_p_mut_r_0.01_500k_1,dis,csk,0.608696,0.183057,0.001554
2,GB_GA_log_p_mut_r_0.01_500k_2,dis,csk,0.300000,0.207543,0.000894
3,GB_GA_log_p_mut_r_0.01_500k_3,dis,csk,0.432432,0.198284,0.002186
4,GB_GA_log_p_mut_r_0.01_500k_4,dis,csk,0.697674,0.207906,0.009384
5,GB_GA_log_p_mut_r_0.01_500k_mean,dis,csk,0.467761,0.197646,0.003121

GB_GA_log_p_mut_r_0.5_500k

============================================================
Starting calculation for GB_GA_log_p_mut_r_0.5_500k
Receptor: Glucocorticoid_receptor
Cluster type: dis
Scaffold type: csk
CPUs: 100
============================================================

--- Processing cluster 0 ---

[12:46:27] Explicit valence for atom # 31 C, 5, is greater than permitted
[12:46:33] Explicit valence for atom # 23 C, 5, is greater than permitted

--- Processing cluster 1 ---

[12:46:59] Explicit valence for atom # 19 C, 5, is greater than permitted

--- Processing cluster 2 ---

[12:47:35] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:47:35] Explicit valence for atom # 11 C, 5, is greater than permitted
[12:47:41] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:47:41] Explicit valence for atom # 31 C, 5, is greater than permitted

--- Processing cluster 3 ---

[12:48:12] Explicit valence for atom # 2 C, 5, is greater than permitted

--- Processing cluster 4 ---

[12:48:55] Explicit valence for atom # 7 C, 5, is greater than permitted
[12:48:58] Explicit valence for atom # 2 C, 5, is greater than permitted

Calculation complete! Processed 5 clusters

,name,type_cluster,scaffold,RS,SED,ASER
0,GB_GA_log_p_mut_r_0.5_500k_0,dis,csk,0.325000,0.142398,0.010644
1,GB_GA_log_p_mut_r_0.5_500k_1,dis,csk,0.434783,0.141502,0.001684
2,GB_GA_log_p_mut_r_0.5_500k_2,dis,csk,0.275000,0.166585,0.000774
3,GB_GA_log_p_mut_r_0.5_500k_3,dis,csk,0.378378,0.139512,0.002482
4,GB_GA_log_p_mut_r_0.5_500k_4,dis,csk,0.674419,0.137170,0.005834
5,GB_GA_log_p_mut_r_0.5_500k_mean,dis,csk,0.417516,0.145433,0.004284

addcarbon_500k

============================================================
Starting calculation for addcarbon_500k
Receptor: Glucocorticoid_receptor
Cluster type: dis
Scaffold type: csk
CPUs: 100
============================================================

--- Processing cluster 0 ---

--- Processing cluster 1 ---

--- Processing cluster 2 ---

--- Processing cluster 3 ---

--- Processing cluster 4 ---
Calculation complete! Processed 5 clusters

                  name type_cluster scaffold        RS       SED      ASER
0     addcarbon_500k_0          dis      csk  0.050000  0.001532  0.001832
1     addcarbon_500k_1          dis      csk  0.043478  0.001884  0.003634
2     addcarbon_500k_2          dis      csk  0.000000  0.001516  0.000000
3     addcarbon_500k_3          dis      csk  0.027027  0.001774  0.000400
4     addcarbon_500k_4          dis      csk  0.046512  0.001862  0.003488
5  addcarbon_500k_mean          dis      csk  0.033403  0.001714  0.001871

Molpher_250k

============================================================
Starting calculation for Molpher_250k
Receptor: Glucocorticoid_receptor
Cluster type: dis
Scaffold type: csk
CPUs: 100
============================================================

--- Processing cluster 0 ---

--- Processing cluster 1 ---

--- Processing cluster 2 ---

[12:53:03] Explicit valence for atom # 12 C, 5, is greater than permitted
[12:53:03] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:53:03] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:53:03] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:53:03] Explicit valence for atom # 4 C, 5, is greater than permitted
[12:53:05] Explicit valence for atom # 9 C, 5, is greater than permitted

--- Processing cluster 3 ---

[12:53:26] Explicit valence for atom # 18 C, 5, is greater than permitted

--- Processing cluster 4 ---
Calculation complete! Processed 5 clusters

                name type_cluster scaffold        RS       SED      ASER
0     Molpher_250k_0          dis      csk  0.275000  0.150588  0.005155
1     Molpher_250k_1          dis      csk  0.391304  0.142650  0.001006
2     Molpher_250k_2          dis      csk  0.175000  0.148006  0.000144
3     Molpher_250k_3          dis      csk  0.378378  0.157444  0.006094
4     Molpher_250k_4          dis      csk  0.767442  0.169550  0.012522
5  Molpher_250k_mean          dis      csk  0.397425  0.153648  0.004984

REINVENT_250k

============================================================
Starting calculation for REINVENT_250k
Receptor: Glucocorticoid_receptor
Cluster type: dis
Scaffold type: csk
CPUs: 100
============================================================

--- Processing cluster 0 ---

[12:54:08] Can't kekulize mol.  Unkekulized atoms: 29 31 32 33 42 43 44
[12:54:08] Can't kekulize mol.  Unkekulized atoms: 29 30 31 32 33 34 35 39 40
[12:54:08] Can't kekulize mol.  Unkekulized atoms: 30 31 32 33 34 35 37 38 42 43 44
[12:54:08] Can't kekulize mol.  Unkekulized atoms: 27 28 29 30 31 33 39 40 41
[12:54:08] Can't kekulize mol.  Unkekulized atoms: 17 18 19 20 21 22 23 32 33
[12:54:08] Can't kekulize mol.  Unkekulized atoms: 5 6 7 9 10 11 24
[12:54:08] SMILES Parse Error: unclosed ring for input: 'CC(NC(c1ccc2c(c1)CCCO2)=O)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1n(CCF)c2cccc(OC3CCC4)c3c2C1'
[12:54:08] Can't kekulize mol.  Unkekulized atoms: 31 33 34 35 36 44 45 46
[12:54:08] SMILES Parse Error: extra close parentheses while parsing: CC(C)C(CC(O)(Cc1cc2nc(C)oc2cc1)C(F)(F)F)C(C)N)(F)F
[12:54:08] SMILES Parse Error: check for mistakes around position 46:
[12:54:08] c2cc1)C(F)(F)F)C(C)N)(F)F
[12:54:08] Can't kekulize mol.  Unkekulized atoms: 34 35 36 37 42 43 44 45 46
[12:54:08] ~~~~~~~~~~~~~~~~~~~~^
[12:54:08] Can't kekulize mol.  Unkekulized atoms: 34 35 36 38 40 41 51 52 53
[12:54:08] SMILES Parse Error: Failed parsing SMILES 'CC(C)C(CC(O)(Cc1cc2nc(C)oc2cc1)C(F)(F)F)C(C)N)(F)F' for input: 'CC(C)C(CC(O)(Cc1cc2nc(C)oc2cc1)C(F)(F)F)C(C)N)(F)F'
[12:54:08] Can't kekulize mol.  Unkekulized atoms: 29 31 32 33 42 43 44
[12:54:08] Can't kekulize mol.  Unkekulized atoms: 30 32 33 34 41 42 50 51 52
[12:54:08] Can't kekulize mol.  Unkekulized atoms: 35 36 37 38 39 40 41 42 43
[12:54:08] Can't kekulize mol.  Unkekulized atoms: 28 29 30 32 33 34 36
[12:54:08] Can't kekulize mol.  Unkekulized atoms: 33 34 35 36 37 38 39 43 44
[12:54:08] Can't kekulize mol.  Unkekulized atoms: 26 27 28 29 30 34 37 38
[12:54:08] SMILES Parse Error: unclosed ring for input: 'CC(NC(c1nccnc1)=O)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1csc2c1nnn(-c1ccc(F)c(Cl)c1)c1=N2'
[12:54:08] Explicit valence for atom # 35 C, 5, is greater than permitted
[12:54:08] Can't kekulize mol.  Unkekulized atoms: 29 30 31 32 33 34 35 36 42
[12:54:08] Can't kekulize mol.  Unkekulized atoms: 31 33 34 35 48 49 50 51 52
[12:54:08] Can't kekulize mol.  Unkekulized atoms: 28 29 30 31 32 33 34 35 36 38 39
[12:54:08] Can't kekulize mol.  Unkekulized atoms: 32 33 34 36 38 39 40 41 42
[12:54:08] Can't kekulize mol.  Unkekulized atoms: 27 29 30 31 32 33 34 43
[12:54:08] Can't kekulize mol.  Unkekulized atoms: 6 7 8 9 11 12 13 14 15
[12:54:08] Can't kekulize mol.  Unkekulized atoms: 6 9
[12:54:08] Can't kekulize mol.  Unkekulized atoms: 17 18 19
[12:54:08] Can't kekulize mol.  Unkekulized atoms: 4 5 6 7 8 9 29
[12:54:08] Can't kekulize mol.  Unkekulized atoms: 6 8 11
[12:54:08] Can't kekulize mol.  Unkekulized atoms: 32 33 34 35 36 37 38 39 40
[12:54:08] Can't kekulize mol.  Unkekulized atoms: 19 20 21 22 23 24 25 33 34
[12:54:08] Can't kekulize mol.  Unkekulized atoms: 38 39 44
[12:54:08] Can't kekulize mol.  Unkekulized atoms: 4 5 6 7 8 9 10 13 14
[12:54:08] Can't kekulize mol.  Unkekulized atoms: 30 31 32 36 37
[12:54:08] SMILES Parse Error: unclosed ring for input: 'CC(NC(=O)c1cnn(C(F)F)c1)C(Oc2ccc2c(cnn2-c3ccc(F)cc3)cc2C1)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1ccccn1'
[12:54:08] Can't kekulize mol.  Unkekulized atoms: 5 6 7 8 17 18 19 20 21
[12:54:08] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:54:08] Can't kekulize mol.  Unkekulized atoms: 4 6 7 9 10 11 12
[12:54:08] Can't kekulize mol.  Unkekulized atoms: 33 34 35 36 37 38 39 40 41
[12:54:08] SMILES Parse Error: unclosed ring for input: 'CC(NC(c1sc(C)nc1)=O)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1cc(F)c2c(cnn2-c2ccs3)cc2c1'
[12:54:08] Can't kekulize mol.  Unkekulized atoms: 4 6 7 8 9 11
[12:54:08] Can't kekulize mol.  Unkekulized atoms: 34 35 36 37 38 39 46 47 48 50 51
[12:54:08] SMILES Parse Error: unclosed ring for input: 'CC(NC(COc1cccc(F)c1)=O)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c2ccc2c(O)oc1'
[12:54:08] Can't kekulize mol.  Unkekulized atoms: 14 15 16 17 18 19 23 24 34 35 36
[12:54:08] Can't kekulize mol.  Unkekulized atoms: 27 30 31 32 37 38
[12:54:08] Can't kekulize mol.  Unkekulized atoms: 29 30 31 32 33 34 35 36 38
[12:54:08] Can't kekulize mol.  Unkekulized atoms: 14 15 16 17 18 30 34
[12:54:08] Can't kekulize mol.  Unkekulized atoms: 5 6 7 8 10 11 13
[12:54:08] SMILES Parse Error: ring closure 1 duplicates bond between atom 1 and atom 2 for input: 'oc1-c1ccc2c(c(C(C)=O)cn2CC(C)C)c1C#N'
[12:54:08] Can't kekulize mol.  Unkekulized atoms: 29 31 32 33 34 35
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 33 35 36 37 38 39
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 8 9 10 11 12 22 23 25 32
[12:54:09] Explicit valence for atom # 34 S, 6, is greater than permitted
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 33 34 35 36 38 39 40 41 44
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 5 6 7 15 16 17 19
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 31 32 34 35 36 44
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 35 36 37 38 40 42 44 45 46
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 30 32 33 34 37 38
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 30 31 32 34 36 37 40
[12:54:09] SMILES Parse Error: unclosed ring for input: 'COc1c(O)ccc2ccc3c4c(c(Nc5cccc6cnccc65)cc(O)c4O)cc4c(O)c5c6c(c(c1)c43)c6c(c25)OCO5'
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 31 33 34 35 36 37 38 39 40
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 13 14 15 16 17 18 19 30 31
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 30 32 33 34 43 44 45
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 31 32 33 34 35 36 37 38 39 40 41 42 43
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 31 32 33 35 36 37 38 47 48
[12:54:09] SMILES Parse Error: unclosed ring for input: 'CC(NC(=O)c1cnn(CC)c1Cl)C(Oc1ccc2c(cnn2-c2ccncc2)c1)c1cc2c(C)noc3c(Cl)cc2c1'
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 36 37 38 39 40
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 36 38 39 40 41 42
[12:54:09] SMILES Parse Error: extra close parentheses while parsing: CC(NC(=O)C1CC[S+]([O-])CC1)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1cc2c(n(C)c3c2CCCCCC3)cc1)(O)C(F)(F)F
[12:54:09] SMILES Parse Error: check for mistakes around position 85:
[12:54:09] (n(C)c3c2CCCCCC3)cc1)(O)C(F)(F)F
[12:54:09] ~~~~~~~~~~~~~~~~~~~~^
[12:54:09] SMILES Parse Error: Failed parsing SMILES 'CC(NC(=O)C1CC[S+]([O-])CC1)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1cc2c(n(C)c3c2CCCCCC3)cc1)(O)C(F)(F)F' for input: 'CC(NC(=O)C1CC[S+]([O-])CC1)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1cc2c(n(C)c3c2CCCCCC3)cc1)(O)C(F)(F)F'
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 30 31 32 33 34 35 39 40 41 44 45
[12:54:09] SMILES Parse Error: unclosed ring for input: 'CC(NC(=O)c1cscn1)C(Oc1ccc2c(cnn2-c2ccc3oc(=O)[nH]c3c2)c1)c1ccc2c(c1)OCC1C(CC)O2'
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 32 34 35 42 43 44
[12:54:09] Explicit valence for atom # 2 N, 4, is greater than permitted
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 3 4 6 7 9 10 11 12 13 23 24 25 26 27 28 29 30 31 32 37 38
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 5 7 8 10 11 12
[12:54:09] Explicit valence for atom # 36 S, 7, is greater than permitted
[12:54:09] SMILES Parse Error: extra close parentheses while parsing: CC(N)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1cc2c(c(F)c1)OCCN2C1CCC1)(C)C
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 31 32 33 35 36 37
[12:54:09] SMILES Parse Error: check for mistakes around position 62:
[12:54:09] c(c(F)c1)OCCN2C1CCC1)(C)C
[12:54:09] ~~~~~~~~~~~~~~~~~~~~^
[12:54:09] SMILES Parse Error: Failed parsing SMILES 'CC(N)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1cc2c(c(F)c1)OCCN2C1CCC1)(C)C' for input: 'CC(N)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1cc2c(c(F)c1)OCCN2C1CCC1)(C)C'
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 6 7 8 9 10 11 12
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 29 31 32 33 35 36 39
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 30 32 33 35 36 44 46
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 29 30 31 33 34 35 38
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 5 7 8
[12:54:09] SMILES Parse Error: unclosed ring for input: 'CC(NC(c2ccno1)c(NC(c1ccccc1C)=O)c2)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1c2c(ncc1)ccc(F)c2'
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 3 4 11 12 13 14 15
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 27 28 29 34 36 37
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 4 6 8
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 10 11 12 13 15
[12:54:09] SMILES Parse Error: unclosed ring for input: 'CC(NC(c1ccc2c(c1)CCO2)=O)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1cc1c(C)cs1'
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 30 31 32 34 36 37 46 47 48
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 3 4 5 6 8 9 10 33
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 5 6 7 8 9 12 13 14 15
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 28 30 31 32 34 35 38
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 26 27 28 39 40
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 30 31 32 38 39
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 30 31 32 33 34 35 36 37 40
[12:54:09] SMILES Parse Error: ring closure 1 duplicates bond between atom 30 and atom 31 for input: 'CC(NC(=O)c1cc(C)cnc1)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1c1cncn1'
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 32 33 34 35 37 38 39 40 41
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 27 28 29 33 34
[12:54:09] Explicit valence for atom # 36 F, 2, is greater than permitted
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 47 48 49
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 5 6 8 13 14 15 16
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 34 35 36 37 39 40 41
[12:54:09] SMILES Parse Error: unclosed ring for input: 'CC(NC(=O)c1ncsc1)C(Oc1ccc2c(cnn2-c2ccc3c(c(=N)oc4c3cc(C)cc2C)c1)Cc1csc(C)n1)C'
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 5 6 7 8 10
[12:54:09] SMILES Parse Error: extra open parentheses while parsing: CC(NC(=O)c1c(F)cccn1)C(Oc1ccc2c(cnn2-c2ccc(F)cc2
[12:54:09] SMILES Parse Error: check for mistakes around position 23:
[12:54:09] (NC(=O)c1c(F)cccn1)C(Oc1ccc2c(cnn2-c2ccc(
[12:54:09] ~~~~~~~~~~~~~~~~~~~~^
[12:54:09] SMILES Parse Error: extra open parentheses while parsing: CC(NC(=O)c1c(F)cccn1)C(Oc1ccc2c(cnn2-c2ccc(F)cc2
[12:54:09] SMILES Parse Error: check for mistakes around position 32:
[12:54:09] c(F)cccn1)C(Oc1ccc2c(cnn2-c2ccc(F)cc2
[12:54:09] ~~~~~~~~~~~~~~~~~~~~^
[12:54:09] SMILES Parse Error: Failed parsing SMILES 'CC(NC(=O)c1c(F)cccn1)C(Oc1ccc2c(cnn2-c2ccc(F)cc2' for input: 'CC(NC(=O)c1c(F)cccn1)C(Oc1ccc2c(cnn2-c2ccc(F)cc2'
[12:54:09] SMILES Parse Error: unclosed ring for input: 'S(=O)(N(CC(C)C)Cc2ccccc1Cl)c1cccc12'
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 27 28 35 38
[12:54:09] SMILES Parse Error: unclosed ring for input: 'CC(NC(=O)c2c(SC)cc(C)cc1)cc2'
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 27 29 30 31 32 33 34 38 39
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 36 37 38 41 42
[12:54:09] SMILES Parse Error: ring closure 3 duplicates bond between atom 38 and atom 39 for input: 'CC(NC(=O)Cc1csc(C)n1)C(Oc1ccc2c(cnn2-c2ccc(F)cc2F)c1)c1ccc(N2CCC3(C3)CC2)nc1'
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 28 29 30 31 32 33 36 38
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 31 34 35 36 37 44
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 29 30 31 32 37 38 40
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 17 20 21 22 23 24 26
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 31 33 34 35 36 37
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 4 5 7 12 13 14 15
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 31 33 34 35 36 37
[12:54:09] SMILES Parse Error: unclosed ring for input: 'CC(NC(c1cccnc1N(C)C)=O)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1cc(F)c2c(c1)c(N1C(C)CNCC1C)nccc3cc2'
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 30 31 32 33 36 37 44 45 46
[12:54:09] SMILES Parse Error: extra close parentheses while parsing: CC(NC(=O)c1ccnn1C)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1cc2c(c(C)cc(N(C)C)n2)cc1)(C)C
[12:54:09] SMILES Parse Error: check for mistakes around position 76:
[12:54:09] (c(C)cc(N(C)C)n2)cc1)(C)C
[12:54:09] ~~~~~~~~~~~~~~~~~~~~^
[12:54:09] SMILES Parse Error: Failed parsing SMILES 'CC(NC(=O)c1ccnn1C)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1cc2c(c(C)cc(N(C)C)n2)cc1)(C)C' for input: 'CC(NC(=O)c1ccnn1C)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1cc2c(c(C)cc(N(C)C)n2)cc1)(C)C'
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 6 7 9 10 11
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 30 31 43
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 10 11 12 13 15 18 19 20 21 22 23 24 25 26 27
[12:54:09] SMILES Parse Error: unclosed ring for input: 'S(=O)(c2cccs1)c(NC(CN1CCN(CCc3ccccc3)CC1)=O)c2'
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 25 28 29 30 33 34 36
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 32 34 35 36 37 38
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 29 33 34 35 39 40
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 29 30 31 32 33 34 35 36 38
[12:54:09] Explicit valence for atom # 40 F, 2, is greater than permitted
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 4 5 6 8 9
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 5 6 8 9 10
[12:54:09] SMILES Parse Error: unclosed ring for input: 'CC(NC(c1cncs1)=O)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c2cc(F)c2oc(-c2ccc(F)cc2)cc1=O'
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 30 32 33 34 41 44
[12:54:09] SMILES Parse Error: ring closure 2 duplicates bond between atom 38 and atom 39 for input: 'CC(NC(=O)Cc1c2ccc(C)cc2[nH]c1)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1ccc(N2C2CCC2COC1)=O'
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 31 34 36 37 39 40
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 31 32 33 34 35 36 37 38 39
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 27 29 30 31 32 33
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 4 5 7 8 9 10 11 24 25
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 6 7 8 9 11 12 13 14 15
[12:54:09] SMILES Parse Error: unclosed ring for input: 'CC(NC(c1sncn1)=O)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1cc2c(cn1)OCCO1O2'
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 30 31 45
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 31 33 34 35 36 37
[12:54:09] SMILES Parse Error: extra close parentheses while parsing: CC(NC(=O)C1CC[S+]([O-])CC1)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1cc(F)c2c(c1)CCN(C)C2)C
[12:54:09] SMILES Parse Error: check for mistakes around position 81:
[12:54:09] cc(F)c2c(c1)CCN(C)C2)C
[12:54:09] ~~~~~~~~~~~~~~~~~~~~^
[12:54:09] SMILES Parse Error: Failed parsing SMILES 'CC(NC(=O)C1CC[S+]([O-])CC1)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1cc(F)c2c(c1)CCN(C)C2)C' for input: 'CC(NC(=O)C1CC[S+]([O-])CC1)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1cc(F)c2c(c1)CCN(C)C2)C'
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 4 6 7 20
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 15 16 17
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 28 29 30 31 32 33 42 43 44
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 6 7 8 9 11 12 13 14 15
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 30 32 33 34 35 36
[12:54:09] SMILES Parse Error: unclosed ring for input: 'CC(NC(=O)Cc1noc(-c2cccs2)c1)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1ccc2c(c1)OCC1CC2C1(C)CCCC1'
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 12 13 14 15 16 17 20 21 22
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 26 28 29 36 37 39
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 2 3 5 6 8 9 10 11 12 13 14
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 34 36 37 38 46 47 48
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 4 5 6 7 8 9 10 11 12
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 28 29 30 31 32 33 37 39 41
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 4 5 6 7 8 9 10 11 12
[12:54:09] SMILES Parse Error: unclosed ring for input: 'CCNC(=O)c1oc(OC)cc1C=C2C(=O)Nc2cc(F)c(F)c1'
[12:54:09] Explicit valence for atom # 33 C greater than permitted
[12:54:09] SMILES Parse Error: unclosed ring for input: 'CC(NC(NCc1n2ccsc2nc1C)=O)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c2cccc(N2CCCC2)c1'
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 36 37 45
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 28 29 30 31 34 35 45 46 47
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 36 37 38 40 42 43 46
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 35 36 37 38 39 41 43
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 4 5 6 7 9 10 11 12 13
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 15 16 17 18 19 20 21 32 33
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 4 6 7 8 15 17 18
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 34 36 37 38 39 40
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 30 31 32 33 34 35 38 39 40
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 32 33 34 35 36 37 41 43 44
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 5 6 10 12 29
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 31 32 33 35 37 38 41
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 2 3 5 6 7 34 35
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 30 31 32 34 36 37 40
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 32 34 35 42 43 44
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 27 29 30 35 36 38
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 33 34 35 37 38 39 46 48 49
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 10 11 12 13 14 15 22 23 24
[12:54:09] Explicit valence for atom # 39 C greater than permitted
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 29 32 33 35 36 44 45
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 30 31 45
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 32 33 34 35 37 38 39 40 41
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 29 30 31 32 33 34 40 42 43
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 27 30 31 32 33 34 42 43 44
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 16 17 18
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 6 7 8 10 11 12 19 20
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 29 30 32 33 34 35 36
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 33 34 35 37 39 40 44 45 46
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 29 31 32 33 34 35 36 40
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 30 31 32 33 34 35 43
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 27 28 29 30 31 32 33 34 35
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 37 38 39 40 41 51 52
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 26 27 28 29 30 44 45 46 47
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 29 30 32 33 34 35 36
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 7 8 10 13 15
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 29 30 31 32 33 34 47 48 49
[12:54:09] Explicit valence for atom # 5 C, 6, is greater than permitted
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 5 6 7 8 9 11 12 13 14
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 2 3 23 24 25 26 28 29 33
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 15 16 17 18 19 20 21 29 30 31 32
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 5 6 8 9 10
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 24 26 27 28 36 37
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 31 32 33 35 36 37 38 41 42
[12:54:09] SMILES Parse Error: ring closure 3 duplicates bond between atom 9 and atom 10 for input: 'CCc1cc(-c2cccc3n3c(-c3ccccn3)nn2)c(C)cc1N1CCOCC1'
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 29 31 32 34 35 41 43
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 32 33 34 36 37 38 39
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 33 34 35 36 41 43 44
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 28 29 30 31 32 34 35 38 39 40 42 43
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 2 3 5 6 7 9 10 20 21
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 17 18 19 20 21 22 23 32 33
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 8 9 10 11 12 13 14 16 17 18 19 21 22 23 24 25 27 28 29 30 31
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 29 30 31 33 35 36 39
[12:54:09] Can't kekulize mol.  Unkekulized atoms: 29 30 31 32 33 34 35 36 39

--- Processing cluster 1 ---

[12:54:30] SMILES Parse Error: unclosed ring for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2C1=CC2CCCN2CC1CCNC(=O)C2CCc2cccn1C'
[12:54:30] SMILES Parse Error: extra close parentheses while parsing: CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CC(CC1NC(=O)c3ccccc3N1C)C)C2
[12:54:30] SMILES Parse Error: check for mistakes around position 56:
[12:54:30] 1NC(=O)c3ccccc3N1C)C)C2
[12:54:30] ~~~~~~~~~~~~~~~~~~~~^
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 24 25 26 35 36
[12:54:30] SMILES Parse Error: Failed parsing SMILES 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CC(CC1NC(=O)c3ccccc3N1C)C)C2' for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CC(CC1NC(=O)c3ccccc3N1C)C)C2'
[12:54:30] Explicit valence for atom # 21 C, 5, is greater than permitted
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 4 6 8 9 11 12 24
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 25 29 30
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 23 24 25 26 28 29 31 32 33
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 27 28 29 30 31
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 21 22 24 25 26 27 28 29 30 31 32
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 25 26 28 29 30
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 30 31 32
[12:54:30] Explicit valence for atom # 22 C, 5, is greater than permitted
[12:54:30] SMILES Parse Error: ring closure 1 duplicates bond between atom 22 and atom 26 for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2C(CC1(C2CC2)C1)NC(=O)C1C(C)(C)C1'
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 20 21 22 23 24 25 26
[12:54:30] SMILES Parse Error: unclosed ring for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCN(CC(=O)N(CCC)C1CCc3c1ccc(-n4cccn4)n1C3)C2'
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 28 29 30 31 32 36 37 38 39
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 21 22 24 25 26 31 32
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 30 31 32
[12:54:30] SMILES Parse Error: ring closure 3 duplicates bond between atom 22 and atom 30 for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CC(C1CCC3(CC1c1nocc1)O3)C2(C)C'
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 22 23 24
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 22 23 29 30 31
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 25 26 27 28 29 37 38 39 40
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 26
[12:54:30] SMILES Parse Error: ring closure 4 duplicates bond between atom 26 and atom 30 for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CC(CC1CN(C(CC3C4(CCC3)C4)C)CCC1)C2'
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 27
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 26
[12:54:30] SMILES Parse Error: unclosed ring for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2C(=O)c1cc(-n3cccn2)ccc3ccc1'
[12:54:30] SMILES Parse Error: ring closure 1 duplicates bond between atom 21 and atom 36 for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCCC2C1(CN2CCNCC2c2c(N)cccc2)C1'
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 25 26 27 35 36
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 23 24 25 26 27 30 37 38 39
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 20 21 25
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 20 21 22 31 32
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 20 22 24 25 26 27 28
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 35 36 37
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 26 27 28 29 32
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 25 26 27 32 33
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 21 27 28
[12:54:30] SMILES Parse Error: unclosed ring for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CC(CC1CCNC2c1ccccc1)CCCC'
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 26 27 28 29 30 31 32 33 34
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 22 23 24 26 29
[12:54:30] SMILES Parse Error: unclosed ring for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2C1CCc2cc(F)cc3c2C1C1CCCN1C'
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 23 26
[12:54:30] SMILES Parse Error: ring closure 1 duplicates bond between atom 20 and atom 21 for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CC(Cc1n1cc(Cl)cc2)(C)CCOc1ccc2c(n1)cncc2'
[12:54:30] Explicit valence for atom # 28 N, 4, is greater than permitted
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 22 23 24 27 28 29 30
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 26 27 28 29 31
[12:54:30] SMILES Parse Error: ring closure 4 duplicates bond between atom 24 and atom 33 for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CC(CC1CC3(C)C4(CCCC3=CC(=O)C1)C4)CC2'
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 17 20 21
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 21 22 36
[12:54:30] non-ring atom 25 marked aromatic
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 20 21 24 25 26 27 33
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 26 27 30 31 32 33 34
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 20 21 30 31 32
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 26 27 29 30 32 33 34
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 21 23 24 25 27 28 29 30 31 34
[12:54:30] Explicit valence for atom # 23 O, 3, is greater than permitted
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 27 28 29 30 32
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 21 22 23 39 40
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 21 22 23 25 26 27 29
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 24 25 26 29
[12:54:30] SMILES Parse Error: unclosed ring for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CC(CN(Cc1cc3c(cn1)[nH]c1ccccc33)CC1)cc2'
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 26 27 30 37 38 39 40
[12:54:30] SMILES Parse Error: unclosed ring for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2C1CN2CCc3cccc(c21)CC(N1CCC2(CC1)C(=O)NCC2)=O'
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 24 25 27 28 30
[12:54:30] SMILES Parse Error: unclosed ring for input: 'S(N)(=O)(c1ccc(-n2ncc3c2C=C2CCCC(C(c4c5c(ccc2)OCCO4)S(=O)(=O)C3)ccc4F)cc2c(C)cc(=O)[nH]c21)=O'
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 27 28 29 30 47
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 30
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 26
[12:54:30] SMILES Parse Error: duplicated ring closure 1 bonds atom 20 to itself for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CC(CC11CCN(C(=O)COc3ccc(OC)cc3)CC1)CC2'
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 26 27 28 29 30 31 32
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 27
[12:54:30] Explicit valence for atom # 26 C, 5, is greater than permitted
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 23 24 25
[12:54:30] SMILES Parse Error: ring closure 2 duplicates bond between atom 26 and atom 35 for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2C(CN(C1CCC2(c3cnc(OC)nc3)C2C1)C)C'
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 26
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 19 20 22 26 27 28 29 30 31
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 20 21 22
[12:54:30] Explicit valence for atom # 30 O, 3, is greater than permitted
[12:54:30] Explicit valence for atom # 20 N, 4, is greater than permitted
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 26 29 30
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 22 23 24 26 27
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 28 29 31 32 33 34 35
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 22 23 25 26 27 28 32
[12:54:30] Explicit valence for atom # 21 C, 6, is greater than permitted
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 8 9 10 11 13 14 22 23 24 25 26
[12:54:30] SMILES Parse Error: unclosed ring for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2C(Cn1nnc(C2CCCC2=Cc2cc(F)n(C)n2)C1)cc1'
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 30 31 32 33 35
[12:54:30] SMILES Parse Error: ring closure 2 duplicates bond between atom 25 and atom 32 for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2Cc1ncc(C2(CNS(C)(=O)=O)C2)cc1'
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 26 27 28 29 30 32 33
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 27 28 29 30 31 32 43 44 45 46 48
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 22 23 28 29 30
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 23 24 25 26 27 28 29 35 36
[12:54:30] SMILES Parse Error: ring closure 2 duplicates bond between atom 25 and atom 27 for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2N(C(=O)C1CC2(C1)C2)c1cnn(C)c1'
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 25 26 27 28 29 30 31
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 23 24 27
[12:54:30] Explicit valence for atom # 20 N, 4, is greater than permitted
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 20 21 22 23 24
[12:54:30] SMILES Parse Error: unclosed ring for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2CNc1cc2[nH]ccc3cccc4c1c23'
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 24 25 27 33 34
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 0 24 25 26 27 33 34 35
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 29 30 31 32 33 34 35
[12:54:30] SMILES Parse Error: ring closure 1 duplicates bond between atom 19 and atom 24 for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1C(CC1(C(C)(C)C)C1)CCC2'
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 27 28 29 30 31 32 33
[12:54:30] SMILES Parse Error: unclosed ring for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2N1CCOc2cc(F)cc3c2C1CC1(C)C(CC)Cc2c1cccc2'
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 2 4 5 6 7
[12:54:30] non-ring atom 24 marked aromatic
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 22 24 25 26 27 28 31
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 22 23 24
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 31 32 33
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 26 27 37 38 39
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 25 26 27 28 30
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 32 33 34 35 36
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 21 23 24 25 26 27 35
[12:54:30] Explicit valence for atom # 19 O, 3, is greater than permitted
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 28 29 30 31 32 33 35
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 26 27 36 37 38
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 26 27 28
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 24 25 26 29 30 31 32 35 36
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 26 27 28 29 30
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 24 25 32
[12:54:30] Explicit valence for atom # 22 O, 4, is greater than permitted
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 22 24 25 26 27 28 29 30 34
[12:54:30] Explicit valence for atom # 26 N, 5, is greater than permitted
[12:54:30] SMILES Parse Error: unclosed ring for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2C1CN2CCc3c(c(-c3cccnc3)c(C)cn2)C1'
[12:54:30] SMILES Parse Error: unclosed ring for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCCC2NCc1c(-n2cncn3)cccc2CC1'
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 21 23 29 30 31 32 33
[12:54:30] Explicit valence for atom # 29 C, 5, is greater than permitted
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 21 22 24 25 26 27 30
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 1 2 14 15 16 17 18 26 38
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 25 26 27
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 24 25 26 27 29 31 33
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 23 24 26 27 37
[12:54:30] Explicit valence for atom # 19 C, 5, is greater than permitted
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 10 11 12 25 26 27 28 29 30
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 21 22 23 25 26 29 30 31
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 20 22
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 23 24 25 37 39 40 41 42 43 44 45
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 20 21 22 23 26
[12:54:30] Explicit valence for atom # 23 C, 5, is greater than permitted
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 20 21 22 34 35
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 26 27 31 32 33
[12:54:30] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 25 33 34
[12:54:30] SMILES Parse Error: unclosed ring for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2C1CN2Cc3c(cn(Cc4ccc(Cl)cc4)n2)N=C1c1ccncc1'
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 24 25 27 28 30
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 26 27 28 32 34 36
[12:54:31] SMILES Parse Error: unclosed ring for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2C(CCCC)(O)CCCc2ccccn1'
[12:54:31] SMILES Parse Error: ring closure 1 duplicates bond between atom 35 and atom 36 for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2Cc1c(C2(C)COC2)cc(C)c2c1CCC21C1(F)C'
[12:54:31] SMILES Parse Error: ring closure 2 duplicates bond between atom 23 and atom 30 for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2CC(=O)C12CCC(C#N)CC12c1ccc(F)cc1'
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 24 25 26 27 28 30 31 32 33
[12:54:31] Explicit valence for atom # 26 C, 5, is greater than permitted
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 23 25
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 23 24 25 28 29 30 31 32 33 34 35 36 37
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 20 22 23 33 34 36 37 38 39
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 20 22 23 28 29 30 40
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 32 33 34 35 36 37 38 39 40
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 28 29 30 31 32 33 34
[12:54:31] Explicit valence for atom # 20 C, 5, is greater than permitted
[12:54:31] SMILES Parse Error: unclosed ring for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2C1CN2CCc3c(ccc(-c3cccnc3)c2)C1C1COCC1'
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 23 24 25 26 27 30 33 34 35
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 27 28 29 30 31 32 35
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 25 26 27 37 38
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 23 25 26 27 29 30 32 33 34
[12:54:31] SMILES Parse Error: unclosed ring for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2C(CSc1ccnc2ccnn3c21)(C)C'
[12:54:31] SMILES Parse Error: ring closure 1 duplicates bond between atom 26 and atom 27 for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2C1C2C(CC1)CC1(C1)C(C)(C)CC(C)N2'
[12:54:31] Explicit valence for atom # 25 C, 5, is greater than permitted
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 26 27 33
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 21 22 24 25 26 27 28
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 20 21 22 25 26 33 34
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 26
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 22 23 25 26 27 33 34 35 36
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 3 4 5 14 19 20 21 22 23
[12:54:31] SMILES Parse Error: ring closure 1 duplicates bond between atom 21 and atom 22 for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CC(C(=O)c1c1cc(C#N)cc2)(C)C'
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 25 27 28 29 30
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 2 3 5 6 19 28 31 32 33
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 23 34
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 21 22 24 25 26 28 29
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 25 26 27 28 29
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 22 23 27 28 29 30 31 32 33
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 23 24 25 26 32 33 34
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 26 27 28
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 14 15 16 19 20 21 22 23 24
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 26 35 36 37 38
[12:54:31] Explicit valence for atom # 34 F, 2, is greater than permitted
[12:54:31] SMILES Parse Error: extra close parentheses while parsing: CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2C(C)(NCc1cc2n(C)ccc2cn1)C1CC1)(O)C
[12:54:31] SMILES Parse Error: check for mistakes around position 64:
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 20 21 22 23 24 25 26 37 38
[12:54:31] cc2n(C)ccc2cn1)C1CC1)(O)C
[12:54:31] ~~~~~~~~~~~~~~~~~~~~^
[12:54:31] SMILES Parse Error: Failed parsing SMILES 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2C(C)(NCc1cc2n(C)ccc2cn1)C1CC1)(O)C' for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2C(C)(NCc1cc2n(C)ccc2cn1)C1CC1)(O)C'
[12:54:31] SMILES Parse Error: unclosed ring for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2N1CC(C)N(Cc2cccc3c2nccc3-c2c(C)nnc3C)CC2CC1'
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 26 27 28 29 30 31 32
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 26 28 29 31 34 35 36
[12:54:31] Explicit valence for atom # 23 C, 5, is greater than permitted
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 28 29 30 31 32 33 34
[12:54:31] Explicit valence for atom # 25 O, 3, is greater than permitted
[12:54:31] SMILES Parse Error: ring closure 1 duplicates bond between atom 23 and atom 24 for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2C(C)(N=c1c1c(C)ccn1-c1c(Cl)cc(F)cc1)C'
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 25 26 27 34 35
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 26 27 28 29 36
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 21 22 23 25 26 33 34 42 43
[12:54:31] Explicit valence for atom # 21 O, 3, is greater than permitted
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 32 33 34
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 27
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 20 21 23 24 25 26 39 40 41
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 28 29 31
[12:54:31] non-ring atom 25 marked aromatic
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 31 32 33 34 35 36 37 38 39
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 23 24 25 26 27 28 32
[12:54:31] SMILES Parse Error: unclosed ring for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2C1CN2C(=NC2=O)CCCCC13'
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 23 24 25 27 28
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 25 26 27 35 36
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 24 25 26 27 28
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 25 26 27 28 29
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 25 26 38
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 22 24 25 26 27 38
[12:54:31] SMILES Parse Error: ring closure 1 duplicates bond between atom 23 and atom 31 for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CC(C(F)(CNC1(c3cnc(Cl)cc3)C1)C)CC2'
[12:54:31] Explicit valence for atom # 28 O, 4, is greater than permitted
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 3 4 5 14 19 20 23 24 25
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 3 4 5 6 7
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 2 3 5 27 28 37 38
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 24 25 26 28 29 30 31 32 33 34 35 36 37
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 25 26 27 28 29 30 31 39 40
[12:54:31] Explicit valence for atom # 19 C, 5, is greater than permitted
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 26 27 36 37 38
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 21 22 23 28 29
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 20 21 22 23 24 38 39
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 24 25 26 27 28 29 33 34 35
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 25 26 32 33 34
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 25 26 27 28 29
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 23 24 26 27 28
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 23 24 25 26 28 31 32 33 34
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 26 27 28 29 30 42 43
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 21 37 38
[12:54:31] SMILES Parse Error: ring closure 3 duplicates bond between atom 27 and atom 28 for input: 'CC12Cc3cnn(-c4ccc(F)cc4)c3C=C1CCC2C1C2CCC(CNc3c3non2)C2=C1CCC2'
[12:54:31] Can't kekulize mol.  Unkekulized atoms: 23 24 25 26 27 32 33 34 35

--- Processing cluster 2 ---

[12:54:52] SMILES Parse Error: ring closure 1 duplicates bond between atom 31 and atom 32 for input: 'CC(NC(=O)c1cnncc1)C(Oc1ccc2c(cnn2-c2ccc3c(c2)CCC3)c1)c1c1cncc1'
[12:54:52] Can't kekulize mol.  Unkekulized atoms: 31 32 33 34 36
[12:54:52] Can't kekulize mol.  Unkekulized atoms: 19 20 21 26 27 28 29 30 31 32 33 34 35
[12:54:52] Can't kekulize mol.  Unkekulized atoms: 29 30 31 32 33 35 37 38 40
[12:54:52] Can't kekulize mol.  Unkekulized atoms: 39 42 43 45 46 48 49
[12:54:52] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 5 6 7 8 9 10 11 12 13 16 17 18 20
[12:54:52] SMILES Parse Error: unclosed ring for input: 'CC(NC(=O)c1cc[nH]n1)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1cn(C23CC4CC(C2)CC3)nc1'
[12:54:52] Can't kekulize mol.  Unkekulized atoms: 27 29 31 32 33 39
[12:54:52] Can't kekulize mol.  Unkekulized atoms: 29 30 31 33 38 39 40 41 42
[12:54:52] Can't kekulize mol.  Unkekulized atoms: 30 31 32 33 34 35 38 40 41
[12:54:52] Can't kekulize mol.  Unkekulized atoms: 40 42 43 44 45 46
[12:54:52] Can't kekulize mol.  Unkekulized atoms: 9 10 15
[12:54:52] Can't kekulize mol.  Unkekulized atoms: 4 5 6 7 8 9 12 13 15 16 17 18 19 20 21 22 23
[12:54:52] Can't kekulize mol.  Unkekulized atoms: 36 37 39 40 48 49 50
[12:54:52] Can't kekulize mol.  Unkekulized atoms: 27 28 30 31 33 34 36 37 38
[12:54:52] Explicit valence for atom # 27 O, 5, is greater than permitted
[12:54:52] Can't kekulize mol.  Unkekulized atoms: 27 28 29 30 31 32 33 35
[12:54:52] SMILES Parse Error: unclosed ring for input: 'CC(NC(c1cnccn1)=O)C(Oc2cccc2cccn1)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1cc(F)cnc1'
[12:54:52] Can't kekulize mol.  Unkekulized atoms: 30 31 32 34 35 36 37 38 39 40 41
[12:54:52] Can't kekulize mol.  Unkekulized atoms: 34 36 40 41 42
[12:54:52] Can't kekulize mol.  Unkekulized atoms: 29 32 33
[12:54:52] Explicit valence for atom # 39 C greater than permitted
[12:54:52] SMILES Parse Error: extra close parentheses while parsing: CC(NC(=O)C(C)(C)C)C(Oc1ccc2c(cnn2-c2ccccc2)c1)c1ccc2c(c1)OCCC2)CC(C)(C)c1cc(F)ccc1O
[12:54:52] SMILES Parse Error: check for mistakes around position 63:
[12:54:52] )c1)c1ccc2c(c1)OCCC2)CC(C)(C)c1cc(F)ccc1O
[12:54:52] SMILES Parse Error: unclosed ring for input: 'CC(NC(=O)c1cccc2c1CCCC2)C(Oc1ccc2c(cnn2-c2cccnc2)c1)c1nn1ccc1C(F)(F)F'
[12:54:52] ~~~~~~~~~~~~~~~~~~~~^
[12:54:52] SMILES Parse Error: Failed parsing SMILES 'CC(NC(=O)C(C)(C)C)C(Oc1ccc2c(cnn2-c2ccccc2)c1)c1ccc2c(c1)OCCC2)CC(C)(C)c1cc(F)ccc1O' for input: 'CC(NC(=O)C(C)(C)C)C(Oc1ccc2c(cnn2-c2ccccc2)c1)c1ccc2c(c1)OCCC2)CC(C)(C)c1cc(F)ccc1O'
[12:54:52] Can't kekulize mol.  Unkekulized atoms: 30 31 32 33 34 35 36 37 38 39 40
[12:54:52] Can't kekulize mol.  Unkekulized atoms: 34 35 37 38 39 40 42
[12:54:52] Can't kekulize mol.  Unkekulized atoms: 8 9 10 11 12
[12:54:52] non-ring atom 10 marked aromatic
[12:54:52] Can't kekulize mol.  Unkekulized atoms: 5 6 7 8 9 10 14
[12:54:52] Can't kekulize mol.  Unkekulized atoms: 33 34 35 36 42
[12:54:52] Can't kekulize mol.  Unkekulized atoms: 34 35 37 38 39 40 43
[12:54:52] Can't kekulize mol.  Unkekulized atoms: 36 37 38 40 41 42 46 47 48
[12:54:52] SMILES Parse Error: unclosed ring for input: 'CC(NC(N(C)C1CC1)=O)C(Oc1ccc2c(cnn2-c2cc3c(cc2)ncs2)cc3c1)c1cnc(C)cc1'
[12:54:52] SMILES Parse Error: unclosed ring for input: 'CC(NC(c1sccc1)=O)C(Oc1ccc2c(cnn2-c2ccc3onc(-c4c(F)cccc6)c4c3c2)c1)c1ccccc1'
[12:54:52] Can't kekulize mol.  Unkekulized atoms: 28 29 31 32 39
[12:54:52] Can't kekulize mol.  Unkekulized atoms: 5 18
[12:54:52] Can't kekulize mol.  Unkekulized atoms: 0 1 9
[12:54:52] SMILES Parse Error: extra close parentheses while parsing: CC(NC(=O)c1c(SC)cccc1)C(Oc1ccc2c(cnn2-c2cccnc2)c1)c1cnn(C(C)(C(F)(F)F)F)c1)C
[12:54:52] SMILES Parse Error: check for mistakes around position 75:
[12:54:52] n(C(C)(C(F)(F)F)F)c1)C
[12:54:52] ~~~~~~~~~~~~~~~~~~~~^
[12:54:52] SMILES Parse Error: Failed parsing SMILES 'CC(NC(=O)c1c(SC)cccc1)C(Oc1ccc2c(cnn2-c2cccnc2)c1)c1cnn(C(C)(C(F)(F)F)F)c1)C' for input: 'CC(NC(=O)c1c(SC)cccc1)C(Oc1ccc2c(cnn2-c2cccnc2)c1)c1cnn(C(C)(C(F)(F)F)F)c1)C'
[12:54:52] Can't kekulize mol.  Unkekulized atoms: 10 17 18
[12:54:52] Can't kekulize mol.  Unkekulized atoms: 14 15 16 25 26 27 28 29 30
[12:54:52] SMILES Parse Error: extra close parentheses while parsing: CC(NC(=O)C(C)(C)C)C(Oc1ccc2c(cnn2-c2cc(C#N)ccc2)c1)c1c[nH]n2c1nc(C)cc2=N)C
[12:54:52] SMILES Parse Error: check for mistakes around position 73:
[12:54:52] Can't kekulize mol.  Unkekulized atoms: 26 27 28 29 31 32 33 35 36
[12:54:52] 1c[nH]n2c1nc(C)cc2=N)C
[12:54:52] ~~~~~~~~~~~~~~~~~~~~^
[12:54:52] SMILES Parse Error: Failed parsing SMILES 'CC(NC(=O)C(C)(C)C)C(Oc1ccc2c(cnn2-c2cc(C#N)ccc2)c1)c1c[nH]n2c1nc(C)cc2=N)C' for input: 'CC(NC(=O)C(C)(C)C)C(Oc1ccc2c(cnn2-c2cc(C#N)ccc2)c1)c1c[nH]n2c1nc(C)cc2=N)C'
[12:54:52] Can't kekulize mol.  Unkekulized atoms: 31 32 34 35 36
[12:54:52] Can't kekulize mol.  Unkekulized atoms: 36 37 38 39 40 42
[12:54:52] Can't kekulize mol.  Unkekulized atoms: 23 24 25 26 27 28 36
[12:54:52] Can't kekulize mol.  Unkekulized atoms: 7 8 9 10 11
[12:54:52] Can't kekulize mol.  Unkekulized atoms: 31 32 33 34 36 37 38 39 41
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 26 27 28 29 31 32 33 34 35
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 31 32 33 35 36 39 40 41
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 31 32 33 34 35 36 38 40
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 34 35 36 38 39 42 43 44 45
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 4 5 8 9 10 11 20 21 22
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 36 37 38 39 40 42 43 50 51
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 36 37 38 39 41
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 29 30 31 32 34 35 36 38 39
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 32 33 34 35 36 46 48 49 50
[12:54:53] SMILES Parse Error: ring closure 2 duplicates bond between atom 32 and atom 36 for input: 'CC(NC(=O)c1c(F)cccc1)C(Oc1ccc2c(cnn2-c2cccnc2)c1)c1cn(C2(C(O)=O)C2)c2c1cccn2'
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 38 39 40 41 43
[12:54:53] Explicit valence for atom # 40 N, 6, is greater than permitted
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 26 27 28 29 30 31 35 36 37
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 19 20 21 22 23 24 25 26 27
[12:54:53] SMILES Parse Error: ring closure 1 duplicates bond between atom 40 and atom 41 for input: 'CC(NC(=O)C1CCCC1)C(Oc1ccc2c(cnn2-c2cc3c(cco3)cc2)c1)c1ccc2c(c1)CCN2C(c1c1ccccc1)=O'
[12:54:53] SMILES Parse Error: unclosed ring for input: 'CC(NC(=O)N1CCN(CC)CC1)C(Oc1ccc2c(cnn2-c3cccc(F)c2)c3cc1)c1noc(C)c1'
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 30 31 32 35
[12:54:53] SMILES Parse Error: unclosed ring for input: 'CC(NC(NCc1ccccc1F)=O)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1cn(C23CC4CC(CC(C2)C3)C)nc1'
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 27 28 29 30 32 33 35 36 37
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 5 6 7 8 9 10 11
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 30 31 33 34 36 37 40
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 27 28 29 31 32 33 36 37 40
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 24 25 26 27 28 29 30 38 39 40 41
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 41 43 44
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 35 36 37 38 39 42 43
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 27 28 29 30 31 33 35 36 38
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 34 36 37 38 46
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 31 32 45
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 28 29 30 31 32 33 36 38 39
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 23 24 25 26 27 28 32
[12:54:53] SMILES Parse Error: extra close parentheses while parsing: CC(NC(N1CCCC(N2CCOCC2)C1)=O)C(Oc1ccc2c(cnn2-c2ccncc2)c1)c1ccc2c(c1)F)CCC2
[12:54:53] SMILES Parse Error: check for mistakes around position 69:
[12:54:53] ncc2)c1)c1ccc2c(c1)F)CCC2
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 7 8 9 10 11 12 13 14 15 16 17
[12:54:53] ~~~~~~~~~~~~~~~~~~~~^
[12:54:53] SMILES Parse Error: unclosed ring for input: 'CC(NC(NCc1ccsc1)=O)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1nnn(C3(C#N)CC1)c1'
[12:54:53] SMILES Parse Error: Failed parsing SMILES 'CC(NC(N1CCCC(N2CCOCC2)C1)=O)C(Oc1ccc2c(cnn2-c2ccncc2)c1)c1ccc2c(c1)F)CCC2' for input: 'CC(NC(N1CCCC(N2CCOCC2)C1)=O)C(Oc1ccc2c(cnn2-c2ccncc2)c1)c1ccc2c(c1)F)CCC2'
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 37 40 41 42 43
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 33 34 35 36 37 38 47 48 49 50 52 53 54
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 29 30 33
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 5 6 7 8 9 11 12 13 14 15 16
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 10 11 12
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 4 5 6 8 9
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 7 8 9 11 12
[12:54:53] SMILES Parse Error: unclosed ring for input: 'CC(NC(N1CC2CCC(CC2)C1)=O)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1c3oc2c(c1)ccc(F)c2'
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 43 44 45 46 47 48 49 51 52
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 29 30 31 32 33 34 35 40 41
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 7 8 9 15 16 17
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 30 31 33 34 38 39
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 0 10 12 13 29
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 29 30 31 32 34
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 26 27 28 29 31
[12:54:53] SMILES Parse Error: ring closure 2 duplicates bond between atom 34 and atom 35 for input: 'CC(NC(c1c(Cl)cc(Cl)cc1)=O)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1nnc2n2CCC1'
[12:54:53] SMILES Parse Error: ring closure 2 duplicates bond between atom 37 and atom 38 for input: 'CC(NC(=O)Nc1cc2c(cc1)OCCO2)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1nnc2n2CCC1'
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 1 4 5 6 15 16 17
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 36 37 38 39 40 41 43 45
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 4 6 7 9 10 11 12 13 14 15 16 17 18
[12:54:53] SMILES Parse Error: unclosed ring for input: 'CC(NC(=O)N2CCOCC1CCCC2)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1ccc2nnnn21'
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 31 32 34 35 36 37 38 40 41 42 43 44 45
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 26 27 28 29 32 44
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 27 28 29 30 31
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 28 30 33 34
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 32 33 35 37 38 39 40
[12:54:53] Explicit valence for atom # 32 C, 5, is greater than permitted
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 2 3 4 10 17
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 5 6 7 8 9 10 14
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 25 26 27 28 29 30 43 44 45
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 31 32 33 35 36 37 38 39 40
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 24 25 26 27 28 29 31
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 8
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 30 31 32 33 35 36 37 38 39
[12:54:53] SMILES Parse Error: unclosed ring for input: 'CC(NC(=O)c1ccncc1)C(Oc1ccc2c(cnn2-c2cccnc2)c1)c1cn(C23CC4CC(C2)CC3)nc1'
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 5 6 8 9 17
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 32 33 46
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 0 28 29 30 31 32 36 37 38 39 40
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 26 27 28 29 31 32 33 34 36
[12:54:53] SMILES Parse Error: unclosed ring for input: 'CC(NC(Nc1c(C)onc1C)=O)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1nnc(OC)c(-c3ccncc2)n1'
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 27 28 30 31 32 33 34 35 36 38 39
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 36 37 39 40 49
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 5 6 7 8 9 11 12 31 32
[12:54:53] Explicit valence for atom # 29 O, 5, is greater than permitted
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 31 32 33 35 36 37 38 41 42 43 44 45 48
[12:54:53] SMILES Parse Error: ring closure 3 duplicates bond between atom 29 and atom 30 for input: 'CC(NC(=O)C(F)(F)F)C(Oc1ccc2c(cnn2-c2ccc3c(n(C)c4c3CC3(C3)C(=O)Nc3ccccc34)c2)c1)c1cn(C2CC2)nc1'
[12:54:53] SMILES Parse Error: unclosed ring for input: 'CC(NC(=O)NCC1CCN(C(C)C)CC1)C(Oc1ccc2c(cnn2-c2ccc(F)c(F)c2)c1)c2cocn1'
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 34 35 38 39 40 41 42 44 45
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 9 10 11 12 14 15 16 17 24 25 26 27 28
[12:54:53] Explicit valence for atom # 38 N, 5, is greater than permitted
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 2 3 4 38 39
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 26 27 28 30 31 33 34
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 29 31 37 38 40 41 42
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 6 9 12
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 30 31 33 34 35 36 37 38 39
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 30 31 33 34 35 36 37
[12:54:53] SMILES Parse Error: unclosed ring for input: 'oc1NC(=O)c1cc(-n2ncc3cc(OC(C(Nc4ccccc4)C)C(F)(F)F)ccc32)ccc1'
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 28 29 30 32 33 34 35 41 42
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 25 26 27 28 35
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 7 8 9 15 16
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 26 27 28 29 30 32 33 34 35
[12:54:53] Explicit valence for atom # 39 F, 2, is greater than permitted
[12:54:53] Explicit valence for atom # 42 N, 6, is greater than permitted
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 34 35 36 38 39
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 35 36 37 38 46 47 48
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 26 27 31
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 30 32 34 36 37 38
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 34 35 36 39 40
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 23 24 25 26 27 28 30 36 37 38 39 40 41
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 27 28 29 30 31
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 34 35 36 37 39 40 41 42 43
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 28 29 30
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 25 26 27 28 29
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 26 27 28 33 34
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 30 31 34 35 36
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 30 31 33 34 35 36 37 38 39
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 28 29 32 33 34 35 36 37 39
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 29 31 33 35 36 37 38
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 30 31 32 33 34 36 37 38 41
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 33 34 35 36 37 38 40 41 42
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 34 35 36 38 39 40 41 42 43 44 45
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 33 34 36 37 38
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 29 30 31 33 34 38 39 41 42
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 36 37 39 40 48
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 13 14 15 16 17 18 19 27 28
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 33 34 36 37 38 40 41 42 43 44 45
[12:54:53] SMILES Parse Error: extra close parentheses while parsing: CC(NC(=O)C(F)(F)F)C(Oc1ccc2c(cnn2-c2cccnc2)c1)c1ccc2c(c1O)nc(OCC)[nH]2)(C)C
[12:54:53] SMILES Parse Error: check for mistakes around position 71:
[12:54:53] c2c(c1O)nc(OCC)[nH]2)(C)C
[12:54:53] SMILES Parse Error: unclosed ring for input: 'CC(NC(NCc1n(CC)cnn1)=O)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1cc2n(-c3ccc(F)cc4)ncc3ccc2c1'
[12:54:53] ~~~~~~~~~~~~~~~~~~~~^
[12:54:53] SMILES Parse Error: Failed parsing SMILES 'CC(NC(=O)C(F)(F)F)C(Oc1ccc2c(cnn2-c2cccnc2)c1)c1ccc2c(c1O)nc(OCC)[nH]2)(C)C' for input: 'CC(NC(=O)C(F)(F)F)C(Oc1ccc2c(cnn2-c2cccnc2)c1)c1ccc2c(c1O)nc(OCC)[nH]2)(C)C'
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 29 30 31 32 33 37 38 39 40
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 6 7 8 9 11 13 14 15 17
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 31 33 34 35 42 43 44 45 46
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 26 27 28 29 30 31 39 42
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 28 29 30 32 33 47 48
[12:54:53] SMILES Parse Error: unclosed ring for input: 'ClC(C#Cc2cncnc2)nc1'
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 32 33 34 35 36 38 40 41 42 43 44
[12:54:53] SMILES Parse Error: unclosed ring for input: 'CC(NC(=O)NCC1CC2C(CC(c3ccncc4)OC3C2)C1)C'
[12:54:53] SMILES Parse Error: unclosed ring for input: 'CC(NC(=O)N1CCNCC1c1cn(C)nc1)C(Oc1ccc2c(cnn2-c3ccc(F)cc2)cc3c1)c1ccc2c(c1)OCCO2'
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 5 7 8 9 16 17 18 19 20
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 38 39 40 41 42
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 7 8 15
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 30 31 33 34 35 36 37 38 40 41 42
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 0 1 2 29 30 33 34 35 36
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 5 7
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 20 21 22 23 24 25 26 27 28
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 39 40 43 44 45 46 47 48 49
[12:54:53] SMILES Parse Error: unclosed ring for input: 'N(C(C(C)(C)C)C(Oc2ccc3c(cnn3-c3cccnc3)c2CC1)c1cccc(Cl)c1)C(=O)C(C)(C)C'
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 28 29 31 39 40 41 42
[12:54:53] SMILES Parse Error: unclosed ring for input: 'CC(NC(=O)NCCc1ccc(F)cc1)C(Oc1ccc2c(cnn2-c2cccc(F)c2)c1)c1nn2c(cc1)ncc1'
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 11 12 13 14 16 37 38 39 40
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 6 7 8 14 15 16 17 18 20 21
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 5 6 7 8 15 16 17 18 19
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 29 30 31 32 33 34 35 37 38 39 40
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 23 24 25 26 27 28 29 30 31
[12:54:53] SMILES Parse Error: unclosed ring for input: 'CC(NC(=O)C(C)(C)C)C(Oc1ccc2c(cnn2-c2ccc2c(c1)OCC)nnc2)Cc1ccccc1'
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 29 30 31 33 34 37 38 39
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 28 29 30 32 33 38 39 40
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 40 41 42 43 44
[12:54:53] SMILES Parse Error: unclosed ring for input: 'CC(NC(=O)N1CCN(C(C)C)CC1)C(Oc1ccc2c(cnn2-c2ccc(F)cc2)c1)c1cn(C23CC4CC(CC(C2)C3)C3)nc1'
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 29 30 31 32 34
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 34 35 36 47 48 49 50
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 19 20 21 22 23 24 25 26 27 30 31 32 33 34 35
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 32 33 35 36 37 38 41
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 27 28 29 30 31 32 33
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 32 33 35 36 44 54
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 29 30 31 32 33 34 47
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 1 3 18 19
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 33 34 35 37 48
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 7 8 16 18 19 20 21
[12:54:53] SMILES Parse Error: unclosed ring for input: 'CC(NC(N1CC(C)(C)CC(O)C1)=O)C(Oc1ccc2c(cnn2-c2ccncc2)c1)c1ccc2c(cc(F)[nH]3)c2c1'
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 29 30 31 33 34 35 36 37
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 31 32 33 34 35 36 37 39
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 23 24 25 26 30 31 32
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 30 32 33 34 35 38
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 31 32 33 48 49
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 30 31 33 34 35 36 47
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 19 20 21 22 24 25 26 27 28 29 30
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 31 32 33 35 40 41 42 43 44
[12:54:53] Can't kekulize mol.  Unkekulized atoms: 19 20 21 22 23 24 25 26 27

--- Processing cluster 3 ---

[12:55:16] SMILES Parse Error: ring closure 3 duplicates bond between atom 13 and atom 14 for input: 'c1c(F)ccc(C2=C3C4C(CCC3C3C3c3c([nH]nn3)CC4)C2)c1'
[12:55:17] Explicit valence for atom # 10 C, 5, is greater than permitted
[12:55:17] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 2 4 5 6 11 12
[12:55:17] SMILES Parse Error: ring closure 2 duplicates bond between atom 10 and atom 18 for input: 'C1(CCC(F)(F)F)(O)CCC2(Cc3ccccc3)C2C1'
[12:55:17] SMILES Parse Error: unclosed ring for input: 'C1(O)CC(O)C=CC12CCC1C(=C2)C#CC(C)(C)C'
[12:55:17] Explicit valence for atom # 2 N, 6, is greater than permitted
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 6 7 8 9 27 28 30
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 2 3 9 10 11 12 13 14 15
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 12 13 14 32 33
[12:55:17] Explicit valence for atom # 5 C, 5, is greater than permitted
[12:55:17] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:55:17] Explicit valence for atom # 5 C, 5, is greater than permitted
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6 8 9 10 11
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 15 16 18
[12:55:17] Explicit valence for atom # 28 C, 5, is greater than permitted
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 10 11 12 24 27
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 24
[12:55:17] Explicit valence for atom # 17 C, 6, is greater than permitted
[12:55:17] Explicit valence for atom # 0 C, 5, is greater than permitted
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5 6 7 8 10
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 1 2 23 24
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 3 4 5 6 26 27 28 32 33 34 35 36 37
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 3 4 5 7 8 9 10 11 14 15 16 17 18 19 26
[12:55:17] Explicit valence for atom # 29 C, 5, is greater than permitted
[12:55:17] Explicit valence for atom # 4 C, 5, is greater than permitted
[12:55:17] SMILES Parse Error: unclosed ring for input: 's1c(-c2sc(C3(O)CCC4C(C(C)Oc5ccc6c(oc(C)c5)C4=O)(C(O)=O)C3)c(C)n2)cc2c1cccc2'
[12:55:17] Explicit valence for atom # 0 N, 4, is greater than permitted
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 10 12 14 17
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 13 24 25 26 27 28 29
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 5 7 19 27
[12:55:17] Explicit valence for atom # 19 C, 5, is greater than permitted
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 6 7 8 28 29 30 31
[12:55:17] SMILES Parse Error: unclosed ring for input: 'c12ccoc1cc1c(c3c(o1)C=C1C(CCCN11)C3)c2'
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 2 3 10 11 12 33 34 35
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 6 8 9 11 12 13 33
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 6 7 8 9 10
[12:55:17] SMILES Parse Error: duplicated ring closure 5 bonds atom 8 to itself for input: 'C1(C2C3(OC)CCC4(C55c6c(ccc(O)c6OC42)C5)CCN3CC2CC2)CCC1'
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 1 6 17 18 19 20 23 26 27 28
[12:55:17] Explicit valence for atom # 17 C, 5, is greater than permitted
[12:55:17] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 3 4 5 6 7 8 9 10 12 13 14 15 16
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5 6 18 19 20 21 23
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 7 8 11 12 13
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 5 6 7 25 26
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17
[12:55:17] Explicit valence for atom # 8 C, 5, is greater than permitted
[12:55:17] SMILES Parse Error: unclosed ring for input: 'OC(C)C1COC(=O)N1c2cc[nH]c(=NC(C)c2c(OC)nccc1)C'
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 1 3 4 5 6 7 43 44
[12:55:17] Explicit valence for atom # 10 C, 5, is greater than permitted
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 7 27 29
[12:55:17] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 10 11 12 14 23 24 25 28 34
[12:55:17] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:55:17] Explicit valence for atom # 9 C, 5, is greater than permitted
[12:55:17] SMILES Parse Error: ring closure 2 duplicates bond between atom 17 and atom 18 for input: 'C1(c2ccc(-c3ccccc3OC)s2)(O)CCC2C2(C)CCC2C3(C)CCC(=O)C=C3CCC12'
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 11 12 13 18 22
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 1 14 15 16 17 22 23 24 25 26
[12:55:17] SMILES Parse Error: unclosed ring for input: 'C1COCCN1CCC1(O)CCC2C3CCC4=Cc5c(cc(-n6cc(-c7ccc(F)cc6)nn6)c(OC)c5)CC4(C)C3CCC12C'
[12:55:17] Explicit valence for atom # 17 O, 3, is greater than permitted
[12:55:17] SMILES Parse Error: unclosed ring for input: 'c1ccc2c(c1)C(NC(C(CC(O)C(CC1CCCCC1)NC(=O)c1cc(-c1ccccc1S(C)(=O)=O)=O)Cc1ccccc1)O)C(O)C2'
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 21 22 23 24 36 37
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6 16 17 20 21 22 23
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 10 11 13 14 16 17 19
[12:55:17] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:55:17] Explicit valence for atom # 11 C, 5, is greater than permitted
[12:55:17] SMILES Parse Error: unclosed ring for input: 'C1C2C34OOC(C)(CCC3C(C)CC2)OC4OC1(CO)O1'
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 6 9 10 11 12 13 14 15 16 17
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6 7 11 14 16 18 19
[12:55:17] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 6 7 8 9 10 20 38 39 40 41 42
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 8 9 10 12 14
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 14
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 1 2 5 7 8 9 10 11 12 13 14 15 16 17 18
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 16 17 20 22 23 24 25 26 27 28 29
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 11 12 13 14 15 16 17 18 19
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 6 7 8 9 10 11 12 13 14 15 16 17 18
[12:55:17] SMILES Parse Error: unclosed ring for input: 'C1C(=NOCc2ccccc2)C2C(CO)(C(=O)C3(O)C(C2)C24C(O)(C(C)(C5(O)CC2)CC(=O)C4CC(=O)C3)OC(c2ccccc2)(O5)O2)CC2C1O2'
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 22 23 24 30 31
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6 7 8 9 10
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 1 2 31 32 34 35 37 38
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 1 2 7 8 9 10 11 12 15 16
[12:55:17] Explicit valence for atom # 11 C, 5, is greater than permitted
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 18 20 21 22 23 24 25
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 4 5 6 7 8 9 15
[12:55:17] Explicit valence for atom # 8 C, 5, is greater than permitted
[12:55:17] SMILES Parse Error: ring closure 5 duplicates bond between atom 9 and atom 10 for input: 'C12(O)C3(O)CCC(C)(C4C5(O5)C(C)CC(=O)C4=C)C(c4ccoc4)CC3CC1C2'
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 7 8 9 10 11 12 18 19 20 21 22
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 9 10 11 28 29 30 31 32 34
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 19 20 21 22 23 24 25 26 27
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 8 9 10 11 12 14 15 26 27
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 11 12 13 14 15 17 19
[12:55:17] Explicit valence for atom # 15 O, 3, is greater than permitted
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 8 32 33
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 9 10 14 17 19
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 7 8 19 20 21 22 23
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 1 7 8 9 10 11
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 4 5 6 9 10 14 19
[12:55:17] Explicit valence for atom # 16 N, 5, is greater than permitted
[12:55:17] Explicit valence for atom # 12 C, 5, is greater than permitted
[12:55:17] Explicit valence for atom # 22 C, 6, is greater than permitted
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 1 2 4 5 6 8 9 12
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 11 12 13
[12:55:17] SMILES Parse Error: ring closure 1 duplicates bond between atom 9 and atom 10 for input: 'c1(OC)ccc2c3c1OC1C14C(c1cccnc1)CCC4(O)C(C2)N(CC1CC1)CC3'
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 4 5 6 28 29
[12:55:17] SMILES Parse Error: unclosed ring for input: 'c1c(C=C2C3CCC4(C)C5(CC(c6ccccc6)OC6C5)C5C(CC4C2C3)C2(C)C(=CC(=O)CC2)CO5)ccc(C)c1'
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 18 23 24
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 4 5 6 7 8 9 10 12 13 14 16 17 18
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 10 11 12 13 14 15 16 17 18
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 8 10 11 12 13 14 15 28 29
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 6 7 8 9 10 11 12 30 31 32 33 34 35
[12:55:17] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 6 7 8 9 11 12
[12:55:17] Explicit valence for atom # 9 C, 5, is greater than permitted
[12:55:17] SMILES Parse Error: unclosed ring for input: 'c1nc2c(C[n+]3ccccc3)c3c(c(O)c2c(NCCCNCCCNCCCCNC(C(=Cc2c(N)c(C)ccc2)c1ccc(F)cc1)(C)C)=O)cccc3'
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 1 2 3 14 15 16 17 18 19
[12:55:17] Explicit valence for atom # 9 C, 5, is greater than permitted
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 1 4 5 6 7 8 9 13 22 23
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 1 6 7 24 25 26 27 28
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 3 4 5 6 17 18
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 1 2 4 6 7 24 25 28 29 30
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 4 5 7 8 11 12 31 32 33 34 35
[12:55:17] Explicit valence for atom # 4 N, 6, is greater than permitted
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 7 8 28
[12:55:17] Explicit valence for atom # 10 C, 5, is greater than permitted
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 6 7 8 9 10 11 12
[12:55:17] SMILES Parse Error: unclosed ring for input: 'C1C(F)CC2=C3C(OC(=O)c4ccccc4)C(C(=O)C)(O)C2(C)C1OC(C)=O'
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 2 17 18 20 21 22 23 24 25 26 27 28
[12:55:17] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 1 5 13 15 16 17 18 23
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 6 7 28
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 4 5 6 7 8 9 10 11 12 39 40
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 6 7 17
[12:55:17] Explicit valence for atom # 8 C, 5, is greater than permitted
[12:55:17] SMILES Parse Error: extra open parentheses while parsing: FC(C(CNC(c1c(Sc2cc3n[nH]c(C=Cc4ncccc4)c3cc2)cccc1)=O)(CC1CC1)OC(=O)CC(C)(C)C
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 5 6 7 36 37 38 39 40 41
[12:55:17] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:55:17] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 1 2 5 6 8 15 17 18
[12:55:17] SMILES Parse Error: check for mistakes around position 3:
[12:55:17] Explicit valence for atom # 11 C, 5, is greater than permitted
[12:55:17] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:55:17] FC(C(CNC(c1c(Sc2cc3n[nH]c(C=Cc4ncccc4)c3c
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 12 13 14 15 17 18 19 34 36 37 39
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 8 9 10 11 12
[12:55:17] Explicit valence for atom # 39 F, 2, is greater than permitted
[12:55:17] SMILES Parse Error: unclosed ring for input: 'C12(CC3(O)C45c6c(ccc(O)c6OC4c4c(c5cccc5n4CCCC)C3)C1)CCC(=O)C2'
[12:55:17] ~~^
[12:55:17] Explicit valence for atom # 16 C, 5, is greater than permitted
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 1 2 9 11 22 23
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 6 7 8 21 22 24 26
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 1 2 9 10 12 19 20
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 1 2 7 8 9 22
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 6 7 8
[12:55:17] SMILES Parse Error: ring closure 4 duplicates bond between atom 29 and atom 30 for input: 'C1C2C3CCC4=CC(=O)C=CC4(C)C3(F)C(O)CC2(C)C(OC(C23C4C(=CC5OC44C4CCC2(C)C3S(=O)(=O)N2CCC2)=O)OCCO5)C1'
[12:55:17] Explicit valence for atom # 17 C, 5, is greater than permitted
[12:55:17] SMILES Parse Error: ring closure 3 duplicates bond between atom 17 and atom 24 for input: 'C1(OC(CC(C)(CC(=O)O)C)=O)C2C(C(C)CC3(CC(=C)C2(C)C)C3(O)C)C(C)=CC1'
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 11 12 13 14 15 16 17 18 19
[12:55:17] SMILES Parse Error: Failed parsing SMILES 'FC(C(CNC(c1c(Sc2cc3n[nH]c(C=Cc4ncccc4)c3cc2)cccc1)=O)(CC1CC1)OC(=O)CC(C)(C)C' for input: 'FC(C(CNC(c1c(Sc2cc3n[nH]c(C=Cc4ncccc4)c3cc2)cccc1)=O)(CC1CC1)OC(=O)CC(C)(C)C'
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 5 6 14
[12:55:17] SMILES Parse Error: ring closure 4 duplicates bond between atom 22 and atom 40 for input: 'C1CC(C)C(O)(C(CSc2nc3ccccc3s2)=O)C2CCC34C5(C(C6(C)CCC(O)C(CO)(C)C6CC5)CCC34C)C12C'
[12:55:17] Explicit valence for atom # 14 C, 5, is greater than permitted
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 7 8 9 10 11 17 26 27 28 29 30 31 32
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 10 13 23
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 33 34 35
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 9 10 11 12 13 14 15 17 18 19 20 24 25 27 28
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 1 2 3 9 10 11 12 13 14
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 1 2 30 31 33 34 35 36
[12:55:17] Explicit valence for atom # 12 C, 5, is greater than permitted
[12:55:17] SMILES Parse Error: unclosed ring for input: 'O=C1OC(c2cocc2)C2(C)CC(=O)C3C4(C)C(CC(OC(=O)C)C33C12C(C)(Oc1c2c(ccc3O)CC3CC2CCC(C)(C)C35C)cccc14)OC(C)(C)OO3'
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 1 5 6 10 11 12 13 15 16 17 18 19 20 21 24 25 26 27 28 29
[12:55:17] Explicit valence for atom # 9 C, 5, is greater than permitted
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 16 17 18 19 20
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 2 24 30 31 32 33
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 8 9 10 14 15 16 17
[12:55:17] SMILES Parse Error: unclosed ring for input: 'c1cc2[nH]c3c4c(c5c(c32)CCc2c-4cn(C)n2)C(=O)N1C(CO)C'
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 8 11 12 13 14 24 26 27 28 29
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5 6 7 8 11
[12:55:17] Explicit valence for atom # 3 C, 7, is greater than permitted
[12:55:17] Explicit valence for atom # 1 N, 4, is greater than permitted
[12:55:17] Explicit valence for atom # 16 C, 5, is greater than permitted
[12:55:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[12:55:17] Explicit valence for atom # 8 S, 8, is greater than permitted
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 1 17 18 20 21 22 23 24 25 26
[12:55:17] SMILES Parse Error: unclosed ring for input: 'C12C3C4C(C5(NC(=O)C)CC6C(=C)CCC(CNc7ccc8c(c5)NCCO8)(C)C4(C)C=CC3=NCCC6)C(=C1)CC2C(C)=C'
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 1 14 15 16 17 18 20 21 22 23 24 25
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5 6 7 8 9 11 13 14 15 16 17 18 19 20 21
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 17 18 19
[12:55:17] Explicit valence for atom # 0 C, 5, is greater than permitted
[12:55:17] Explicit valence for atom # 8 C, 5, is greater than permitted
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 1 3 17
[12:55:17] Explicit valence for atom # 42 O, 3, is greater than permitted
[12:55:17] SMILES Parse Error: extra close parentheses while parsing: O=C(c1nc2n(c1)CCOc1c-2cc(C#CC(C)(C)O)cc1)NC1C(O)CCS2(=O)=O)cnn2c1
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 22 23 25 26
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 7 18 30
[12:55:17] SMILES Parse Error: check for mistakes around position 59:
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 10 11 12 13 14 15 16 17 18
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 1 3 4 5 6 7 8 9 13 14 15 16 17 18
[12:55:17] c1)NC1C(O)CCS2(=O)=O)cnn2c1
[12:55:17] Explicit valence for atom # 20 C, 5, is greater than permitted
[12:55:17] SMILES Parse Error: unclosed ring for input: 'c1cc(NC(=O)CCCCCC(C)=O)ccc1CC1C(Cc2cc3c(cc2)OCO5)COC(C)C3OC1=O'
[12:55:17] ~~~~~~~~~~~~~~~~~~~~^
[12:55:17] SMILES Parse Error: Failed parsing SMILES 'O=C(c1nc2n(c1)CCOc1c-2cc(C#CC(C)(C)O)cc1)NC1C(O)CCS2(=O)=O)cnn2c1' for input: 'O=C(c1nc2n(c1)CCOc1c-2cc(C#CC(C)(C)O)cc1)NC1C(O)CCS2(=O)=O)cnn2c1'
[12:55:17] SMILES Parse Error: unclosed ring for input: 'CC1CC2(O)C(C=C(C)C3C(C(=C)CC3)C2)C2OC(O3)C2(O)C1'
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 9 10 11 12 14 15 16 17 18 19 20
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 1 7 19 20 21 22 23 24 25 26
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 12 13 14 15 16 18 19 30 31
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 1 2 7 9
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 5 6 7 8 17 18 19 37 39
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 14 15 16 23 24 25
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 11 12 13 14 15
[12:55:17] SMILES Parse Error: unclosed ring for input: 'c1ccc(C#CC2(O)C3(C)COC4(CC3)C35C(O2)C2C(C)(C3(O)C(O)C6(C)CCC24)CN(C)C5=O)nc1'
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 27 28 29
[12:55:17] Explicit valence for atom # 5 C, 5, is greater than permitted
[12:55:17] Explicit valence for atom # 9 C, 5, is greater than permitted
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 1 2 4 5 6 21 22 23 24
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 14 15 16 17 22 24 25
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 4 5 7 8 10 11 12 13 14 15 16
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 6 7 10 11 12 13 14 19
[12:55:17] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 3 4 5 6 7 11 12 13 14
[12:55:17] Explicit valence for atom # 12 C, 5, is greater than permitted
[12:55:17] Explicit valence for atom # 20 C, 5, is greater than permitted
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 6 7 12 13 14 24 25 29 30 31 32
[12:55:17] Explicit valence for atom # 17 C, 5, is greater than permitted
[12:55:17] Explicit valence for atom # 12 C, 5, is greater than permitted
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 12 13 14 15 16 17 22 23 24
[12:55:17] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 4 5 6 8 9 12 14 15 16 17 18 19 20
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 9 10 11 12 13 14 15 16 17 18 19 29 30 31 34 35 36
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 6 7 8 12 13 14 15 16 17 18 19
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 10 11 21 22
[12:55:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[12:55:17] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 3 5 10
[12:55:17] SMILES Parse Error: ring closure 5 duplicates bond between atom 5 and atom 17 for input: 'C(#N)C12CC3(C45N=Cc6c(cccc6)N=C(C)C54)ccc3C(=O)N1CCc1c2cc(OC)c(OC)c1'
[12:55:17] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 1 2 20 21 22 23 24 25 30 31
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 10 21 23 24 25
[12:55:17] Explicit valence for atom # 16 C, 5, is greater than permitted
[12:55:17] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 15 29 30

--- Processing cluster 4 ---

[12:55:36] SMILES Parse Error: unclosed ring for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(CCN(C(=O)C1CC13c1cccnc11)CC3)CCCC2'
[12:55:36] Explicit valence for atom # 22 S, 6, is greater than permitted
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 19 20 21 22 24 25 27
[12:55:36] SMILES Parse Error: unclosed ring for input: 'O=C1C=CC2(C)C(=C1)CCC1C3CCC(O)(C(=O)CSc4nc5c(n4CC)ccc(Cl)c3)CC21C'
[12:55:36] Explicit valence for atom # 23 C, 5, is greater than permitted
[12:55:36] Explicit valence for atom # 18 N, 4, is greater than permitted
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 31 32 33
[12:55:36] SMILES Parse Error: unclosed ring for input: 'C1C2=Cc3c(cnn3-c3ccc(F)cc3)CC2(C)C(=O)C1C=CC(C)1O'
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 19 20 21 22 23 29 30 31 32 34 35
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 21 23 24
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 34 35 36
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 9 10 11 12 13 20 21 22 25 26 27 30 31
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 24 25 26
[12:55:36] Explicit valence for atom # 25 C, 6, is greater than permitted
[12:55:36] SMILES Parse Error: ring closure 1 duplicates bond between atom 25 and atom 27 for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(C)C(C(C1(O)CC3CC1C1(C)C1(C)CCCC3)CC2)=O'
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 18 19 20 28 29
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 26 27 28 29 35
[12:55:36] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 0 29 48 49 51
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 19 20 21 22 23 24 25 26 27
[12:55:36] SMILES Parse Error: unclosed ring for input: 'c1(-n2ncc3cc(OC(c4cc5nc(-c6cn(C)nc7)cnc5cc4)C)ccc32)cccc(C2(O)CCNCC2)c1'
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 23 24 25 27 29
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 33 36 37 38 39
[12:55:36] SMILES Parse Error: unclosed ring for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(CCN(S(=O)(CCC1C(O)CCC5CC1)=O)CCC2)CCCCCC1CC1'
[12:55:36] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:55:36] SMILES Parse Error: unclosed ring for input: 'C12=Cc3c(cnn3-c3ccc(F)cc4)cc3CC1(C)N(C(C1CCN(C(=O)C3CCCN3C(c3ccc(OC)nc3)=O)CC1)=O)CC2'
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 31 32 42
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 2 3 5 6 7 8 9 10 11 13 14 15 17 19 20
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 25 26 27 28 29
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 1 2 5
[12:55:36] Explicit valence for atom # 18 N, 4, is greater than permitted
[12:55:36] SMILES Parse Error: unclosed ring for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(C)C(N1CCC(C3(C)CC3c4c(cc(Cl)c(F)c4)NC3=O)CC1)CC2'
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 23 24 25 26 28 29 30 33 35
[12:55:36] Explicit valence for atom # 18 N, 4, is greater than permitted
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 24 25 26 28 29 31 33
[12:55:36] Explicit valence for atom # 18 N, 4, is greater than permitted
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 19 20 22 23 24 25 26
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 32 33 34 35 37
[12:55:36] Explicit valence for atom # 21 C, 5, is greater than permitted
[12:55:36] SMILES Parse Error: extra close parentheses while parsing: C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(C)C(N(C(=O)C1CCCO1)Cc1cc(C)c(O)c(C)c1)CCC2)(F
[12:55:36] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:55:36] SMILES Parse Error: check for mistakes around position 73:
[12:55:36] Explicit valence for atom # 22 N, 4, is greater than permitted
[12:55:36] SMILES Parse Error: unclosed ring for input: 'c1cc(-n2ncc3cc(OC(c4ccc(OC)cc4)C(NC(=O)C(F)(C)C)C)ccc23)ncc1-c2ccc(O)cc1'
[12:55:36] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:55:36] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:55:36] cc(C)c(O)c(C)c1)CCC2)(F
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 23 24 25 26 27 28 29 30 31 32 33 35 36
[12:55:36] ~~~~~~~~~~~~~~~~~~~~^
[12:55:36] SMILES Parse Error: Failed parsing SMILES 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(C)C(N(C(=O)C1CCCO1)Cc1cc(C)c(O)c(C)c1)CCC2)(F' for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(C)C(N(C(=O)C1CCCO1)Cc1cc(C)c(O)c(C)c1)CCC2)(F'
[12:55:36] Explicit valence for atom # 22 C, 5, is greater than permitted
[12:55:36] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:55:36] Explicit valence for atom # 19 N, 4, is greater than permitted
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 23 24 25 26 27
[12:55:36] Explicit valence for atom # 19 N, 4, is greater than permitted
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 21 22 23 30 31
[12:55:36] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:55:36] Explicit valence for atom # 27 N, 4, is greater than permitted
[12:55:36] SMILES Parse Error: ring closure 2 duplicates bond between atom 0 and atom 12 for input: 'C123C(CCC4C(C(O)(C)C)CCC21)C1(C)C(CCC3C(C)(C)C(=O)C=C1)CC4'
[12:55:36] Explicit valence for atom # 18 N, 4, is greater than permitted
[12:55:36] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:55:36] SMILES Parse Error: ring closure 1 duplicates bond between atom 21 and atom 28 for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(C)C(O)CC(C1(CCCCCC)C1)C2'
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 19 20 22 23 24 25 26
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 28 29 32 33 34
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 37
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 30
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 19 20 21 22 23 24 25 27 28
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 6 7 8 9 10 11 12 13 14 15 16 31 32 34 35 37 38
[12:55:36] Explicit valence for atom # 21 C, 5, is greater than permitted
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 36
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 0 1 33 44 45
[12:55:36] SMILES Parse Error: ring closure 1 duplicates bond between atom 20 and atom 21 for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(CNC(=O)N1C1CC1CC1C)CC(C)(C)NC2=O'
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6 31 32
[12:55:36] Explicit valence for atom # 26 C greater than permitted
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 23 24 25 28 29
[12:55:36] SMILES Parse Error: ring closure 1 duplicates bond between atom 18 and atom 29 for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(C)C(C1(c3cc4c(cc3)N(C)CC4)C1)CCC2'
[12:55:36] SMILES Parse Error: ring closure 1 duplicates bond between atom 20 and atom 33 for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(CCN(C(C1(C3COCC3c3ccc(F)cc3)C1)=O)C)CCC2'
[12:55:36] SMILES Parse Error: ring closure 1 duplicates bond between atom 21 and atom 22 for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(COCCN(C1C1CC(C)C)CC2)CCCF'
[12:55:36] SMILES Parse Error: unclosed ring for input: 'C12=Cc3c(cnn3-c3ccc(F)cc4)cc3CC1(COCC1COCC1)CCCC2Cc1cncn1C'
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 24 25 36
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 34 35 36
[12:55:36] SMILES Parse Error: unclosed ring for input: 'C12C(=Cc3c(F)cc(C)cc3)CC3=Cc4c(cnn4-c5ccc(F)cc3)CC1(C)C(C(=O)CSc1ocnn1)CC2'
[12:55:36] Explicit valence for atom # 18 N, 4, is greater than permitted
[12:55:36] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:55:36] SMILES Parse Error: ring closure 1 duplicates bond between atom 18 and atom 19 for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(CCN1C1(C(F)(F)F)c1ccccn1)CCC2'
[12:55:36] SMILES Parse Error: unclosed ring for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(C)C(=NO1)CC(C(F)(Sc1cc(F)cnc1)C)CC2'
[12:55:36] Explicit valence for atom # 36 S, 7, is greater than permitted
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 8 13 14 15 16 17 19
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 23 24 28
[12:55:36] Explicit valence for atom # 12 C greater than permitted
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 20 21 22 23 24 25 35 36 37
[12:55:36] Explicit valence for atom # 6 C greater than permitted
[12:55:36] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 19 20 21 22 25
[12:55:36] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 19 20 21 23 24 32 33
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 18 19 20 28 29 37 38
[12:55:36] SMILES Parse Error: ring closure 4 duplicates bond between atom 26 and atom 27 for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(C)C(C(N1CCN(c3noc4c4CCCC3)CC1)=O)CC2'
[12:55:36] SMILES Parse Error: unclosed ring for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(C)C(C(N1C(C(=O)N3CC4(C)CC3CC(C)(C3)C4)C1)=O)CCC2'
[12:55:36] Explicit valence for atom # 18 N, 4, is greater than permitted
[12:55:36] Explicit valence for atom # 18 N, 4, is greater than permitted
[12:55:36] Explicit valence for atom # 8 S, 6, is greater than permitted
[12:55:36] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 25
[12:55:36] Explicit valence for atom # 24 C, 5, is greater than permitted
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 26 27 28 34
[12:55:36] Explicit valence for atom # 19 N, 4, is greater than permitted
[12:55:36] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:55:36] Explicit valence for atom # 23 C, 5, is greater than permitted
[12:55:36] Explicit valence for atom # 17 N, 4, is greater than permitted
[12:55:36] Explicit valence for atom # 18 N, 4, is greater than permitted
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 19 20 21 22 23
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 0 1 34 35 36 37 38
[12:55:36] Explicit valence for atom # 20 C, 5, is greater than permitted
[12:55:36] Explicit valence for atom # 19 O, 3, is greater than permitted
[12:55:36] Explicit valence for atom # 19 N, 4, is greater than permitted
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 26 29 30 31
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 18 19 20 22 25
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 29 30 33 34 35
[12:55:36] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 21 22 23 24 30 31 32
[12:55:36] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:55:36] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 30
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 26 27 28 29 40
[12:55:36] SMILES Parse Error: ring closure 1 duplicates bond between atom 29 and atom 30 for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(C)C(C(C(NCc1c3c(ccc1O)n1c1C=CCCC3)=O)C)CC2'
[12:55:36] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 21 22 24 25 26 28 29
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 16 17 19 20 21 23 24 26 28
[12:55:36] SMILES Parse Error: unclosed ring for input: 'c1(Cl)nc2c(SC)ncc(-c3cc(F)c(C2(C)C(=O)N(C)CCC3)c2)cc1'
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 22 23 30
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 27 28 29 30 31
[12:55:36] SMILES Parse Error: ring closure 1 duplicates bond between atom 23 and atom 25 for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(C)C(O)CC(C(NC1(C)C1)=O)C2'
[12:55:36] Explicit valence for atom # 18 N, 4, is greater than permitted
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 21 22 23 27 28
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 21 22 32
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 5 6 7 8 9 10 15 16 17
[12:55:36] SMILES Parse Error: unclosed ring for input: 'c1(-n2ncc3cc(OC(c4ccc4c(c4)OCCC5C)C4CCC5(c5cc(O)ccc5)C4)cc23)nc(C)nc(C)c1'
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 0 2 3 4 5 6 7
[12:55:36] Explicit valence for atom # 18 N, 4, is greater than permitted
[12:55:36] Explicit valence for atom # 18 N, 4, is greater than permitted
[12:55:36] SMILES Parse Error: ring closure 1 duplicates bond between atom 17 and atom 18 for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(CN1C1CN(C(=O)C1(F)CC1)CC1CCC1)CCC2'
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 27
[12:55:36] Explicit valence for atom # 18 N, 4, is greater than permitted
[12:55:36] SMILES Parse Error: unclosed ring for input: 'C12=Cc3n(-c4ccc(F)cc4)ncc3CC1(C)C(C(N(C2CC1C)C1CC1)C)CCC2'
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 29 30 33
[12:55:36] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:55:36] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 19 20 21 29 30
[12:55:36] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 23 41 43
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 5 6 7 8 11 12 13 14 18
[12:55:36] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 27
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 10 11 12 31 32
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 25 26 28 29 30
[12:55:36] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 19 20 21 23 24 33
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 21 22 27
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 16 17 18 19 28
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 28 29 30 31 32 34 35 37 38
[12:55:36] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 19 20 21 25 26 27 28 29 30 31 33
[12:55:36] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 19 20 22 24 25 26 27
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 26 27 29 31 33 36 37 39 40
[12:55:36] Explicit valence for atom # 2 C greater than permitted
[12:55:36] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 21 23 25 26 27 35 37
[12:55:36] Explicit valence for atom # 22 N, 4, is greater than permitted
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 29 30 31 32 33 34 35 38 39
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 36
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6 28 29 31 34 41 42 44 45
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 21 22 23 26 27 28 32 33 34
[12:55:36] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 23 24 25 32 33
[12:55:36] Explicit valence for atom # 21 C, 5, is greater than permitted
[12:55:36] SMILES Parse Error: ring closure 1 duplicates bond between atom 18 and atom 19 for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(C)C(C1C1(C)C(=O)CC2)C'
[12:55:36] SMILES Parse Error: ring closure 1 duplicates bond between atom 17 and atom 18 for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(CN1c1c(-c1n(C3CCCNCC3)ccc1)CC)CCC2'
[12:55:36] SMILES Parse Error: unclosed ring for input: 'CC(NC(=O)C(F)(F)F)C(Oc1ccc2c(cnn2C)c1)c1ccc2c(c1)OCC3N2CC=C'
[12:55:36] Explicit valence for atom # 23 C, 5, is greater than permitted
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 29 30 32
[12:55:36] SMILES Parse Error: ring closure 1 duplicates bond between atom 18 and atom 19 for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(C)C(C1(C1C=C)CN(CCc1ccccc1)C2)C'
[12:55:36] Explicit valence for atom # 20 C, 5, is greater than permitted
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 27 28 29
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 23 24 28
[12:55:36] SMILES Parse Error: unclosed ring for input: 'c1(-n2ncc3cc(OC(c4cc(OCc5cc5ccccc6cn5)ccc4)C(C)NC(C4CC4)=O)ccc32)ncccn1'
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6 21 22 23 24 26 27
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 38
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 18 19 20 22 32
[12:55:36] Explicit valence for atom # 18 C, 6, is greater than permitted
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 32 39 40
[12:55:36] Explicit valence for atom # 21 C, 5, is greater than permitted
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 20 21 22 23 24
[12:55:36] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 2 3 5 7 9 10 11
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 19 20 22 23 25 40 41 42 43 44 45 46 47 48
[12:55:36] Explicit valence for atom # 22 N, 4, is greater than permitted
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 21 22 23 24 26 27 28
[12:55:36] Explicit valence for atom # 17 N, 4, is greater than permitted
[12:55:36] SMILES Parse Error: unclosed ring for input: 'C12=Cc3c(cnn3-c3ccc(F)cc4)cc3CC1(C)C(C(=O)N(Cc1nonc1C)CN(C)C)CC2'
[12:55:36] SMILES Parse Error: duplicated ring closure 1 bonds atom 21 to itself for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(CCN(C(=O)C11CC1)CC(C)(C)C2)CC'
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 17 18 19 20 34 35 36
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 23 24 26 27 45
[12:55:36] Explicit valence for atom # 18 N, 4, is greater than permitted
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 6 7 8 9 10 11 12 21 22 23 24
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 19 22 23 33
[12:55:36] SMILES Parse Error: ring closure 1 duplicates bond between atom 23 and atom 30 for input: 'C12=Cc3c(cnn3-c3ccc(F)cn3)CC1(COCCN(C(=O)C1(c3cnn(C)c3)C1)C)CCC2'
[12:55:36] Explicit valence for atom # 18 N, 4, is greater than permitted
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 24 25 26
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 19 20 21 22 23 25 26 27 33
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 27
[12:55:36] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 23 24 25 27 28 29 30 31 32 33 34 35 36
[12:55:36] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:55:36] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 22 23 25 26 35
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 22 23 24
[12:55:36] Explicit valence for atom # 21 C, 5, is greater than permitted
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 19 20 22 23 24 25 26
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6 12 13
[12:55:36] SMILES Parse Error: unclosed ring for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(CCN(S(C1CC1)(=O)=O)CC3CC1)CCCC2'
[12:55:36] Explicit valence for atom # 17 N, 4, is greater than permitted
[12:55:36] non-ring atom 22 marked aromatic
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 22 23 24 25 34
[12:55:36] SMILES Parse Error: unclosed ring for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(C(=O)c2ccc[n+]([O-])c1)CCCCCCC(F)(F)F'
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 45
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 9 10 11 12 13 14 27
[12:55:36] Explicit valence for atom # 24 N, 4, is greater than permitted
[12:55:36] Explicit valence for atom # 26 S, 6, is greater than permitted
[12:55:36] non-ring atom 10 marked aromatic
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 20 21 22 23 28 29 30
[12:55:36] SMILES Parse Error: unclosed ring for input: 'C12=Cc3c(cnn3-c3ccc(F)cc3)CC1(C)C(C(c1c3c(n(C)c1)c(C4=CCNCC4)c(F)cc1CC3)=O)CC2'
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 19 20 21 23 28 29 30
[12:55:36] SMILES Parse Error: unclosed ring for input: 'c1(-n2ncc3cc(OC(c4ccc(OC)cc4)C(C)NC(=O)C(F)(F)F)ccc23)cc(-c1nc(C2CC2)ncc1)CO'
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 23 24 25 26 27 28 29
[12:55:36] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 32 33 36 37 38 39 42 43 46
[12:55:36] Explicit valence for atom # 18 N, 4, is greater than permitted

Calculation complete! Processed 5 clusters

                 name type_cluster scaffold        RS       SED      ASER
0     REINVENT_250k_0          dis      csk  0.150000  0.108233  0.000761
1     REINVENT_250k_1          dis      csk  0.391304  0.182030  0.000207
2     REINVENT_250k_2          dis      csk  0.050000  0.122522  0.000020
3     REINVENT_250k_3          dis      csk  0.675676  0.231956  0.013635
4     REINVENT_250k_4          dis      csk  0.395349  0.194727  0.007512
5  REINVENT_250k_mean          dis      csk  0.332466  0.167894  0.004427

DrugEx_GT_epsilon_0.1_250k

============================================================
Starting calculation for DrugEx_GT_epsilon_0.1_250k
Receptor: Glucocorticoid_receptor
Cluster type: dis
Scaffold type: csk
CPUs: 100
============================================================

--- Processing cluster 0 ---

--- Processing cluster 1 ---

[12:56:19] Explicit valence for atom # 20 C, 5, is greater than permitted
[12:56:19] Explicit valence for atom # 17 C, 5, is greater than permitted
[12:56:20] Explicit valence for atom # 10 C, 5, is greater than permitted
[12:56:21] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:56:21] Explicit valence for atom # 9 C, 5, is greater than permitted
[12:56:21] Explicit valence for atom # 19 C, 5, is greater than permitted
[12:56:21] Explicit valence for atom # 37 C, 5, is greater than permitted
[12:56:21] Explicit valence for atom # 1 C, 5, is greater than permitted

--- Processing cluster 2 ---

[12:56:39] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:56:41] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:56:42] Explicit valence for atom # 9 C, 5, is greater than permitted
[12:56:44] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[12:56:44] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[12:56:44] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[12:56:44] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[12:56:44] Explicit valence for atom # 25 C, 5, is greater than permitted
[12:56:44] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:56:45] Explicit valence for atom # 8 C, 6, is greater than permitted

--- Processing cluster 3 ---

[12:57:04] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:57:04] Explicit valence for atom # 13 C, 5, is greater than permitted
[12:57:04] Explicit valence for atom # 26 C, 5, is greater than permitted
[12:57:05] Explicit valence for atom # 33 C, 5, is greater than permitted
[12:57:05] Explicit valence for atom # 16 C, 5, is greater than permitted
[12:57:05] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:57:06] Explicit valence for atom # 5 C, 5, is greater than permitted
[12:57:08] Explicit valence for atom # 21 C, 5, is greater than permitted
[12:57:08] Explicit valence for atom # 13 C, 5, is greater than permitted
[12:57:08] Explicit valence for atom # 14 C, 5, is greater than permitted
[12:57:08] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:57:09] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:57:11] Explicit valence for atom # 35 C, 5, is greater than permitted

--- Processing cluster 4 ---

[12:57:28] Explicit valence for atom # 5 C, 5, is greater than permitted
[12:57:30] Explicit valence for atom # 17 C, 5, is greater than permitted
[12:57:30] Explicit valence for atom # 15 C, 5, is greater than permitted
[12:57:30] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:57:31] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:57:32] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:57:32] Explicit valence for atom # 11 C, 5, is greater than permitted
[12:57:33] Explicit valence for atom # 37 C, 5, is greater than permitted
[12:57:34] Explicit valence for atom # 24 C, 5, is greater than permitted
[12:57:35] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:57:35] Explicit valence for atom # 33 C, 5, is greater than permitted

Calculation complete! Processed 5 clusters

,name,type_cluster,scaffold,RS,SED,ASER
0,DrugEx_GT_epsilon_0.1_250k_0,dis,csk,0.475000,0.243561,0.006802
1,DrugEx_GT_epsilon_0.1_250k_1,dis,csk,0.434783,0.198893,0.000601
2,DrugEx_GT_epsilon_0.1_250k_2,dis,csk,0.200000,0.222655,0.000188
3,DrugEx_GT_epsilon_0.1_250k_3,dis,csk,0.351351,0.209623,0.005742
4,DrugEx_GT_epsilon_0.1_250k_4,dis,csk,0.720930,0.270996,0.011319
5,DrugEx_GT_epsilon_0.1_250k_mean,dis,csk,0.436413,0.229146,0.004930

DrugEx_GT_epsilon_0.6_250k

============================================================
Starting calculation for DrugEx_GT_epsilon_0.6_250k
Receptor: Glucocorticoid_receptor
Cluster type: dis
Scaffold type: csk
CPUs: 100
============================================================

--- Processing cluster 0 ---

[12:57:51] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:57:51] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:57:51] Explicit valence for atom # 4 C, 5, is greater than permitted
[12:57:51] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:57:51] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:57:51] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:57:51] Explicit valence for atom # 26 C, 5, is greater than permitted
[12:57:52] Explicit valence for atom # 35 C, 5, is greater than permitted
[12:57:52] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:57:52] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:57:52] Explicit valence for atom # 12 C, 5, is greater than permitted
[12:57:52] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:57:52] Explicit valence for atom # 31 C, 5, is greater than permitted
[12:57:52] Explicit valence for atom # 8 C, 5, is greater than permitted
[12:57:53] Explicit valence for atom # 10 C, 5, is greater than permitted
[12:57:53] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:57:53] Explicit valence for atom # 44 C, 5, is greater than permitted
[12:57:54] Explicit valence for atom # 22 C, 5, is greater than permitted
[12:57:54] Explicit valence for atom # 23 C, 5, is greater than permitted
[12:57:54] Explicit valence for atom # 10 C, 5, is greater than permitted
[12:57:54] Explicit valence for atom # 21 C, 5, is greater than permitted
[12:57:54] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[12:57:54] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[12:57:54] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[12:57:54] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[12:57:54] Explicit valence for atom # 11 C, 5, is greater than permitted
[12:57:54] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:57:54] Explicit valence for atom # 13 C, 5, is greater than permitted
[12:57:54] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:57:54] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:57:55] Explicit valence for atom # 16 C, 5, is greater than permitted
[12:57:55] Explicit valence for atom # 10 C, 5, is greater than permitted
[12:57:55] Explicit valence for atom # 12 C, 5, is greater than permitted
[12:57:55] Explicit valence for atom # 23 C, 5, is greater than permitted
[12:57:55] Explicit valence for atom # 4 C, 5, is greater than permitted
[12:57:55] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:57:55] Explicit valence for atom # 37 C, 5, is greater than permitted
[12:57:56] Explicit valence for atom # 12 C, 5, is greater than permitted
[12:57:56] Explicit valence for atom # 38 C, 5, is greater than permitted
[12:57:57] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:57:57] Explicit valence for atom # 39 C, 5, is greater than permitted
[12:57:57] Explicit valence for atom # 8 C, 5, is greater than permitted
[12:57:58] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:57:59] Explicit valence for atom # 15 C, 5, is greater than permitted

--- Processing cluster 1 ---

[12:58:03] Explicit valence for atom # 8 C, 5, is greater than permitted
[12:58:03] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:58:03] Explicit valence for atom # 15 C, 5, is greater than permitted
[12:58:04] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:58:04] Explicit valence for atom # 35 C, 5, is greater than permitted
[12:58:04] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:58:04] Explicit valence for atom # 20 C, 5, is greater than permitted
[12:58:04] Explicit valence for atom # 14 C, 5, is greater than permitted
[12:58:04] Explicit valence for atom # 8 C, 5, is greater than permitted
[12:58:04] Explicit valence for atom # 4 C, 5, is greater than permitted
[12:58:04] Explicit valence for atom # 37 C, 5, is greater than permitted
[12:58:04] Explicit valence for atom # 12 C, 5, is greater than permitted
[12:58:04] Explicit valence for atom # 24 C, 5, is greater than permitted
[12:58:05] Explicit valence for atom # 32 C, 5, is greater than permitted
[12:58:05] Explicit valence for atom # 14 C, 5, is greater than permitted
[12:58:05] Explicit valence for atom # 32 C, 5, is greater than permitted
[12:58:05] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:58:05] Explicit valence for atom # 14 C, 5, is greater than permitted
[12:58:06] Explicit valence for atom # 17 C, 5, is greater than permitted

--- Processing cluster 2 ---

[12:58:13] Explicit valence for atom # 49 C, 5, is greater than permitted
[12:58:13] Explicit valence for atom # 21 C, 5, is greater than permitted
[12:58:13] Explicit valence for atom # 15 C, 5, is greater than permitted
[12:58:13] Explicit valence for atom # 9 C, 5, is greater than permitted
[12:58:13] Explicit valence for atom # 13 C, 5, is greater than permitted
[12:58:14] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:58:14] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:58:14] Explicit valence for atom # 36 C, 5, is greater than permitted
[12:58:14] Explicit valence for atom # 16 C, 5, is greater than permitted
[12:58:14] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:58:14] Explicit valence for atom # 33 C, 5, is greater than permitted
[12:58:14] Explicit valence for atom # 22 C, 5, is greater than permitted
[12:58:14] Explicit valence for atom # 33 C, 5, is greater than permitted
[12:58:14] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:58:14] Explicit valence for atom # 35 C, 5, is greater than permitted
[12:58:15] Explicit valence for atom # 22 C, 5, is greater than permitted
[12:58:15] Explicit valence for atom # 11 C, 5, is greater than permitted
[12:58:15] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:58:15] Explicit valence for atom # 19 C, 5, is greater than permitted
[12:58:15] Explicit valence for atom # 33 C, 5, is greater than permitted
[12:58:15] Explicit valence for atom # 17 C, 5, is greater than permitted
[12:58:15] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:58:15] Explicit valence for atom # 34 C, 5, is greater than permitted
[12:58:15] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:58:15] Explicit valence for atom # 20 C, 5, is greater than permitted
[12:58:16] Explicit valence for atom # 11 C, 5, is greater than permitted
[12:58:16] Explicit valence for atom # 17 C, 5, is greater than permitted
[12:58:16] Explicit valence for atom # 4 C, 5, is greater than permitted
[12:58:16] Explicit valence for atom # 43 C, 5, is greater than permitted
[12:58:16] Explicit valence for atom # 3 C, 5, is greater than permitted
[12:58:16] Explicit valence for atom # 17 C, 5, is greater than permitted
[12:58:16] Explicit valence for atom # 4 C, 5, is greater than permitted
[12:58:16] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:58:16] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:58:16] Explicit valence for atom # 20 C, 5, is greater than permitted
[12:58:16] Explicit valence for atom # 1 C, 5, is greater than permitted
[12:58:17] Explicit valence for atom # 13 C, 5, is greater than permitted
[12:58:18] Explicit valence for atom # 28 C, 5, is greater than permitted

--- Processing cluster 3 ---

[12:58:33] Explicit valence for atom # 30 C, 5, is greater than permitted
[12:58:33] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:58:35] Explicit valence for atom # 29 C, 5, is greater than permitted
[12:58:36] Explicit valence for atom # 8 C, 5, is greater than permitted
[12:58:36] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:58:36] Explicit valence for atom # 39 C, 5, is greater than permitted
[12:58:37] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[12:58:37] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[12:58:37] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[12:58:37] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[12:58:37] Explicit valence for atom # 34 C, 5, is greater than permitted
[12:58:37] Explicit valence for atom # 13 C, 5, is greater than permitted
[12:58:37] Explicit valence for atom # 8 C, 5, is greater than permitted
[12:58:37] Explicit valence for atom # 4 C, 5, is greater than permitted
[12:58:37] Explicit valence for atom # 19 C, 5, is greater than permitted
[12:58:38] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:58:38] Explicit valence for atom # 19 C, 5, is greater than permitted
[12:58:38] Explicit valence for atom # 16 C, 5, is greater than permitted
[12:58:38] Explicit valence for atom # 29 C, 5, is greater than permitted
[12:58:39] Explicit valence for atom # 5 C, 5, is greater than permitted

--- Processing cluster 4 ---

[12:58:57] Explicit valence for atom # 12 C, 5, is greater than permitted
[12:58:57] Explicit valence for atom # 10 C, 5, is greater than permitted
[12:58:57] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:59:00] Explicit valence for atom # 30 C, 5, is greater than permitted
[12:59:01] Explicit valence for atom # 38 C, 5, is greater than permitted
[12:59:01] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:59:03] Explicit valence for atom # 8 C, 5, is greater than permitted

Calculation complete! Processed 5 clusters

,name,type_cluster,scaffold,RS,SED,ASER
0,DrugEx_GT_epsilon_0.6_250k_0,dis,csk,0.675000,0.345174,0.007442
1,DrugEx_GT_epsilon_0.6_250k_1,dis,csk,0.695652,0.343285,0.004434
2,DrugEx_GT_epsilon_0.6_250k_2,dis,csk,0.300000,0.344133,0.000905
3,DrugEx_GT_epsilon_0.6_250k_3,dis,csk,0.567568,0.389671,0.008030
4,DrugEx_GT_epsilon_0.6_250k_4,dis,csk,0.813953,0.404039,0.018628
5,DrugEx_GT_epsilon_0.6_250k_mean,dis,csk,0.610435,0.365260,0.007888

DrugEx_RNN_epsilon_0.1_250k

============================================================
Starting calculation for DrugEx_RNN_epsilon_0.1_250k
Receptor: Glucocorticoid_receptor
Cluster type: dis
Scaffold type: csk
CPUs: 100
============================================================

--- Processing cluster 0 ---

[12:59:22] Explicit valence for atom # 28 C, 5, is greater than permitted
[12:59:22] Explicit valence for atom # 28 C greater than permitted
[12:59:22] Explicit valence for atom # 40 C greater than permitted
[12:59:22] Explicit valence for atom # 31 C greater than permitted
[12:59:22] Explicit valence for atom # 28 C greater than permitted
[12:59:22] Explicit valence for atom # 31 C, 5, is greater than permitted
[12:59:22] Explicit valence for atom # 12 C greater than permitted
[12:59:22] Explicit valence for atom # 40 C greater than permitted
[12:59:22] Explicit valence for atom # 23 C greater than permitted
[12:59:22] Explicit valence for atom # 32 C, 5, is greater than permitted
[12:59:22] Explicit valence for atom # 28 C greater than permitted
[12:59:22] Explicit valence for atom # 13 C greater than permitted
[12:59:22] Explicit valence for atom # 14 C, 5, is greater than permitted
[12:59:23] Explicit valence for atom # 35 C greater than permitted
[12:59:23] Explicit valence for atom # 26 Si, 5, is greater than permitted
[12:59:23] Explicit valence for atom # 6 C greater than permitted
[12:59:23] Explicit valence for atom # 18 C greater than permitted
[12:59:23] Explicit valence for atom # 34 C, 5, is greater than permitted
[12:59:23] Explicit valence for atom # 19 C, 5, is greater than permitted
[12:59:23] Explicit valence for atom # 13 C greater than permitted
[12:59:23] Explicit valence for atom # 29 C, 5, is greater than permitted
[12:59:23] Explicit valence for atom # 32 C greater than permitted
[12:59:23] Explicit valence for atom # 31 C greater than permitted
[12:59:23] Explicit valence for atom # 27 C greater than permitted
[12:59:23] Explicit valence for atom # 24 C greater than permitted
[12:59:23] Explicit valence for atom # 31 C greater than permitted
[12:59:23] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:59:23] Explicit valence for atom # 13 C greater than permitted
[12:59:23] Explicit valence for atom # 28 C greater than permitted
[12:59:23] Explicit valence for atom # 16 C greater than permitted
[12:59:23] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:59:23] Explicit valence for atom # 6 P, 7, is greater than permitted
[12:59:23] Explicit valence for atom # 5 C greater than permitted
[12:59:23] Explicit valence for atom # 31 C greater than permitted
[12:59:23] Explicit valence for atom # 29 C greater than permitted
[12:59:23] Explicit valence for atom # 13 C greater than permitted
[12:59:23] Explicit valence for atom # 13 C greater than permitted
[12:59:23] Explicit valence for atom # 24 P, 7, is greater than permitted
[12:59:23] Explicit valence for atom # 28 C greater than permitted
[12:59:23] Explicit valence for atom # 37 C greater than permitted
[12:59:23] Explicit valence for atom # 25 C greater than permitted
[12:59:23] Explicit valence for atom # 30 Si, 5, is greater than permitted
[12:59:23] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:59:23] Explicit valence for atom # 20 C greater than permitted
[12:59:23] Explicit valence for atom # 31 C greater than permitted
[12:59:23] Explicit valence for atom # 33 Si, 5, is greater than permitted
[12:59:23] Explicit valence for atom # 10 C, 5, is greater than permitted
[12:59:23] Explicit valence for atom # 33 C greater than permitted
[12:59:23] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:59:23] Explicit valence for atom # 17 C greater than permitted
[12:59:23] Explicit valence for atom # 29 C greater than permitted
[12:59:24] Explicit valence for atom # 6 C greater than permitted
[12:59:24] Explicit valence for atom # 18 C greater than permitted
[12:59:24] Explicit valence for atom # 15 C greater than permitted
[12:59:24] Explicit valence for atom # 30 C greater than permitted
[12:59:24] Explicit valence for atom # 29 C, 5, is greater than permitted
[12:59:24] Explicit valence for atom # 43 C greater than permitted
[12:59:24] Explicit valence for atom # 28 C greater than permitted
[12:59:24] Explicit valence for atom # 34 C greater than permitted
[12:59:24] Explicit valence for atom # 29 C greater than permitted
[12:59:24] Explicit valence for atom # 27 C greater than permitted
[12:59:24] Explicit valence for atom # 19 C greater than permitted
[12:59:24] Explicit valence for atom # 16 C greater than permitted
[12:59:24] Explicit valence for atom # 27 C greater than permitted
[12:59:24] Explicit valence for atom # 22 C, 5, is greater than permitted
[12:59:24] Explicit valence for atom # 11 C greater than permitted
[12:59:24] Explicit valence for atom # 17 C greater than permitted
[12:59:24] Explicit valence for atom # 28 C, 5, is greater than permitted
[12:59:24] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:59:24] Explicit valence for atom # 28 C greater than permitted
[12:59:24] Explicit valence for atom # 29 C greater than permitted
[12:59:24] Explicit valence for atom # 26 Si, 5, is greater than permitted
[12:59:24] Explicit valence for atom # 32 C, 6, is greater than permitted
[12:59:24] Explicit valence for atom # 31 C, 5, is greater than permitted
[12:59:24] Explicit valence for atom # 33 C greater than permitted
[12:59:24] Explicit valence for atom # 26 C greater than permitted
[12:59:24] Explicit valence for atom # 31 C greater than permitted
[12:59:24] Explicit valence for atom # 29 C greater than permitted
[12:59:24] Explicit valence for atom # 29 C greater than permitted
[12:59:24] Explicit valence for atom # 35 C greater than permitted
[12:59:24] Explicit valence for atom # 31 C greater than permitted
[12:59:25] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:59:25] Explicit valence for atom # 19 C greater than permitted
[12:59:25] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:59:25] Explicit valence for atom # 19 Si, 5, is greater than permitted
[12:59:25] Explicit valence for atom # 31 C greater than permitted
[12:59:25] Explicit valence for atom # 31 C, 5, is greater than permitted
[12:59:25] Explicit valence for atom # 30 C greater than permitted
[12:59:25] Explicit valence for atom # 28 C greater than permitted
[12:59:25] Explicit valence for atom # 37 C greater than permitted
[12:59:25] Explicit valence for atom # 10 C greater than permitted
[12:59:25] Explicit valence for atom # 13 C greater than permitted
[12:59:25] Explicit valence for atom # 13 C greater than permitted
[12:59:25] Explicit valence for atom # 24 C greater than permitted
[12:59:25] Explicit valence for atom # 11 C greater than permitted
[12:59:25] Explicit valence for atom # 31 C, 5, is greater than permitted
[12:59:25] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:59:25] Explicit valence for atom # 32 C, 5, is greater than permitted
[12:59:25] Explicit valence for atom # 28 C greater than permitted
[12:59:25] Explicit valence for atom # 26 C, 5, is greater than permitted
[12:59:25] Explicit valence for atom # 26 Si, 5, is greater than permitted
[12:59:25] Explicit valence for atom # 17 C greater than permitted
[12:59:25] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:59:25] Explicit valence for atom # 30 C greater than permitted
[12:59:25] Explicit valence for atom # 13 C greater than permitted
[12:59:25] Explicit valence for atom # 13 C greater than permitted
[12:59:25] Explicit valence for atom # 17 Si, 5, is greater than permitted
[12:59:25] Explicit valence for atom # 24 P, 7, is greater than permitted
[12:59:25] Explicit valence for atom # 40 C, 5, is greater than permitted
[12:59:25] Explicit valence for atom # 29 C greater than permitted
[12:59:25] Explicit valence for atom # 13 C greater than permitted
[12:59:25] Explicit valence for atom # 39 C greater than permitted
[12:59:25] Explicit valence for atom # 31 C greater than permitted
[12:59:25] Explicit valence for atom # 29 C greater than permitted
[12:59:25] Explicit valence for atom # 47 C greater than permitted
[12:59:26] Explicit valence for atom # 26 C, 5, is greater than permitted
[12:59:26] Explicit valence for atom # 35 C, 5, is greater than permitted
[12:59:26] Explicit valence for atom # 2 P, 7, is greater than permitted
[12:59:26] Explicit valence for atom # 40 C greater than permitted
[12:59:26] Explicit valence for atom # 29 C, 6, is greater than permitted
[12:59:26] Explicit valence for atom # 23 C, 5, is greater than permitted
[12:59:26] Explicit valence for atom # 28 C greater than permitted
[12:59:26] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:59:26] Explicit valence for atom # 32 C, 5, is greater than permitted
[12:59:26] Explicit valence for atom # 35 C greater than permitted
[12:59:26] Explicit valence for atom # 24 C greater than permitted
[12:59:27] Explicit valence for atom # 21 C greater than permitted
[12:59:27] Explicit valence for atom # 32 C greater than permitted
[12:59:27] Explicit valence for atom # 31 C, 5, is greater than permitted
[12:59:27] Explicit valence for atom # 6 C, 5, is greater than permitted

--- Processing cluster 1 ---

[12:59:40] Explicit valence for atom # 30 C greater than permitted
[12:59:40] Explicit valence for atom # 31 Si, 5, is greater than permitted
[12:59:40] Explicit valence for atom # 27 C greater than permitted
[12:59:40] Explicit valence for atom # 27 C greater than permitted
[12:59:40] Explicit valence for atom # 42 C greater than permitted
[12:59:40] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:59:40] Explicit valence for atom # 28 C greater than permitted
[12:59:40] Explicit valence for atom # 30 C greater than permitted
[12:59:40] Explicit valence for atom # 33 C greater than permitted
[12:59:40] Explicit valence for atom # 27 C greater than permitted
[12:59:40] Explicit valence for atom # 36 C greater than permitted
[12:59:40] Explicit valence for atom # 33 C greater than permitted
[12:59:40] Explicit valence for atom # 33 C greater than permitted
[12:59:40] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:59:40] Explicit valence for atom # 26 C greater than permitted
[12:59:41] Explicit valence for atom # 27 P, 7, is greater than permitted
[12:59:41] Explicit valence for atom # 42 C greater than permitted
[12:59:41] Explicit valence for atom # 40 C greater than permitted
[12:59:41] Explicit valence for atom # 29 Si, 5, is greater than permitted
[12:59:41] Explicit valence for atom # 21 C greater than permitted
[12:59:41] Explicit valence for atom # 28 C greater than permitted
[12:59:41] Explicit valence for atom # 38 C greater than permitted
[12:59:41] Explicit valence for atom # 27 C greater than permitted
[12:59:41] Explicit valence for atom # 31 C greater than permitted
[12:59:41] Explicit valence for atom # 28 C greater than permitted
[12:59:41] Explicit valence for atom # 22 C greater than permitted
[12:59:41] Explicit valence for atom # 27 C greater than permitted
[12:59:41] Explicit valence for atom # 41 C greater than permitted
[12:59:41] Explicit valence for atom # 28 P, 7, is greater than permitted
[12:59:41] Explicit valence for atom # 10 C greater than permitted
[12:59:41] Explicit valence for atom # 15 C greater than permitted
[12:59:41] Explicit valence for atom # 24 C, 5, is greater than permitted
[12:59:41] Explicit valence for atom # 33 Si, 5, is greater than permitted
[12:59:41] Explicit valence for atom # 27 C greater than permitted
[12:59:41] Explicit valence for atom # 31 Si, 5, is greater than permitted
[12:59:41] Explicit valence for atom # 30 Si, 6, is greater than permitted
[12:59:41] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:59:41] Explicit valence for atom # 15 C greater than permitted
[12:59:41] Explicit valence for atom # 24 C greater than permitted
[12:59:41] Explicit valence for atom # 31 C greater than permitted
[12:59:41] Explicit valence for atom # 29 C greater than permitted
[12:59:41] Explicit valence for atom # 37 C greater than permitted
[12:59:41] Explicit valence for atom # 29 C greater than permitted
[12:59:42] Explicit valence for atom # 29 C greater than permitted
[12:59:42] Explicit valence for atom # 33 C greater than permitted
[12:59:42] Explicit valence for atom # 32 C greater than permitted
[12:59:42] Explicit valence for atom # 39 C greater than permitted
[12:59:42] Explicit valence for atom # 25 C greater than permitted
[12:59:42] Explicit valence for atom # 15 C greater than permitted
[12:59:42] Explicit valence for atom # 28 C, 5, is greater than permitted
[12:59:42] Explicit valence for atom # 27 P, 7, is greater than permitted
[12:59:42] Explicit valence for atom # 37 C greater than permitted
[12:59:42] Explicit valence for atom # 31 C greater than permitted
[12:59:42] Explicit valence for atom # 31 P, 7, is greater than permitted
[12:59:42] Explicit valence for atom # 33 C greater than permitted
[12:59:42] Explicit valence for atom # 24 C greater than permitted
[12:59:42] Explicit valence for atom # 25 C, 5, is greater than permitted
[12:59:42] Explicit valence for atom # 32 C greater than permitted
[12:59:42] Explicit valence for atom # 29 C, 5, is greater than permitted
[12:59:42] Explicit valence for atom # 27 Si, 5, is greater than permitted
[12:59:42] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:59:42] Explicit valence for atom # 30 P, 7, is greater than permitted
[12:59:42] Explicit valence for atom # 33 C greater than permitted
[12:59:42] Explicit valence for atom # 41 C greater than permitted
[12:59:42] Explicit valence for atom # 29 P, 7, is greater than permitted
[12:59:42] Explicit valence for atom # 34 C greater than permitted
[12:59:42] Explicit valence for atom # 31 C greater than permitted
[12:59:42] Explicit valence for atom # 33 C greater than permitted
[12:59:42] Explicit valence for atom # 37 C greater than permitted
[12:59:42] Explicit valence for atom # 26 Si, 5, is greater than permitted
[12:59:42] Explicit valence for atom # 34 C greater than permitted
[12:59:42] Explicit valence for atom # 26 Si, 5, is greater than permitted
[12:59:42] Explicit valence for atom # 13 C greater than permitted
[12:59:42] Explicit valence for atom # 18 C, 5, is greater than permitted
[12:59:42] Explicit valence for atom # 29 C greater than permitted
[12:59:43] Explicit valence for atom # 32 C, 5, is greater than permitted
[12:59:43] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:59:43] Explicit valence for atom # 27 C, 4, is greater than permitted
[12:59:43] Explicit valence for atom # 24 C, 5, is greater than permitted
[12:59:43] Explicit valence for atom # 26 C greater than permitted
[12:59:43] Explicit valence for atom # 32 C greater than permitted
[12:59:43] Explicit valence for atom # 29 C greater than permitted
[12:59:43] Explicit valence for atom # 35 C greater than permitted
[12:59:43] Explicit valence for atom # 32 C greater than permitted
[12:59:43] Explicit valence for atom # 30 C greater than permitted
[12:59:43] Explicit valence for atom # 32 C greater than permitted
[12:59:43] Explicit valence for atom # 22 C greater than permitted
[12:59:43] Explicit valence for atom # 36 C greater than permitted
[12:59:43] Explicit valence for atom # 34 C, 5, is greater than permitted
[12:59:43] Explicit valence for atom # 25 C greater than permitted
[12:59:43] Explicit valence for atom # 38 C greater than permitted
[12:59:43] Explicit valence for atom # 34 C greater than permitted
[12:59:43] Explicit valence for atom # 30 C greater than permitted
[12:59:44] Explicit valence for atom # 26 C greater than permitted
[12:59:44] Explicit valence for atom # 35 C greater than permitted
[12:59:44] Explicit valence for atom # 32 C greater than permitted
[12:59:44] Explicit valence for atom # 33 C greater than permitted
[12:59:44] Explicit valence for atom # 24 C greater than permitted
[12:59:44] Explicit valence for atom # 31 C greater than permitted
[12:59:44] Explicit valence for atom # 33 Si, 5, is greater than permitted
[12:59:44] Explicit valence for atom # 25 C greater than permitted
[12:59:44] Explicit valence for atom # 31 C greater than permitted
[12:59:44] Explicit valence for atom # 25 Si, 5, is greater than permitted
[12:59:44] Explicit valence for atom # 40 C greater than permitted
[12:59:44] Explicit valence for atom # 26 C greater than permitted
[12:59:44] Explicit valence for atom # 0 C greater than permitted
[12:59:44] Explicit valence for atom # 32 C greater than permitted
[12:59:44] Explicit valence for atom # 33 C greater than permitted
[12:59:44] Explicit valence for atom # 6 C, 5, is greater than permitted
[12:59:44] Explicit valence for atom # 30 C, 5, is greater than permitted
[12:59:44] Explicit valence for atom # 39 Si, 5, is greater than permitted
[12:59:44] Explicit valence for atom # 30 C greater than permitted
[12:59:44] Explicit valence for atom # 27 C, 6, is greater than permitted
[12:59:44] Explicit valence for atom # 0 C greater than permitted
[12:59:44] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:59:44] Explicit valence for atom # 40 C greater than permitted
[12:59:44] Explicit valence for atom # 26 C greater than permitted
[12:59:44] Explicit valence for atom # 32 C greater than permitted
[12:59:45] Explicit valence for atom # 27 C, 5, is greater than permitted
[12:59:47] Explicit valence for atom # 13 Si, 5, is greater than permitted
[12:59:47] Explicit valence for atom # 26 C greater than permitted
[12:59:47] Explicit valence for atom # 32 C greater than permitted

--- Processing cluster 2 ---

[12:59:58] Explicit valence for atom # 31 C greater than permitted
[12:59:58] Explicit valence for atom # 23 C greater than permitted
[12:59:58] Explicit valence for atom # 23 C, 5, is greater than permitted
[12:59:58] Explicit valence for atom # 8 C, 5, is greater than permitted
[12:59:59] Explicit valence for atom # 23 C greater than permitted
[12:59:59] Explicit valence for atom # 37 C greater than permitted
[12:59:59] Explicit valence for atom # 28 C greater than permitted
[12:59:59] Explicit valence for atom # 24 C greater than permitted
[12:59:59] Explicit valence for atom # 9 C, 5, is greater than permitted
[12:59:59] Explicit valence for atom # 35 C greater than permitted
[12:59:59] Explicit valence for atom # 35 C greater than permitted
[12:59:59] Explicit valence for atom # 29 C greater than permitted
[12:59:59] Explicit valence for atom # 2 C, 5, is greater than permitted
[12:59:59] Explicit valence for atom # 15 C, 5, is greater than permitted
[12:59:59] Explicit valence for atom # 24 C greater than permitted
[12:59:59] Explicit valence for atom # 4 C, 5, is greater than permitted
[12:59:59] Explicit valence for atom # 36 C greater than permitted
[12:59:59] Explicit valence for atom # 22 Si, 6, is greater than permitted
[12:59:59] Explicit valence for atom # 16 C greater than permitted
[12:59:59] Explicit valence for atom # 33 C greater than permitted
[12:59:59] Explicit valence for atom # 8 C greater than permitted
[12:59:59] Explicit valence for atom # 30 C greater than permitted
[12:59:59] Explicit valence for atom # 34 C greater than permitted
[12:59:59] Explicit valence for atom # 23 C greater than permitted
[12:59:59] Explicit valence for atom # 30 C, 5, is greater than permitted
[12:59:59] Explicit valence for atom # 32 C greater than permitted
[12:59:59] Explicit valence for atom # 30 C greater than permitted
[12:59:59] Explicit valence for atom # 37 C greater than permitted
[12:59:59] Explicit valence for atom # 38 C greater than permitted
[12:59:59] Explicit valence for atom # 11 C greater than permitted
[12:59:59] Explicit valence for atom # 22 C greater than permitted
[13:00:00] Explicit valence for atom # 25 C greater than permitted
[13:00:00] Explicit valence for atom # 25 C greater than permitted
[13:00:00] Explicit valence for atom # 31 C greater than permitted
[13:00:00] Explicit valence for atom # 29 C greater than permitted
[13:00:00] Explicit valence for atom # 7 C greater than permitted
[13:00:00] Explicit valence for atom # 26 C greater than permitted
[13:00:00] Explicit valence for atom # 27 C greater than permitted
[13:00:00] Explicit valence for atom # 18 C greater than permitted
[13:00:00] Explicit valence for atom # 23 C greater than permitted
[13:00:00] Explicit valence for atom # 19 C greater than permitted
[13:00:00] Explicit valence for atom # 28 C, 5, is greater than permitted
[13:00:00] Explicit valence for atom # 34 C greater than permitted
[13:00:00] Explicit valence for atom # 28 C greater than permitted
[13:00:00] Explicit valence for atom # 30 C greater than permitted
[13:00:00] Explicit valence for atom # 33 C greater than permitted
[13:00:00] Explicit valence for atom # 25 C greater than permitted
[13:00:00] Explicit valence for atom # 35 C greater than permitted
[13:00:00] Explicit valence for atom # 28 C, 5, is greater than permitted
[13:00:01] Explicit valence for atom # 37 C greater than permitted
[13:00:01] Explicit valence for atom # 33 C greater than permitted
[13:00:01] Explicit valence for atom # 32 C greater than permitted
[13:00:01] Explicit valence for atom # 31 C greater than permitted
[13:00:01] Explicit valence for atom # 30 C greater than permitted
[13:00:01] Explicit valence for atom # 29 C greater than permitted
[13:00:01] Explicit valence for atom # 28 C greater than permitted
[13:00:01] Explicit valence for atom # 26 C, 5, is greater than permitted
[13:00:01] Explicit valence for atom # 11 C greater than permitted
[13:00:01] Explicit valence for atom # 26 C greater than permitted
[13:00:01] Explicit valence for atom # 28 C, 5, is greater than permitted
[13:00:01] Explicit valence for atom # 24 C greater than permitted
[13:00:01] Explicit valence for atom # 29 C greater than permitted
[13:00:01] Explicit valence for atom # 32 C greater than permitted
[13:00:01] Explicit valence for atom # 30 C greater than permitted
[13:00:01] Explicit valence for atom # 18 C greater than permitted
[13:00:01] Explicit valence for atom # 28 C greater than permitted
[13:00:02] Explicit valence for atom # 7 C greater than permitted
[13:00:02] Explicit valence for atom # 20 C greater than permitted
[13:00:03] Explicit valence for atom # 8 C greater than permitted
[13:00:03] Explicit valence for atom # 32 C greater than permitted
[13:00:04] Explicit valence for atom # 34 C greater than permitted

--- Processing cluster 3 ---

[13:00:12] Explicit valence for atom # 3 C greater than permitted
[13:00:12] Explicit valence for atom # 19 C greater than permitted
[13:00:12] Explicit valence for atom # 33 C greater than permitted
[13:00:12] Explicit valence for atom # 33 C greater than permitted
[13:00:12] Explicit valence for atom # 20 C greater than permitted
[13:00:12] Explicit valence for atom # 33 C greater than permitted
[13:00:12] Explicit valence for atom # 14 C greater than permitted
[13:00:12] Explicit valence for atom # 32 C greater than permitted
[13:00:12] Explicit valence for atom # 33 C greater than permitted
[13:00:12] Explicit valence for atom # 36 P, 7, is greater than permitted
[13:00:12] Explicit valence for atom # 3 C greater than permitted
[13:00:12] Explicit valence for atom # 35 C greater than permitted
[13:00:12] Explicit valence for atom # 30 C greater than permitted
[13:00:12] Explicit valence for atom # 32 C, 5, is greater than permitted
[13:00:12] Explicit valence for atom # 34 C greater than permitted
[13:00:12] Explicit valence for atom # 39 P, 7, is greater than permitted
[13:00:12] Explicit valence for atom # 32 C greater than permitted
[13:00:12] Explicit valence for atom # 33 C greater than permitted
[13:00:12] Explicit valence for atom # 34 Si, 5, is greater than permitted
[13:00:12] Explicit valence for atom # 24 C greater than permitted
[13:00:12] Explicit valence for atom # 33 Si, 5, is greater than permitted
[13:00:12] Explicit valence for atom # 35 P, 7, is greater than permitted
[13:00:12] Explicit valence for atom # 27 P, 7, is greater than permitted
[13:00:12] Explicit valence for atom # 27 C greater than permitted
[13:00:12] Explicit valence for atom # 27 C greater than permitted
[13:00:12] Explicit valence for atom # 26 C greater than permitted
[13:00:12] Explicit valence for atom # 24 C, 5, is greater than permitted
[13:00:12] Explicit valence for atom # 26 P, 7, is greater than permitted
[13:00:12] Explicit valence for atom # 21 C, 5, is greater than permitted
[13:00:12] Explicit valence for atom # 36 Si, 5, is greater than permitted
[13:00:12] Explicit valence for atom # 31 Si, 5, is greater than permitted
[13:00:12] Explicit valence for atom # 32 C greater than permitted
[13:00:12] Explicit valence for atom # 32 Si, 5, is greater than permitted
[13:00:13] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:00:13] Explicit valence for atom # 29 P, 7, is greater than permitted
[13:00:13] Explicit valence for atom # 6 C greater than permitted
[13:00:13] Explicit valence for atom # 34 P, 7, is greater than permitted
[13:00:13] Explicit valence for atom # 36 C greater than permitted
[13:00:13] Explicit valence for atom # 29 C greater than permitted
[13:00:13] Explicit valence for atom # 30 P, 7, is greater than permitted
[13:00:13] Explicit valence for atom # 2 C greater than permitted
[13:00:13] Explicit valence for atom # 41 C greater than permitted
[13:00:13] Explicit valence for atom # 40 C greater than permitted
[13:00:13] Explicit valence for atom # 30 C greater than permitted
[13:00:13] Explicit valence for atom # 30 Si, 5, is greater than permitted
[13:00:13] Explicit valence for atom # 32 Si, 5, is greater than permitted
[13:00:13] Explicit valence for atom # 27 P, 7, is greater than permitted
[13:00:13] Explicit valence for atom # 28 P, 7, is greater than permitted
[13:00:13] Explicit valence for atom # 24 C greater than permitted
[13:00:13] Explicit valence for atom # 32 Si, 6, is greater than permitted
[13:00:13] Explicit valence for atom # 30 Si, 5, is greater than permitted
[13:00:13] Explicit valence for atom # 34 P, 7, is greater than permitted
[13:00:13] Explicit valence for atom # 31 Si, 5, is greater than permitted
[13:00:13] Explicit valence for atom # 30 C greater than permitted
[13:00:13] Explicit valence for atom # 29 C greater than permitted
[13:00:13] Explicit valence for atom # 35 P, 7, is greater than permitted
[13:00:13] Explicit valence for atom # 32 P, 7, is greater than permitted
[13:00:13] Explicit valence for atom # 30 C, 5, is greater than permitted
[13:00:13] Explicit valence for atom # 24 C greater than permitted
[13:00:13] Explicit valence for atom # 38 C greater than permitted
[13:00:13] Explicit valence for atom # 31 Si, 5, is greater than permitted
[13:00:13] Explicit valence for atom # 30 P, 7, is greater than permitted
[13:00:13] Explicit valence for atom # 40 C greater than permitted
[13:00:13] Explicit valence for atom # 34 Si, 5, is greater than permitted
[13:00:13] Explicit valence for atom # 25 C greater than permitted
[13:00:13] Explicit valence for atom # 18 C greater than permitted
[13:00:13] Explicit valence for atom # 31 Si, 5, is greater than permitted
[13:00:13] Explicit valence for atom # 29 C greater than permitted
[13:00:13] Explicit valence for atom # 2 P, 7, is greater than permitted
[13:00:13] Explicit valence for atom # 33 C greater than permitted
[13:00:13] Explicit valence for atom # 25 C greater than permitted
[13:00:13] Explicit valence for atom # 28 C greater than permitted
[13:00:13] Explicit valence for atom # 24 P, 7, is greater than permitted
[13:00:13] Explicit valence for atom # 36 Si, 5, is greater than permitted
[13:00:13] Explicit valence for atom # 16 C greater than permitted
[13:00:13] Explicit valence for atom # 36 C greater than permitted
[13:00:13] Explicit valence for atom # 36 P, 7, is greater than permitted
[13:00:13] Explicit valence for atom # 36 P, 7, is greater than permitted
[13:00:13] Explicit valence for atom # 36 P, 7, is greater than permitted
[13:00:13] Explicit valence for atom # 14 C greater than permitted
[13:00:13] Explicit valence for atom # 30 Si, 5, is greater than permitted
[13:00:14] Explicit valence for atom # 37 Si, 5, is greater than permitted
[13:00:14] Explicit valence for atom # 27 C greater than permitted
[13:00:14] Explicit valence for atom # 32 Si, 5, is greater than permitted
[13:00:14] Explicit valence for atom # 19 Si, 5, is greater than permitted
[13:00:14] Explicit valence for atom # 4 C, 5, is greater than permitted
[13:00:14] Explicit valence for atom # 30 Si, 5, is greater than permitted
[13:00:14] Explicit valence for atom # 27 C, 5, is greater than permitted
[13:00:14] Explicit valence for atom # 27 C, 5, is greater than permitted
[13:00:14] Explicit valence for atom # 37 C greater than permitted
[13:00:14] Explicit valence for atom # 33 C greater than permitted
[13:00:14] Explicit valence for atom # 33 C greater than permitted
[13:00:14] Explicit valence for atom # 28 P, 7, is greater than permitted
[13:00:14] Explicit valence for atom # 32 C greater than permitted
[13:00:14] Explicit valence for atom # 33 Si, 5, is greater than permitted
[13:00:14] Explicit valence for atom # 30 Si, 5, is greater than permitted
[13:00:14] Explicit valence for atom # 27 P, 7, is greater than permitted
[13:00:14] Explicit valence for atom # 32 Si, 5, is greater than permitted
[13:00:14] Explicit valence for atom # 3 C greater than permitted
[13:00:14] Explicit valence for atom # 33 C greater than permitted
[13:00:14] Explicit valence for atom # 14 Si, 5, is greater than permitted
[13:00:14] Explicit valence for atom # 33 Si, 5, is greater than permitted
[13:00:14] Explicit valence for atom # 32 Si, 5, is greater than permitted
[13:00:14] Explicit valence for atom # 24 C greater than permitted
[13:00:14] Explicit valence for atom # 18 C greater than permitted
[13:00:14] Explicit valence for atom # 33 C greater than permitted
[13:00:14] Explicit valence for atom # 26 C, 5, is greater than permitted
[13:00:14] Explicit valence for atom # 36 C greater than permitted
[13:00:14] Explicit valence for atom # 30 Si, 5, is greater than permitted
[13:00:14] Explicit valence for atom # 27 P, 7, is greater than permitted
[13:00:14] Explicit valence for atom # 32 C greater than permitted
[13:00:14] Explicit valence for atom # 28 Si, 5, is greater than permitted
[13:00:14] Explicit valence for atom # 31 C greater than permitted
[13:00:14] Explicit valence for atom # 33 P, 7, is greater than permitted
[13:00:14] Explicit valence for atom # 28 P, 7, is greater than permitted
[13:00:14] Explicit valence for atom # 33 C greater than permitted
[13:00:14] Explicit valence for atom # 30 Si, 5, is greater than permitted
[13:00:14] Explicit valence for atom # 26 P, 7, is greater than permitted
[13:00:14] Explicit valence for atom # 33 Si, 5, is greater than permitted
[13:00:14] Explicit valence for atom # 30 C, 6, is greater than permitted
[13:00:14] Explicit valence for atom # 37 Si, 5, is greater than permitted
[13:00:14] Explicit valence for atom # 35 P, 7, is greater than permitted
[13:00:14] Explicit valence for atom # 35 Si, 5, is greater than permitted
[13:00:14] Explicit valence for atom # 3 C greater than permitted
[13:00:14] Explicit valence for atom # 32 C greater than permitted
[13:00:14] Explicit valence for atom # 26 C greater than permitted
[13:00:14] Explicit valence for atom # 31 C greater than permitted
[13:00:14] Explicit valence for atom # 32 C greater than permitted
[13:00:14] Explicit valence for atom # 27 P, 7, is greater than permitted
[13:00:14] Explicit valence for atom # 18 C greater than permitted
[13:00:14] Explicit valence for atom # 37 Si, 5, is greater than permitted
[13:00:14] Explicit valence for atom # 32 C, 5, is greater than permitted
[13:00:15] Explicit valence for atom # 33 C, 5, is greater than permitted
[13:00:15] Explicit valence for atom # 31 Si, 5, is greater than permitted
[13:00:15] Explicit valence for atom # 42 C greater than permitted
[13:00:15] Explicit valence for atom # 38 C greater than permitted
[13:00:15] Explicit valence for atom # 6 C greater than permitted
[13:00:15] Explicit valence for atom # 3 C greater than permitted
[13:00:15] Explicit valence for atom # 25 C greater than permitted
[13:00:15] Explicit valence for atom # 26 C, 5, is greater than permitted
[13:00:15] Explicit valence for atom # 25 C, 5, is greater than permitted
[13:00:15] Explicit valence for atom # 27 Si, 5, is greater than permitted
[13:00:16] Explicit valence for atom # 5 C greater than permitted
[13:00:16] Explicit valence for atom # 6 C, 5, is greater than permitted

--- Processing cluster 4 ---

[13:00:32] Explicit valence for atom # 17 C greater than permitted
[13:00:32] Explicit valence for atom # 27 C, 5, is greater than permitted
[13:00:32] Explicit valence for atom # 17 C greater than permitted
[13:00:32] Explicit valence for atom # 23 Si, 5, is greater than permitted
[13:00:32] Explicit valence for atom # 27 C, 5, is greater than permitted
[13:00:33] Explicit valence for atom # 29 C greater than permitted
[13:00:33] Explicit valence for atom # 27 C greater than permitted
[13:00:33] Explicit valence for atom # 2 C greater than permitted
[13:00:33] Explicit valence for atom # 8 C greater than permitted
[13:00:33] Explicit valence for atom # 28 P, 5, is greater than permitted
[13:00:33] Explicit valence for atom # 27 C, 5, is greater than permitted
[13:00:33] Explicit valence for atom # 14 C greater than permitted
[13:00:33] Explicit valence for atom # 27 C, 5, is greater than permitted
[13:00:33] Explicit valence for atom # 22 C greater than permitted
[13:00:33] Explicit valence for atom # 43 C greater than permitted
[13:00:33] Explicit valence for atom # 25 C greater than permitted
[13:00:33] Explicit valence for atom # 31 C greater than permitted
[13:00:33] Explicit valence for atom # 29 C greater than permitted
[13:00:33] Explicit valence for atom # 29 C greater than permitted
[13:00:33] Explicit valence for atom # 27 C, 5, is greater than permitted
[13:00:33] Explicit valence for atom # 27 C, 5, is greater than permitted
[13:00:33] Explicit valence for atom # 27 C greater than permitted
[13:00:33] Explicit valence for atom # 27 C, 5, is greater than permitted
[13:00:33] Explicit valence for atom # 27 C, 5, is greater than permitted
[13:00:33] Explicit valence for atom # 42 C greater than permitted
[13:00:33] Explicit valence for atom # 29 C greater than permitted
[13:00:33] Explicit valence for atom # 20 C greater than permitted
[13:00:33] Explicit valence for atom # 47 C greater than permitted
[13:00:33] Explicit valence for atom # 28 C greater than permitted
[13:00:33] Explicit valence for atom # 41 C greater than permitted
[13:00:33] Explicit valence for atom # 26 Si, 5, is greater than permitted
[13:00:33] Explicit valence for atom # 14 C greater than permitted
[13:00:33] Explicit valence for atom # 28 C greater than permitted
[13:00:33] Explicit valence for atom # 28 C greater than permitted
[13:00:33] Explicit valence for atom # 27 C greater than permitted
[13:00:33] Explicit valence for atom # 27 C, 5, is greater than permitted
[13:00:33] Explicit valence for atom # 22 C greater than permitted
[13:00:33] Explicit valence for atom # 29 C greater than permitted
[13:00:33] Explicit valence for atom # 28 C greater than permitted
[13:00:33] Explicit valence for atom # 28 C greater than permitted
[13:00:33] Explicit valence for atom # 26 C, 6, is greater than permitted
[13:00:33] Explicit valence for atom # 28 C greater than permitted
[13:00:34] Explicit valence for atom # 26 C greater than permitted
[13:00:34] Explicit valence for atom # 27 C, 5, is greater than permitted
[13:00:34] Explicit valence for atom # 25 C greater than permitted
[13:00:34] Explicit valence for atom # 35 Si, 5, is greater than permitted
[13:00:34] Explicit valence for atom # 20 C, 5, is greater than permitted
[13:00:34] Explicit valence for atom # 23 Si, 5, is greater than permitted
[13:00:34] Explicit valence for atom # 31 Si, 5, is greater than permitted
[13:00:34] Explicit valence for atom # 38 P, 7, is greater than permitted
[13:00:34] Explicit valence for atom # 28 C greater than permitted
[13:00:34] Explicit valence for atom # 30 C greater than permitted
[13:00:34] Explicit valence for atom # 28 Si, 5, is greater than permitted
[13:00:34] Explicit valence for atom # 2 C greater than permitted
[13:00:34] Explicit valence for atom # 35 C, 5, is greater than permitted
[13:00:34] Explicit valence for atom # 28 C greater than permitted
[13:00:34] Explicit valence for atom # 27 C, 5, is greater than permitted
[13:00:34] Explicit valence for atom # 24 C greater than permitted
[13:00:34] Explicit valence for atom # 32 C greater than permitted
[13:00:34] Explicit valence for atom # 35 C greater than permitted
[13:00:34] Explicit valence for atom # 27 C, 5, is greater than permitted
[13:00:34] Explicit valence for atom # 41 Si, 5, is greater than permitted
[13:00:34] Explicit valence for atom # 35 C, 5, is greater than permitted
[13:00:34] Explicit valence for atom # 27 C, 5, is greater than permitted
[13:00:34] Explicit valence for atom # 26 C greater than permitted
[13:00:34] Explicit valence for atom # 30 C greater than permitted
[13:00:34] Explicit valence for atom # 26 P, 6, is greater than permitted
[13:00:34] Explicit valence for atom # 28 C greater than permitted
[13:00:34] Explicit valence for atom # 27 C, 5, is greater than permitted
[13:00:34] Explicit valence for atom # 24 C greater than permitted
[13:00:34] Explicit valence for atom # 8 C greater than permitted
[13:00:34] Explicit valence for atom # 11 C greater than permitted
[13:00:34] Explicit valence for atom # 27 Si, 5, is greater than permitted
[13:00:34] Explicit valence for atom # 12 C, 5, is greater than permitted
[13:00:34] Explicit valence for atom # 28 C greater than permitted
[13:00:34] Explicit valence for atom # 37 Si, 5, is greater than permitted
[13:00:34] Explicit valence for atom # 42 C greater than permitted
[13:00:34] Explicit valence for atom # 31 C greater than permitted
[13:00:34] Explicit valence for atom # 3 C greater than permitted
[13:00:34] Explicit valence for atom # 32 C, 5, is greater than permitted
[13:00:34] Explicit valence for atom # 25 C greater than permitted
[13:00:34] Explicit valence for atom # 41 C greater than permitted
[13:00:34] Explicit valence for atom # 6 C greater than permitted
[13:00:34] Explicit valence for atom # 34 C greater than permitted
[13:00:34] Explicit valence for atom # 30 Si, 5, is greater than permitted
[13:00:34] Explicit valence for atom # 41 C greater than permitted
[13:00:35] Explicit valence for atom # 3 C greater than permitted
[13:00:35] Explicit valence for atom # 33 C greater than permitted
[13:00:35] Explicit valence for atom # 39 C greater than permitted
[13:00:35] Explicit valence for atom # 36 C greater than permitted
[13:00:35] Explicit valence for atom # 23 Si, 5, is greater than permitted
[13:00:35] Explicit valence for atom # 27 C, 5, is greater than permitted
[13:00:35] Explicit valence for atom # 38 C greater than permitted
[13:00:35] Explicit valence for atom # 42 C greater than permitted
[13:00:35] Explicit valence for atom # 29 C greater than permitted
[13:00:35] Explicit valence for atom # 42 C greater than permitted
[13:00:35] Explicit valence for atom # 23 Si, 5, is greater than permitted
[13:00:35] Explicit valence for atom # 31 Si, 5, is greater than permitted
[13:00:35] Explicit valence for atom # 28 C greater than permitted
[13:00:35] Explicit valence for atom # 23 C greater than permitted
[13:00:35] Explicit valence for atom # 35 C greater than permitted
[13:00:35] Explicit valence for atom # 26 C greater than permitted
[13:00:35] Explicit valence for atom # 32 C greater than permitted
[13:00:35] Explicit valence for atom # 34 C, 5, is greater than permitted
[13:00:35] Explicit valence for atom # 33 P, 7, is greater than permitted
[13:00:35] Explicit valence for atom # 27 C greater than permitted
[13:00:35] Explicit valence for atom # 27 C, 5, is greater than permitted
[13:00:35] Explicit valence for atom # 29 C greater than permitted
[13:00:35] Explicit valence for atom # 27 C, 6, is greater than permitted
[13:00:35] Explicit valence for atom # 27 C greater than permitted
[13:00:35] Explicit valence for atom # 23 C greater than permitted
[13:00:35] Explicit valence for atom # 38 C, 5, is greater than permitted
[13:00:35] Explicit valence for atom # 27 C, 5, is greater than permitted
[13:00:35] Explicit valence for atom # 27 C greater than permitted
[13:00:35] Explicit valence for atom # 35 C greater than permitted
[13:00:35] Explicit valence for atom # 1 C greater than permitted
[13:00:35] Explicit valence for atom # 34 C greater than permitted
[13:00:35] Explicit valence for atom # 28 C greater than permitted
[13:00:35] Explicit valence for atom # 43 C greater than permitted
[13:00:35] Explicit valence for atom # 36 C greater than permitted
[13:00:35] Explicit valence for atom # 27 C greater than permitted
[13:00:35] Explicit valence for atom # 25 C greater than permitted
[13:00:35] Explicit valence for atom # 27 C, 5, is greater than permitted
[13:00:35] Explicit valence for atom # 27 C, 5, is greater than permitted
[13:00:35] Explicit valence for atom # 30 C greater than permitted
[13:00:35] Explicit valence for atom # 33 C greater than permitted
[13:00:35] Explicit valence for atom # 27 C, 5, is greater than permitted
[13:00:35] Explicit valence for atom # 9 C greater than permitted
[13:00:35] Explicit valence for atom # 32 C greater than permitted
[13:00:35] Explicit valence for atom # 27 C, 5, is greater than permitted
[13:00:35] Explicit valence for atom # 27 C greater than permitted
[13:00:35] Explicit valence for atom # 27 C, 5, is greater than permitted
[13:00:35] Explicit valence for atom # 36 C greater than permitted
[13:00:35] Explicit valence for atom # 38 C greater than permitted
[13:00:35] Explicit valence for atom # 38 C greater than permitted
[13:00:35] Explicit valence for atom # 12 C, 5, is greater than permitted
[13:00:35] Explicit valence for atom # 28 C greater than permitted
[13:00:35] Explicit valence for atom # 41 C greater than permitted
[13:00:35] Explicit valence for atom # 14 Si, 6, is greater than permitted
[13:00:36] Explicit valence for atom # 30 C, 5, is greater than permitted
[13:00:36] Explicit valence for atom # 27 C greater than permitted
[13:00:36] Explicit valence for atom # 27 C greater than permitted
[13:00:36] Explicit valence for atom # 29 C greater than permitted
[13:00:36] Explicit valence for atom # 27 C, 5, is greater than permitted
[13:00:36] Explicit valence for atom # 8 C greater than permitted
[13:00:36] Explicit valence for atom # 27 C, 5, is greater than permitted
[13:00:36] Explicit valence for atom # 29 Si, 5, is greater than permitted
[13:00:36] Explicit valence for atom # 42 C greater than permitted
[13:00:36] Explicit valence for atom # 33 C greater than permitted
[13:00:36] Explicit valence for atom # 36 C greater than permitted
[13:00:36] Explicit valence for atom # 27 Si, 6, is greater than permitted
[13:00:36] Explicit valence for atom # 29 C greater than permitted
[13:00:36] Explicit valence for atom # 4 C, 5, is greater than permitted
[13:00:36] Explicit valence for atom # 22 C greater than permitted
[13:00:36] Explicit valence for atom # 39 C greater than permitted
[13:00:36] Explicit valence for atom # 1 C greater than permitted
[13:00:36] Explicit valence for atom # 27 C, 5, is greater than permitted
[13:00:36] Explicit valence for atom # 24 C greater than permitted
[13:00:36] Explicit valence for atom # 38 C greater than permitted
[13:00:36] Explicit valence for atom # 31 C greater than permitted
[13:00:36] Explicit valence for atom # 27 C, 5, is greater than permitted
[13:00:36] Explicit valence for atom # 38 C greater than permitted
[13:00:36] Explicit valence for atom # 25 C greater than permitted
[13:00:36] Explicit valence for atom # 30 C, 5, is greater than permitted
[13:00:36] Explicit valence for atom # 27 C, 5, is greater than permitted
[13:00:36] Explicit valence for atom # 27 C greater than permitted
[13:00:36] Explicit valence for atom # 23 C greater than permitted
[13:00:36] Explicit valence for atom # 25 Si, 5, is greater than permitted
[13:00:36] Explicit valence for atom # 27 C, 5, is greater than permitted
[13:00:36] Explicit valence for atom # 23 C greater than permitted
[13:00:36] Explicit valence for atom # 24 Si, 5, is greater than permitted
[13:00:36] Explicit valence for atom # 36 C greater than permitted
[13:00:36] Explicit valence for atom # 32 P, 7, is greater than permitted
[13:00:36] Explicit valence for atom # 28 C, 5, is greater than permitted
[13:00:37] Explicit valence for atom # 26 C greater than permitted
[13:00:37] Explicit valence for atom # 15 C greater than permitted
[13:00:37] Explicit valence for atom # 28 C greater than permitted
[13:00:37] Explicit valence for atom # 25 P, 7, is greater than permitted
[13:00:37] Explicit valence for atom # 27 C, 5, is greater than permitted
[13:00:37] Explicit valence for atom # 27 C, 5, is greater than permitted
[13:00:37] Explicit valence for atom # 1 C greater than permitted
[13:00:37] Explicit valence for atom # 21 C greater than permitted
[13:00:37] Explicit valence for atom # 26 C greater than permitted
[13:00:37] Explicit valence for atom # 26 C greater than permitted
[13:00:37] Explicit valence for atom # 23 C greater than permitted
[13:00:37] Explicit valence for atom # 27 C, 5, is greater than permitted
[13:00:37] Explicit valence for atom # 30 C greater than permitted
[13:00:37] Explicit valence for atom # 36 C greater than permitted
[13:00:37] Explicit valence for atom # 38 C greater than permitted
[13:00:37] Explicit valence for atom # 27 C, 5, is greater than permitted
[13:00:37] Explicit valence for atom # 28 C greater than permitted
[13:00:37] Explicit valence for atom # 26 Si, 6, is greater than permitted
[13:00:37] Explicit valence for atom # 35 C greater than permitted
[13:00:37] Explicit valence for atom # 43 C greater than permitted
[13:00:37] Explicit valence for atom # 17 C greater than permitted
[13:00:37] Explicit valence for atom # 35 C greater than permitted
[13:00:37] Explicit valence for atom # 15 P, 7, is greater than permitted
[13:00:37] Explicit valence for atom # 29 C, 5, is greater than permitted
[13:00:37] Explicit valence for atom # 27 C, 5, is greater than permitted
[13:00:37] Explicit valence for atom # 40 C greater than permitted
[13:00:37] Explicit valence for atom # 20 C greater than permitted
[13:00:37] Explicit valence for atom # 30 C greater than permitted
[13:00:38] Explicit valence for atom # 33 C greater than permitted
[13:00:38] Explicit valence for atom # 29 C greater than permitted
[13:00:39] Explicit valence for atom # 34 C greater than permitted
[13:00:39] Explicit valence for atom # 40 C greater than permitted
[13:00:40] Explicit valence for atom # 27 C, 5, is greater than permitted

Calculation complete! Processed 5 clusters

,name,type_cluster,scaffold,RS,SED,ASER
0,DrugEx_RNN_epsilon_0.1_250k_0,dis,csk,0.175000,0.108531,0.001981
1,DrugEx_RNN_epsilon_0.1_250k_1,dis,csk,0.304348,0.127735,0.002806
2,DrugEx_RNN_epsilon_0.1_250k_2,dis,csk,0.075000,0.132739,0.000020
3,DrugEx_RNN_epsilon_0.1_250k_3,dis,csk,0.297297,0.107211,0.001529
4,DrugEx_RNN_epsilon_0.1_250k_4,dis,csk,0.651163,0.185109,0.018968
5,DrugEx_RNN_epsilon_0.1_250k_mean,dis,csk,0.300562,0.132265,0.005061

DrugEx_RNN_epsilon_0.6_250k

============================================================
Starting calculation for DrugEx_RNN_epsilon_0.6_250k
Receptor: Glucocorticoid_receptor
Cluster type: dis
Scaffold type: csk
CPUs: 100
============================================================

--- Processing cluster 0 ---

[13:00:56] Explicit valence for atom # 24 C greater than permitted
[13:00:56] Explicit valence for atom # 25 C greater than permitted
[13:00:56] Explicit valence for atom # 19 C greater than permitted
[13:00:56] Explicit valence for atom # 20 C greater than permitted
[13:00:56] Explicit valence for atom # 33 C greater than permitted
[13:00:56] Explicit valence for atom # 10 C greater than permitted
[13:00:56] Explicit valence for atom # 20 C greater than permitted
[13:00:56] Explicit valence for atom # 26 C, 5, is greater than permitted
[13:00:56] Explicit valence for atom # 26 C greater than permitted
[13:00:56] Explicit valence for atom # 21 C greater than permitted
[13:00:56] Explicit valence for atom # 20 C greater than permitted
[13:00:56] Explicit valence for atom # 27 C greater than permitted
[13:00:56] Explicit valence for atom # 21 C greater than permitted
[13:00:56] Explicit valence for atom # 30 C greater than permitted
[13:00:56] Explicit valence for atom # 28 C greater than permitted
[13:00:56] Explicit valence for atom # 22 C, 6, is greater than permitted
[13:00:56] Explicit valence for atom # 31 C greater than permitted
[13:00:56] Explicit valence for atom # 13 C greater than permitted
[13:00:56] Explicit valence for atom # 20 C greater than permitted
[13:00:56] Explicit valence for atom # 25 C greater than permitted
[13:00:56] Explicit valence for atom # 17 C greater than permitted
[13:00:57] Explicit valence for atom # 19 C greater than permitted
[13:00:57] Explicit valence for atom # 21 C greater than permitted
[13:00:57] Explicit valence for atom # 22 C greater than permitted
[13:00:57] Explicit valence for atom # 24 P, 6, is greater than permitted
[13:00:57] Explicit valence for atom # 13 Si, 5, is greater than permitted
[13:00:57] Explicit valence for atom # 17 C greater than permitted
[13:00:57] Explicit valence for atom # 7 C greater than permitted
[13:00:57] Explicit valence for atom # 24 Si, 5, is greater than permitted
[13:00:57] Explicit valence for atom # 22 C greater than permitted
[13:00:57] Explicit valence for atom # 19 C, 5, is greater than permitted
[13:00:57] Explicit valence for atom # 6 C greater than permitted
[13:00:57] Explicit valence for atom # 21 C greater than permitted
[13:00:57] Explicit valence for atom # 7 C greater than permitted
[13:00:57] Explicit valence for atom # 19 C greater than permitted
[13:00:57] Explicit valence for atom # 9 P, 7, is greater than permitted
[13:00:57] Explicit valence for atom # 31 C, 5, is greater than permitted
[13:00:57] Explicit valence for atom # 28 C, 6, is greater than permitted
[13:00:57] Explicit valence for atom # 24 C greater than permitted
[13:00:57] Explicit valence for atom # 12 C greater than permitted
[13:00:57] Explicit valence for atom # 13 C greater than permitted
[13:00:57] Explicit valence for atom # 4 C, 5, is greater than permitted
[13:00:57] Explicit valence for atom # 18 C greater than permitted
[13:00:57] Explicit valence for atom # 31 C greater than permitted
[13:00:57] Explicit valence for atom # 23 C, 5, is greater than permitted
[13:00:57] Explicit valence for atom # 11 C greater than permitted
[13:00:57] Explicit valence for atom # 31 C greater than permitted
[13:00:57] Explicit valence for atom # 19 C greater than permitted
[13:00:57] Explicit valence for atom # 28 C, 5, is greater than permitted
[13:00:57] Explicit valence for atom # 26 C, 5, is greater than permitted
[13:00:57] Explicit valence for atom # 29 C greater than permitted
[13:00:57] Explicit valence for atom # 23 C greater than permitted
[13:00:57] Explicit valence for atom # 30 C greater than permitted
[13:00:57] Explicit valence for atom # 22 C greater than permitted
[13:00:57] Explicit valence for atom # 15 C greater than permitted
[13:00:57] Explicit valence for atom # 12 C greater than permitted
[13:00:57] Explicit valence for atom # 26 C greater than permitted
[13:00:57] Explicit valence for atom # 25 C greater than permitted
[13:00:57] Explicit valence for atom # 4 C, 5, is greater than permitted
[13:00:57] Explicit valence for atom # 28 C, 6, is greater than permitted
[13:00:57] Explicit valence for atom # 32 C greater than permitted
[13:00:57] Explicit valence for atom # 25 C greater than permitted
[13:00:57] Explicit valence for atom # 35 C, 5, is greater than permitted
[13:00:57] Explicit valence for atom # 28 C, 5, is greater than permitted
[13:00:57] Explicit valence for atom # 28 C greater than permitted
[13:00:57] Explicit valence for atom # 4 C greater than permitted
[13:00:57] Explicit valence for atom # 22 C greater than permitted
[13:00:57] Explicit valence for atom # 21 C, 5, is greater than permitted
[13:00:57] Explicit valence for atom # 33 C greater than permitted
[13:00:57] Explicit valence for atom # 22 C greater than permitted
[13:00:57] Explicit valence for atom # 31 C greater than permitted
[13:00:57] Explicit valence for atom # 28 C greater than permitted
[13:00:57] Explicit valence for atom # 26 C greater than permitted
[13:00:57] Explicit valence for atom # 34 Si, 5, is greater than permitted
[13:00:58] Explicit valence for atom # 36 C greater than permitted
[13:00:58] Explicit valence for atom # 28 C, 6, is greater than permitted
[13:00:58] Explicit valence for atom # 27 C, 5, is greater than permitted
[13:00:58] Explicit valence for atom # 37 C, 5, is greater than permitted
[13:00:58] Explicit valence for atom # 10 C, 6, is greater than permitted
[13:00:58] Explicit valence for atom # 22 C greater than permitted
[13:00:58] Explicit valence for atom # 28 C greater than permitted
[13:00:58] Explicit valence for atom # 18 P, 7, is greater than permitted
[13:00:58] Explicit valence for atom # 23 C, 5, is greater than permitted
[13:00:58] Explicit valence for atom # 24 P, 7, is greater than permitted
[13:00:58] Explicit valence for atom # 24 P, 6, is greater than permitted
[13:00:58] Explicit valence for atom # 30 C greater than permitted
[13:00:58] Explicit valence for atom # 16 C greater than permitted
[13:00:58] Explicit valence for atom # 23 C, 5, is greater than permitted
[13:00:58] Explicit valence for atom # 26 P, 7, is greater than permitted
[13:00:58] Explicit valence for atom # 42 C greater than permitted
[13:00:58] Explicit valence for atom # 28 C greater than permitted
[13:00:58] Explicit valence for atom # 18 C greater than permitted
[13:00:58] Explicit valence for atom # 24 C greater than permitted
[13:00:58] Explicit valence for atom # 22 C greater than permitted
[13:00:58] Explicit valence for atom # 16 C greater than permitted
[13:00:58] Explicit valence for atom # 23 C greater than permitted
[13:00:58] Explicit valence for atom # 31 C greater than permitted
[13:00:58] Explicit valence for atom # 28 C, 6, is greater than permitted
[13:00:58] Explicit valence for atom # 22 C greater than permitted
[13:00:58] Explicit valence for atom # 35 C, 5, is greater than permitted
[13:00:58] Explicit valence for atom # 23 C greater than permitted
[13:00:58] Explicit valence for atom # 19 Si, 5, is greater than permitted
[13:00:58] Explicit valence for atom # 20 C greater than permitted
[13:00:58] Explicit valence for atom # 23 C greater than permitted
[13:00:58] Explicit valence for atom # 27 C, 5, is greater than permitted
[13:00:58] Explicit valence for atom # 33 C greater than permitted
[13:00:58] Explicit valence for atom # 23 Si, 5, is greater than permitted
[13:00:58] Explicit valence for atom # 30 C, 5, is greater than permitted
[13:00:58] Explicit valence for atom # 24 C greater than permitted
[13:00:58] Explicit valence for atom # 10 C greater than permitted
[13:00:58] Explicit valence for atom # 9 C, 5, is greater than permitted
[13:00:58] Explicit valence for atom # 34 C greater than permitted
[13:00:58] Explicit valence for atom # 29 C greater than permitted
[13:00:58] Explicit valence for atom # 13 C greater than permitted
[13:00:58] Explicit valence for atom # 22 C greater than permitted
[13:00:58] Explicit valence for atom # 27 C, 5, is greater than permitted
[13:00:58] Explicit valence for atom # 16 P, 7, is greater than permitted
[13:00:59] Explicit valence for atom # 13 C greater than permitted
[13:00:59] Explicit valence for atom # 4 C, 5, is greater than permitted
[13:00:59] Explicit valence for atom # 29 C greater than permitted
[13:00:59] Explicit valence for atom # 29 C greater than permitted
[13:00:59] Explicit valence for atom # 18 C greater than permitted
[13:00:59] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:00:59] Explicit valence for atom # 13 P, 7, is greater than permitted
[13:00:59] Explicit valence for atom # 16 C greater than permitted
[13:00:59] Explicit valence for atom # 31 C greater than permitted
[13:00:59] Explicit valence for atom # 11 C greater than permitted
[13:00:59] Explicit valence for atom # 26 Si, 5, is greater than permitted
[13:00:59] Explicit valence for atom # 21 C greater than permitted
[13:00:59] Explicit valence for atom # 27 Si, 5, is greater than permitted
[13:00:59] Explicit valence for atom # 29 Si, 5, is greater than permitted
[13:00:59] Explicit valence for atom # 7 C greater than permitted
[13:00:59] Explicit valence for atom # 30 C greater than permitted
[13:00:59] Explicit valence for atom # 34 C greater than permitted
[13:00:59] Explicit valence for atom # 15 C greater than permitted
[13:00:59] Explicit valence for atom # 40 C greater than permitted
[13:00:59] Explicit valence for atom # 6 C greater than permitted
[13:00:59] Explicit valence for atom # 38 C greater than permitted
[13:00:59] Explicit valence for atom # 19 C greater than permitted
[13:00:59] Explicit valence for atom # 30 C greater than permitted
[13:01:00] Explicit valence for atom # 34 C greater than permitted
[13:01:00] Explicit valence for atom # 26 C greater than permitted
[13:01:00] Explicit valence for atom # 4 C greater than permitted
[13:01:00] Explicit valence for atom # 19 C greater than permitted
[13:01:00] Explicit valence for atom # 11 C, 5, is greater than permitted
[13:01:02] Explicit valence for atom # 28 C greater than permitted

--- Processing cluster 1 ---

[13:01:17] Explicit valence for atom # 17 C greater than permitted
[13:01:17] Explicit valence for atom # 13 C greater than permitted
[13:01:17] Explicit valence for atom # 22 C greater than permitted
[13:01:17] Explicit valence for atom # 25 C greater than permitted
[13:01:17] Explicit valence for atom # 27 C, 6, is greater than permitted
[13:01:17] Explicit valence for atom # 27 P, 7, is greater than permitted
[13:01:17] Explicit valence for atom # 6 C, 5, is greater than permitted
[13:01:17] Explicit valence for atom # 6 C, 5, is greater than permitted
[13:01:17] Explicit valence for atom # 12 C greater than permitted
[13:01:17] Explicit valence for atom # 22 C greater than permitted
[13:01:17] Explicit valence for atom # 14 C, 5, is greater than permitted
[13:01:17] Explicit valence for atom # 22 C greater than permitted
[13:01:17] Explicit valence for atom # 6 C greater than permitted
[13:01:17] Explicit valence for atom # 18 C greater than permitted
[13:01:17] Explicit valence for atom # 22 C, 6, is greater than permitted
[13:01:17] Explicit valence for atom # 1 C greater than permitted
[13:01:17] Explicit valence for atom # 6 C, 5, is greater than permitted
[13:01:17] Explicit valence for atom # 14 C greater than permitted
[13:01:17] Explicit valence for atom # 12 C greater than permitted
[13:01:17] Explicit valence for atom # 27 C greater than permitted
[13:01:17] Explicit valence for atom # 12 C, 5, is greater than permitted
[13:01:17] Explicit valence for atom # 7 C greater than permitted
[13:01:18] Explicit valence for atom # 17 C greater than permitted
[13:01:18] Explicit valence for atom # 25 P, 7, is greater than permitted
[13:01:18] Explicit valence for atom # 30 C greater than permitted
[13:01:18] Explicit valence for atom # 27 C greater than permitted
[13:01:18] Explicit valence for atom # 22 C, 5, is greater than permitted
[13:01:18] Explicit valence for atom # 24 C greater than permitted
[13:01:18] Explicit valence for atom # 7 C greater than permitted
[13:01:18] Explicit valence for atom # 33 C greater than permitted
[13:01:18] Explicit valence for atom # 13 C greater than permitted
[13:01:18] Explicit valence for atom # 32 C greater than permitted
[13:01:18] Explicit valence for atom # 34 C, 5, is greater than permitted
[13:01:18] Explicit valence for atom # 13 C greater than permitted
[13:01:18] Explicit valence for atom # 19 C greater than permitted
[13:01:18] Explicit valence for atom # 19 C greater than permitted
[13:01:18] Explicit valence for atom # 14 C, 6, is greater than permitted
[13:01:18] Explicit valence for atom # 21 C, 5, is greater than permitted
[13:01:18] Explicit valence for atom # 10 C greater than permitted
[13:01:18] Explicit valence for atom # 19 P, 6, is greater than permitted
[13:01:18] Explicit valence for atom # 27 C, 6, is greater than permitted
[13:01:18] Explicit valence for atom # 23 C greater than permitted
[13:01:18] Explicit valence for atom # 25 C, 6, is greater than permitted
[13:01:18] Explicit valence for atom # 23 C greater than permitted
[13:01:18] Explicit valence for atom # 37 C greater than permitted
[13:01:18] Explicit valence for atom # 33 C greater than permitted
[13:01:18] Explicit valence for atom # 21 Si, 5, is greater than permitted
[13:01:18] Explicit valence for atom # 34 C greater than permitted
[13:01:18] Explicit valence for atom # 23 C greater than permitted
[13:01:18] Explicit valence for atom # 28 C greater than permitted
[13:01:18] Explicit valence for atom # 7 P, 7, is greater than permitted
[13:01:18] Explicit valence for atom # 25 P, 7, is greater than permitted
[13:01:18] Explicit valence for atom # 29 C greater than permitted
[13:01:18] Explicit valence for atom # 28 C greater than permitted
[13:01:18] Explicit valence for atom # 22 C greater than permitted
[13:01:18] Explicit valence for atom # 31 C greater than permitted
[13:01:18] Explicit valence for atom # 21 C, 5, is greater than permitted
[13:01:18] Explicit valence for atom # 20 Si, 5, is greater than permitted
[13:01:18] Explicit valence for atom # 22 C greater than permitted
[13:01:18] Explicit valence for atom # 9 P, 7, is greater than permitted
[13:01:18] Explicit valence for atom # 23 C, 5, is greater than permitted
[13:01:18] Explicit valence for atom # 17 C greater than permitted
[13:01:18] Explicit valence for atom # 30 C greater than permitted
[13:01:18] Explicit valence for atom # 22 C greater than permitted
[13:01:18] Explicit valence for atom # 24 C greater than permitted
[13:01:18] Explicit valence for atom # 26 Si, 5, is greater than permitted
[13:01:18] Explicit valence for atom # 29 C greater than permitted
[13:01:18] Explicit valence for atom # 29 C greater than permitted
[13:01:18] Explicit valence for atom # 21 C, 6, is greater than permitted
[13:01:18] Explicit valence for atom # 12 C greater than permitted
[13:01:18] Explicit valence for atom # 21 P, 7, is greater than permitted
[13:01:18] Explicit valence for atom # 28 C, 5, is greater than permitted
[13:01:18] Explicit valence for atom # 13 P, 7, is greater than permitted
[13:01:18] Explicit valence for atom # 20 Si, 5, is greater than permitted
[13:01:18] Explicit valence for atom # 19 C greater than permitted
[13:01:18] Explicit valence for atom # 24 C, 5, is greater than permitted
[13:01:18] Explicit valence for atom # 27 P, 7, is greater than permitted
[13:01:18] Explicit valence for atom # 12 C greater than permitted
[13:01:18] Explicit valence for atom # 23 C, 5, is greater than permitted
[13:01:18] Explicit valence for atom # 38 C greater than permitted
[13:01:18] Explicit valence for atom # 11 C, 5, is greater than permitted
[13:01:18] Explicit valence for atom # 11 C greater than permitted
[13:01:18] Explicit valence for atom # 17 C greater than permitted
[13:01:18] Explicit valence for atom # 1 C greater than permitted
[13:01:18] Explicit valence for atom # 5 C, 5, is greater than permitted
[13:01:18] Explicit valence for atom # 11 C, 6, is greater than permitted
[13:01:18] Explicit valence for atom # 21 C, 5, is greater than permitted
[13:01:18] Explicit valence for atom # 28 C greater than permitted
[13:01:18] Explicit valence for atom # 29 C greater than permitted
[13:01:18] Explicit valence for atom # 27 C greater than permitted
[13:01:18] Explicit valence for atom # 9 C, 5, is greater than permitted
[13:01:18] Explicit valence for atom # 15 C greater than permitted
[13:01:18] Explicit valence for atom # 35 C greater than permitted
[13:01:18] Explicit valence for atom # 24 C greater than permitted
[13:01:18] Explicit valence for atom # 17 C greater than permitted
[13:01:18] Explicit valence for atom # 13 C greater than permitted
[13:01:18] Explicit valence for atom # 30 C greater than permitted
[13:01:18] Explicit valence for atom # 29 P, 7, is greater than permitted
[13:01:18] Explicit valence for atom # 14 C greater than permitted
[13:01:18] Explicit valence for atom # 1 C, 5, is greater than permitted
[13:01:18] Explicit valence for atom # 22 P, 7, is greater than permitted
[13:01:18] Explicit valence for atom # 21 C greater than permitted
[13:01:18] Explicit valence for atom # 6 C greater than permitted
[13:01:18] Explicit valence for atom # 22 C greater than permitted
[13:01:18] Explicit valence for atom # 5 C, 5, is greater than permitted
[13:01:18] Explicit valence for atom # 28 C, 6, is greater than permitted
[13:01:18] Explicit valence for atom # 19 C greater than permitted
[13:01:18] Explicit valence for atom # 21 C greater than permitted
[13:01:18] Explicit valence for atom # 33 C greater than permitted
[13:01:18] Explicit valence for atom # 36 C, 5, is greater than permitted
[13:01:18] Explicit valence for atom # 8 C greater than permitted
[13:01:18] Explicit valence for atom # 37 C greater than permitted
[13:01:18] Explicit valence for atom # 17 C greater than permitted
[13:01:18] Explicit valence for atom # 6 C greater than permitted
[13:01:18] Explicit valence for atom # 23 C, 5, is greater than permitted
[13:01:18] Explicit valence for atom # 39 C greater than permitted
[13:01:18] Explicit valence for atom # 23 C, 6, is greater than permitted
[13:01:18] Explicit valence for atom # 22 C greater than permitted
[13:01:18] Explicit valence for atom # 20 C, 6, is greater than permitted
[13:01:18] Explicit valence for atom # 21 C greater than permitted
[13:01:19] Explicit valence for atom # 31 C greater than permitted
[13:01:19] Explicit valence for atom # 24 P, 7, is greater than permitted
[13:01:19] Explicit valence for atom # 23 C, 5, is greater than permitted
[13:01:19] Explicit valence for atom # 23 C, 5, is greater than permitted
[13:01:19] Explicit valence for atom # 5 C greater than permitted
[13:01:19] Explicit valence for atom # 24 C greater than permitted
[13:01:19] Explicit valence for atom # 9 P, 6, is greater than permitted
[13:01:19] Explicit valence for atom # 18 P, 7, is greater than permitted
[13:01:19] Explicit valence for atom # 24 C, 5, is greater than permitted
[13:01:19] Explicit valence for atom # 25 C, 5, is greater than permitted
[13:01:19] Explicit valence for atom # 15 C, 6, is greater than permitted
[13:01:19] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:01:19] Explicit valence for atom # 14 P, 7, is greater than permitted
[13:01:19] Explicit valence for atom # 7 P, 7, is greater than permitted
[13:01:19] Explicit valence for atom # 20 C greater than permitted
[13:01:19] Explicit valence for atom # 27 P, 7, is greater than permitted
[13:01:19] Explicit valence for atom # 21 C greater than permitted
[13:01:19] Explicit valence for atom # 35 C greater than permitted
[13:01:19] Explicit valence for atom # 24 Si, 5, is greater than permitted
[13:01:19] Explicit valence for atom # 23 C, 6, is greater than permitted
[13:01:19] Explicit valence for atom # 20 C, 5, is greater than permitted
[13:01:19] Explicit valence for atom # 26 C greater than permitted
[13:01:19] Explicit valence for atom # 37 C greater than permitted
[13:01:19] Explicit valence for atom # 6 C, 5, is greater than permitted
[13:01:19] Explicit valence for atom # 22 C, 5, is greater than permitted
[13:01:19] Explicit valence for atom # 27 Si, 5, is greater than permitted
[13:01:19] Explicit valence for atom # 20 C, 6, is greater than permitted
[13:01:19] Explicit valence for atom # 23 C greater than permitted
[13:01:19] Explicit valence for atom # 26 C, 6, is greater than permitted
[13:01:19] Explicit valence for atom # 19 C, 5, is greater than permitted
[13:01:19] Explicit valence for atom # 3 C greater than permitted
[13:01:19] Explicit valence for atom # 12 C greater than permitted
[13:01:19] Explicit valence for atom # 21 C greater than permitted
[13:01:19] Explicit valence for atom # 37 C greater than permitted
[13:01:19] Explicit valence for atom # 25 C greater than permitted
[13:01:19] Explicit valence for atom # 28 C, 5, is greater than permitted
[13:01:19] Explicit valence for atom # 35 C greater than permitted
[13:01:19] Explicit valence for atom # 21 C greater than permitted
[13:01:19] Explicit valence for atom # 14 C greater than permitted
[13:01:19] Explicit valence for atom # 7 P, 7, is greater than permitted
[13:01:19] Explicit valence for atom # 18 C greater than permitted
[13:01:19] Explicit valence for atom # 20 C greater than permitted
[13:01:19] Explicit valence for atom # 28 C greater than permitted
[13:01:19] Explicit valence for atom # 20 C greater than permitted
[13:01:19] Explicit valence for atom # 23 C greater than permitted
[13:01:19] Explicit valence for atom # 1 C, 5, is greater than permitted
[13:01:19] Explicit valence for atom # 35 C greater than permitted
[13:01:19] Explicit valence for atom # 27 C, 5, is greater than permitted
[13:01:19] Explicit valence for atom # 6 C, 5, is greater than permitted
[13:01:19] Explicit valence for atom # 19 Si, 5, is greater than permitted
[13:01:19] Explicit valence for atom # 21 P, 7, is greater than permitted
[13:01:19] Explicit valence for atom # 26 C, 6, is greater than permitted
[13:01:19] Explicit valence for atom # 6 C, 5, is greater than permitted
[13:01:19] Explicit valence for atom # 33 P, 7, is greater than permitted
[13:01:19] Explicit valence for atom # 14 C, 5, is greater than permitted
[13:01:19] Explicit valence for atom # 32 C greater than permitted
[13:01:19] Explicit valence for atom # 13 C greater than permitted
[13:01:19] Explicit valence for atom # 14 C, 5, is greater than permitted
[13:01:19] Explicit valence for atom # 27 C greater than permitted
[13:01:19] Explicit valence for atom # 23 C greater than permitted
[13:01:19] Explicit valence for atom # 32 Si, 5, is greater than permitted
[13:01:19] Explicit valence for atom # 3 Si, 5, is greater than permitted
[13:01:19] Explicit valence for atom # 20 C, 5, is greater than permitted
[13:01:19] Explicit valence for atom # 23 C, 6, is greater than permitted
[13:01:19] Explicit valence for atom # 12 C greater than permitted
[13:01:19] Explicit valence for atom # 26 C greater than permitted
[13:01:19] Explicit valence for atom # 7 C, 5, is greater than permitted
[13:01:19] Explicit valence for atom # 34 C, 6, is greater than permitted
[13:01:19] Explicit valence for atom # 15 C greater than permitted
[13:01:19] Explicit valence for atom # 25 C, 5, is greater than permitted
[13:01:19] Explicit valence for atom # 26 C greater than permitted
[13:01:19] Explicit valence for atom # 18 C greater than permitted
[13:01:19] Explicit valence for atom # 18 C greater than permitted
[13:01:19] Explicit valence for atom # 17 C greater than permitted
[13:01:19] Explicit valence for atom # 19 C, 6, is greater than permitted
[13:01:19] Explicit valence for atom # 1 C, 5, is greater than permitted
[13:01:19] Explicit valence for atom # 12 P, 5, is greater than permitted
[13:01:19] Explicit valence for atom # 22 C greater than permitted
[13:01:19] Explicit valence for atom # 31 C, 6, is greater than permitted
[13:01:19] Explicit valence for atom # 35 C greater than permitted
[13:01:19] Explicit valence for atom # 23 C greater than permitted
[13:01:19] Explicit valence for atom # 13 P, 5, is greater than permitted
[13:01:19] Explicit valence for atom # 15 C greater than permitted
[13:01:19] Explicit valence for atom # 12 C greater than permitted
[13:01:19] Explicit valence for atom # 22 C, 5, is greater than permitted
[13:01:19] Explicit valence for atom # 26 C greater than permitted
[13:01:19] Explicit valence for atom # 11 C, 5, is greater than permitted
[13:01:20] Explicit valence for atom # 21 Si, 5, is greater than permitted
[13:01:20] Explicit valence for atom # 13 C greater than permitted
[13:01:20] Explicit valence for atom # 21 C greater than permitted
[13:01:20] Explicit valence for atom # 22 C, 6, is greater than permitted
[13:01:20] Explicit valence for atom # 31 C greater than permitted
[13:01:20] Explicit valence for atom # 12 P, 6, is greater than permitted
[13:01:20] Explicit valence for atom # 5 C, 5, is greater than permitted
[13:01:20] Explicit valence for atom # 5 C, 5, is greater than permitted
[13:01:20] Explicit valence for atom # 16 C, 5, is greater than permitted
[13:01:20] Explicit valence for atom # 7 C greater than permitted
[13:01:20] Explicit valence for atom # 26 C greater than permitted
[13:01:20] Explicit valence for atom # 26 C greater than permitted
[13:01:20] Explicit valence for atom # 31 Si, 5, is greater than permitted
[13:01:20] Explicit valence for atom # 10 C greater than permitted
[13:01:20] Explicit valence for atom # 6 C, 5, is greater than permitted
[13:01:20] Explicit valence for atom # 17 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 22 C, 5, is greater than permitted
[13:01:20] Explicit valence for atom # 6 C, 5, is greater than permitted
[13:01:20] Explicit valence for atom # 21 C greater than permitted
[13:01:20] Explicit valence for atom # 7 C greater than permitted
[13:01:20] Explicit valence for atom # 23 C greater than permitted
[13:01:20] Explicit valence for atom # 22 C, 6, is greater than permitted
[13:01:20] Explicit valence for atom # 32 C, 5, is greater than permitted
[13:01:20] Explicit valence for atom # 17 C greater than permitted
[13:01:20] Explicit valence for atom # 29 C greater than permitted
[13:01:20] Explicit valence for atom # 11 C, 6, is greater than permitted
[13:01:20] Explicit valence for atom # 20 C greater than permitted
[13:01:20] Explicit valence for atom # 16 C, 6, is greater than permitted
[13:01:20] Explicit valence for atom # 27 C, 6, is greater than permitted
[13:01:20] Explicit valence for atom # 34 C, 5, is greater than permitted
[13:01:20] Explicit valence for atom # 18 C greater than permitted
[13:01:20] Explicit valence for atom # 25 C greater than permitted
[13:01:20] Explicit valence for atom # 21 C, 5, is greater than permitted
[13:01:20] Explicit valence for atom # 28 C, 5, is greater than permitted
[13:01:20] Explicit valence for atom # 21 C greater than permitted
[13:01:20] Explicit valence for atom # 22 C greater than permitted
[13:01:20] Explicit valence for atom # 30 C greater than permitted
[13:01:20] Explicit valence for atom # 2 Si, 5, is greater than permitted
[13:01:20] Explicit valence for atom # 18 C, 6, is greater than permitted
[13:01:20] Explicit valence for atom # 29 C greater than permitted
[13:01:20] Explicit valence for atom # 8 C, 5, is greater than permitted
[13:01:20] Explicit valence for atom # 22 C greater than permitted
[13:01:20] Explicit valence for atom # 25 C, 5, is greater than permitted
[13:01:20] Explicit valence for atom # 36 C greater than permitted
[13:01:20] Explicit valence for atom # 6 C greater than permitted
[13:01:20] Explicit valence for atom # 22 C greater than permitted
[13:01:20] Explicit valence for atom # 5 C, 5, is greater than permitted
[13:01:20] Explicit valence for atom # 30 C greater than permitted
[13:01:20] Explicit valence for atom # 31 C, 5, is greater than permitted
[13:01:20] Explicit valence for atom # 30 C greater than permitted
[13:01:20] Explicit valence for atom # 22 P, 7, is greater than permitted
[13:01:20] Explicit valence for atom # 22 Si, 5, is greater than permitted
[13:01:20] Explicit valence for atom # 8 Si, 5, is greater than permitted
[13:01:20] Explicit valence for atom # 23 C, 6, is greater than permitted
[13:01:20] Explicit valence for atom # 22 C greater than permitted
[13:01:20] Explicit valence for atom # 29 C greater than permitted
[13:01:20] Explicit valence for atom # 16 C, 5, is greater than permitted
[13:01:20] Explicit valence for atom # 30 C, 5, is greater than permitted
[13:01:20] Explicit valence for atom # 2 C greater than permitted
[13:01:20] Explicit valence for atom # 14 C greater than permitted
[13:01:20] Explicit valence for atom # 22 C, 5, is greater than permitted
[13:01:20] Explicit valence for atom # 0 C greater than permitted
[13:01:20] Explicit valence for atom # 21 C greater than permitted
[13:01:21] Explicit valence for atom # 27 C, 6, is greater than permitted
[13:01:21] Explicit valence for atom # 25 C greater than permitted
[13:01:21] Explicit valence for atom # 6 C, 5, is greater than permitted
[13:01:21] Explicit valence for atom # 21 C, 5, is greater than permitted
[13:01:21] Explicit valence for atom # 12 P, 6, is greater than permitted
[13:01:21] Explicit valence for atom # 14 C greater than permitted
[13:01:21] Explicit valence for atom # 22 C greater than permitted
[13:01:21] Explicit valence for atom # 30 C, 5, is greater than permitted
[13:01:22] Explicit valence for atom # 30 C greater than permitted

--- Processing cluster 2 ---

[13:01:37] Explicit valence for atom # 7 C greater than permitted
[13:01:37] Explicit valence for atom # 20 C, 5, is greater than permitted
[13:01:37] Explicit valence for atom # 26 Si, 5, is greater than permitted
[13:01:37] Explicit valence for atom # 18 C, 5, is greater than permitted
[13:01:37] Explicit valence for atom # 28 C greater than permitted
[13:01:37] Explicit valence for atom # 12 C greater than permitted
[13:01:37] Explicit valence for atom # 30 C greater than permitted
[13:01:37] Explicit valence for atom # 7 P, 7, is greater than permitted
[13:01:37] Explicit valence for atom # 30 C greater than permitted
[13:01:37] Explicit valence for atom # 1 C, 5, is greater than permitted
[13:01:37] Explicit valence for atom # 33 C greater than permitted
[13:01:37] Explicit valence for atom # 25 C greater than permitted
[13:01:37] Explicit valence for atom # 7 C, 5, is greater than permitted
[13:01:37] Explicit valence for atom # 28 P, 7, is greater than permitted
[13:01:37] Explicit valence for atom # 18 C greater than permitted
[13:01:37] Explicit valence for atom # 28 Si, 5, is greater than permitted
[13:01:37] Explicit valence for atom # 39 C greater than permitted
[13:01:37] Explicit valence for atom # 24 C greater than permitted
[13:01:37] Explicit valence for atom # 26 Si, 5, is greater than permitted
[13:01:37] Explicit valence for atom # 24 C, 5, is greater than permitted
[13:01:37] Explicit valence for atom # 14 C greater than permitted
[13:01:37] Explicit valence for atom # 8 C greater than permitted
[13:01:37] Explicit valence for atom # 23 C, 5, is greater than permitted
[13:01:37] Explicit valence for atom # 26 C greater than permitted
[13:01:37] Explicit valence for atom # 26 C, 5, is greater than permitted
[13:01:37] Explicit valence for atom # 29 C, 5, is greater than permitted
[13:01:37] Explicit valence for atom # 19 C greater than permitted
[13:01:37] Explicit valence for atom # 35 C greater than permitted
[13:01:37] Explicit valence for atom # 8 C greater than permitted
[13:01:37] Explicit valence for atom # 14 C greater than permitted
[13:01:37] Explicit valence for atom # 16 C greater than permitted
[13:01:37] Explicit valence for atom # 30 C greater than permitted
[13:01:37] Explicit valence for atom # 1 C, 5, is greater than permitted
[13:01:37] Explicit valence for atom # 17 C, 5, is greater than permitted
[13:01:37] Explicit valence for atom # 21 C greater than permitted
[13:01:37] Explicit valence for atom # 26 C greater than permitted
[13:01:38] Explicit valence for atom # 32 C greater than permitted
[13:01:38] Explicit valence for atom # 21 C greater than permitted
[13:01:38] Explicit valence for atom # 6 C greater than permitted
[13:01:38] Explicit valence for atom # 17 C greater than permitted
[13:01:38] Explicit valence for atom # 34 C, 5, is greater than permitted
[13:01:38] Explicit valence for atom # 20 C, 5, is greater than permitted
[13:01:38] Explicit valence for atom # 24 C greater than permitted
[13:01:38] Explicit valence for atom # 3 C greater than permitted
[13:01:38] Explicit valence for atom # 28 C, 5, is greater than permitted
[13:01:38] Explicit valence for atom # 18 C greater than permitted
[13:01:38] Explicit valence for atom # 32 C greater than permitted
[13:01:38] Explicit valence for atom # 23 Si, 5, is greater than permitted
[13:01:38] Explicit valence for atom # 26 C, 5, is greater than permitted
[13:01:38] Explicit valence for atom # 17 C, 5, is greater than permitted
[13:01:38] Explicit valence for atom # 20 C, 6, is greater than permitted
[13:01:38] Explicit valence for atom # 15 C, 5, is greater than permitted
[13:01:38] Explicit valence for atom # 23 C, 5, is greater than permitted
[13:01:38] Explicit valence for atom # 16 C, 5, is greater than permitted
[13:01:38] Explicit valence for atom # 6 C, 5, is greater than permitted
[13:01:38] Explicit valence for atom # 26 C greater than permitted
[13:01:38] Explicit valence for atom # 24 C greater than permitted
[13:01:38] Explicit valence for atom # 28 P, 7, is greater than permitted
[13:01:38] Explicit valence for atom # 27 C greater than permitted
[13:01:38] Explicit valence for atom # 12 C, 5, is greater than permitted
[13:01:38] Explicit valence for atom # 4 C, 5, is greater than permitted
[13:01:38] Explicit valence for atom # 10 C greater than permitted
[13:01:38] Explicit valence for atom # 14 C greater than permitted
[13:01:38] Explicit valence for atom # 7 C, 5, is greater than permitted
[13:01:38] Explicit valence for atom # 20 C, 5, is greater than permitted
[13:01:38] Explicit valence for atom # 37 C greater than permitted
[13:01:38] Explicit valence for atom # 6 C, 5, is greater than permitted
[13:01:38] Explicit valence for atom # 5 C, 5, is greater than permitted
[13:01:38] Explicit valence for atom # 22 C greater than permitted
[13:01:38] Explicit valence for atom # 22 C greater than permitted
[13:01:38] Explicit valence for atom # 23 C greater than permitted
[13:01:38] Explicit valence for atom # 30 C greater than permitted
[13:01:38] Explicit valence for atom # 22 C greater than permitted
[13:01:38] Explicit valence for atom # 21 C greater than permitted
[13:01:38] Explicit valence for atom # 15 C greater than permitted
[13:01:38] Explicit valence for atom # 29 C greater than permitted
[13:01:38] Explicit valence for atom # 21 C greater than permitted
[13:01:38] Explicit valence for atom # 13 C, 5, is greater than permitted
[13:01:38] Explicit valence for atom # 38 C greater than permitted
[13:01:38] Explicit valence for atom # 12 C, 6, is greater than permitted
[13:01:38] Explicit valence for atom # 33 C greater than permitted
[13:01:38] Explicit valence for atom # 26 C greater than permitted
[13:01:38] Explicit valence for atom # 28 C, 5, is greater than permitted
[13:01:38] Explicit valence for atom # 28 Si, 5, is greater than permitted
[13:01:38] Explicit valence for atom # 40 C greater than permitted
[13:01:38] Explicit valence for atom # 24 C greater than permitted
[13:01:38] Explicit valence for atom # 28 C greater than permitted
[13:01:38] Explicit valence for atom # 16 C greater than permitted
[13:01:38] Explicit valence for atom # 29 C greater than permitted
[13:01:38] Explicit valence for atom # 30 C greater than permitted
[13:01:38] Explicit valence for atom # 26 C, 5, is greater than permitted
[13:01:38] Explicit valence for atom # 24 C, 5, is greater than permitted
[13:01:38] Explicit valence for atom # 32 P, 7, is greater than permitted
[13:01:38] Explicit valence for atom # 7 C, 5, is greater than permitted
[13:01:38] Explicit valence for atom # 24 C, 5, is greater than permitted
[13:01:38] Explicit valence for atom # 28 C greater than permitted
[13:01:38] Explicit valence for atom # 12 C, 5, is greater than permitted
[13:01:38] Explicit valence for atom # 29 C greater than permitted
[13:01:38] Explicit valence for atom # 32 C greater than permitted
[13:01:38] Explicit valence for atom # 19 C, 6, is greater than permitted
[13:01:38] Explicit valence for atom # 2 C greater than permitted
[13:01:38] Explicit valence for atom # 27 C greater than permitted
[13:01:38] Explicit valence for atom # 24 C, 5, is greater than permitted
[13:01:38] Explicit valence for atom # 36 C, 5, is greater than permitted
[13:01:38] Explicit valence for atom # 25 C, 5, is greater than permitted
[13:01:38] Explicit valence for atom # 5 C, 6, is greater than permitted
[13:01:38] Explicit valence for atom # 21 C, 6, is greater than permitted
[13:01:38] Explicit valence for atom # 32 C greater than permitted
[13:01:38] Explicit valence for atom # 12 C greater than permitted
[13:01:38] Explicit valence for atom # 44 C greater than permitted
[13:01:38] Explicit valence for atom # 30 C greater than permitted
[13:01:38] Explicit valence for atom # 29 C greater than permitted
[13:01:38] Explicit valence for atom # 1 C, 5, is greater than permitted
[13:01:38] Explicit valence for atom # 22 C greater than permitted
[13:01:38] Explicit valence for atom # 13 C greater than permitted
[13:01:38] Explicit valence for atom # 10 P, 7, is greater than permitted
[13:01:38] Explicit valence for atom # 6 Si, 5, is greater than permitted
[13:01:38] Explicit valence for atom # 12 C greater than permitted
[13:01:38] Explicit valence for atom # 33 C greater than permitted
[13:01:38] Explicit valence for atom # 9 C, 5, is greater than permitted
[13:01:38] Explicit valence for atom # 28 C, 5, is greater than permitted
[13:01:39] Explicit valence for atom # 28 Si, 5, is greater than permitted
[13:01:39] Explicit valence for atom # 21 C greater than permitted
[13:01:39] Explicit valence for atom # 35 C, 5, is greater than permitted
[13:01:39] Explicit valence for atom # 26 C greater than permitted
[13:01:39] Explicit valence for atom # 14 C greater than permitted
[13:01:39] Explicit valence for atom # 7 C, 5, is greater than permitted
[13:01:39] Explicit valence for atom # 1 C, 5, is greater than permitted
[13:01:39] Explicit valence for atom # 22 C greater than permitted
[13:01:39] Explicit valence for atom # 1 Si, 5, is greater than permitted
[13:01:39] Explicit valence for atom # 20 C greater than permitted
[13:01:39] Explicit valence for atom # 30 C, 5, is greater than permitted
[13:01:39] Explicit valence for atom # 12 C, 6, is greater than permitted
[13:01:39] Explicit valence for atom # 18 C, 6, is greater than permitted
[13:01:39] Explicit valence for atom # 28 C, 5, is greater than permitted
[13:01:39] Explicit valence for atom # 20 P, 7, is greater than permitted
[13:01:39] Explicit valence for atom # 27 C greater than permitted
[13:01:39] Explicit valence for atom # 25 C greater than permitted
[13:01:39] Explicit valence for atom # 20 C greater than permitted
[13:01:39] Explicit valence for atom # 29 C greater than permitted
[13:01:39] Explicit valence for atom # 6 C, 6, is greater than permitted
[13:01:39] Explicit valence for atom # 20 C greater than permitted
[13:01:39] Explicit valence for atom # 29 C greater than permitted
[13:01:39] Explicit valence for atom # 18 C greater than permitted
[13:01:39] Explicit valence for atom # 20 C greater than permitted
[13:01:39] Explicit valence for atom # 26 C greater than permitted
[13:01:39] Explicit valence for atom # 15 C greater than permitted
[13:01:39] Explicit valence for atom # 36 C greater than permitted
[13:01:39] Explicit valence for atom # 20 C, 5, is greater than permitted
[13:01:39] Explicit valence for atom # 12 C, 5, is greater than permitted
[13:01:39] Explicit valence for atom # 30 C, 5, is greater than permitted
[13:01:39] Explicit valence for atom # 28 C, 5, is greater than permitted
[13:01:39] Explicit valence for atom # 28 C greater than permitted
[13:01:39] Explicit valence for atom # 12 C greater than permitted
[13:01:39] Explicit valence for atom # 10 P, 7, is greater than permitted
[13:01:39] Explicit valence for atom # 25 C greater than permitted
[13:01:39] Explicit valence for atom # 26 C, 5, is greater than permitted
[13:01:39] Explicit valence for atom # 23 C greater than permitted
[13:01:39] Explicit valence for atom # 10 P, 7, is greater than permitted
[13:01:39] Explicit valence for atom # 26 C greater than permitted
[13:01:39] Explicit valence for atom # 18 C greater than permitted
[13:01:39] Explicit valence for atom # 23 C, 5, is greater than permitted
[13:01:39] Explicit valence for atom # 15 C, 6, is greater than permitted
[13:01:39] Explicit valence for atom # 23 C greater than permitted
[13:01:39] Explicit valence for atom # 16 C greater than permitted
[13:01:39] Explicit valence for atom # 16 C, 5, is greater than permitted
[13:01:39] Explicit valence for atom # 25 C greater than permitted
[13:01:39] Explicit valence for atom # 26 C greater than permitted
[13:01:39] Explicit valence for atom # 29 C, 5, is greater than permitted
[13:01:39] Explicit valence for atom # 11 C, 5, is greater than permitted
[13:01:39] Explicit valence for atom # 29 C greater than permitted
[13:01:39] Explicit valence for atom # 1 C, 5, is greater than permitted
[13:01:39] Explicit valence for atom # 23 C greater than permitted
[13:01:39] Explicit valence for atom # 28 C greater than permitted
[13:01:39] Explicit valence for atom # 33 C greater than permitted
[13:01:39] Explicit valence for atom # 22 C greater than permitted
[13:01:39] Explicit valence for atom # 28 C greater than permitted
[13:01:39] Explicit valence for atom # 23 C greater than permitted
[13:01:39] Explicit valence for atom # 13 Si, 5, is greater than permitted
[13:01:39] Explicit valence for atom # 12 C, 5, is greater than permitted
[13:01:39] Explicit valence for atom # 34 C greater than permitted
[13:01:39] Explicit valence for atom # 17 Si, 5, is greater than permitted
[13:01:39] Explicit valence for atom # 45 C greater than permitted
[13:01:39] Explicit valence for atom # 13 C greater than permitted
[13:01:39] Explicit valence for atom # 31 C, 5, is greater than permitted
[13:01:39] Explicit valence for atom # 8 C greater than permitted
[13:01:39] Explicit valence for atom # 14 C, 5, is greater than permitted
[13:01:39] Explicit valence for atom # 18 Si, 5, is greater than permitted
[13:01:39] Explicit valence for atom # 21 C greater than permitted
[13:01:39] Explicit valence for atom # 6 C, 5, is greater than permitted
[13:01:39] Explicit valence for atom # 26 C greater than permitted
[13:01:39] Explicit valence for atom # 28 C greater than permitted
[13:01:39] Explicit valence for atom # 31 C, 5, is greater than permitted
[13:01:39] Explicit valence for atom # 28 P, 7, is greater than permitted
[13:01:39] Explicit valence for atom # 24 C greater than permitted
[13:01:39] Explicit valence for atom # 21 C greater than permitted
[13:01:39] Explicit valence for atom # 16 C greater than permitted
[13:01:39] Explicit valence for atom # 25 C, 5, is greater than permitted
[13:01:39] Explicit valence for atom # 17 C, 5, is greater than permitted
[13:01:39] Explicit valence for atom # 23 C greater than permitted
[13:01:39] Explicit valence for atom # 16 C greater than permitted
[13:01:40] Explicit valence for atom # 15 Si, 5, is greater than permitted
[13:01:40] Explicit valence for atom # 15 C, 5, is greater than permitted
[13:01:40] Explicit valence for atom # 13 C greater than permitted
[13:01:40] Explicit valence for atom # 33 C greater than permitted
[13:01:40] Explicit valence for atom # 27 C greater than permitted
[13:01:40] Explicit valence for atom # 25 C greater than permitted
[13:01:40] Explicit valence for atom # 13 C greater than permitted
[13:01:40] Explicit valence for atom # 18 P, 6, is greater than permitted
[13:01:40] Explicit valence for atom # 14 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 22 C, 5, is greater than permitted
[13:01:40] Explicit valence for atom # 18 C greater than permitted
[13:01:40] Explicit valence for atom # 25 C greater than permitted
[13:01:40] Explicit valence for atom # 22 C greater than permitted
[13:01:40] Explicit valence for atom # 32 C greater than permitted
[13:01:40] Explicit valence for atom # 11 P, 7, is greater than permitted
[13:01:40] Explicit valence for atom # 6 C, 5, is greater than permitted
[13:01:42] Explicit valence for atom # 20 C greater than permitted
[13:01:42] Explicit valence for atom # 10 C, 5, is greater than permitted

--- Processing cluster 3 ---

[13:01:53] Explicit valence for atom # 16 C greater than permitted
[13:01:53] Explicit valence for atom # 19 C greater than permitted
[13:01:53] Explicit valence for atom # 13 C greater than permitted
[13:01:53] Explicit valence for atom # 28 C greater than permitted
[13:01:53] Explicit valence for atom # 18 C, 6, is greater than permitted
[13:01:53] Explicit valence for atom # 23 C greater than permitted
[13:01:53] Explicit valence for atom # 18 C greater than permitted
[13:01:53] Explicit valence for atom # 31 C greater than permitted
[13:01:53] Explicit valence for atom # 31 C greater than permitted
[13:01:53] Explicit valence for atom # 31 C greater than permitted
[13:01:53] Explicit valence for atom # 29 C greater than permitted
[13:01:53] Explicit valence for atom # 23 C greater than permitted
[13:01:53] Explicit valence for atom # 5 C greater than permitted
[13:01:53] Explicit valence for atom # 10 C, 5, is greater than permitted
[13:01:53] Explicit valence for atom # 16 C, 5, is greater than permitted
[13:01:53] Explicit valence for atom # 2 C, 5, is greater than permitted
[13:01:53] Explicit valence for atom # 4 C greater than permitted
[13:01:53] Explicit valence for atom # 24 C greater than permitted
[13:01:53] Explicit valence for atom # 35 C greater than permitted
[13:01:53] Explicit valence for atom # 26 C greater than permitted
[13:01:54] Explicit valence for atom # 28 C greater than permitted
[13:01:54] Explicit valence for atom # 22 C greater than permitted
[13:01:54] Explicit valence for atom # 22 C, 5, is greater than permitted
[13:01:54] Explicit valence for atom # 26 C, 5, is greater than permitted
[13:01:54] Explicit valence for atom # 26 C greater than permitted
[13:01:54] Explicit valence for atom # 15 C, 5, is greater than permitted
[13:01:54] Explicit valence for atom # 28 C greater than permitted
[13:01:54] Explicit valence for atom # 23 C greater than permitted
[13:01:54] Explicit valence for atom # 23 C greater than permitted
[13:01:54] Explicit valence for atom # 25 C greater than permitted
[13:01:54] Explicit valence for atom # 28 C greater than permitted
[13:01:54] Explicit valence for atom # 28 C, 5, is greater than permitted
[13:01:54] Explicit valence for atom # 5 C greater than permitted
[13:01:54] Explicit valence for atom # 29 C greater than permitted
[13:01:54] Explicit valence for atom # 26 C greater than permitted
[13:01:54] Explicit valence for atom # 17 C greater than permitted
[13:01:54] Explicit valence for atom # 26 C greater than permitted
[13:01:54] Explicit valence for atom # 30 C, 5, is greater than permitted
[13:01:54] Explicit valence for atom # 22 Si, 5, is greater than permitted
[13:01:54] Explicit valence for atom # 25 Si, 5, is greater than permitted
[13:01:54] Explicit valence for atom # 28 C greater than permitted
[13:01:54] Explicit valence for atom # 1 C greater than permitted
[13:01:54] Explicit valence for atom # 20 Si, 5, is greater than permitted
[13:01:54] Explicit valence for atom # 21 Si, 5, is greater than permitted
[13:01:54] Explicit valence for atom # 21 C greater than permitted
[13:01:54] Explicit valence for atom # 19 C, 5, is greater than permitted
[13:01:54] Explicit valence for atom # 24 C greater than permitted
[13:01:54] Explicit valence for atom # 26 C greater than permitted
[13:01:54] Explicit valence for atom # 3 C greater than permitted
[13:01:54] Explicit valence for atom # 29 C greater than permitted
[13:01:54] Explicit valence for atom # 27 C, 6, is greater than permitted
[13:01:54] Explicit valence for atom # 34 C greater than permitted
[13:01:54] Explicit valence for atom # 13 C greater than permitted
[13:01:54] Explicit valence for atom # 0 C greater than permitted
[13:01:54] Explicit valence for atom # 25 C, 6, is greater than permitted
[13:01:54] Explicit valence for atom # 31 C greater than permitted
[13:01:54] Explicit valence for atom # 26 P, 7, is greater than permitted
[13:01:54] Explicit valence for atom # 17 C greater than permitted
[13:01:54] Explicit valence for atom # 36 C, 5, is greater than permitted
[13:01:54] Explicit valence for atom # 23 C greater than permitted
[13:01:54] Explicit valence for atom # 33 C greater than permitted
[13:01:54] Explicit valence for atom # 21 P, 7, is greater than permitted
[13:01:54] Explicit valence for atom # 36 C greater than permitted
[13:01:54] Explicit valence for atom # 19 C greater than permitted
[13:01:54] Explicit valence for atom # 42 C greater than permitted
[13:01:54] Explicit valence for atom # 26 C greater than permitted
[13:01:54] Explicit valence for atom # 33 Si, 5, is greater than permitted
[13:01:54] Explicit valence for atom # 12 P, 7, is greater than permitted
[13:01:54] Explicit valence for atom # 26 Si, 5, is greater than permitted
[13:01:54] Explicit valence for atom # 33 C greater than permitted
[13:01:54] Explicit valence for atom # 25 C greater than permitted
[13:01:54] Explicit valence for atom # 28 C greater than permitted
[13:01:54] Explicit valence for atom # 26 C, 5, is greater than permitted
[13:01:54] Explicit valence for atom # 25 C greater than permitted
[13:01:54] Explicit valence for atom # 10 P, 7, is greater than permitted
[13:01:54] Explicit valence for atom # 17 C greater than permitted
[13:01:54] Explicit valence for atom # 24 C greater than permitted
[13:01:54] Explicit valence for atom # 23 C greater than permitted
[13:01:54] Explicit valence for atom # 20 C greater than permitted
[13:01:54] Explicit valence for atom # 19 C greater than permitted
[13:01:54] Explicit valence for atom # 3 C greater than permitted
[13:01:54] Explicit valence for atom # 31 C, 4, is greater than permitted
[13:01:54] Explicit valence for atom # 5 C greater than permitted
[13:01:54] Explicit valence for atom # 26 C greater than permitted
[13:01:54] Explicit valence for atom # 29 C greater than permitted
[13:01:54] Explicit valence for atom # 33 C greater than permitted
[13:01:54] Explicit valence for atom # 37 C greater than permitted
[13:01:54] Explicit valence for atom # 32 C greater than permitted
[13:01:54] Explicit valence for atom # 23 Si, 5, is greater than permitted
[13:01:54] Explicit valence for atom # 20 C greater than permitted
[13:01:54] Explicit valence for atom # 19 C, 5, is greater than permitted
[13:01:54] Explicit valence for atom # 41 C greater than permitted
[13:01:54] Explicit valence for atom # 30 C greater than permitted
[13:01:54] Explicit valence for atom # 37 C greater than permitted
[13:01:54] Explicit valence for atom # 0 C greater than permitted
[13:01:54] Explicit valence for atom # 33 Si, 5, is greater than permitted
[13:01:54] Explicit valence for atom # 25 C, 5, is greater than permitted
[13:01:54] Explicit valence for atom # 28 C, 5, is greater than permitted
[13:01:54] Explicit valence for atom # 37 C greater than permitted
[13:01:54] Explicit valence for atom # 28 C greater than permitted
[13:01:54] Explicit valence for atom # 25 C greater than permitted
[13:01:54] Explicit valence for atom # 21 C, 5, is greater than permitted
[13:01:54] Explicit valence for atom # 19 C, 5, is greater than permitted
[13:01:54] Explicit valence for atom # 15 C greater than permitted
[13:01:54] Explicit valence for atom # 23 C greater than permitted
[13:01:54] Explicit valence for atom # 30 C greater than permitted
[13:01:54] Explicit valence for atom # 9 C greater than permitted
[13:01:54] Explicit valence for atom # 23 P, 7, is greater than permitted
[13:01:54] Explicit valence for atom # 13 C greater than permitted
[13:01:54] Explicit valence for atom # 23 Si, 5, is greater than permitted
[13:01:54] Explicit valence for atom # 31 C greater than permitted
[13:01:54] Explicit valence for atom # 32 C greater than permitted
[13:01:54] Explicit valence for atom # 26 C greater than permitted
[13:01:54] Explicit valence for atom # 22 C greater than permitted
[13:01:54] Explicit valence for atom # 28 C greater than permitted
[13:01:54] Explicit valence for atom # 15 C greater than permitted
[13:01:54] Explicit valence for atom # 28 C greater than permitted
[13:01:54] Explicit valence for atom # 12 C, 5, is greater than permitted
[13:01:54] Explicit valence for atom # 26 C greater than permitted
[13:01:54] Explicit valence for atom # 34 C greater than permitted
[13:01:54] Explicit valence for atom # 29 C greater than permitted
[13:01:54] Explicit valence for atom # 25 C greater than permitted
[13:01:54] Explicit valence for atom # 13 C greater than permitted
[13:01:54] Explicit valence for atom # 33 P, 7, is greater than permitted
[13:01:54] Explicit valence for atom # 30 C greater than permitted
[13:01:54] Explicit valence for atom # 37 C greater than permitted
[13:01:54] Explicit valence for atom # 10 C, 5, is greater than permitted
[13:01:54] Explicit valence for atom # 30 C greater than permitted
[13:01:54] Explicit valence for atom # 23 C greater than permitted
[13:01:54] Explicit valence for atom # 23 C, 5, is greater than permitted
[13:01:54] Explicit valence for atom # 16 C greater than permitted
[13:01:54] Explicit valence for atom # 17 C greater than permitted
[13:01:54] Explicit valence for atom # 27 C greater than permitted
[13:01:54] Explicit valence for atom # 3 P, 7, is greater than permitted
[13:01:54] Explicit valence for atom # 24 C, 6, is greater than permitted
[13:01:54] Explicit valence for atom # 25 C, 5, is greater than permitted
[13:01:54] Explicit valence for atom # 29 C greater than permitted
[13:01:54] Explicit valence for atom # 4 P, 6, is greater than permitted
[13:01:54] Explicit valence for atom # 23 C, 5, is greater than permitted
[13:01:54] Explicit valence for atom # 23 Si, 5, is greater than permitted
[13:01:54] Explicit valence for atom # 25 C greater than permitted
[13:01:54] Explicit valence for atom # 3 P, 7, is greater than permitted
[13:01:54] Explicit valence for atom # 12 P, 7, is greater than permitted
[13:01:54] Explicit valence for atom # 16 C greater than permitted
[13:01:54] Explicit valence for atom # 24 C greater than permitted
[13:01:54] Explicit valence for atom # 33 C greater than permitted
[13:01:54] Explicit valence for atom # 32 C greater than permitted
[13:01:55] Explicit valence for atom # 27 C greater than permitted
[13:01:54] Explicit valence for atom # 35 Si, 6, is greater than permitted
[13:01:55] Explicit valence for atom # 21 C, 5, is greater than permitted
[13:01:55] Explicit valence for atom # 37 C greater than permitted
[13:01:55] Explicit valence for atom # 37 C greater than permitted
[13:01:55] Explicit valence for atom # 18 P, 7, is greater than permitted
[13:01:55] Explicit valence for atom # 9 C greater than permitted
[13:01:55] Explicit valence for atom # 28 C, 5, is greater than permitted
[13:01:55] Explicit valence for atom # 25 C, 5, is greater than permitted
[13:01:55] Explicit valence for atom # 39 C greater than permitted
[13:01:55] Explicit valence for atom # 16 Si, 6, is greater than permitted
[13:01:55] Explicit valence for atom # 26 C greater than permitted
[13:01:55] Explicit valence for atom # 28 Si, 5, is greater than permitted
[13:01:55] Explicit valence for atom # 15 C greater than permitted
[13:01:55] Explicit valence for atom # 24 C, 5, is greater than permitted
[13:01:55] Explicit valence for atom # 3 C greater than permitted
[13:01:55] Explicit valence for atom # 4 C greater than permitted
[13:01:55] Explicit valence for atom # 28 C greater than permitted
[13:01:55] Explicit valence for atom # 21 C greater than permitted
[13:01:55] Explicit valence for atom # 17 C greater than permitted
[13:01:55] Explicit valence for atom # 34 C greater than permitted
[13:01:55] Explicit valence for atom # 19 As, 6, is greater than permitted
[13:01:55] Explicit valence for atom # 17 Si, 5, is greater than permitted
[13:01:55] Explicit valence for atom # 27 C greater than permitted
[13:01:55] Explicit valence for atom # 24 C greater than permitted
[13:01:55] Explicit valence for atom # 24 C greater than permitted
[13:01:55] Explicit valence for atom # 24 C greater than permitted
[13:01:55] Explicit valence for atom # 0 C greater than permitted
[13:01:55] Explicit valence for atom # 6 C greater than permitted
[13:01:55] Explicit valence for atom # 21 C greater than permitted
[13:01:55] Explicit valence for atom # 28 C greater than permitted
[13:01:55] Explicit valence for atom # 32 C greater than permitted
[13:01:55] Explicit valence for atom # 18 C, 6, is greater than permitted
[13:01:55] Explicit valence for atom # 28 C greater than permitted
[13:01:55] Explicit valence for atom # 31 C greater than permitted
[13:01:55] Explicit valence for atom # 5 C greater than permitted
[13:01:55] Explicit valence for atom # 34 C greater than permitted
[13:01:55] Explicit valence for atom # 26 Si, 5, is greater than permitted
[13:01:55] Explicit valence for atom # 22 P, 7, is greater than permitted
[13:01:55] Explicit valence for atom # 17 C greater than permitted
[13:01:55] Explicit valence for atom # 15 Si, 5, is greater than permitted
[13:01:55] Explicit valence for atom # 36 C greater than permitted
[13:01:55] Explicit valence for atom # 10 C, 5, is greater than permitted
[13:01:55] Explicit valence for atom # 22 C greater than permitted
[13:01:55] Explicit valence for atom # 25 C greater than permitted
[13:01:55] Explicit valence for atom # 19 C greater than permitted
[13:01:55] Explicit valence for atom # 22 C, 5, is greater than permitted
[13:01:55] Explicit valence for atom # 40 C greater than permitted
[13:01:55] Explicit valence for atom # 47 C greater than permitted
[13:01:55] Explicit valence for atom # 14 C greater than permitted
[13:01:55] Explicit valence for atom # 23 C greater than permitted
[13:01:55] Explicit valence for atom # 26 P, 7, is greater than permitted
[13:01:55] Explicit valence for atom # 31 C, 5, is greater than permitted
[13:01:55] Explicit valence for atom # 31 C greater than permitted
[13:01:55] Explicit valence for atom # 7 C greater than permitted
[13:01:55] Explicit valence for atom # 26 C, 5, is greater than permitted
[13:01:55] Explicit valence for atom # 24 C greater than permitted
[13:01:55] Explicit valence for atom # 30 C greater than permitted
[13:01:55] Explicit valence for atom # 26 C greater than permitted
[13:01:55] Explicit valence for atom # 23 C greater than permitted
[13:01:55] Explicit valence for atom # 32 C greater than permitted
[13:01:55] Explicit valence for atom # 21 C, 5, is greater than permitted
[13:01:55] Explicit valence for atom # 24 P, 7, is greater than permitted
[13:01:55] Explicit valence for atom # 22 C greater than permitted
[13:01:55] Explicit valence for atom # 24 C, 5, is greater than permitted
[13:01:55] Explicit valence for atom # 25 C, 5, is greater than permitted
[13:01:55] Explicit valence for atom # 23 C greater than permitted
[13:01:55] Explicit valence for atom # 10 C, 5, is greater than permitted
[13:01:55] Explicit valence for atom # 2 C greater than permitted
[13:01:55] Explicit valence for atom # 7 P, 7, is greater than permitted
[13:01:55] Explicit valence for atom # 1 C greater than permitted
[13:01:55] Explicit valence for atom # 6 C, 5, is greater than permitted
[13:01:55] Explicit valence for atom # 20 C greater than permitted
[13:01:55] Explicit valence for atom # 23 C greater than permitted
[13:01:55] Explicit valence for atom # 27 C, 5, is greater than permitted
[13:01:55] Explicit valence for atom # 22 Si, 5, is greater than permitted
[13:01:55] Explicit valence for atom # 42 Si, 5, is greater than permitted
[13:01:55] Explicit valence for atom # 17 Si, 5, is greater than permitted
[13:01:55] Explicit valence for atom # 28 C, 5, is greater than permitted
[13:01:55] Explicit valence for atom # 3 C greater than permitted
[13:01:55] Explicit valence for atom # 30 C greater than permitted
[13:01:55] Explicit valence for atom # 33 C greater than permitted
[13:01:55] Explicit valence for atom # 24 C greater than permitted
[13:01:55] Explicit valence for atom # 16 C greater than permitted
[13:01:55] Explicit valence for atom # 24 C greater than permitted
[13:01:55] Explicit valence for atom # 27 C greater than permitted
[13:01:55] Explicit valence for atom # 15 C greater than permitted
[13:01:55] Explicit valence for atom # 35 C greater than permitted
[13:01:55] Explicit valence for atom # 26 C greater than permitted
[13:01:55] Explicit valence for atom # 17 C greater than permitted
[13:01:55] Explicit valence for atom # 17 C greater than permitted
[13:01:55] Explicit valence for atom # 18 C greater than permitted
[13:01:55] Explicit valence for atom # 33 C greater than permitted
[13:01:55] Explicit valence for atom # 38 C greater than permitted
[13:01:55] Explicit valence for atom # 8 C greater than permitted
[13:01:55] Explicit valence for atom # 27 C greater than permitted
[13:01:55] Explicit valence for atom # 5 C greater than permitted
[13:01:55] Explicit valence for atom # 25 C, 5, is greater than permitted
[13:01:55] Explicit valence for atom # 13 C greater than permitted
[13:01:55] Explicit valence for atom # 23 C greater than permitted
[13:01:55] Explicit valence for atom # 31 C, 6, is greater than permitted
[13:01:55] Explicit valence for atom # 22 Si, 5, is greater than permitted
[13:01:55] Explicit valence for atom # 28 C greater than permitted
[13:01:55] Explicit valence for atom # 23 C greater than permitted
[13:01:55] Explicit valence for atom # 24 C greater than permitted
[13:01:55] Explicit valence for atom # 40 C greater than permitted
[13:01:55] Explicit valence for atom # 20 C greater than permitted
[13:01:55] Explicit valence for atom # 5 P, 7, is greater than permitted
[13:01:55] Explicit valence for atom # 37 C greater than permitted
[13:01:55] Explicit valence for atom # 30 C, 5, is greater than permitted
[13:01:55] Explicit valence for atom # 38 C greater than permitted
[13:01:55] Explicit valence for atom # 25 C greater than permitted
[13:01:55] Explicit valence for atom # 29 C greater than permitted
[13:01:55] Explicit valence for atom # 4 C, 6, is greater than permitted
[13:01:55] Explicit valence for atom # 4 P, 7, is greater than permitted
[13:01:56] Explicit valence for atom # 24 C greater than permitted
[13:01:56] Explicit valence for atom # 17 C greater than permitted
[13:01:56] Explicit valence for atom # 43 C greater than permitted
[13:01:56] Explicit valence for atom # 36 C greater than permitted
[13:01:56] Explicit valence for atom # 26 C greater than permitted
[13:01:56] Explicit valence for atom # 9 C greater than permitted
[13:01:56] Explicit valence for atom # 6 C, 5, is greater than permitted
[13:01:56] Explicit valence for atom # 15 C greater than permitted
[13:01:56] Explicit valence for atom # 30 P, 7, is greater than permitted
[13:01:56] Explicit valence for atom # 23 C greater than permitted
[13:01:56] Explicit valence for atom # 35 C greater than permitted
[13:01:56] Explicit valence for atom # 1 Si, 5, is greater than permitted
[13:01:56] Explicit valence for atom # 21 C greater than permitted
[13:01:56] Explicit valence for atom # 25 Si, 5, is greater than permitted
[13:01:56] Explicit valence for atom # 29 C greater than permitted
[13:01:56] Explicit valence for atom # 17 P, 7, is greater than permitted
[13:01:56] Explicit valence for atom # 24 C, 5, is greater than permitted
[13:01:56] Explicit valence for atom # 23 Si, 5, is greater than permitted
[13:01:56] Explicit valence for atom # 19 C greater than permitted
[13:01:56] Explicit valence for atom # 17 C greater than permitted
[13:01:56] Explicit valence for atom # 39 C greater than permitted
[13:01:56] Explicit valence for atom # 29 C greater than permitted
[13:01:56] Explicit valence for atom # 8 C greater than permitted
[13:01:56] Explicit valence for atom # 17 C greater than permitted
[13:01:56] Explicit valence for atom # 26 C greater than permitted
[13:01:56] Explicit valence for atom # 28 C greater than permitted
[13:01:56] Explicit valence for atom # 27 C greater than permitted

--- Processing cluster 4 ---

[13:02:10] Explicit valence for atom # 30 C greater than permitted
[13:02:10] Explicit valence for atom # 31 C, 5, is greater than permitted
[13:02:10] Explicit valence for atom # 36 C greater than permitted
[13:02:10] Explicit valence for atom # 32 C greater than permitted
[13:02:10] Explicit valence for atom # 34 C greater than permitted
[13:02:10] Explicit valence for atom # 31 C greater than permitted
[13:02:10] Explicit valence for atom # 21 C greater than permitted
[13:02:10] Explicit valence for atom # 15 Si, 6, is greater than permitted
[13:02:10] Explicit valence for atom # 1 C greater than permitted
[13:02:10] Explicit valence for atom # 23 C greater than permitted
[13:02:10] Explicit valence for atom # 20 C greater than permitted
[13:02:10] Explicit valence for atom # 1 C, 5, is greater than permitted
[13:02:10] Explicit valence for atom # 33 C greater than permitted
[13:02:10] Explicit valence for atom # 26 C greater than permitted
[13:02:10] Explicit valence for atom # 5 P, 7, is greater than permitted
[13:02:10] Explicit valence for atom # 39 C greater than permitted
[13:02:10] Explicit valence for atom # 15 C greater than permitted
[13:02:10] Explicit valence for atom # 22 Si, 5, is greater than permitted
[13:02:10] Explicit valence for atom # 47 C greater than permitted
[13:02:10] Explicit valence for atom # 35 C greater than permitted
[13:02:10] Explicit valence for atom # 26 Si, 5, is greater than permitted
[13:02:10] Explicit valence for atom # 33 C greater than permitted
[13:02:10] Explicit valence for atom # 31 C greater than permitted
[13:02:10] Explicit valence for atom # 35 C greater than permitted
[13:02:10] Explicit valence for atom # 26 C greater than permitted
[13:02:10] Explicit valence for atom # 28 C greater than permitted
[13:02:10] Explicit valence for atom # 27 C greater than permitted
[13:02:10] Explicit valence for atom # 13 Si, 5, is greater than permitted
[13:02:10] Explicit valence for atom # 21 C greater than permitted
[13:02:10] Explicit valence for atom # 40 Si, 5, is greater than permitted
[13:02:10] Explicit valence for atom # 32 C greater than permitted
[13:02:10] Explicit valence for atom # 23 C greater than permitted
[13:02:10] Explicit valence for atom # 19 C greater than permitted
[13:02:10] Explicit valence for atom # 39 C greater than permitted
[13:02:10] Explicit valence for atom # 26 P, 7, is greater than permitted
[13:02:10] Explicit valence for atom # 3 Si, 5, is greater than permitted
[13:02:11] Explicit valence for atom # 18 C, 5, is greater than permitted
[13:02:11] Explicit valence for atom # 22 C greater than permitted
[13:02:11] Explicit valence for atom # 30 C greater than permitted
[13:02:11] Explicit valence for atom # 28 C greater than permitted
[13:02:11] Explicit valence for atom # 40 C greater than permitted
[13:02:11] Explicit valence for atom # 24 C greater than permitted
[13:02:11] Explicit valence for atom # 25 C greater than permitted
[13:02:11] Explicit valence for atom # 20 C, 5, is greater than permitted
[13:02:11] Explicit valence for atom # 36 C greater than permitted
[13:02:11] Explicit valence for atom # 22 C greater than permitted
[13:02:11] Explicit valence for atom # 14 C greater than permitted
[13:02:11] Explicit valence for atom # 33 C greater than permitted
[13:02:11] Explicit valence for atom # 15 C greater than permitted
[13:02:11] Explicit valence for atom # 31 C greater than permitted
[13:02:11] Explicit valence for atom # 14 C, 5, is greater than permitted
[13:02:11] Explicit valence for atom # 30 C greater than permitted
[13:02:11] Explicit valence for atom # 17 C greater than permitted
[13:02:11] Explicit valence for atom # 22 C greater than permitted
[13:02:11] Explicit valence for atom # 17 C greater than permitted
[13:02:11] Explicit valence for atom # 4 C, 5, is greater than permitted
[13:02:11] Explicit valence for atom # 20 C greater than permitted
[13:02:11] Explicit valence for atom # 2 Si, 5, is greater than permitted
[13:02:11] Explicit valence for atom # 21 C greater than permitted
[13:02:11] Explicit valence for atom # 20 Si, 5, is greater than permitted
[13:02:11] Explicit valence for atom # 27 C greater than permitted
[13:02:11] Explicit valence for atom # 24 C greater than permitted
[13:02:11] Explicit valence for atom # 29 C greater than permitted
[13:02:11] Explicit valence for atom # 25 C greater than permitted
[13:02:11] Explicit valence for atom # 31 C greater than permitted
[13:02:11] Explicit valence for atom # 22 C greater than permitted
[13:02:11] Explicit valence for atom # 30 C greater than permitted
[13:02:11] Explicit valence for atom # 19 P, 7, is greater than permitted
[13:02:11] Explicit valence for atom # 25 C greater than permitted
[13:02:11] Explicit valence for atom # 20 C greater than permitted
[13:02:11] Explicit valence for atom # 20 C greater than permitted
[13:02:11] Explicit valence for atom # 26 C greater than permitted
[13:02:11] Explicit valence for atom # 30 C greater than permitted
[13:02:11] Explicit valence for atom # 8 C, 6, is greater than permitted
[13:02:11] Explicit valence for atom # 13 C greater than permitted
[13:02:11] Explicit valence for atom # 19 C greater than permitted
[13:02:11] Explicit valence for atom # 29 P, 7, is greater than permitted
[13:02:11] Explicit valence for atom # 12 C greater than permitted
[13:02:11] Explicit valence for atom # 36 C greater than permitted
[13:02:11] Explicit valence for atom # 40 C greater than permitted
[13:02:11] Explicit valence for atom # 23 C greater than permitted
[13:02:11] Explicit valence for atom # 30 C, 5, is greater than permitted
[13:02:11] Explicit valence for atom # 12 C greater than permitted
[13:02:11] Explicit valence for atom # 26 P, 7, is greater than permitted
[13:02:11] Explicit valence for atom # 23 P, 6, is greater than permitted
[13:02:11] Explicit valence for atom # 35 C greater than permitted
[13:02:11] Explicit valence for atom # 30 Si, 5, is greater than permitted
[13:02:11] Explicit valence for atom # 41 Si, 5, is greater than permitted
[13:02:11] Explicit valence for atom # 19 C greater than permitted
[13:02:11] Explicit valence for atom # 20 C greater than permitted
[13:02:11] Explicit valence for atom # 24 C greater than permitted
[13:02:11] Explicit valence for atom # 13 C greater than permitted
[13:02:11] Explicit valence for atom # 16 C greater than permitted
[13:02:11] Explicit valence for atom # 21 C greater than permitted
[13:02:11] Explicit valence for atom # 9 C greater than permitted
[13:02:11] Explicit valence for atom # 33 C greater than permitted
[13:02:11] Explicit valence for atom # 30 C greater than permitted
[13:02:11] Explicit valence for atom # 28 C greater than permitted
[13:02:11] Explicit valence for atom # 10 C greater than permitted
[13:02:11] Explicit valence for atom # 18 C greater than permitted
[13:02:11] Explicit valence for atom # 19 C greater than permitted
[13:02:11] Explicit valence for atom # 20 C greater than permitted
[13:02:11] Explicit valence for atom # 41 C greater than permitted
[13:02:11] Explicit valence for atom # 18 C greater than permitted
[13:02:11] Explicit valence for atom # 16 C, 5, is greater than permitted
[13:02:11] Explicit valence for atom # 26 Si, 5, is greater than permitted
[13:02:11] Explicit valence for atom # 20 C greater than permitted
[13:02:11] Explicit valence for atom # 35 C greater than permitted
[13:02:11] Explicit valence for atom # 25 C greater than permitted
[13:02:11] Explicit valence for atom # 28 C greater than permitted
[13:02:11] Explicit valence for atom # 29 C greater than permitted
[13:02:11] Explicit valence for atom # 26 C greater than permitted
[13:02:11] Explicit valence for atom # 6 C greater than permitted
[13:02:11] Explicit valence for atom # 33 C greater than permitted
[13:02:11] Explicit valence for atom # 31 C, 5, is greater than permitted
[13:02:11] Explicit valence for atom # 19 Si, 5, is greater than permitted
[13:02:11] Explicit valence for atom # 12 C, 6, is greater than permitted
[13:02:11] Explicit valence for atom # 15 C greater than permitted
[13:02:11] Explicit valence for atom # 20 C greater than permitted
[13:02:11] Explicit valence for atom # 25 C greater than permitted
[13:02:11] Explicit valence for atom # 39 C greater than permitted
[13:02:11] Explicit valence for atom # 34 C greater than permitted
[13:02:11] Explicit valence for atom # 30 C greater than permitted
[13:02:11] Explicit valence for atom # 22 Si, 5, is greater than permitted
[13:02:11] Explicit valence for atom # 24 C, 5, is greater than permitted
[13:02:11] Explicit valence for atom # 17 P, 7, is greater than permitted
[13:02:11] Explicit valence for atom # 6 C greater than permitted
[13:02:11] Explicit valence for atom # 26 C greater than permitted
[13:02:11] Explicit valence for atom # 21 C greater than permitted
[13:02:11] Explicit valence for atom # 21 C greater than permitted
[13:02:11] Explicit valence for atom # 19 C greater than permitted
[13:02:11] Explicit valence for atom # 23 C greater than permitted
[13:02:11] Explicit valence for atom # 23 C greater than permitted
[13:02:11] Explicit valence for atom # 19 C greater than permitted
[13:02:11] Explicit valence for atom # 23 Si, 5, is greater than permitted
[13:02:11] Explicit valence for atom # 10 C, 5, is greater than permitted
[13:02:11] Explicit valence for atom # 31 C greater than permitted
[13:02:11] Explicit valence for atom # 21 C greater than permitted
[13:02:11] Explicit valence for atom # 18 C greater than permitted
[13:02:11] Explicit valence for atom # 1 C, 5, is greater than permitted
[13:02:11] Explicit valence for atom # 26 C greater than permitted
[13:02:11] Explicit valence for atom # 7 C greater than permitted
[13:02:11] Explicit valence for atom # 30 C, 5, is greater than permitted
[13:02:11] Explicit valence for atom # 8 C greater than permitted
[13:02:11] Explicit valence for atom # 28 C greater than permitted
[13:02:11] Explicit valence for atom # 31 C greater than permitted
[13:02:11] Explicit valence for atom # 17 C greater than permitted
[13:02:11] Explicit valence for atom # 20 C greater than permitted
[13:02:11] Explicit valence for atom # 22 C greater than permitted
[13:02:11] Explicit valence for atom # 19 C, 6, is greater than permitted
[13:02:11] Explicit valence for atom # 25 C greater than permitted
[13:02:11] Explicit valence for atom # 26 C greater than permitted
[13:02:11] Explicit valence for atom # 18 C greater than permitted
[13:02:11] Explicit valence for atom # 16 C greater than permitted
[13:02:11] Explicit valence for atom # 25 C greater than permitted
[13:02:11] Explicit valence for atom # 20 Si, 5, is greater than permitted
[13:02:11] Explicit valence for atom # 43 C greater than permitted
[13:02:11] Explicit valence for atom # 24 P, 6, is greater than permitted
[13:02:11] Explicit valence for atom # 35 C greater than permitted
[13:02:11] Explicit valence for atom # 35 C greater than permitted
[13:02:11] Explicit valence for atom # 20 C greater than permitted
[13:02:11] Explicit valence for atom # 1 C greater than permitted
[13:02:11] Explicit valence for atom # 34 C greater than permitted
[13:02:11] Explicit valence for atom # 40 C greater than permitted
[13:02:11] Explicit valence for atom # 25 C greater than permitted
[13:02:11] Explicit valence for atom # 14 C greater than permitted
[13:02:11] Explicit valence for atom # 23 S, 6, is greater than permitted
[13:02:11] Explicit valence for atom # 25 C greater than permitted
[13:02:11] Explicit valence for atom # 28 P, 7, is greater than permitted
[13:02:11] Explicit valence for atom # 27 P, 7, is greater than permitted
[13:02:11] Explicit valence for atom # 26 C greater than permitted
[13:02:11] Explicit valence for atom # 30 C greater than permitted
[13:02:11] Explicit valence for atom # 1 C, 5, is greater than permitted
[13:02:11] Explicit valence for atom # 23 C, 4, is greater than permitted
[13:02:11] Explicit valence for atom # 40 C greater than permitted
[13:02:11] Explicit valence for atom # 30 C greater than permitted
[13:02:11] Explicit valence for atom # 15 C, 5, is greater than permitted
[13:02:11] Explicit valence for atom # 10 C greater than permitted
[13:02:11] Explicit valence for atom # 14 C greater than permitted
[13:02:11] Explicit valence for atom # 45 C greater than permitted
[13:02:11] Explicit valence for atom # 32 C greater than permitted
[13:02:11] Explicit valence for atom # 20 C greater than permitted
[13:02:11] Explicit valence for atom # 6 C, 5, is greater than permitted
[13:02:11] Explicit valence for atom # 24 C greater than permitted
[13:02:11] Explicit valence for atom # 19 P, 6, is greater than permitted
[13:02:12] Explicit valence for atom # 25 C greater than permitted
[13:02:12] Explicit valence for atom # 24 C, 5, is greater than permitted
[13:02:12] Explicit valence for atom # 31 C greater than permitted
[13:02:12] Explicit valence for atom # 37 C greater than permitted
[13:02:12] Explicit valence for atom # 8 Si, 5, is greater than permitted
[13:02:12] Explicit valence for atom # 18 C greater than permitted
[13:02:12] Explicit valence for atom # 12 C greater than permitted
[13:02:12] Explicit valence for atom # 12 C greater than permitted
[13:02:12] Explicit valence for atom # 28 C greater than permitted
[13:02:12] Explicit valence for atom # 28 C greater than permitted
[13:02:12] Explicit valence for atom # 34 C greater than permitted
[13:02:12] Explicit valence for atom # 20 C greater than permitted
[13:02:12] Explicit valence for atom # 22 C greater than permitted
[13:02:12] Explicit valence for atom # 21 C greater than permitted
[13:02:12] Explicit valence for atom # 28 C greater than permitted
[13:02:12] Explicit valence for atom # 31 C greater than permitted
[13:02:12] Explicit valence for atom # 5 C greater than permitted
[13:02:12] Explicit valence for atom # 23 C greater than permitted
[13:02:12] Explicit valence for atom # 5 Si, 5, is greater than permitted
[13:02:12] Explicit valence for atom # 23 C greater than permitted
[13:02:12] Explicit valence for atom # 21 C greater than permitted
[13:02:12] Explicit valence for atom # 29 C greater than permitted
[13:02:12] Explicit valence for atom # 15 C, 5, is greater than permitted
[13:02:12] Explicit valence for atom # 31 Si, 5, is greater than permitted
[13:02:12] Explicit valence for atom # 32 C greater than permitted
[13:02:12] Explicit valence for atom # 29 C greater than permitted
[13:02:12] Explicit valence for atom # 30 C greater than permitted
[13:02:12] Explicit valence for atom # 26 C greater than permitted
[13:02:12] Explicit valence for atom # 17 C greater than permitted
[13:02:12] Explicit valence for atom # 18 C greater than permitted
[13:02:12] Explicit valence for atom # 27 C greater than permitted
[13:02:12] Explicit valence for atom # 22 C greater than permitted
[13:02:12] Explicit valence for atom # 45 C greater than permitted
[13:02:12] Explicit valence for atom # 7 C greater than permitted
[13:02:12] Explicit valence for atom # 31 C greater than permitted
[13:02:12] Explicit valence for atom # 30 Si, 5, is greater than permitted
[13:02:12] Explicit valence for atom # 6 P, 6, is greater than permitted
[13:02:12] Explicit valence for atom # 17 C greater than permitted
[13:02:12] Explicit valence for atom # 33 C greater than permitted
[13:02:12] Explicit valence for atom # 31 P, 7, is greater than permitted
[13:02:12] Explicit valence for atom # 13 C greater than permitted
[13:02:12] Explicit valence for atom # 1 C greater than permitted
[13:02:12] Explicit valence for atom # 30 C greater than permitted
[13:02:12] Explicit valence for atom # 34 C greater than permitted
[13:02:12] Explicit valence for atom # 18 C greater than permitted
[13:02:12] Explicit valence for atom # 38 C greater than permitted
[13:02:12] Explicit valence for atom # 20 C greater than permitted
[13:02:12] Explicit valence for atom # 12 C, 6, is greater than permitted
[13:02:12] Explicit valence for atom # 13 C greater than permitted
[13:02:12] Explicit valence for atom # 19 P, 7, is greater than permitted
[13:02:12] Explicit valence for atom # 13 C greater than permitted
[13:02:12] Explicit valence for atom # 20 Si, 5, is greater than permitted
[13:02:12] Explicit valence for atom # 26 C greater than permitted
[13:02:12] Explicit valence for atom # 39 C greater than permitted
[13:02:12] Explicit valence for atom # 18 C greater than permitted
[13:02:12] Explicit valence for atom # 44 Si, 5, is greater than permitted
[13:02:12] Explicit valence for atom # 17 P, 7, is greater than permitted
[13:02:12] Explicit valence for atom # 31 C greater than permitted
[13:02:12] Explicit valence for atom # 37 C, 5, is greater than permitted
[13:02:12] Explicit valence for atom # 31 C greater than permitted
[13:02:12] Explicit valence for atom # 34 C greater than permitted
[13:02:12] Explicit valence for atom # 21 C greater than permitted
[13:02:12] Explicit valence for atom # 15 C greater than permitted
[13:02:12] Explicit valence for atom # 18 C greater than permitted
[13:02:12] Explicit valence for atom # 25 C greater than permitted
[13:02:12] Explicit valence for atom # 26 C greater than permitted
[13:02:12] Explicit valence for atom # 30 C greater than permitted
[13:02:12] Explicit valence for atom # 18 Si, 5, is greater than permitted
[13:02:12] Explicit valence for atom # 21 C greater than permitted
[13:02:12] Explicit valence for atom # 6 C greater than permitted
[13:02:12] Explicit valence for atom # 44 C greater than permitted
[13:02:12] Explicit valence for atom # 30 Si, 6, is greater than permitted
[13:02:12] Explicit valence for atom # 29 C greater than permitted
[13:02:12] Explicit valence for atom # 27 C greater than permitted
[13:02:12] Explicit valence for atom # 42 C greater than permitted
[13:02:12] Explicit valence for atom # 32 Si, 5, is greater than permitted
[13:02:12] Explicit valence for atom # 24 C greater than permitted
[13:02:12] Explicit valence for atom # 19 C greater than permitted
[13:02:12] Explicit valence for atom # 30 C greater than permitted
[13:02:12] Explicit valence for atom # 4 C greater than permitted
[13:02:12] Explicit valence for atom # 25 C greater than permitted
[13:02:12] Explicit valence for atom # 36 C greater than permitted
[13:02:12] Explicit valence for atom # 25 C greater than permitted
[13:02:12] Explicit valence for atom # 29 C greater than permitted
[13:02:12] Explicit valence for atom # 42 C greater than permitted
[13:02:12] Explicit valence for atom # 24 C greater than permitted
[13:02:12] Explicit valence for atom # 26 C greater than permitted
[13:02:12] Explicit valence for atom # 22 C, 5, is greater than permitted
[13:02:12] Explicit valence for atom # 22 C greater than permitted
[13:02:12] Explicit valence for atom # 6 C greater than permitted
[13:02:12] Explicit valence for atom # 20 C greater than permitted
[13:02:12] Explicit valence for atom # 24 C greater than permitted
[13:02:12] Explicit valence for atom # 30 C greater than permitted
[13:02:12] Explicit valence for atom # 35 C greater than permitted
[13:02:12] Explicit valence for atom # 22 C, 6, is greater than permitted
[13:02:12] Explicit valence for atom # 23 C greater than permitted
[13:02:12] Explicit valence for atom # 26 C greater than permitted
[13:02:12] Explicit valence for atom # 26 C greater than permitted
[13:02:12] Explicit valence for atom # 17 C greater than permitted
[13:02:12] Explicit valence for atom # 23 C greater than permitted
[13:02:12] Explicit valence for atom # 24 C greater than permitted
[13:02:12] Explicit valence for atom # 9 C, 5, is greater than permitted
[13:02:12] Explicit valence for atom # 15 C greater than permitted
[13:02:12] Explicit valence for atom # 35 C greater than permitted
[13:02:12] Explicit valence for atom # 4 C, 5, is greater than permitted
[13:02:12] Explicit valence for atom # 22 C greater than permitted

Calculation complete! Processed 5 clusters

,name,type_cluster,scaffold,RS,SED,ASER
0,DrugEx_RNN_epsilon_0.6_250k_0,dis,csk,0.400000,0.123409,0.007531
1,DrugEx_RNN_epsilon_0.6_250k_1,dis,csk,0.652174,0.110997,0.002372
2,DrugEx_RNN_epsilon_0.6_250k_2,dis,csk,0.225000,0.128512,0.000440
3,DrugEx_RNN_epsilon_0.6_250k_3,dis,csk,0.675676,0.145924,0.016697
4,DrugEx_RNN_epsilon_0.6_250k_4,dis,csk,0.883721,0.182058,0.061365
5,DrugEx_RNN_epsilon_0.6_250k_mean,dis,csk,0.567314,0.138180,0.017681

GB_GA_mut_r_0.01_250k

============================================================
Starting calculation for GB_GA_mut_r_0.01_250k
Receptor: Glucocorticoid_receptor
Cluster type: dis
Scaffold type: csk
CPUs: 100
============================================================

--- Processing cluster 0 ---

In [ ]:
for receptor in ['Glucocorticoid_receptor']:
    for type_scaffold in ['csk']:
        for type_cluster in ['sim']:
            for subset in ['','_500k', '_250k', '_125k', '_62.5k', '_10k']:
                ncpus = 100
                data_folder = '../'
                # Define generator names with different epsilon values
                generators_name_list = [
                    f"Molpher{subset}",
                    f"REINVENT{subset}",
                    f"DrugEx_GT_epsilon_0.1{subset}",
                    f"DrugEx_GT_epsilon_0.6{subset}",
                    f"DrugEx_RNN_epsilon_0.1{subset}",
                    f"DrugEx_RNN_epsilon_0.6{subset}",
                    f"GB_GA_mut_r_0.01{subset}",
                    f"GB_GA_mut_r_0.5{subset}",
                    f"GB_GA_log_p_mut_r_0.01{subset}",
                    f"GB_GA_log_p_mut_r_0.5{subset}",
                    f"addcarbon{subset}"
                ]
                for generator in generators_name_list:
                    print(generator)
                    calculate_metrics(type_cluster,type_scaffold,generator,receptor, data_folder = data_folder,ncpus = ncpus)

## Combining and Normalizing Metrics

The following cell runs functions that:

- merge the mean values of all metrics into a single `pandas.DataFrame` (using `connect_mean_value`)
- apply Min-Max normalization to scale the values (using `connect_mean_value_normalized`)

In [89]:
from src import metrics_connection # Importing custom metric functions
import importlib as imp
imp.reload(metrics_connection)

In [32]:
for receptor in ['Leukocyte_elastase']:
    for type_scaffold in ['murcko']:
        for type_cluster in ['sim']:  # Different cluster types
            for subset in ['']:
            
                # Define generator names with different epsilon values
                generators_name_list = [
                    f"Molpher{subset}",
                    f"REINVENT{subset}",
                    f"DrugEx_GT_epsilon_0.1{subset}",
                    f"DrugEx_GT_epsilon_0.6{subset}",
                    f"DrugEx_RNN_epsilon_0.1{subset}",
                    f"DrugEx_RNN_epsilon_0.6{subset}",
                    f"GB_GA_mut_r_0.01{subset}",
                    f"GB_GA_mut_r_0.5{subset}",
                    f"GB_GA_log_p_mut_r_0.01{subset}",
                    f"GB_GA_log_p_mut_r_0.5{subset}",
                    f"addcarbon{subset}"
                ]
    
                # Connect and process mean values
                df = metrics_connection.connect_mean_value(type_cluster, type_scaffold, generators_name_list, receptor, subset, data_folder = '../')
                df1 = metrics_connection.connect_mean_value_normalized(type_cluster, type_scaffold, generators_name_list, receptor, subset, data_folder = '../')

                display(df[['name','type_cluster','scaffold','RS','SED','ASER']])
                display(df1[['name','type_cluster','scaffold','RS','SED','ASER']])

,name,type_cluster,scaffold,RS,SED,ASER
0,Molpher_mean,sim,murcko,0.465611,0.304545,0.004538
1,REINVENT_mean,sim,murcko,0.292322,0.569790,0.001211
2,DrugEx_GT_epsilon_0.1_mean,sim,murcko,0.427641,0.574657,0.005542
3,DrugEx_GT_epsilon_0.6_mean,sim,murcko,0.645077,0.614167,0.008375
4,DrugEx_RNN_epsilon_0.1_mean,sim,murcko,0.104826,0.418003,0.018167
5,DrugEx_RNN_epsilon_0.6_mean,sim,murcko,0.562998,0.501544,0.011521
6,GB_GA_mut_r_0.01_mean,sim,murcko,0.476428,0.259681,0.019232
7,GB_GA_mut_r_0.5_mean,sim,murcko,0.559051,0.228702,0.021894
8,GB_GA_log_p_mut_r_0.01_mean,sim,murcko,0.067379,0.256611,0.003444
9,GB_GA_log_p_mut_r_0.5_mean,sim,murcko,0.071259,0.257605,0.005037
10,addcarbon_mean,sim,murcko,0.118272,0.005151,0.001686

,name,type_cluster,scaffold,RS,SED,ASER
0,Molpher_mean,sim,murcko,0.689343,0.491603,0.160834
1,REINVENT_mean,sim,murcko,0.389378,0.927134,0.000000
2,DrugEx_GT_epsilon_0.1_mean,sim,murcko,0.623617,0.935126,0.209377
3,DrugEx_GT_epsilon_0.6_mean,sim,murcko,1.000000,1.000000,0.346346
4,DrugEx_RNN_epsilon_0.1_mean,sim,murcko,0.064821,0.677901,0.819807
5,DrugEx_RNN_epsilon_0.6_mean,sim,murcko,0.857922,0.815075,0.498482
6,GB_GA_mut_r_0.01_mean,sim,murcko,0.708068,0.417936,0.871270
7,GB_GA_mut_r_0.5_mean,sim,murcko,0.851088,0.367069,1.000000
8,GB_GA_log_p_mut_r_0.01_mean,sim,murcko,0.000000,0.412895,0.107940
9,GB_GA_log_p_mut_r_0.5_mean,sim,murcko,0.006715,0.414529,0.184960
10,addcarbon_mean,sim,murcko,0.088097,0.000000,0.022942

In [90]:
data_folder = '../'

for receptor in ['Glucocorticoid_receptor','Leukocyte_elastase']:
    for type_scaffold in ['csk','murcko']:
        for type_cluster in ['dis','sim']:  # Different cluster types
            for subset in ['']:
            
                # Define generator names with different epsilon values
                generators_name_list = [
                    f"Molpher{subset}",
                    f"REINVENT{subset}",
                    f"DrugEx_GT_epsilon_0.1{subset}",
                    f"DrugEx_GT_epsilon_0.6{subset}",
                    f"DrugEx_RNN_epsilon_0.1{subset}",
                    f"DrugEx_RNN_epsilon_0.6{subset}",
                    f"GB_GA_mut_r_0.01{subset}",
                    f"GB_GA_mut_r_0.5{subset}",
                    f"GB_GA_log_p_mut_r_0.01{subset}",
                    f"GB_GA_log_p_mut_r_0.5{subset}",
                    f"addcarbon{subset}"
                ]
                
                df_raw = metrics_connection.connect_mean_value(type_cluster, type_scaffold, generators_name_list, receptor, subset, data_folder = '../')


                out_xlsx = f"{data_folder}img/paper_table/paper_table_{receptor}_{type_cluster}_{type_scaffold}{subset}.xlsx"

                metrics_connection.export_article_excel_table(
                    df=df_raw,
                    out_xlsx=out_xlsx,
                    receptor=receptor,
                    type_scaffold=type_scaffold,
                    subset=subset or "",
                    type_cluster=type_cluster, 
                )

[OK] Excel saved to: ../img/paper_table/paper_table_Glucocorticoid_receptor_dis_csk.xlsx
[OK] Excel saved to: ../img/paper_table/paper_table_Glucocorticoid_receptor_sim_csk.xlsx
[OK] Excel saved to: ../img/paper_table/paper_table_Glucocorticoid_receptor_dis_murcko.xlsx
[OK] Excel saved to: ../img/paper_table/paper_table_Glucocorticoid_receptor_sim_murcko.xlsx
[OK] Excel saved to: ../img/paper_table/paper_table_Leukocyte_elastase_dis_csk.xlsx
[OK] Excel saved to: ../img/paper_table/paper_table_Leukocyte_elastase_sim_csk.xlsx
[OK] Excel saved to: ../img/paper_table/paper_table_Leukocyte_elastase_dis_murcko.xlsx
[OK] Excel saved to: ../img/paper_table/paper_table_Leukocyte_elastase_sim_murcko.xlsx